import { S } from './sources'
import type { CaseStudy, Question } from './types'
import { moreCaseQuestions, moreCaseStudies } from './cases2'

/** Fictional companies. Each case's questions span all three exam domains. */
const firstCaseStudies: CaseStudy[] = [
  {
    id: 'case-fernhollow',
    company: 'Fernhollow Outfitters',
    title: 'Fernhollow Outfitters: retail sales platform',
    summary: 'A regional outdoor retailer is moving sales reporting from an on-premises ERP into Microsoft Fabric, with regional managers who may see only their own region.',
    environment: [
      'Sales and customer data live in a SQL Server ERP database in Fernhollow’s own data center.',
      'Fernhollow has one Fabric F64 capacity and three workspaces: Sales-Dev, Sales-Test, and Sales-Prod.',
      'Data engineers write PySpark; the BI team writes T-SQL and DAX.',
    ],
    requirements: [
      'Land raw ERP extracts in a lakehouse (bronze and silver layers).',
      'Build the gold layer as a star schema with T-SQL stored procedures and multi-table transactions.',
      'Keep a history of each customer’s region so past sales stay with the region at the time of sale.',
      'Serve reports through a Direct Lake semantic model that never falls back to DirectQuery.',
      'Regional managers must see only their own region’s sales.',
      'Promote content from Sales-Dev to Sales-Test to Sales-Prod with deployment pipelines.',
    ],
    constraints: [
      'Users must never see partly loaded data during the nightly ETL.',
      'Row filters for managers must be defined once, in the semantic model.',
    ],
  },
  {
    id: 'case-quillmere',
    company: 'Quillmere Health',
    title: 'Quillmere Health: patient telemetry',
    summary: 'A hospital network streams bedside device telemetry into Fabric and must protect patient data while supporting near-real-time operations and research.',
    environment: [
      'Device telemetry streams into a KQL database in an eventhouse.',
      'Ward occupancy is kept in an operational Azure SQL database that changes every few minutes.',
      'A research team uses notebooks in its own workspace.',
      'Microsoft Purview sensitivity labels are published to all staff.',
    ],
    requirements: [
      'Operations staff need five-minute summaries of device readings.',
      'Data engineers need the telemetry as Delta tables in a lakehouse without a copy pipeline.',
      'Ward dashboards must combine near-real-time occupancy with historical admissions.',
      'Researchers may read lakehouse data from their notebooks but must never query patient names in the warehouse.',
      'Exported reports must keep their label protection where Fabric supports it.',
    ],
    constraints: [
      'Researchers have no role in the clinical workspaces.',
      'No new data copies of telemetry may be scheduled.',
    ],
  },
  {
    id: 'case-saltmarsh',
    company: 'Saltmarsh Haulage',
    title: 'Saltmarsh Haulage: shipment analytics lifecycle',
    summary: 'A freight company is bringing source control, safe releases, and refresh discipline to a growing shipment model that several teams depend on.',
    environment: [
      'Shipment data comes from an Azure SQL database through Dataflow Gen2 into a warehouse.',
      'The Shipments semantic model is an Import model on a Fabric F64 capacity, currently 8 GB and growing.',
      'Developers edit the model in Power BI Desktop and Tabular Editor.',
      'Reports in four other workspaces use the model.',
    ],
    requirements: [
      'Review model and report changes as text diffs in pull requests.',
      'Version the workspace in an Azure DevOps repository.',
      'Keep six years of shipment history and reload only the last seven days each night.',
      'Deploy model changes from Tabular Editor to the service.',
      'Warn report owners before any change to the shipment dataflow’s output.',
    ],
    constraints: [
      'The model will exceed 10 GB within a year.',
      'Some shipment weights arrive as text with invalid values.',
    ],
  },
  {
    id: 'case-lumenvale',
    company: 'Lumenvale Utilities',
    title: 'Lumenvale Utilities: finance and metering models',
    summary: 'A utility’s finance team, trained on PL-300, is standardizing DAX logic, report starting points, and trusted data for smart-meter analytics in Fabric.',
    environment: [
      'Meter readings and tariffs are stored in a warehouse named MeterWH; the meter registry is a lakehouse named RegistryLH in the same workspace.',
      'Tariffs are normalized into Tariff, TariffBand, and TariffFamily tables.',
      'A meter can be shared by several customers in multi-unit buildings.',
      'The finance semantic model has 40 base measures.',
    ],
    requirements: [
      'Provide YTD, prior-year, and YoY% versions of every measure without duplicating measures.',
      'Show amounts in each country’s currency format while charts keep plotting numbers.',
      'Validate measure results with DAX queries before publishing.',
      'Mark RegistryLH as the single authoritative source of meter data.',
      'Give new report authors a standard starting report with the model and queries but no data.',
    ],
    constraints: [
      'Report hierarchies must be built from single tables.',
      'Some measures filter large tables and are slow.',
    ],
  },
]

const f = 'case-fernhollow'
const c = 'case-quillmere'
const t = 'case-saltmarsh'
const b = 'case-lumenvale'

const firstCaseQuestions: Question[] = [
  // ── Fernhollow Outfitters ─────────────────────────────────────────
  {
    id: 'CS1-01',
    caseStudyId: f,
    machineId: 'thread-intake',
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 2,
    stem: 'Fernhollow needs a Dataflow Gen2 to read the ERP tables on its SQL Server for the bronze layer. What must be in place for the connection?',
    sources: [S.gateway, S.connections],
    options: [
      { id: 'a', text: 'A OneLake shortcut to the SQL Server database', explain: 'Shortcuts point to storage locations, not to an on-premises SQL Server.' },
      { id: 'b', text: 'An on-premises data gateway in Fernhollow’s network', explain: 'Correct. Learn: use the on-premises data gateway to connect on-premises data to the cloud.' },
      { id: 'c', text: 'Mirroring of the Fabric warehouse', explain: 'Mirroring the warehouse doesn’t reach the on-premises source.' },
      { id: 'd', text: 'A workspace identity with Contributor access', explain: 'An identity doesn’t provide network access to an on-premises server.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS1-02',
    caseStudyId: f,
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'stores',
    stem: 'Fernhollow’s BI team will build the gold star schema with T-SQL stored procedures that update several tables in one transaction. Which data store should hold the gold layer?',
    sources: [S.decisionLhWh],
    options: [
      { id: 'a', text: 'The lakehouse, through its SQL analytics endpoint', explain: 'The endpoint is read-only, so procedures can’t modify data there.' },
      { id: 'b', text: 'An eventhouse', explain: 'Eventhouses are for streaming event data queried with KQL.' },
      { id: 'c', text: 'A warehouse', explain: 'Correct. Learn: the warehouse is developed with T-SQL and provides full multi-table ACID transactions and stored procedures.' },
      { id: 'd', text: 'A semantic model with calculated tables', explain: 'A semantic model isn’t a store for T-SQL ETL.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS1-03',
    caseStudyId: f,
    machineId: 'weave-planner',
    bulletIds: ['P2.3'],
    format: 'yesno',
    difficulty: 3,
    trapPairId: 'scd1-vs-scd2',
    stem: 'Fernhollow must keep each customer’s region history so past sales stay with the region at the time of sale. For each proposed design, select Yes if it meets the goal. Otherwise, select No.',
    sources: [S.dimTables, S.loadTables],
    statements: [
      { id: 's1', text: 'Overwrite Region in DimCustomer whenever the ERP value changes, matching on CustomerID.', answer: false, explain: 'No. That is SCD type 1, which rolls all past sales up to the new region.' },
      { id: 's2', text: 'Expire the current DimCustomer row and insert a new version with a new surrogate key; facts store the surrogate key current at load time.', answer: true, explain: 'Yes. SCD type 2 with surrogate keys keeps each fact on the version that was valid.' },
      { id: 's3', text: 'Truncate and reload DimCustomer from the ERP each night with new surrogate keys.', answer: false, explain: 'No. Learn says never to truncate and reload a dimension with generated surrogate keys; it invalidates facts and loses history.' },
    ],
  },
  {
    id: 'CS1-04',
    caseStudyId: f,
    machineId: 'direct-lake-shuttle',
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'Fernhollow’s Direct Lake model must never fall back to DirectQuery, and manager row filters are defined in the semantic model. Which Direct Lake option and setting meets the requirements?',
    sources: [S.directLake, S.dlHow],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints with DirectLakeBehavior set to Automatic', explain: 'Automatic falls back to DirectQuery silently, which the requirement forbids.' },
      { id: 'b', text: 'Direct Lake on SQL analytics endpoints with DirectLakeBehavior set to DirectQueryOnly', explain: 'DirectQueryOnly forces every query to DirectQuery.' },
      { id: 'c', text: 'Direct Lake on SQL analytics endpoints with SQL RLS defined in the warehouse', explain: 'SQL RLS makes Direct Lake on SQL fall back, and the filters must live in the semantic model.' },
      { id: 'd', text: 'Direct Lake on OneLake', explain: 'Correct. It runs only in DirectLakeOnly mode and never falls back; semantic model RLS applies to it.' },
    ],
    answer: 'd',
  },
  {
    id: 'CS1-05',
    caseStudyId: f,
    machineId: 'direct-lake-shuttle',
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'framing-vs-import-refresh',
    stem: 'Fernhollow’s nightly pipeline loads gold tables for two hours. Managers must never see partly loaded data in the Direct Lake model. What should the pipeline do?',
    sources: [S.dlHow],
    options: [
      { id: 'a', text: 'Refresh the model every 15 minutes during the load', explain: 'Each refresh would frame partly loaded tables.' },
      { id: 'b', text: 'Run with automatic updates off, and refresh the model after the last table loads', explain: 'Correct. Framing only after the load completes shows users a consistent point in time.' },
      { id: 'c', text: 'Set the model to the large storage format', explain: 'Storage format doesn’t control framing.' },
      { id: 'd', text: 'Rebuild the model’s relationships after each load', explain: 'Relationships don’t control which data version users see.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS1-06',
    caseStudyId: f,
    machineId: 'thread-sieves',
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    stem: 'Fernhollow’s regional managers are workspace Viewers. A table maps each manager’s email to a region. How should you restrict each manager to their own region?',
    sources: [S.modelRls],
    options: [
      { id: 'a', text: 'A semantic model role with the filter [ManagerEmail] = USERPRINCIPALNAME()', explain: 'Correct. Dynamic RLS matches the signed-in user, and the filter flows through relationships.' },
      { id: 'b', text: 'A security policy in the gold warehouse', explain: 'The requirement says to define filters once, in the semantic model.' },
      { id: 'c', text: 'One workspace per region with copied reports', explain: 'Copying content doesn’t scale and duplicates reports.' },
      { id: 'd', text: 'Give managers the Contributor role', explain: 'Contributors bypass semantic model RLS.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS1-07',
    caseStudyId: f,
    machineId: 'conveyor',
    bulletIds: ['M2.3'],
    format: 'yesno',
    difficulty: 3,
    stem: 'After deploying the Direct Lake model from Sales-Test to Sales-Prod, Prod reports show Test data. For each proposed solution, select Yes if it meets the goal. Otherwise, select No.',
    sources: [S.pipelinesProcess, S.pipelinesRules],
    statements: [
      { id: 's1', text: 'Add a datasource rule in the Sales-Prod stage that points the model to the Prod gold warehouse, then deploy again.', answer: true, explain: 'Yes. Direct Lake models don’t autobind to the target stage’s items; datasource rules fix the binding.' },
      { id: 's2', text: 'Refresh the semantic model in Sales-Prod.', answer: false, explain: 'No. Refresh reframes against the source the model is bound to, which is still in Test.' },
      { id: 's3', text: 'Redeploy only the reports to Sales-Prod.', answer: false, explain: 'No. Reports autobind to the Prod model; the model itself is still bound to Test.' },
    ],
  },

  // ── Quillmere Health ───────────────────────────────────────────
  {
    id: 'CS2-01',
    caseStudyId: c,
    machineId: 'tension-meter',
    bulletIds: ['P3.3'],
    format: 'dropdown',
    difficulty: 2,
    stem: 'Quillmere’s operations staff need the average heart rate per device in five-minute buckets for the last hour, from the Readings table. Complete the KQL query.',
    sources: [S.kqlWhere, S.kqlSummarize, S.kqlBin],
    language: 'kql',
    code: 'Readings\n| where Timestamp > [[1]](1h)\n| summarize AvgHeartRate = [[2]](HeartRate) by DeviceId, bin(Timestamp, [[3]])',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'ago', explain: 'Correct. ago(1h) is one hour before now.' },
          { id: 'b', text: 'bin', explain: 'bin buckets values; it doesn’t compute a time relative to now.' },
          { id: 'c', text: 'between', explain: 'between needs a range of two values.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'count', explain: 'count() counts rows; it doesn’t average values.' },
          { id: 'b', text: 'dcount', explain: 'dcount() estimates distinct values.' },
          { id: 'c', text: 'avg', explain: 'Correct. avg() averages HeartRate per group.' },
        ],
        answer: 'c',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: '5m', explain: 'Correct. 5m is a five-minute timespan.' },
          { id: 'b', text: '1h', explain: 'This would give hourly buckets.' },
          { id: 'c', text: '300', explain: 'Binning a datetime column takes a timespan size, written like 5m.' },
        ],
        answer: 'a',
      },
    ],
  },
  {
    id: 'CS2-02',
    caseStudyId: c,
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'onelake-availability-vs-integration',
    stem: 'Quillmere’s data engineers need the eventhouse telemetry as Delta tables in their lakehouse, and no new copy jobs may be scheduled. What should you do?',
    sources: [S.eventhouseOneLake, S.shortcuts],
    options: [
      { id: 'a', text: 'Schedule a pipeline that copies the KQL tables to the lakehouse nightly', explain: 'This is the scheduled copy the constraint forbids.' },
      { id: 'b', text: 'Export the KQL tables to CSV in the Files area', explain: 'CSV files aren’t Delta tables, and exports are copies.' },
      { id: 'c', text: 'Turn on OneLake availability for the KQL database and create shortcuts in the lakehouse', explain: 'Correct. OneLake availability exposes the data in Delta format, and shortcuts make it visible in the lakehouse.' },
      { id: 'd', text: 'Mirror the eventhouse into a warehouse', explain: 'Mirroring isn’t how eventhouse data is exposed to a lakehouse.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS2-03',
    caseStudyId: c,
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'catalog-vs-rthub',
    stem: 'A Quillmere engineer wants to browse the data streams available in the organization, including the telemetry stream, to find a new device feed. Where should they look?',
    sources: [S.rtHub, S.catalog],
    options: [
      { id: 'a', text: 'The Real-Time hub', explain: 'Correct. The Real-Time hub is where you discover and manage streaming data.' },
      { id: 'b', text: 'The lakehouse Files area', explain: 'Files shows stored files, not streams across the organization.' },
      { id: 'c', text: 'The deployment pipeline view', explain: 'Pipelines promote content between stages.' },
      { id: 'd', text: 'The semantic model’s lineage view', explain: 'Lineage shows item dependencies, not available streams.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS2-04',
    caseStudyId: c,
    machineId: 'double-loom',
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'storage-modes',
    stem: 'Quillmere’s ward dashboard must show occupancy from the Azure SQL database within minutes, next to historical admissions that refresh nightly. Admissions, Ward, and Date come from the same Azure SQL database, and Ward and Date relate to both facts. How should you configure the model?',
    sources: [S.composite, S.storageMode],
    options: [
      { id: 'a', text: 'Import every table and refresh every five minutes', explain: 'Scheduled refresh limits make this impractical, and it copies all data repeatedly.' },
      { id: 'b', text: 'Occupancy in DirectQuery, admissions in Import, and Ward and Date in Dual', explain: 'Correct. A composite model gives current occupancy, fast history, and Dual dimensions keep relationships regular.' },
      { id: 'c', text: 'Every table in DirectQuery', explain: 'History would be slower than needed and gains nothing from DirectQuery.' },
      { id: 'd', text: 'Occupancy in DirectQuery and the dimensions in Import', explain: 'Import dimensions relate to DirectQuery facts through limited relationships; Dual avoids that.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS2-05',
    caseStudyId: c,
    machineId: 'thread-sieves',
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'cls-vs-ols-vs-ddm',
    stem: 'The clinical warehouse is shared with Quillmere’s researchers with Read All with SQL analytics endpoint permission. Any query that touches dbo.Patients.PatientName must fail for them, while other columns stay available. What should you implement?',
    sources: [S.whCls],
    options: [
      { id: 'a', text: 'Dynamic data masking on PatientName', explain: 'Masking returns the column with obscured values instead of failing.' },
      { id: 'b', text: 'A sensitivity label on the warehouse', explain: 'Labels don’t block columns in SQL queries.' },
      { id: 'c', text: 'Column-level security that grants SELECT on every column except PatientName', explain: 'Correct. Queries that touch a denied column fail with a permission error.' },
      { id: 'd', text: 'Row-level security on dbo.Patients', explain: 'RLS filters rows, not columns.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS2-06',
    caseStudyId: c,
    machineId: 'item-locks',
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 2,
    stem: 'Quillmere’s researchers have no role in the clinical workspace. They must read the telemetry lakehouse from notebooks in their own workspace. Which permission should you grant when sharing the lakehouse?',
    sources: [S.shareItems, S.roles],
    options: [
      { id: 'a', text: 'Read All with SQL analytics endpoint', explain: 'This allows T-SQL reads, not Spark.' },
      { id: 'b', text: 'Read all with Apache Spark', explain: 'Correct. ReadAll allows reading through OneLake APIs and Spark.' },
      { id: 'c', text: 'Build', explain: 'Build applies to semantic models.' },
      { id: 'd', text: 'The workspace Viewer role', explain: 'The Viewer role doesn’t include reading data through OneLake and Spark (ReadAll), and it would cover every item in the workspace.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS2-07',
    caseStudyId: c,
    machineId: 'seal-and-stamp',
    bulletIds: ['M1.4'],
    format: 'yesno',
    difficulty: 2,
    stem: 'Quillmere’s ward report carries a Highly Confidential label with an encryption policy. For each export, select Yes if the label’s protection stays with the exported file. Otherwise, select No.',
    sources: [S.infoProtection],
    statements: [
      { id: 's1', text: 'Export to Excel', answer: true, explain: 'Yes. Excel is a supported export path.' },
      { id: 's2', text: 'Export of a table visual to .txt', answer: false, explain: 'No. Other export paths such as .csv and .txt aren’t supported.' },
      { id: 's3', text: 'Analyze in Excel with a live connection to the model', answer: true, explain: 'Yes. Learn lists Analyze in Excel as a supported export path.' },
    ],
  },

  // ── Saltmarsh Haulage ───────────────────────────────────────────────
  {
    id: 'CS3-01',
    caseStudyId: t,
    machineId: 'carding-machine',
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 2,
    stem: 'Saltmarsh’s staging table stores ShipmentWeight as text, and some values are invalid, such as “n/a”. The warehouse load must convert valid values to decimal without failing on bad rows. Which expression should you use?',
    sources: [S.tryCast],
    options: [
      { id: 'a', text: 'CAST(ShipmentWeight AS decimal(10,2))', explain: 'CAST raises an error on the first invalid value and stops the load.' },
      { id: 'b', text: 'TRY_CAST(ShipmentWeight AS decimal(10,2))', explain: 'Correct. TRY_CAST returns NULL when a value can’t be converted.' },
      { id: 'c', text: "COALESCE(ShipmentWeight, '0')", explain: 'COALESCE replaces NULLs; it doesn’t convert types or handle invalid text.' },
      { id: 'd', text: "CONCAT(ShipmentWeight, '.00')", explain: 'This produces more text, not a decimal.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS3-02',
    caseStudyId: t,
    machineId: 'twisting-frame',
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 3,
    stem: 'Saltmarsh’s dashboards only show monthly totals by carrier and lane, but the fact table stores one row per shipment line. Analysts never need shipment-level detail. What should you do to reduce the fact table’s size?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Load an aggregated result grouped by all the dimension keys at month grain', explain: 'Correct. Aggregating raises the grain and reduces dimensionality, at the cost of detail nobody needs.' },
      { id: 'b', text: 'Partition the fact table by shipment number', explain: 'Partitioning doesn’t reduce the stored rows.' },
      { id: 'c', text: 'Add a calculated column with the monthly total', explain: 'This adds data to every row instead of reducing it.' },
      { id: 'd', text: 'Convert the fact table to a snowflake design', explain: 'Snowflaking applies to dimensions, not fact grain.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS3-03',
    caseStudyId: t,
    machineId: 'batch-winder',
    bulletIds: ['S2.5'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'archive-vs-refresh-period',
    stem: 'Saltmarsh must keep six years of shipments and reload only the last seven days each night. Shipments carry a LastModified column, and the policy partitions on ShipDate. Which two settings should the incremental refresh policy use? Choose two.',
    sources: [S.incrementalCfg],
    options: [
      { id: 'a', text: 'Archive data starting 6 years before the refresh date, and incrementally refresh 7 days before', explain: 'Correct. The archive period keeps history; the refresh period is the reloaded window.' },
      { id: 'b', text: 'Detect data changes using the LastModified column', explain: 'Correct. Only periods whose LastModified value changed are refreshed, and it differs from the partition column.' },
      { id: 'c', text: 'Detect data changes using the ShipDate column', explain: 'Learn says the detect-changes column shouldn’t be the same column used to partition the data.' },
      { id: 'd', text: 'Archive data starting 7 days before, and incrementally refresh 6 years before', explain: 'This swaps the periods and reloads six years each night.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'CS3-04',
    caseStudyId: t,
    machineId: 'wide-beam',
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 2,
    stem: 'Saltmarsh’s Shipments model will pass 10 GB within a year, and developers will deploy it from Tabular Editor over XMLA. Which model setting is required beyond 10 GB and also recommended for XMLA write operations?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'Large semantic model storage format', explain: 'Correct. It’s required beyond 10 GB and improves XMLA write performance.' },
      { id: 'b', text: 'Dual storage mode on the fact table', explain: 'Dual doesn’t change size limits or XMLA performance.' },
      { id: 'c', text: 'Query caching', explain: 'Caching speeds up reads only.' },
      { id: 'd', text: 'Automatic page refresh', explain: 'This is a report page setting; it doesn’t change model size limits or XMLA performance.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS3-05',
    caseStudyId: t,
    machineId: 'draft-table',
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'pbi-files',
    stem: 'Saltmarsh wants to review model and report changes as text diffs in pull requests. How should developers save their Power BI Desktop work?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'As a .pbix file in a shared folder', explain: 'A .pbix is a single file, not the plain-text project files built for source control.' },
      { id: 'b', text: 'As a .pbit template', explain: 'A template is a starting point, not a source-control format.' },
      { id: 'c', text: 'As a .pbids file', explain: 'A .pbids holds only a connection.' },
      { id: 'd', text: 'As a Power BI project (.pbip)', explain: 'Correct. Projects store definitions as plain text built for source control.' },
    ],
    answer: 'd',
  },
  {
    id: 'CS3-06',
    caseStudyId: t,
    machineId: 'ripple-map',
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'lineage-vs-impact',
    stem: 'Saltmarsh plans to rename a column in the shipment dataflow’s output. Reports in four other workspaces depend on it, and some of those workspaces are inaccessible to you. What should you do first?',
    sources: [S.impact, S.lineage],
    options: [
      { id: 'a', text: 'Open lineage view in your workspace and email the owners you see', explain: 'Lineage view doesn’t show downstream items in other workspaces.' },
      { id: 'b', text: 'Rename the column and watch for refresh failures', explain: 'This breaks downstream content without warning.' },
      { id: 'c', text: 'Run impact analysis on the dataflow and use Notify contacts', explain: 'Correct. Impact analysis lists dependents across workspaces and notifies their contacts, even ones you can’t access.' },
      { id: 'd', text: 'Certify the dataflow so owners see the change', explain: 'Endorsement doesn’t notify anyone.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS3-07',
    caseStudyId: t,
    machineId: 'remote-loom-control',
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'xmla-read-vs-readwrite',
    stem: 'Saltmarsh’s first deployment from Tabular Editor to the workspace fails with a write error, although querying the model works. What should the capacity admin change?',
    sources: [S.xmla],
    options: [
      { id: 'a', text: 'Turn off the large storage format', explain: 'Learn recommends large format on for XMLA writes.' },
      { id: 'b', text: 'Set the capacity’s XMLA Endpoint setting to Read Write', explain: 'Correct. Read-only is the default; deployments need Read Write.' },
      { id: 'c', text: 'Move the workspace to Pro', explain: 'Pro workspaces don’t support XMLA writes.' },
      { id: 'd', text: 'Disconnect the workspace from Git', explain: 'Git doesn’t block XMLA writes.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS3-08',
    caseStudyId: t,
    machineId: 'pattern-ledger',
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 1,
    stem: 'Saltmarsh’s lead developer is a workspace Member and tries to connect the workspace to the Azure DevOps repository, but can’t. Git integration is enabled for the organization. What is needed?',
    sources: [S.gitIntro, S.roles],
    options: [
      { id: 'a', text: 'A workspace Admin must make the connection', explain: 'Correct. Only Admins can connect a workspace to Git.' },
      { id: 'b', text: 'The developer needs a deployment pipeline first', explain: 'Pipelines aren’t a prerequisite for Git.' },
      { id: 'c', text: 'The repository must be moved to GitHub', explain: 'Azure DevOps is supported.' },
      { id: 'd', text: 'The model must be saved as .pbit', explain: 'Templates have nothing to do with the Git connection.' },
    ],
    answer: 'a',
  },

  // ── Lumenvale Utilities ───────────────────────────────────────────────
  {
    id: 'CS4-01',
    caseStudyId: b,
    machineId: 'dax-scale',
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 2,
    stem: 'Lumenvale’s finance team wants to check [Billed Amount] by region and month before publishing a change, without building a visual. Which DAX query should they run in DAX query view?',
    sources: [S.daxQueries, S.summarizeColumns],
    options: [
      { id: 'a', text: "EVALUATE SUMMARIZECOLUMNS('Region'[Region], 'Date'[Month], \"Billed\", [Billed Amount])", explain: 'Correct. SUMMARIZECOLUMNS groups by the columns and returns the measure for each group.' },
      { id: 'b', text: "SELECT Region, Month, [Billed Amount] FROM Sales", explain: 'This is SQL, not a DAX query.' },
      { id: 'c', text: "EVALUATE [Billed Amount] BY 'Region'[Region]", explain: 'A measure needs a table expression; BY isn’t DAX query syntax.' },
      { id: 'd', text: "DEFINE SUMMARIZECOLUMNS('Region'[Region], [Billed Amount])", explain: 'DEFINE holds definitions; a query needs EVALUATE.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS4-02',
    caseStudyId: b,
    machineId: 'recipe-book',
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'star-vs-snowflake',
    stem: 'Lumenvale’s tariffs are normalized into Tariff, TariffBand, and TariffFamily in MeterWH. The finance model needs a Family > Band > Tariff hierarchy, and hierarchies must come from single tables. What should you create in MeterWH?',
    sources: [S.dimTables, S.createView],
    options: [
      { id: 'a', text: 'A stored procedure that returns the three tables', explain: 'The model can’t import a procedure’s result as a table this way.' },
      { id: 'b', text: 'A view that joins the three tables into one tariff result', explain: 'Correct. Learn: expose a snowflake through a view that joins it into a denormalized result.' },
      { id: 'c', text: 'Three separate shortcuts to the tables', explain: 'Shortcuts keep three tables, so the hierarchy still can’t be built.' },
      { id: 'd', text: 'An inline table-valued function per level', explain: 'Separate functions still produce separate tables.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS4-03',
    caseStudyId: b,
    machineId: 'inspection-bench',
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 2,
    stem: 'In MeterWH, you need to join dbo.Readings to the Meters table in RegistryLH, which is in the same workspace and has been added to the Explorer. How should you reference the lakehouse table in T-SQL?',
    sources: [S.queryWarehouse],
    options: [
      { id: 'a', text: 'OPENROWSET over RegistryLH/Files', explain: 'The table is reachable directly by name; Files holds raw files.' },
      { id: 'b', text: 'A four-part name that includes the workspace', explain: 'Cross-database queries in the same workspace use three-part names.' },
      { id: 'c', text: 'RegistryLH.dbo.Meters', explain: 'Correct. Reference the added database’s table with a three-part name.' },
      { id: 'd', text: 'A KQL cross-cluster query', explain: 'KQL doesn’t run in the warehouse SQL editor.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS4-04',
    caseStudyId: b,
    machineId: 'jacquard-head',
    bulletIds: ['S1.5'],
    format: 'multi',
    difficulty: 2,
    trapPairId: 'calcgroup-vs-fieldparam',
    stem: 'Lumenvale needs YTD, prior-year, and YoY% versions of 40 measures, and amounts in each country’s currency format while charts keep plotting numbers. Which two features should you implement? Choose two.',
    sources: [S.calcGroups, S.dynamicFormat],
    options: [
      { id: 'a', text: 'FORMAT() inside each measure', explain: 'FORMAT returns text, which breaks charts.' },
      { id: 'b', text: 'A field parameter with 120 measures', explain: 'A field parameter switches fields; it doesn’t create the variants.' },
      { id: 'c', text: 'A calculation group for the time intelligence variants', explain: 'Correct. Calculation items apply YTD, PY, and YoY% to any measure.' },
      { id: 'd', text: 'Dynamic format strings for the currency formats', explain: 'Correct. Measures stay numeric while the format changes by context.' },
    ],
    answers: ['c', 'd'],
  },
  {
    id: 'CS4-05',
    caseStudyId: b,
    machineId: 'speed-governor',
    bulletIds: ['S2.2'],
    format: 'single',
    difficulty: 3,
    stem: "A slow Lumenvale measure is CALCULATE([Usage], FILTER('Meter', 'Meter'[Type] = \"Smart\")). Which rewrite follows Learn’s guidance and keeps any existing Type filter?",
    sources: [S.bpFilter],
    options: [
      { id: 'a', text: "CALCULATE([Usage], FILTER(ALL('Meter'), 'Meter'[Type] = \"Smart\"))", explain: 'This still iterates the table and also removes existing Meter filters.' },
      { id: 'b', text: "SUMX(FILTER('Meter', 'Meter'[Type] = \"Smart\"), [Usage])", explain: 'Iterating meters and evaluating the measure per row is slower.' },
      { id: 'c', text: "CALCULATE([Usage], 'Meter'[Type] = \"Smart\" || 'Meter'[Type] = \"Legacy\")", explain: 'This changes the result by adding Legacy meters.' },
      { id: 'd', text: "CALCULATE([Usage], KEEPFILTERS('Meter'[Type] = \"Smart\"))", explain: 'Correct. A Boolean column filter is optimized, and KEEPFILTERS keeps existing Type filters.' },
    ],
    answer: 'd',
  },
  {
    id: 'CS4-06',
    caseStudyId: b,
    machineId: 'warp-frame',
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 3,
    stem: 'In Lumenvale’s model, a meter can be shared by several customers, and a customer can have several meters. Readings relate to Meter. How should Customer filter readings?',
    sources: [S.manyToMany],
    options: [
      { id: 'a', text: 'Relate Customer directly to Readings', explain: 'Readings have no customer key; they belong to meters.' },
      { id: 'b', text: 'Relate Customer to Meter with a many-to-many relationship on MeterID', explain: 'Learn doesn’t recommend relating many-to-many dimensions directly.' },
      { id: 'c', text: 'Add a customer-meter bridging table with two one-to-many relationships, one set to Both', explain: 'Correct. A bridging table resolves the many-to-many dimensions so Customer filters reach Readings.' },
      { id: 'd', text: 'Merge Customer into the Meter table', explain: 'This duplicates meters per customer and breaks the Meter key.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS4-07',
    caseStudyId: b,
    machineId: 'seal-and-stamp',
    bulletIds: ['M1.5'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'endorse-vs-label',
    stem: 'Lumenvale wants RegistryLH marked as the single authoritative source of meter data so that teams stop using copies. What should you apply?',
    sources: [S.endorsement],
    options: [
      { id: 'a', text: 'The Promoted badge', explain: 'Promoted means ready to share, not authoritative.' },
      { id: 'b', text: 'A Confidential sensitivity label', explain: 'Labels state sensitivity, not authority.' },
      { id: 'c', text: 'A deployment pipeline rule', explain: 'Rules change settings between stages.' },
      { id: 'd', text: 'The Master data badge', explain: 'Correct. Master data marks a data item as the authoritative source for core data.' },
    ],
    answer: 'd',
  },
  {
    id: 'CS4-08',
    caseStudyId: b,
    machineId: 'pattern-book',
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'pbi-files',
    stem: 'Lumenvale’s new report authors should start from a standard report with the finance model and queries, but no data. What should you give them?',
    sources: [S.templates],
    options: [
      { id: 'a', text: 'A Power BI template (.pbit)', explain: 'Correct. A template has report pages, model definition, and queries without data.' },
      { id: 'b', text: 'A .pbids file', explain: 'A .pbids holds only a data source connection.' },
      { id: 'c', text: 'A copy of the published .pbix', explain: 'A .pbix includes imported data.' },
      { id: 'd', text: 'Read permission on the model', explain: 'Permissions don’t give a starting report.' },
    ],
    answer: 'a',
  },
]

export const caseStudies: CaseStudy[] = [...firstCaseStudies, ...moreCaseStudies]
export const caseQuestions: Question[] = [...firstCaseQuestions, ...moreCaseQuestions]
