import { S } from './sources'
import type { CaseStudy, Question } from './types'

/** Step 7: two more fictional case studies (names checked against a web search for real companies). */
export const moreCaseStudies: CaseStudy[] = [
  {
    id: 'case-corrowmere',
    company: 'Corrowmere Seed Cooperative',
    title: 'Corrowmere Seed Cooperative: field sensors and seed orders',
    summary: 'A farming cooperative wants one analytics model that combines live soil-sensor data with seed orders, secured by region and released through a controlled lifecycle.',
    environment: [
      'Soil-moisture sensors stream readings into an eventhouse with a KQL database named SensorDB, which already holds several months of data.',
      'Seed orders are loaded into a warehouse named OrdersWH in the Operations workspace. The source system resends changed orders, so staging contains several versions of some orders.',
      'Grower reference data lives in a lakehouse named AgronomyLH in a separate Research workspace that IT manages.',
      'Regional sales targets are kept by analysts in a spreadsheet.',
      'Semantic models connect to their data with a fixed identity, so report readers don’t need their own permissions on the underlying data.',
      'The Operations workspace is connected to a GitHub repository, and a deployment pipeline moves content from Development to Test to Production.',
    ],
    requirements: [
      'Agronomists must see hourly average soil moisture per field for the last week.',
      'The semantic model must use sensor data, orders, and the regional targets together, with in-memory query performance.',
      'Sensor data must not be copied into another store to make it available to the model.',
      'Orders must be loaded once per order, using the latest version.',
      'Regional managers, who are workspace Viewers, must see only their own region’s orders in reports.',
      'Grower data from AgronomyLH must be joined with orders without copying it.',
    ],
    constraints: [
      'Analysts can’t write to AgronomyLH or OrdersWH.',
      'Changes merged in GitHub must reach the Development workspace before they are deployed onward.',
    ],
  },
  {
    id: 'case-brindlecombe',
    company: 'Brindlecombe Transit',
    title: 'Brindlecombe Transit: ridership and fares',
    summary: 'A city transit authority is scaling a large ridership model, adding live fare data, and tightening governance as more teams build on it.',
    environment: [
      'A ridership semantic model in Import mode holds six years of tap-on events in a fact table partitioned by tap date.',
      'The model is about 7 GB today and is expected to exceed 10 GB within a year. It is in a workspace on a Fabric F capacity.',
      'Fare tables in a SQL source change every few minutes.',
      'A stop dimension records stop names, and stops are sometimes renamed.',
      'Model developers use Tabular Editor and DAX Studio through the XMLA endpoint.',
      'The ridership data carries a Microsoft Purview sensitivity label with protection.',
    ],
    requirements: [
      'Each refresh must reload only the last three days of taps while keeping six years of history.',
      'Fare figures in reports must always be current, while stop and route dimensions stay fast to filter.',
      'Trips must still show the stop name that was in use when the trip happened.',
      'Planners must switch one chart between Boardings, Revenue, and On-time % with a slicer.',
      'Before changing a column in the fares warehouse, owners of every dependent report must be warned.',
    ],
    constraints: [
      'Developers can query the model from DAX Studio, but saving changes from Tabular Editor fails.',
      'Some reports that depend on the fares warehouse live in other departments’ workspaces.',
      'Data exports must keep the label’s protection.',
    ],
  },
]

const r = 'case-corrowmere'
const t = 'case-brindlecombe'

export const moreCaseQuestions: Question[] = [
  // ── Corrowmere Seed Cooperative ─────────────────────────────────────
  {
    id: 'CS5-01',
    caseStudyId: r,
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'onelake-availability-vs-integration',
    stem: 'Corrowmere’s semantic model must use the sensor readings in SensorDB, including the months already stored, without copying them into another store. What should you do?',
    sources: [S.eventhouseOneLake, S.modelOneLake],
    options: [
      { id: 'a', text: 'Turn on OneLake integration in the semantic model’s settings and refresh it', explain: 'Semantic model OneLake integration exports an Import model’s tables to OneLake; it doesn’t expose eventhouse data.' },
      { id: 'b', text: 'Turn on OneLake availability for SensorDB and choose Apply to existing tables', explain: 'Correct. OneLake availability creates a logical Delta copy of KQL data, with no extra storage cost, that other engines such as Direct Lake can read; applying it to existing tables back-fills the stored months.' },
      { id: 'c', text: 'Turn on OneLake availability for SensorDB at the database level only', explain: 'At database level only new tables are included unless you apply it to existing tables, so the stored readings would be missing.' },
      { id: 'd', text: 'Copy the readings into OrdersWH with a pipeline every hour', explain: 'That copies the data, which the requirements rule out.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS5-02',
    caseStudyId: r,
    machineId: 'direct-lake-shuttle',
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'Corrowmere’s model must combine the SensorDB data (with OneLake availability on), tables from OrdersWH, and the analysts’ regional targets spreadsheet, with in-memory performance. Which storage design should you use?',
    sources: [S.directLake, S.composite],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints over OrdersWH, with the targets as an Import table', explain: 'Direct Lake on SQL uses a single source item, doesn’t support KQL databases, and can’t mix storage modes in the same model.' },
      { id: 'b', text: 'Import mode for every table, refreshed hourly', explain: 'Import copies the sensor data into the model, and Learn positions Direct Lake for large Fabric data already in Delta format.' },
      { id: 'c', text: 'Direct Lake on OneLake for the sensor and order tables, with the targets added as an Import table', explain: 'Correct. Direct Lake on OneLake can use tables from more than one Fabric item, supports KQL databases with OneLake availability, and can be combined with Import tables.' },
      { id: 'd', text: 'DirectQuery to SensorDB and OrdersWH, with the targets as an Import table', explain: 'DirectQuery sends every query to the sources, giving up the in-memory performance the requirement asks for.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS5-03',
    caseStudyId: r,
    machineId: 'tension-meter',
    bulletIds: ['P3.3'],
    format: 'dropdown',
    difficulty: 2,
    stem: 'Corrowmere’s agronomists need hourly average soil moisture per field for the last week from SensorDB. Complete the KQL query.',
    sources: [S.kqlSummarize, S.kqlBin, S.kqlWhere],
    language: 'kql',
    code: 'SoilReadings\n| [[1]] Timestamp > ago(7d)\n| summarize AvgMoisture = [[2]](Moisture) by FieldId, [[3]](Timestamp, 1h)',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'where', explain: 'Correct. where filters rows to the last seven days.' },
          { id: 'b', text: 'project', explain: 'project chooses columns; it doesn’t filter rows.' },
          { id: 'c', text: 'extend', explain: 'extend adds columns; it doesn’t filter rows.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'sum', explain: 'sum adds the readings instead of averaging them.' },
          { id: 'b', text: 'dcount', explain: 'dcount counts distinct values.' },
          { id: 'c', text: 'avg', explain: 'Correct. avg() returns the average for each group.' },
        ],
        answer: 'c',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'ago', explain: 'ago() returns a point in time; it doesn’t group values.' },
          { id: 'b', text: 'bin', explain: 'Correct. bin() groups timestamps into 1-hour ranges.' },
          { id: 'c', text: 'take', explain: 'take is an operator that returns sample rows, not a grouping function.' },
        ],
        answer: 'b',
      },
    ],
  },
  {
    id: 'CS5-04',
    caseStudyId: r,
    machineId: 'carding-machine',
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'where-having-qualify',
    stem: 'Corrowmere’s staging.Orders table in OrdersWH holds several versions of some orders, each with a LoadedAt timestamp. Which T-SQL keeps only the latest version of each order?',
    sources: [S.qualify],
    options: [
      { id: 'a', text: 'SELECT * FROM staging.Orders WHERE ROW_NUMBER() OVER (PARTITION BY OrderID ORDER BY LoadedAt DESC) = 1', explain: 'WHERE runs before window functions, so it can’t reference ROW_NUMBER().' },
      { id: 'b', text: 'SELECT * FROM staging.Orders QUALIFY ROW_NUMBER() OVER (PARTITION BY OrderID ORDER BY LoadedAt DESC) = 1', explain: 'Correct. QUALIFY filters after window functions are evaluated, so it keeps row 1 per order without a subquery.' },
      { id: 'c', text: 'SELECT DISTINCT * FROM staging.Orders', explain: 'Versions differ in LoadedAt and other values, so DISTINCT keeps them all.' },
      { id: 'd', text: 'SELECT OrderID, MAX(LoadedAt) FROM staging.Orders GROUP BY OrderID HAVING COUNT(*) > 1', explain: 'This returns only orders with several versions, and only two columns.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS5-05',
    caseStudyId: r,
    machineId: 'thread-sieves',
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 3,
    stem: 'Corrowmere’s regional managers are Viewers in the workspace and read reports built on the Direct Lake on OneLake model. Each must see only their own region’s orders. Where should the row filter be defined?',
    sources: [S.modelRls, S.dlManage],
    options: [
      { id: 'a', text: 'A row-level security security policy on the orders table in OrdersWH', explain: 'Direct Lake on OneLake doesn’t check permissions through the SQL analytics endpoint, so a SQL policy isn’t how this model filters rows.' },
      { id: 'b', text: 'A filter on each report page', explain: 'Report filters aren’t security; users with access to the model can still query other regions.' },
      { id: 'c', text: 'Object-level security on the Region column', explain: 'OLS hides objects such as columns; it doesn’t filter rows.' },
      { id: 'd', text: 'A row-level security role in the semantic model whose filter keeps the manager’s region', explain: 'Correct. Semantic model RLS restricts users with Viewer permissions, which is what the managers are.' },
    ],
    answer: 'd',
  },
  {
    id: 'CS5-06',
    caseStudyId: r,
    machineId: 'thread-intake',
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'Corrowmere must join grower data from AgronomyLH (Research workspace) with orders in the Operations workspace, without copying it. Analysts can’t write to AgronomyLH. What should you create?',
    sources: [S.shortcuts, S.queryWarehouse],
    options: [
      { id: 'a', text: 'A cross-database query from OrdersWH to AgronomyLH using a three-part name', explain: 'Three-part names work only within the same workspace.' },
      { id: 'b', text: 'A Copy job from AgronomyLH into OrdersWH', explain: 'A Copy job makes a copy, which the requirement rules out.' },
      { id: 'c', text: 'A OneLake shortcut in a lakehouse in the Operations workspace that points to the AgronomyLH tables', explain: 'Correct. A shortcut references the data in place, needs no write access to the target, and can then be joined from the same workspace.' },
      { id: 'd', text: 'Mirroring of AgronomyLH into the Operations workspace', explain: 'Mirroring replicates operational databases into OneLake; it isn’t used to reference another lakehouse.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS5-07',
    caseStudyId: r,
    machineId: 'pattern-ledger',
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'commit-vs-update',
    stem: 'A pull request that changes a pipeline definition was merged into the branch connected to Corrowmere’s Development workspace. The pipeline now shows Update required in the workspace. What should a developer do before deploying to Test?',
    sources: [S.gitProcess],
    options: [
      { id: 'a', text: 'Commit the workspace’s pipeline to the branch', explain: 'Commit sends workspace changes to Git and would try to overwrite the merged change.' },
      { id: 'b', text: 'Update the workspace from Git', explain: 'Correct. Update brings the branch’s latest commit into the workspace, which is what Update required asks for.' },
      { id: 'c', text: 'Disconnect and reconnect the workspace', explain: 'Reconnecting isn’t needed; Update applies the merged change.' },
      { id: 'd', text: 'Deploy from Development to Test; the pipeline picks up the change automatically', explain: 'Deployment copies the workspace’s current item, which doesn’t yet include the merged change.' },
    ],
    answer: 'b',
  },
  // ── Brindlecombe Transit ────────────────────────────────────────────
  {
    id: 'CS6-01',
    caseStudyId: t,
    machineId: 'batch-winder',
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'archive-vs-refresh-period',
    stem: 'Brindlecombe’s tap fact table must keep six years of history while each refresh reloads only the last three days. Which incremental refresh setup meets the requirement?',
    sources: [S.incrementalCfg, S.incremental],
    options: [
      { id: 'a', text: 'Archive data starting 3 days before refresh date; incrementally refresh data starting 6 years before refresh date', explain: 'The periods are swapped: the archive period is how much history to keep, and the refresh period is what each refresh reloads.' },
      { id: 'b', text: 'Filter TapDate >= RangeStart and TapDate <= RangeEnd; archive 6 years; refresh 3 days', explain: 'Equal-to on both parameters can put a boundary row in two partitions and duplicate data.' },
      { id: 'c', text: 'Filter TapDate >= RangeStart and TapDate < RangeEnd; archive 6 years; refresh 3 days', explain: 'Correct. The filter uses equal-to on only one parameter, the archive period keeps six years, and the refresh period reloads the last three days.' },
      { id: 'd', text: 'Two parameters named TapFrom and TapTo; archive 6 years; refresh 3 days', explain: 'Incremental refresh requires the reserved, case-sensitive names RangeStart and RangeEnd.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS6-02',
    caseStudyId: t,
    machineId: 'wide-beam',
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 2,
    stem: 'Brindlecombe’s ridership model will grow past 10 GB through refreshes in the service, and developers manage it through the XMLA endpoint. What should you configure?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'Large semantic model storage format for the model', explain: 'Correct. It is required for models beyond 10 GB and recommended for XMLA write operations.' },
      { id: 'b', text: 'Switch the fact table to Direct Lake', explain: 'The model is an Import model fed by refreshes; switching modes isn’t what the size requirement asks.' },
      { id: 'c', text: 'Publish the full history from Power BI Desktop', explain: 'Publishing from Desktop is capped at 10 GB; the model grows through refresh in the service.' },
      { id: 'd', text: 'Move the workspace to Pro', explain: 'Pro workspaces don’t support XMLA write operations and don’t lift the size limit.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS6-03',
    caseStudyId: t,
    machineId: 'remote-loom-control',
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'xmla-read-vs-readwrite',
    stem: 'Brindlecombe’s developers can query the model from DAX Studio, but saving changes from Tabular Editor through the XMLA endpoint fails. The developers are workspace Contributors. What should be changed?',
    sources: [S.xmla],
    options: [
      { id: 'a', text: 'Give each developer Build permission on the model', explain: 'Contributors already have Write permission on models over XMLA; the endpoint setting is the blocker.' },
      { id: 'b', text: 'Set the capacity’s XMLA Endpoint setting to Read Write', explain: 'Correct. Read-only is the default and allows queries; metadata changes such as Tabular Editor saves need Read Write, set for the capacity.' },
      { id: 'c', text: 'Promote the developers to workspace Admin', explain: 'Contributors and above already have Write permission over XMLA, so the role isn’t the problem.' },
      { id: 'd', text: 'Turn off large semantic model storage format', explain: 'Large format is recommended for XMLA writes; turning it off doesn’t enable them.' },
    ],
    answer: 'b',
  },
  {
    id: 'CS6-04',
    caseStudyId: t,
    machineId: 'double-loom',
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dual-vs-hybrid',
    stem: 'Brindlecombe adds the fare tables in DirectQuery so fare figures are always current. Stop and route dimensions come from the same SQL source and must stay fast to filter, with regular relationships to the fares. Which storage mode should the dimensions use?',
    sources: [S.modes, S.composite],
    options: [
      { id: 'a', text: 'Import', explain: 'Import dimensions sit in a different source group from DirectQuery facts, so the relationships would be limited.' },
      { id: 'b', text: 'DirectQuery', explain: 'DirectQuery dimensions keep relationships regular but give up in-memory speed for filtering.' },
      { id: 'c', text: 'Dual', explain: 'Correct. Dual lets the engine serve the dimension from cache or by DirectQuery per query, keeping relationships with DirectQuery facts regular and filtering fast.' },
      { id: 'd', text: 'Hybrid', explain: 'A hybrid table is a partitioned fact table, usually created through an incremental refresh policy with real-time DirectQuery; it isn’t a storage mode for dimensions.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS6-05',
    caseStudyId: t,
    machineId: 'ripple-map',
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'lineage-vs-impact',
    stem: 'Before changing a column in Brindlecombe’s fares warehouse, owners of every dependent report must be warned, including reports in other departments’ workspaces. What should you use?',
    sources: [S.impact, S.lineage],
    options: [
      { id: 'a', text: 'Lineage view in the fares workspace', explain: 'Lineage view doesn’t show downstream items in other workspaces.' },
      { id: 'b', text: 'The OneLake catalog’s Explore tab', explain: 'Listing downstream items across workspaces and notifying their contacts is what impact analysis does.' },
      { id: 'c', text: 'Impact analysis on the warehouse with All downstream items, then Notify contacts', explain: 'Correct. Impact analysis lists downstream items across workspaces, and Notify contacts emails their workspaces’ contacts.' },
      { id: 'd', text: 'A sensitivity label on the warehouse', explain: 'Labels classify sensitivity; they don’t warn report owners.' },
    ],
    answer: 'c',
  },
  {
    id: 'CS6-06',
    caseStudyId: t,
    machineId: 'seal-and-stamp',
    bulletIds: ['M1.4'],
    format: 'multi',
    difficulty: 2,
    stem: 'Brindlecombe’s ridership data carries a sensitivity label with protection, and exports must keep it. Which two export paths keep the label’s protection? Choose two.',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'Export to PDF', explain: 'Correct. Protection travels with PDF exports.' },
      { id: 'b', text: 'Export to CSV', explain: 'CSV exports aren’t protected.' },
      { id: 'c', text: 'Sharing with a partner organization’s tenant', explain: 'Label access control works only in the tenant where it was applied.' },
      { id: 'd', text: 'Export to Excel', explain: 'Correct. Protection travels with Excel exports.' },
    ],
    answers: ['a', 'd'],
  },
  {
    id: 'CS6-07',
    caseStudyId: t,
    machineId: 'weave-planner',
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'scd1-vs-scd2',
    stem: 'Brindlecombe’s trips must still show the stop name that was in use when each trip happened, even after a stop is renamed. How should the stop dimension handle renames?',
    sources: [S.dimTables, S.loadTables],
    options: [
      { id: 'a', text: 'As SCD type 2: expire the current row and insert a new version with a new surrogate key', explain: 'Correct. Type 2 keeps history, so facts keep pointing at the version that was true when they happened.' },
      { id: 'b', text: 'As SCD type 1: overwrite the name', explain: 'Type 1 loses history, so every trip would show the new name.' },
      { id: 'c', text: 'Truncate and reload the stop dimension nightly', explain: 'Learn warns that truncating a dimension with generated surrogate keys breaks fact references and type 2 history.' },
      { id: 'd', text: 'Store the stop name in the trip fact and drop the dimension', explain: 'That abandons the star schema the warehouse is built on.' },
    ],
    answer: 'a',
  },
  {
    id: 'CS6-08',
    caseStudyId: t,
    machineId: 'jacquard-head',
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'calcgroup-vs-fieldparam',
    stem: 'Brindlecombe’s planners must switch one chart between Boardings, Revenue, and On-time % with a slicer. What should you add to the model?',
    sources: [S.fieldParams, S.calcGroups],
    options: [
      { id: 'a', text: 'A calculation group with Boardings, Revenue, and On-time % items', explain: 'A calculation group applies one calculation to whichever measure is selected; it doesn’t let readers pick which measure the chart shows.' },
      { id: 'b', text: 'A field parameter listing the three measures, used in a slicer and the chart', explain: 'Correct. A field parameter lets readers switch which fields a visual shows.' },
      { id: 'c', text: 'A dynamic format string on each measure', explain: 'Dynamic format strings change display formats, not which measure is shown.' },
      { id: 'd', text: 'Three bookmarks and three charts', explain: 'Bookmarks can mimic switching, but the model-based way to let a slicer switch measures is a field parameter.' },
    ],
    answer: 'b',
  },
]
