import type { Question } from './types'

const L = 'https://learn.microsoft.com/en-us/'
const OVERVIEW = `${L}fabric/fundamentals/microsoft-fabric-overview`
const TERMS = `${L}fabric/fundamentals/fabric-terminology`
const ONELAKE = `${L}fabric/onelake/onelake-overview`
const LICENSES = `${L}fabric/enterprise/licenses`
const THROTTLING = `${L}fabric/enterprise/throttling`
const TRIAL = `${L}fabric/fundamentals/fabric-trial`
const DECISION = `${L}fabric/fundamentals/decision-guide-data-store`
const LAKEHOUSE = `${L}fabric/data-engineering/lakehouse-overview`
const WAREHOUSE = `${L}fabric/data-warehouse/data-warehousing`
const EVENTHOUSE = `${L}fabric/real-time-intelligence/eventhouse`
const DECIDE_LH_WH = `${L}fabric/fundamentals/decision-guide-lakehouse-warehouse`
const WORKSPACES = `${L}fabric/fundamentals/workspaces`
const DATA_FACTORY = `${L}fabric/data-factory/data-factory-overview`
const MEDALLION = `${L}fabric/onelake/onelake-medallion-lakehouse-architecture`
const PIPELINES_INTRO = `${L}fabric/cicd/deployment-pipelines/intro-to-deployment-pipelines`
const DAX_QUERY_VIEW = `${L}power-bi/transform-model/dax-query-view`

export const orientationQuestions: Question[] = [
  // ── Founding Charter ─────────────────────────────────────────────────
  {
    id: 'FO-01',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'Your company is adopting Microsoft Fabric. Data engineers will use Spark, analysts will use T-SQL, and report authors will use Power BI. You need all three groups to work on the same copy of the data. Which Fabric component provides the shared storage?',
    sources: [OVERVIEW, ONELAKE],
    options: [
      { id: 'a', text: 'OneLake', explain: 'Correct. Every Fabric workload stores and reads data in OneLake, so one copy serves Spark, T-SQL, and Power BI without duplication.' },
      { id: 'b', text: 'The Real-Time hub', explain: 'The Real-Time hub is the tenant-wide place to discover and ingest streaming data and events, not the storage layer for all workloads.' },
      { id: 'c', text: 'A Fabric capacity', explain: 'A capacity provides compute (capacity units), not storage. Workspaces run on capacities, but data lives in OneLake.' },
      { id: 'd', text: 'The OneLake catalog', explain: 'The OneLake catalog is for discovering and governing items. It doesn’t store the data itself.' },
    ],
    answer: 'a',
  },
  {
    id: 'FO-02',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'match',
    difficulty: 1,
    stem: 'You are explaining Fabric workloads to a new team. Match each task to the workload that provides it.',
    sources: [OVERVIEW, TERMS, DATA_FACTORY],
    prompts: [
      { id: 'p1', text: 'Connect to many data sources with built-in connectors and orchestrate data movement with pipelines' },
      { id: 'p2', text: 'Process large datasets with Apache Spark notebooks' },
      { id: 'p3', text: 'Analyze streaming IoT and log data as it arrives' },
      { id: 'p4', text: 'Build an enterprise warehouse developed with T-SQL' },
    ],
    choices: [
      { id: 'c1', text: 'Data Factory' },
      { id: 'c2', text: 'Data Engineering' },
      { id: 'c3', text: 'Real-Time Intelligence' },
      { id: 'c4', text: 'Data Warehouse' },
      { id: 'c5', text: 'Data Science' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Data Factory provides the connectors, pipelines, and Dataflow Gen2 used for data integration.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Data Engineering provides Apache Spark with notebooks for large-scale processing.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Real-Time Intelligence analyzes data in motion such as IoT readings, logs, and clickstreams.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Fabric Data Warehouse is a T-SQL relational warehouse. Data Science (the unused choice) is for building ML models.' },
    ],
  },
  {
    id: 'FO-03',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are reviewing statements in a Fabric onboarding document. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [OVERVIEW, ONELAKE, TERMS, PIPELINES_INTRO],
    statements: [
      { id: 's1', text: 'Each user needs their own Azure subscription before they can use Fabric.', answer: false, explain: 'No. Fabric is SaaS and OneLake hides Azure details; Learn states you don’t need an Azure account to use Fabric.' },
      { id: 's2', text: 'A table created with T-SQL in a warehouse can be read by a Spark notebook without exporting or copying it.', answer: true, explain: 'Yes. All engines store tables in OneLake in Delta format, so Spark reads the warehouse’s tables directly.' },
      { id: 's3', text: 'A Data Factory pipeline and a deployment pipeline are the same kind of item.', answer: false, explain: 'No. Learn notes that data pipelines (orchestration) are different from deployment pipelines (lifecycle promotion between stages).' },
    ],
  },

  // ── Water Wheel ──────────────────────────────────────────────────────
  {
    id: 'FO-04',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'Your organization will publish Power BI reports to a Fabric workspace. Most report consumers have only a Microsoft Fabric free license and will be given the Viewer role. You need them to view the reports without buying more per-user licenses, at the lowest cost. What should you assign the workspace to?',
    sources: [LICENSES],
    options: [
      { id: 'a', text: 'F32', explain: 'On F SKUs smaller than F64, every viewer of Power BI content needs a Pro, PPU, or individual trial license.' },
      { id: 'b', text: 'F64', explain: 'Correct. On F64 or larger, users with only a free license and the Viewer role can view Power BI content.' },
      { id: 'c', text: 'F2', explain: 'F2 is the smallest F SKU. Free-license viewers still need Pro, PPU, or a trial license to view Power BI content there.' },
      { id: 'd', text: 'A Premium Per User (PPU) workspace', explain: 'A PPU workspace requires each viewer to have a PPU license (or individual trial), and it isn’t a Fabric capacity.' },
    ],
    answer: 'b',
  },
  {
    id: 'FO-05',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'A capacity administrator is investigating slow reports during a large overnight data load. For each statement about Fabric capacity behavior, select Yes if it is true. Otherwise, select No.',
    sources: [THROTTLING],
    statements: [
      { id: 's1', text: 'Background operations, such as scheduled refreshes, have their CU usage smoothed over 24 hours.', answer: true, explain: 'Yes. Fabric smooths background operations over a 24-hour period.' },
      { id: 's2', text: 'As soon as utilization goes above 100%, Fabric rejects all new requests.', answer: false, explain: 'No. Overage protection allows 10 minutes of future capacity first; throttling then escalates in stages (delays, then rejecting interactive, then rejecting all).' },
      { id: 's3', text: 'An overloaded capacity slows down workspaces that are assigned to other capacities in the same tenant.', answer: false, explain: 'No. Throttling applies at the capacity level; other capacities can keep running normally.' },
    ],
  },
  {
    id: 'FO-06',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'Your Fabric tenant has dozens of workspaces owned by Finance, Marketing, and Operations. You need to group the workspaces by business area so that Fabric administrators can delegate management and apply governance above the workspace level. What should you use?',
    sources: [TERMS, ONELAKE, WORKSPACES],
    options: [
      { id: 'a', text: 'A separate capacity for each business area', explain: 'Capacities control compute and billing. They don’t provide a governance grouping for delegating management.' },
      { id: 'b', text: 'Workspace folders', explain: 'Folders organize items inside a single workspace, not workspaces across the tenant.' },
      { id: 'c', text: 'Domains', explain: 'Correct. Domains group workspaces into business areas so admins can delegate management and apply governance policies above the workspace level.' },
      { id: 'd', text: 'OneLake shortcuts', explain: 'Shortcuts reference data in other locations. They don’t organize workspaces or delegate administration.' },
    ],
    answer: 'c',
  },

  // ── Three Vats ───────────────────────────────────────────────────────
  {
    id: 'FO-07',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'A team of SQL developers needs a Fabric data store for curated sales data. Their load procedures update several tables and must commit or roll back all the changes together. Which data store should they use?',
    sources: [DECIDE_LH_WH, WAREHOUSE, EVENTHOUSE],
    trapPairId: 'stores',
    options: [
      { id: 'a', text: 'A lakehouse', explain: 'A lakehouse doesn’t support multi-table transactions, and it is developed mainly with Spark.' },
      { id: 'b', text: 'The SQL analytics endpoint of a lakehouse', explain: 'The SQL analytics endpoint is read-only for data, so T-SQL there can’t insert, update, or delete rows.' },
      { id: 'c', text: 'An eventhouse', explain: 'An eventhouse targets streaming, time-based event data queried with KQL, not transactional T-SQL loads.' },
      { id: 'd', text: 'A warehouse', explain: 'Correct. A warehouse is developed with T-SQL and supports full multi-table ACID transactions.' },
    ],
    answer: 'd',
  },
  {
    id: 'FO-08',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'You uploaded several CSV files to the Files area of a lakehouse. Analysts report that the data doesn’t appear when they connect to the lakehouse’s SQL analytics endpoint. You need the data to be queryable from the endpoint. What should you do?',
    sources: [LAKEHOUSE],
    trapPairId: 'stores',
    options: [
      { id: 'a', text: 'Load the CSV data into a Delta table in the Tables area', explain: 'Correct. Only Delta tables appear in the SQL analytics endpoint; CSV and Parquet files in Files can’t be queried there until converted.' },
      { id: 'b', text: 'Give the analysts the Contributor workspace role', explain: 'This is about format and location, not permissions. Even workspace admins can’t query CSV files through the endpoint.' },
      { id: 'c', text: 'Turn on OneLake availability for the lakehouse', explain: 'OneLake availability is an eventhouse (KQL database) setting, not a lakehouse one. The SQL analytics endpoint shows only Delta tables, so the CSV files must be loaded into a Delta table.' },
      { id: 'd', text: 'Create a shortcut to the CSV folder in the Files area', explain: 'Files-area shortcuts aren’t discovered as tables, and the data still isn’t in Delta format.' },
    ],
    answer: 'a',
  },
  {
    id: 'FO-09',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'match',
    difficulty: 2,
    stem: 'You are designing a Fabric solution with three workloads. Match each workload to the data store you should use.',
    sources: [DECISION, DECIDE_LH_WH, EVENTHOUSE],
    trapPairId: 'stores',
    prompts: [
      { id: 'p1', text: 'High-volume telemetry events analyzed interactively with KQL within seconds of arrival' },
      { id: 'p2', text: 'Raw JSON, images, and Parquet files processed by data engineers in PySpark notebooks' },
      { id: 'p3', text: 'A star schema for BI built and loaded by SQL developers with T-SQL stored procedures' },
    ],
    choices: [
      { id: 'c1', text: 'Eventhouse' },
      { id: 'c2', text: 'Lakehouse' },
      { id: 'c3', text: 'Warehouse' },
      { id: 'c4', text: 'SQL database in Fabric' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Eventhouses are built for streaming, time-based event data queried with KQL.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Lakehouses hold structured and unstructured data and are developed mainly with Spark.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Warehouses are T-SQL-first and suit dimensional models for BI. SQL database in Fabric (unused) also runs T-SQL, but Learn positions it for operational OLTP workloads, not enterprise warehousing and SQL-based BI.' },
    ],
  },

  // ── Mill Lease ───────────────────────────────────────────────────────
  {
    id: 'FO-10',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'Your 60-day Fabric trial capacity expired yesterday. The workspace contains a lakehouse and notebooks you want to keep using. What should you do?',
    sources: [TRIAL],
    options: [
      { id: 'a', text: 'Export each item to a .pbix file before the content is deleted', explain: 'Learn’s way to keep trial content is to reassign the workspace to a paid capacity within 7 days; exporting items isn’t part of that guidance.' },
      { id: 'b', text: 'Assign the workspace to a paid F or P capacity within 7 days', explain: 'Correct. Content stays in OneLake for 7 days after the trial ends and is reactivated when the workspace is assigned to a paid F or P capacity.' },
      { id: 'c', text: 'Start a new Power BI individual trial', explain: 'A Power BI individual trial is a per-user license. It doesn’t give the workspace the capacity that non-Power BI items need.' },
      { id: 'd', text: 'Change the workspace type to Pro', explain: 'The workspace is already reverted to Pro when the trial ends, and Pro can’t run non-Power BI Fabric items.' },
    ],
    answer: 'b',
  },
  {
    id: 'FO-11',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'yesno',
    difficulty: 1,
    stem: 'You are planning hands-on labs on a Fabric trial capacity. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [TRIAL],
    statements: [
      { id: 's1', text: 'When the trial ends, workspaces assigned to the trial capacity are reassigned to Pro.', answer: true, explain: 'Yes. Learn: workspaces assigned to the trial capacity are reassigned to Pro, and non-Power BI items become inaccessible until the workspace gets a paid F or P capacity.' },
      { id: 's2', text: 'You can use Copilot in Fabric on the trial capacity.', answer: false, explain: 'No. Copilot isn’t supported on trial capacities.' },
      { id: 's3', text: 'You can store up to 1 TB of data in OneLake during the trial.', answer: true, explain: 'Yes. The trial allows up to 1 TB of OneLake storage.' },
    ],
  },
  {
    id: 'FO-12',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'order',
    difficulty: 1,
    stem: 'You need to start a Fabric trial from the Account manager and begin building items in it. Put the steps in order.',
    sources: [TRIAL],
    items: [
      { id: 'i1', text: 'Create a workspace and set its workspace type to Trial', explain: 'Last: workspaces must use the Trial type so their items run on the trial capacity.' },
      { id: 'i2', text: 'Select Start trial in the Account manager', explain: 'Second: Start trial is in the Account manager.' },
      { id: 'i3', text: 'Open the Account manager from your profile picture', explain: 'First: the Account manager opens from the photo in the upper-right corner.' },
      { id: 'i4', text: 'Choose the trial capacity region and select Activate', explain: 'Third: you choose the trial capacity region (the default is your home region, which you can keep or change) and select Activate.' },
    ],
    answerOrder: ['i3', 'i2', 'i4', 'i1'],
  },
  // ── Step 4 additions: 5 more per machine ────────────────────────────
  // Founding Charter
  {
    id: 'FO-13',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'A manager asks how Microsoft Fabric is delivered. You need to describe its service model in one phrase. What should you say?',
    sources: [OVERVIEW],
    options: [
      { id: 'a', text: 'Infrastructure as a service that you patch yourself', explain: 'Fabric needs no infrastructure management; it isn’t IaaS.' },
      { id: 'b', text: 'Software as a service (SaaS)', explain: 'Correct. Learn: Fabric is delivered as a software-as-a-service (SaaS) platform.' },
      { id: 'c', text: 'An on-premises server product', explain: 'Fabric runs in the cloud as a SaaS platform.' },
      { id: 'd', text: 'A set of separate Azure services you integrate', explain: 'Learn says Fabric removes the need to manually integrate separate services.' },
    ],
    answer: 'b',
  },
  {
    id: 'FO-14',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'Data scientists want to build, deploy, and track machine learning models, with experiment tracking and a model registry, inside Fabric. Which workload should they use?',
    sources: [OVERVIEW],
    options: [
      { id: 'a', text: 'Real-Time Intelligence', explain: 'Real-Time Intelligence analyzes data in motion, such as IoT readings and logs.' },
      { id: 'b', text: 'Data Factory', explain: 'Data Factory ingests, prepares, and transforms data.' },
      { id: 'c', text: 'Fabric Data Science', explain: 'Correct. It builds, deploys, and operationalizes ML models, with built-in experiment tracking and model registry.' },
      { id: 'd', text: 'Fabric Data Warehouse', explain: 'The warehouse provides SQL storage and querying, not ML model management.' },
    ],
    answer: 'c',
  },
  {
    id: 'FO-15',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'multi',
    difficulty: 2,
    stem: 'You are describing the shared platform layer that sits beneath all Fabric workloads. Which two of the following does Learn place in that layer? Choose two.',
    sources: [OVERVIEW],
    options: [
      { id: 'a', text: 'Power BI Report Server', explain: 'Report Server isn’t listed in the Fabric platform layer; Learn lists OneLake, Copilot, and governance.' },
      { id: 'b', text: 'OneLake', explain: 'Correct. OneLake is the centralized, logical data lake used by all workloads.' },
      { id: 'c', text: 'Copilot', explain: 'Correct. Copilot is AI assistance embedded across Fabric workloads.' },
      { id: 'd', text: 'Azure Virtual Machines', explain: 'Fabric is SaaS; you don’t manage virtual machines.' },
    ],
    answers: ['b', 'c'],
  },
  {
    id: 'FO-16',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are checking a slide about Fabric workloads. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [OVERVIEW, DATA_FACTORY],
    statements: [
      { id: 's1', text: 'Fabric Data Engineering provides Apache Spark with notebooks for processing large datasets.', answer: true, explain: 'Yes. Learn describes Data Engineering as providing Apache Spark with notebooks and job tools.' },
      { id: 's2', text: 'Data Factory provides connectors for on-premises and cloud data sources.', answer: true, explain: 'Yes. Learn describes Data Factory connecting to a wide range of on-premises and cloud data sources through its connectors.' },
      { id: 's3', text: 'Fabric Data Warehouse stores its data in a proprietary format that only T-SQL can read.', answer: false, explain: 'No. It natively stores data in the open Delta Lake format.' },
    ],
  },
  {
    id: 'FO-17',
    machineId: 'founding-charter',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'Your team will analyze IoT sensor readings and website clickstreams as they arrive, and act on them in near real time. Which Fabric workload is built for this?',
    sources: [OVERVIEW],
    options: [
      { id: 'a', text: 'Real-Time Intelligence', explain: 'Correct. It analyzes data as it arrives, such as IoT readings, logs, and clickstreams.' },
      { id: 'b', text: 'Fabric Data Science', explain: 'Data Science builds and deploys ML models.' },
      { id: 'c', text: 'Databases', explain: 'Databases provide operational transactional databases such as SQL database in Fabric.' },
      { id: 'd', text: 'Industry Solutions', explain: 'Industry Solutions address industry-specific needs, not streaming analytics in general.' },
    ],
    answer: 'a',
  },
  // Water Wheel
  {
    id: 'FO-18',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'An architect proposes creating a second OneLake for the Finance department to keep its data separate. What should you tell them?',
    sources: [ONELAKE],
    options: [
      { id: 'a', text: 'Create it from the admin portal under OneLake settings', explain: 'There’s no option to create another OneLake.' },
      { id: 'b', text: 'Create it by buying a second capacity', explain: 'Capacities add compute; they don’t add OneLake instances.' },
      { id: 'c', text: 'Each tenant has exactly one OneLake; separate Finance with workspaces and domains instead', explain: 'Correct. Learn: every tenant has a single OneLake that you can’t delete or duplicate; organize it with domains and workspaces.' },
      { id: 'd', text: 'Each workspace already has its own OneLake', explain: 'Workspaces are containers within the tenant’s single OneLake.' },
    ],
    answer: 'c',
  },
  {
    id: 'FO-19',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'order',
    difficulty: 1,
    stem: 'Put the levels of the Fabric data hierarchy in order, from the broadest to the most specific.',
    sources: [ONELAKE],
    items: [
      { id: 'i2', text: 'Workspace', explain: 'Second. Workspaces organize data within the tenant and are each part of a capacity.' },
      { id: 'i3', text: 'Data item, such as a lakehouse or warehouse', explain: 'Last. Workspaces contain data items.' },
      { id: 'i1', text: 'Tenant', explain: 'First. Tenant-level policies protect all data that lands in OneLake.' },
    ],
    answerOrder: ['i1', 'i2', 'i3'],
  },
  {
    id: 'FO-20',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'A capacity is overloaded during a busy afternoon. Interactive report queries are now being rejected, but scheduled background jobs can still start. Which throttling stage is the capacity in?',
    sources: [THROTTLING],
    options: [
      { id: 'a', text: 'Overage protection with no throttling', explain: 'Overage protection lets you use up to 10 minutes of future capacity without any throttling.' },
      { id: 'b', text: 'Interactive delay: 20-second delays on new interactive operations', explain: 'Interactive delay comes before interactive rejection, when usage is over 10 minutes but at most 60.' },
      { id: 'c', text: 'Background rejection: all new requests are rejected', explain: 'At this stage background operations are rejected too.' },
      { id: 'd', text: 'Interactive rejection: new interactive operations are rejected', explain: 'Correct. Learn: in interactive rejection, new interactive operations are rejected while background operations can start and run.' },
    ],
    answer: 'd',
  },
  {
    id: 'FO-21',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are explaining how Fabric capacities absorb spikes in usage. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [THROTTLING],
    statements: [
      { id: 's1', text: 'Bursting lets an operation temporarily use more compute than the capacity SKU provides.', answer: true, explain: 'Yes. Learn: with bursting, operations can temporarily use more compute than provisioned.' },
      { id: 's2', text: 'Background operations are smoothed over a 24-hour period.', answer: true, explain: 'Yes. Background operations are smoothed over 24 hours.' },
      { id: 's3', text: 'Interactive operations are always smoothed over exactly one minute.', answer: false, explain: 'No. Interactive operations are smoothed over a minimum of five minutes and up to 64 minutes.' },
    ],
  },
  {
    id: 'FO-22',
    machineId: 'water-wheel',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'Your organization wants a Fabric capacity it can use without a long-term commitment, billed per second, and Learn’s recommended SKU type. What should you buy?',
    sources: [LICENSES],
    options: [
      { id: 'a', text: 'An F SKU purchased through Azure', explain: 'Correct. F SKUs are billed per second with no commitment and are the recommended capacities for Fabric.' },
      { id: 'b', text: 'A Power BI EM SKU', explain: 'Learn says Power BI EM SKUs don’t support Fabric.' },
      { id: 'c', text: 'An A SKU', explain: 'A SKUs only support Power BI items.' },
      { id: 'd', text: 'Power BI Pro licenses only', explain: 'Pro is a per-user license, not a capacity.' },
    ],
    answer: 'a',
  },
  // Three Vats
  {
    id: 'FO-23',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'You need a Fabric data store built for time-based streaming events, including semi-structured JSON and free-text analysis, that can query billions of events in seconds. What should you choose?',
    sources: [EVENTHOUSE, WAREHOUSE, DECISION, TERMS],
    options: [
      { id: 'a', text: 'A warehouse', explain: 'A warehouse targets T-SQL analytics with multi-table transactions, not streaming events.' },
      { id: 'b', text: 'An eventhouse', explain: 'Correct. Eventhouses are designed for streaming data and are the preferred engine for semi-structured and free-text analysis.' },
      { id: 'c', text: 'A SQL database in Fabric', explain: 'Learn points operational, transactional (OLTP) workloads to SQL database in Fabric, not event analytics.' },
      { id: 'd', text: 'A semantic model', explain: 'A semantic model is a metadata layer (tables, relationships, measures) for reporting, not a store for raw events.' },
    ],
    answer: 'b',
  },
  {
    id: 'FO-24',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'match',
    difficulty: 2,
    stem: 'Your lakehouse follows the medallion architecture. Match each layer to what it stores.',
    sources: [MEDALLION],
    prompts: [
      { id: 'p1', text: 'Bronze' },
      { id: 'p2', text: 'Silver' },
      { id: 'p3', text: 'Gold' },
    ],
    choices: [
      { id: 'c1', text: 'Raw data, stored exactly as it arrives' },
      { id: 'c2', text: 'Enriched data: errors fixed, formats standardized, duplicates removed' },
      { id: 'c3', text: 'Curated data organized for reports and dashboards' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Bronze keeps everything as it arrives; no changes are allowed.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Silver fixes errors, standardizes formats, and removes duplicates.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Gold is organized for reports and dashboards.' },
    ],
  },
  {
    id: 'FO-25',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are comparing Fabric lakehouses and warehouses for a new project. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [LAKEHOUSE, WAREHOUSE],
    statements: [
      { id: 's1', text: 'A lakehouse can store both structured and unstructured data.', answer: true, explain: 'Yes. A lakehouse stores structured and unstructured data in one location.' },
      { id: 's2', text: 'Lakehouses and warehouses store their tables in different, incompatible formats.', answer: false, explain: 'No. Both store data in Delta format on OneLake and share the same SQL engine.' },
      { id: 's3', text: 'The warehouse separates compute from storage so each can scale independently.', answer: true, explain: 'Yes. Learn says storage and compute are separated in Fabric Data Warehouse.' },
    ],
  },
  {
    id: 'FO-26',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'Data engineers in a lakehouse want to write transformations in Python, Scala, Spark SQL, or R. Where do they write and run that code?',
    sources: [LAKEHOUSE, TERMS, DAX_QUERY_VIEW],
    options: [
      { id: 'a', text: 'In the SQL analytics endpoint editor', explain: 'The endpoint runs read-only T-SQL, not Spark code.' },
      { id: 'b', text: 'In a KQL queryset', explain: 'KQL querysets run KQL against KQL databases.' },
      { id: 'c', text: 'In DAX query view', explain: 'DAX query view runs DAX against semantic models.' },
      { id: 'd', text: 'In a notebook attached to the lakehouse', explain: 'Correct. Notebooks run Spark code in Python, Scala, SQL, or R against lakehouse tables and folders.' },
    ],
    answer: 'd',
  },
  {
    id: 'FO-27',
    machineId: 'three-vats',
    bulletIds: [],
    format: 'single',
    difficulty: 3,
    stem: 'A team keeps raw files from a CSV export in the bronze layer and plans the silver and gold layers. According to Learn, which format should the silver and gold layers use?',
    sources: [MEDALLION],
    options: [
      { id: 'a', text: 'The same format as the source, so CSV', explain: 'Keeping the source format describes bronze; for silver and gold, Learn recommends Delta tables (other files are only allowed).' },
      { id: 'b', text: 'Delta tables', explain: 'Correct. Learn: the silver and gold layers should contain Delta tables.' },
      { id: 'c', text: 'JSON files in the Files area', explain: 'Learn recommends Delta tables for silver and gold.' },
      { id: 'd', text: 'Excel workbooks in OneDrive', explain: 'Workbooks aren’t a lakehouse layer format.' },
    ],
    answer: 'b',
  },
  // Mill Lease
  {
    id: 'FO-28',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'single',
    difficulty: 1,
    stem: 'You start a Fabric trial by signing up yourself. Which role do you hold for the new trial capacity?',
    sources: [TRIAL],
    options: [
      { id: 'a', text: 'Capacity administrator', explain: 'Correct. Learn: signing up for a trial capacity makes you its Capacity administrator.' },
      { id: 'b', text: 'Fabric administrator for the tenant', explain: 'Starting a trial makes you its Capacity administrator, which is a different role from Fabric administrator.' },
      { id: 'c', text: 'Viewer only', explain: 'You manage the trial, so you’re more than a viewer.' },
      { id: 'd', text: 'No role; the tenant admin owns it', explain: 'The person who signs up becomes the trial’s Capacity administrator.' },
    ],
    answer: 'a',
  },
  {
    id: 'FO-29',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'You activated a trial capacity in your home region. A month later you want to move a trial workspace that contains Fabric items to a different region. What must you do first?',
    sources: [TRIAL],
    options: [
      { id: 'a', text: 'Nothing; workspaces move between regions automatically', explain: 'Learn requires extra work before moving a workspace with Fabric items.' },
      { id: 'b', text: 'Export the workspace to a .pbix file', explain: 'This isn’t the documented requirement.' },
      { id: 'c', text: 'Delete all existing Fabric items in the workspace', explain: 'Correct. Learn: to move a workspace with Fabric items to another region after the trial is created, you must delete all existing Fabric items first.' },
      { id: 'd', text: 'Start a second trial in the new region', explain: 'A new trial doesn’t move the existing workspace.' },
    ],
    answer: 'c',
  },
  {
    id: 'FO-30',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are the Capacity administrator of a Fabric trial and want coworkers to use it. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [TRIAL],
    statements: [
      { id: 's1', text: 'You can give coworkers permission to create workspaces in your trial capacity.', answer: true, explain: 'Yes. As Capacity administrator, you manage who can create workspaces in the trial.' },
      { id: 's2', text: 'Assigning a workspace to the trial capacity adds coworkers who have roles in that workspace to the trial.', answer: true, explain: 'Yes. Learn says this happens automatically.' },
      { id: 's3', text: 'The trial lasts 120 days unless you cancel it.', answer: false, explain: 'No. The trial capacity lasts 60 days unless you cancel it earlier.' },
    ],
  },
  {
    id: 'FO-31',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'single',
    difficulty: 2,
    stem: 'You started a Fabric trial and don’t have a Power BI Premium Per User license. Which other trial is added for you?',
    sources: [TRIAL],
    options: [
      { id: 'a', text: 'A Microsoft 365 E5 trial', explain: 'Learn doesn’t pair the Fabric trial with a Microsoft 365 trial.' },
      { id: 'b', text: 'A Power BI individual trial', explain: 'Correct. The Fabric trial is complemented with a Power BI individual trial if you don’t already have PPU.' },
      { id: 'c', text: 'An Azure free account', explain: 'This isn’t part of the Fabric trial.' },
      { id: 'd', text: 'A Copilot Pro trial', explain: 'This isn’t part of the Fabric trial.' },
    ],
    answer: 'b',
  },
  {
    id: 'FO-32',
    machineId: 'mill-lease',
    bulletIds: [],
    format: 'single',
    difficulty: 3,
    stem: 'You are the trial’s Capacity administrator and already have a workspace on shared capacity. You want that workspace’s items to run on your trial capacity. What should you do?',
    sources: [TRIAL],
    options: [
      { id: 'a', text: 'Start a second trial from the workspace', explain: 'You already have a trial; you add workspaces to it.' },
      { id: 'b', text: 'Ask a tenant admin to merge the workspace into OneLake', explain: 'Every workspace is already in OneLake; this isn’t the documented step.' },
      { id: 'c', text: 'Create a shortcut from the trial workspace to each item', explain: 'Shortcuts reference data; they don’t move the workspace to the capacity.' },
      { id: 'd', text: 'Change the workspace type to Trial in its workspace settings', explain: 'Correct. Learn: you can add workspaces to the trial capacity by changing their type to Trial in workspace settings.' },
    ],
    answer: 'd',
  },
]
