/** Learn pages cited by questions. Every one is also fetched by check:links. */
const L = 'https://learn.microsoft.com/en-us/'

export const S = {
  // Fabric fundamentals
  overview: `${L}fabric/fundamentals/microsoft-fabric-overview`,
  terms: `${L}fabric/fundamentals/fabric-terminology`,
  onelake: `${L}fabric/onelake/onelake-overview`,
  licenses: `${L}fabric/enterprise/licenses`,
  decisionStore: `${L}fabric/fundamentals/decision-guide-data-store`,
  decisionLhWh: `${L}fabric/fundamentals/decision-guide-lakehouse-warehouse`,
  lakehouse: `${L}fabric/data-engineering/lakehouse-overview`,
  warehouse: `${L}fabric/data-warehouse/data-warehousing`,
  eventhouse: `${L}fabric/real-time-intelligence/eventhouse`,
  medallion: `${L}fabric/onelake/onelake-medallion-lakehouse-architecture`,
  // Get data
  connectors: `${L}fabric/data-factory/connector-overview`,
  connections: `${L}fabric/data-factory/data-source-management`,
  dataFactory: `${L}fabric/data-factory/data-factory-overview`,
  gateway: `${L}fabric/data-factory/how-to-access-on-premises-data`,
  movement: `${L}fabric/data-factory/decision-guide-data-movement`,
  loadLakehouse: `${L}fabric/data-engineering/load-data-lakehouse`,
  notebookLoad: `${L}fabric/data-engineering/lakehouse-notebook-load-data`,
  shortcuts: `${L}fabric/onelake/onelake-shortcuts`,
  mirroring: `${L}fabric/mirroring/overview`,
  ingestWarehouse: `${L}fabric/data-warehouse/ingest-data`,
  copyInto: `${L}fabric/data-warehouse/ingest-data-copy`,
  dataflowGen2: `${L}fabric/data-factory/dataflows-gen2-overview`,
  catalog: `${L}fabric/governance/onelake-catalog-overview`,
  catalogExplore: `${L}fabric/governance/onelake-catalog-explore`,
  rtHub: `${L}fabric/real-time-hub/real-time-hub-overview`,
  eventhouseOneLake: `${L}fabric/real-time-intelligence/event-house-onelake-availability`,
  modelOneLake: `${L}fabric/enterprise/powerbi/onelake-integration-overview`,
  // Transform
  dimOverview: `${L}fabric/data-warehouse/dimensional-modeling-overview`,
  dimTables: `${L}fabric/data-warehouse/dimensional-modeling-dimension-tables`,
  factTables: `${L}fabric/data-warehouse/dimensional-modeling-fact-tables`,
  loadTables: `${L}fabric/data-warehouse/dimensional-modeling-load-tables`,
  tsqlSurface: `${L}fabric/data-warehouse/tsql-surface-area`,
  dataTypes: `${L}fabric/data-warehouse/data-types`,
  endpoint: `${L}fabric/data-engineering/lakehouse-sql-analytics-endpoint`,
  lakehousePrep: `${L}fabric/data-engineering/tutorial-lakehouse-data-preparation`,
  dataWrangler: `${L}fabric/data-science/data-wrangler`,
  qualify: `${L}sql/t-sql/queries/select-qualify-clause-transact-sql?view=fabric`,
  tryCast: `${L}sql/t-sql/functions/try-cast-transact-sql?view=fabric`,
  coalesce: `${L}sql/t-sql/language-elements/coalesce-transact-sql?view=fabric`,
  createView: `${L}sql/t-sql/statements/create-view-transact-sql?view=fabric`,
  createProc: `${L}sql/t-sql/statements/create-procedure-transact-sql?view=fabric`,
  merge: `${L}sql/t-sql/statements/merge-transact-sql?view=fabric`,
  // Query
  visualQuery: `${L}fabric/data-warehouse/visual-query-editor`,
  queryWarehouse: `${L}fabric/data-warehouse/query-warehouse`,
  kqlOperators: `${L}kusto/query/tutorials/learn-common-operators?view=microsoft-fabric`,
  kqlSummarize: `${L}kusto/query/summarize-operator?view=microsoft-fabric`,
  kqlQueryset: `${L}fabric/real-time-intelligence/kusto-query-set`,
  kqlJoin: `${L}kusto/query/join-operator?view=microsoft-fabric`,
  kqlJoinTutorial: `${L}kusto/query/tutorials/join-data-from-multiple-tables?view=microsoft-fabric`,
  kqlTake: `${L}kusto/query/take-operator?view=microsoft-fabric`,
  kqlTop: `${L}kusto/query/top-operator?view=microsoft-fabric`,
  kqlSort: `${L}kusto/query/sort-operator?view=microsoft-fabric`,
  kqlWhere: `${L}kusto/query/where-operator?view=microsoft-fabric`,
  kqlProject: `${L}kusto/query/project-operator?view=microsoft-fabric`,
  kqlExtend: `${L}kusto/query/extend-operator?view=microsoft-fabric`,
  kqlBin: `${L}kusto/query/bin-function?view=microsoft-fabric`,
  sqlToKql: `${L}kusto/query/sql-cheat-sheet?view=microsoft-fabric`,
  daxQueries: `${L}dax/dax-queries`,
  daxQueryView: `${L}power-bi/transform-model/dax-query-view`,
} as const
