import { S } from '../sources'
import type { Question } from '../types'

const gk = 'gate-keys'
const il = 'item-locks'
const ts = 'thread-sieves'
const ss = 'seal-and-stamp'

export const accessQuestions: Question[] = [
  // ── Gate Keys: M1.1 workspace-level access ──────────────────────────
  {
    id: 'GK-01',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'member-vs-contributor',
    stem: 'Data engineers must create and edit lakehouses, warehouses, and notebooks in a Fabric workspace, but must not share items or manage workspace access. Which workspace role should you assign?',
    sources: [S.roles],
    options: [
      { id: 'a', text: 'Admin', explain: 'Admins can also manage permissions and delete the workspace, which is more than needed.' },
      { id: 'b', text: 'Member', explain: 'Members can also share items and add people, which the requirement forbids.' },
      { id: 'c', text: 'Contributor', explain: 'Correct. Contributors can create and modify content but can’t manage access, and can share only if given Reshare permission.' },
      { id: 'd', text: 'Viewer', explain: 'Viewers can only view content; they can’t create or edit items.' },
    ],
    answer: 'c',
  },
  {
    id: 'GK-02',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A workspace Member wants to connect the workspace to a GitHub repository for source control. The option is unavailable to them. Who can make the connection?',
    sources: [S.roles, S.gitIntro],
    options: [
      { id: 'a', text: 'Any Contributor with a GitHub account', explain: 'Contributors can commit after the connection exists, but can’t create it.' },
      { id: 'b', text: 'A workspace Admin', explain: 'Correct. Only Admins can connect a workspace to a Git repository.' },
      { id: 'c', text: 'The capacity administrator only', explain: 'Capacity admins manage capacities; the Git connection is a workspace Admin action.' },
      { id: 'd', text: 'Any Member, after enabling Git in the tenant', explain: 'Even with Git enabled in the tenant, Members can’t connect the workspace.' },
    ],
    answer: 'b',
  },
  {
    id: 'GK-03',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Analysts are workspace Viewers and read reports on a semantic model with RLS. A developer with the Contributor role reports that the RLS filters don’t apply to them. Why?',
    sources: [S.modelRls, S.roles],
    options: [
      { id: 'a', text: 'RLS doesn’t apply to Contributors or higher roles', explain: 'Correct. Users with edit permission on the model (Admin, Member, Contributor) aren’t restricted by RLS.' },
      { id: 'b', text: 'RLS takes effect only after the next scheduled refresh', explain: 'The cause is the developer’s role: RLS doesn’t restrict users who can edit the model.' },
      { id: 'c', text: 'The developer isn’t assigned to any role, so they see nothing', explain: 'They see everything, not nothing.' },
      { id: 'd', text: 'RLS isn’t supported on models in Fabric workspaces', explain: 'Semantic model RLS is supported in Fabric.' },
    ],
    answer: 'a',
  },
  {
    id: 'GK-04',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are planning workspace access for a Fabric analytics team. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.roles, S.workspaces],
    statements: [
      { id: 's1', text: 'Workspace roles can be assigned to security groups as well as to individual users.', answer: true, explain: 'Yes. Roles can go to users, security groups, Microsoft 365 groups, distribution lists, and service principals.' },
      { id: 's2', text: 'A Contributor role in one workspace also grants Contributor rights in other workspaces on the same capacity.', answer: false, explain: 'No. Workspace roles apply only to that workspace.' },
      { id: 's3', text: 'A user who is in two groups, one with Viewer and one with Member, gets the Member role.', answer: true, explain: 'Yes. A user gets the highest role they’re assigned.' },
    ],
  },
  {
    id: 'GK-05',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'member-vs-contributor',
    stem: 'Match each requirement to the least-privileged workspace role that meets it.',
    sources: [S.roles],
    prompts: [
      { id: 'p1', text: 'Delete the workspace and add other admins' },
      { id: 'p2', text: 'Share items and add people as Contributors' },
      { id: 'p3', text: 'Create warehouses and edit notebooks' },
      { id: 'p4', text: 'Open reports without editing anything' },
    ],
    choices: [
      { id: 'c1', text: 'Admin' },
      { id: 'c2', text: 'Member' },
      { id: 'c3', text: 'Contributor' },
      { id: 'c4', text: 'Viewer' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Only Admins can delete the workspace and add admins.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Members can share and add people with Member or lower roles.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Contributors can create and modify content.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Viewers can view content only.' },
    ],
  },
  {
    id: 'GK-06',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You plan OneLake security roles to limit which lakehouse folders people can read. For users in which workspace role do these roles mainly make a difference?',
    sources: [S.roles, S.onelakeAccessModel],
    options: [
      { id: 'a', text: 'Admin', explain: 'Admins already have write access to all data in the workspace.' },
      { id: 'b', text: 'Member', explain: 'Members already have write access to the data.' },
      { id: 'c', text: 'Contributor', explain: 'Contributors also have data access through write permission.' },
      { id: 'd', text: 'Viewer', explain: 'Correct. Admins, Members, and Contributors have data access through write permission, so OneLake security roles mainly restrict Viewers.' },
    ],
    answer: 'd',
  },
  {
    id: 'GK-07',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 1,
    stem: 'You need to give a new team access to a workspace and keep administration simple as people join and leave. What does Learn recommend?',
    sources: [S.roles, S.workspaces, S.onelakeSecurity],
    options: [
      { id: 'a', text: 'Assign the role to a security group', explain: 'Correct. Assigning roles to groups keeps access manageable.' },
      { id: 'b', text: 'Assign the role to each user individually', explain: 'This works, but every change needs a workspace edit.' },
      { id: 'c', text: 'Share every item with each user', explain: 'Item sharing doesn’t scale and doesn’t replace a workspace role.' },
      { id: 'd', text: 'Give everyone the Admin role', explain: 'This grants far more than needed.' },
    ],
    answer: 'a',
  },
  {
    id: 'GK-08',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'access-layers',
    stem: 'Fabric separates control-plane permissions from data-plane permissions. Which of these is a data-plane control?',
    sources: [S.permissionModel, S.onelakeAccessModel, S.onelakeSecurity],
    options: [
      { id: 'a', text: 'The workspace Contributor role', explain: 'Workspace roles are control-plane permissions about what you can do with items.' },
      { id: 'b', text: 'Edit permission on a lakehouse', explain: 'Item permissions such as Edit govern actions on the item.' },
      { id: 'c', text: 'A OneLake security role on a lakehouse folder', explain: 'Correct. OneLake security roles govern which data you can read.' },
      { id: 'd', text: 'Share permission on a semantic model', explain: 'Share is an item permission about resharing.' },
    ],
    answer: 'c',
  },
  {
    id: 'GK-09',
    machineId: gk,
    bulletIds: ['M1.1'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    trapPairId: 'member-vs-contributor',
    stem: 'Which two actions can a workspace Member perform by default that a Contributor without Reshare permission can’t? Choose two.',
    sources: [S.roles],
    options: [
      { id: 'a', text: 'Share an item with another user', explain: 'Correct. Members can share items; Contributors can’t.' },
      { id: 'b', text: 'Create a new warehouse', explain: 'Contributors can create warehouses too.' },
      { id: 'c', text: 'Add a user to the workspace as a Contributor', explain: 'Correct. Members can add people with Member or lower roles.' },
      { id: 'd', text: 'Delete the workspace', explain: 'Only Admins can delete the workspace.' },
    ],
    answers: ['a', 'c'],
  },

  // ── Item Locks: M1.2 item-level access ──────────────────────────────
  {
    id: 'IL-01',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'An analyst without a workspace role needs to query a lakehouse’s tables with T-SQL through its SQL analytics endpoint. Nothing else is needed. Which permission should you grant when sharing the lakehouse?',
    sources: [S.shareItems],
    options: [
      { id: 'a', text: 'Read only', explain: 'Read lets them connect and see metadata, but not read the data.' },
      { id: 'b', text: 'Read all with Apache Spark', explain: 'This grants access through OneLake and Spark, not T-SQL.' },
      { id: 'c', text: 'Read All with SQL analytics endpoint', explain: 'Correct. It grants ReadData, which lets the user read data with T-SQL.' },
      { id: 'd', text: 'Edit', explain: 'Edit grants far more than reading data.' },
    ],
    answer: 'c',
  },
  {
    id: 'IL-02',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A data scientist with no workspace role needs to read a lakehouse’s files and tables from a notebook in their own workspace. Which permission should you grant when sharing?',
    sources: [S.shareItems, S.roles],
    options: [
      { id: 'a', text: 'Read all with Apache Spark', explain: 'Correct. It grants ReadAll, which allows reading through OneLake APIs and Spark.' },
      { id: 'b', text: 'Read All with SQL analytics endpoint', explain: 'This grants T-SQL access only.' },
      { id: 'c', text: 'Build', explain: 'Build is a semantic model permission for creating content.' },
      { id: 'd', text: 'Execute', explain: 'Execute applies to running or cancelling items.' },
    ],
    answer: 'a',
  },
  {
    id: 'IL-03',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 1,
    stem: 'A report author in another workspace needs to build new reports on your semantic model. Which item permission should they have on the model?',
    sources: [S.shareItems],
    options: [
      { id: 'a', text: 'Share', explain: 'Share allows resharing, not building content.' },
      { id: 'b', text: 'Build', explain: 'Correct. Build lets the user create new content on the semantic model.' },
      { id: 'c', text: 'Read All with SQL analytics endpoint', explain: 'This is a lakehouse or warehouse permission.' },
      { id: 'd', text: 'Execute', explain: 'Execute is for running items.' },
    ],
    answer: 'b',
  },
  {
    id: 'IL-04',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are sharing Fabric items with users who have no workspace role. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.shareItems],
    statements: [
      { id: 's1', text: 'A link for “People with existing access” grants access to anyone who opens it.', answer: false, explain: 'No. It generates a URL but doesn’t grant any access.' },
      { id: 's2', text: 'After you revoke a signed-in user’s item permission, it can take up to two hours to take effect.', answer: true, explain: 'Yes. Learn states the delay for signed-in users.' },
      { id: 's3', text: 'The Shared with me option lists every type of Fabric item shared with you.', answer: false, explain: 'No. It currently displays only Power BI items.' },
    ],
  },
  {
    id: 'IL-05',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 3,
    placement: true,
    trapPairId: 'access-layers',
    stem: 'You share a lakehouse with a user and grant only the default Read permission. They can open the item but get errors when querying tables through the SQL analytics endpoint. Why?',
    sources: [S.shareItems, S.roles],
    options: [
      { id: 'a', text: 'Read alone doesn’t include data access', explain: 'Correct. Item Read alone doesn’t include data access; add Read All with SQL analytics endpoint.' },
      { id: 'b', text: 'Shared items need 24 hours before queries work', explain: 'The cause is the missing data permission; Read alone doesn’t include data access.' },
      { id: 'c', text: 'The SQL analytics endpoint must be shared separately from the lakehouse', explain: 'The permission is chosen when sharing the lakehouse.' },
      { id: 'd', text: 'SQL queries need the workspace Admin role', explain: 'Item permissions are enough; no role is required.' },
    ],
    answer: 'a',
  },
  {
    id: 'IL-06',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'You share a warehouse with a colleague. Which two permissions can you add on top of the default Read permission? Choose two.',
    sources: [S.shareItems],
    options: [
      { id: 'a', text: 'Workspace Member', explain: 'Workspace roles aren’t granted through item sharing.' },
      { id: 'b', text: 'Share, so they can reshare the item', explain: 'Correct. Share lets them reshare up to their own permissions.' },
      { id: 'c', text: 'Capacity Contributor', explain: 'Capacity permissions aren’t set by sharing an item.' },
      { id: 'd', text: 'Read All with SQL analytics endpoint', explain: 'Correct. ReadData lets them read data with T-SQL.' },
    ],
    answers: ['b', 'd'],
  },
  {
    id: 'IL-07',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You need to review who has access to a warehouse through sharing and remove one person’s Share permission. Where should you go?',
    sources: [S.shareItems, S.giveAccess],
    options: [
      { id: 'a', text: 'The workspace Manage access pane', explain: 'Manage access adds people to workspace roles, not item permissions.' },
      { id: 'b', text: 'The OneLake catalog Govern tab', explain: 'Item permissions are reviewed and removed with Manage permissions on the item.' },
      { id: 'c', text: 'The tenant admin portal', explain: 'Item permissions are managed on the item.' },
      { id: 'd', text: 'Manage permissions on the warehouse', explain: 'Correct. Manage permissions lets you review and remove item permissions.' },
    ],
    answer: 'd',
  },
  {
    id: 'IL-08',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 3,
    placement: true,
    trapPairId: 'access-layers',
    stem: 'A user has item Read on a warehouse. You also run DENY SELECT ON dbo.Payroll TO [that user]. What can they do with dbo.Payroll?',
    sources: [S.whGranular, S.shareItems],
    options: [
      { id: 'a', text: 'Query it, because item Read overrides SQL permissions', explain: 'SQL permissions apply on top of item access.' },
      { id: 'b', text: 'Query it only from the visual query editor', explain: 'GRANT and DENY apply on top of item access, whichever SQL tool sends the query.' },
      { id: 'c', text: 'Nothing; the DENY blocks SELECT on that table', explain: 'Correct. GRANT and DENY apply on top of the access that item Read provides.' },
      { id: 'd', text: 'Query it through Spark instead', explain: 'Item Read alone doesn’t grant Spark data access either.' },
    ],
    answer: 'c',
  },
  {
    id: 'IL-09',
    machineId: il,
    bulletIds: ['M1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A user needs to open one report and one semantic model in a workspace, but nothing else there. What is the least-privileged approach?',
    sources: [S.shareItems, S.roles],
    options: [
      { id: 'a', text: 'Give the user the workspace Viewer role', explain: 'Viewer applies to every item in the workspace.' },
      { id: 'b', text: 'Share the two items with the user', explain: 'Correct. Item sharing grants access to specific items without a workspace role.' },
      { id: 'c', text: 'Create a new workspace and copy the items', explain: 'Copying duplicates content and adds maintenance.' },
      { id: 'd', text: 'Add the user to the capacity’s contributors', explain: 'Item access comes from workspace roles or item sharing; sharing the two items is the targeted way.' },
    ],
    answer: 'b',
  },

  // ── Thread Sieves: M1.3 RLS / CLS / OLS / file-level ────────────────
  {
    id: 'TS-01',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'You need warehouse row-level security so that sales reps see only their own orders in sales.Orders. The predicate function Security.tvf_securitypredicate already exists. Complete the T-SQL.',
    sources: [S.whRls, S.createSecurityPolicy],
    language: 'tsql',
    code: 'CREATE [[1]] SalesFilter\nADD [[2]] PREDICATE Security.tvf_securitypredicate(SalesRep)\nON sales.Orders\nWITH (STATE = [[3]]);',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'ROLE', explain: 'A database role groups users; it doesn’t bind a predicate to a table.' },
          { id: 'b', text: 'SECURITY POLICY', explain: 'Correct. A security policy binds the predicate function to the table.' },
          { id: 'c', text: 'VIEW', explain: 'A view isn’t how Fabric row-level security works; a security policy binds the predicate function to the table.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'FILTER', explain: 'Correct. A filter predicate silently filters rows for SELECT, UPDATE, and DELETE.' },
          { id: 'b', text: 'MASK', explain: 'Masking is dynamic data masking, defined on columns.' },
          { id: 'c', text: 'CHECK', explain: 'Security policies use FILTER (and BLOCK) predicates, not CHECK.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'OFF', explain: 'OFF creates the policy but doesn’t enforce it.' },
          { id: 'b', text: 'ENABLED', explain: 'The STATE option takes ON or OFF.' },
          { id: 'c', text: 'ON', explain: 'Correct. STATE = ON enforces the policy.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'TS-02',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'cls-vs-ols-vs-ddm',
    stem: 'Support staff must query dbo.Customers in a Fabric warehouse but must never read the CreditCard column. Queries that touch it should fail. What should you implement?',
    sources: [S.whCls],
    options: [
      { id: 'a', text: 'Dynamic data masking on CreditCard', explain: 'Masking still returns the column, with obscured values, instead of failing.' },
      { id: 'b', text: 'A security policy with a filter predicate', explain: 'RLS filters rows, not columns.' },
      { id: 'c', text: 'A sensitivity label on the warehouse', explain: 'Labels classify items; they don’t deny a column in SQL.' },
      { id: 'd', text: 'GRANT SELECT on every column except CreditCard', explain: 'Correct. Column-level security: a query that touches CreditCard fails with a permission error.' },
    ],
    answer: 'd',
  },
  {
    id: 'TS-03',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Users must not be able to see that a Salaries table exists in a semantic model, including in the field list. Which feature should you use?',
    sources: [S.modelOls],
    options: [
      { id: 'a', text: 'Object-level security in a model role', explain: 'Correct. OLS hides the table or column, including its metadata, from members of the role.' },
      { id: 'b', text: 'Row-level security with a FALSE() filter', explain: 'RLS filters rows; it doesn’t hide the table or its metadata the way OLS does.' },
      { id: 'c', text: 'Hiding the table in report view', explain: 'Hiding a table in a view isn’t security; OLS is the feature that secures tables and columns.' },
      { id: 'd', text: 'Dynamic data masking in the source', explain: 'Masking is a warehouse column feature; hiding a model table from a role is OLS.' },
    ],
    answer: 'a',
  },
  {
    id: 'TS-04',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Each sales manager should see only rows for their own region in a semantic model. A mapping table relates each manager’s email to their region. Which DAX filter should the role use on the mapping table?',
    sources: [S.modelRls],
    options: [
      { id: 'a', text: '[UserEmail] = USERNAME() && FALSE()', explain: 'Adding FALSE() returns no rows for anyone.' },
      { id: 'b', text: '[UserEmail] = USERPRINCIPALNAME()', explain: 'Correct. Dynamic RLS matches each signed-in user’s UPN, and the filter flows through relationships.' },
      { id: 'c', text: '[Region] = SELECTEDVALUE([Region])', explain: 'This depends on report selections, not on who is signed in.' },
      { id: 'd', text: '[UserEmail] = "manager@contoso.com"', explain: 'A static filter shows the same rows to every member.' },
    ],
    answer: 'b',
  },
  {
    id: 'TS-05',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'yesno',
    difficulty: 3,
    placement: true,
    stem: 'You are implementing row-level security in a Fabric warehouse. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.whRls, S.whGranular],
    statements: [
      { id: 's1', text: 'Security policies also filter rows for dbo users and members of db_owner.', answer: true, explain: 'Yes. Security policies apply to all users, including dbo.' },
      { id: 's2', text: 'You can change the predicate function while the security policy that uses it still exists.', answer: false, explain: 'No. Drop the policy, alter the function, then recreate the policy.' },
      { id: 's3', text: 'You must run CREATE USER for each analyst before granting permissions.', answer: false, explain: 'No. You can’t run CREATE USER in a Fabric warehouse; the user is created on GRANT or DENY.' },
    ],
  },
  {
    id: 'TS-06',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You define RLS in a lakehouse’s SQL analytics endpoint. A Direct Lake on SQL semantic model uses that table, with DirectLakeBehavior left at its default. What happens to the model’s queries on it?',
    sources: [S.dlHow, S.directLake],
    options: [
      { id: 'a', text: 'They stay in Direct Lake and ignore the SQL RLS', explain: 'SQL-based security is a fallback condition for Direct Lake on SQL, so queries don’t stay in Direct Lake.' },
      { id: 'b', text: 'They fail until the RLS is removed', explain: 'Failing is the DirectLakeOnly behavior; the default, Automatic, falls back silently.' },
      { id: 'c', text: 'They fall back to DirectQuery', explain: 'Correct. SQL RLS on a table is a fallback condition for Direct Lake on SQL.' },
      { id: 'd', text: 'The model copies the RLS rules into its own roles', explain: 'SQL RLS isn’t converted into model roles.' },
    ],
    answer: 'c',
  },
  {
    id: 'TS-07',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'access-layers',
    stem: 'You set object-level DENY permissions in a lakehouse’s SQL analytics endpoint. The same users read the lakehouse tables from a Spark notebook with ReadAll permission. What do they see in Spark?',
    sources: [S.endpoint],
    options: [
      { id: 'a', text: 'All the data in those tables', explain: 'Correct. SQL security rules on the endpoint don’t apply when the data is accessed through Spark.' },
      { id: 'b', text: 'Only the tables they can query in SQL', explain: 'Spark doesn’t evaluate SQL endpoint permissions.' },
      { id: 'c', text: 'An error, because ReadAll conflicts with DENY', explain: 'The two permissions apply to different engines.' },
      { id: 'd', text: 'Masked values for the denied tables', explain: 'Masking isn’t what a DENY does.' },
    ],
    answer: 'a',
  },
  {
    id: 'TS-08',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'cls-vs-ols-vs-ddm',
    stem: 'Match each requirement to the security feature that meets it.',
    sources: [S.whCls, S.whDdm, S.modelOls, S.whRls],
    prompts: [
      { id: 'p1', text: 'Queries that touch the Salary column in a warehouse must fail' },
      { id: 'p2', text: 'Show only the last four digits of phone numbers to most warehouse users' },
      { id: 'p3', text: 'Hide a column, including its name, from a semantic model role' },
      { id: 'p4', text: 'Each rep sees only their own rows in a warehouse table' },
    ],
    choices: [
      { id: 'c1', text: 'Column-level security (GRANT on columns)' },
      { id: 'c2', text: 'Dynamic data masking' },
      { id: 'c3', text: 'Semantic model object-level security' },
      { id: 'c4', text: 'Warehouse row-level security' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'CLS denies the column; queries touching it fail.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Masking returns the column with obscured values for non-privileged users.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'OLS hides the field and its metadata from the role.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'A security policy filters rows per user.' },
    ],
  },
  {
    id: 'TS-09',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'cls-vs-ols-vs-ddm',
    stem: 'A security reviewer proposes dynamic data masking as the only protection for national ID numbers in a warehouse. What does Learn advise?',
    sources: [S.whDdm],
    options: [
      { id: 'a', text: 'Masking alone is sufficient, because stored data is encrypted', explain: 'Masking doesn’t encrypt or change stored data.' },
      { id: 'b', text: 'Combine masking with column- and row-level security', explain: 'Correct. Masking only obscures results, so Learn recommends combining it with CLS and RLS.' },
      { id: 'c', text: 'Replace masking with a sensitivity label', explain: 'Labels don’t restrict columns in SQL queries.' },
      { id: 'd', text: 'Apply masking in the semantic model instead', explain: 'Dynamic data masking is a warehouse feature.' },
    ],
    answer: 'b',
  },
  {
    id: 'TS-10',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A lakehouse holds raw files for three regions under Files/raw/<region>. Each region’s analysts, who are workspace Viewers, may read only their own folder, from Spark or any engine that honors OneLake security. What should you create?',
    sources: [S.onelakeSecurity, S.onelakeAccessModel],
    options: [
      { id: 'a', text: 'A security policy in the SQL analytics endpoint', explain: 'SQL policies filter rows in SQL queries only, not file folders read by Spark.' },
      { id: 'b', text: 'A semantic model role per region', explain: 'Model roles restrict the semantic model only.' },
      { id: 'c', text: 'A OneLake security role per region', explain: 'Correct. OneLake security roles grant read access to chosen folders and are enforced across engines.' },
      { id: 'd', text: 'Three workspaces, one per region', explain: 'This splits the data instead of securing it in place.' },
    ],
    answer: 'c',
  },
  {
    id: 'TS-11',
    machineId: ts,
    bulletIds: ['M1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You need a OneLake security role that lets a group write to a lakehouse table and also restricts which rows they can see. What happens?',
    sources: [S.onelakeAccessModel],
    options: [
      { id: 'a', text: 'The role works; write access applies only to visible rows', explain: 'Learn doesn’t allow RLS constraints on ReadWrite roles.' },
      { id: 'b', text: 'It isn’t possible in one role', explain: 'Correct. Roles that grant ReadWrite can’t also have RLS or CLS constraints.' },
      { id: 'c', text: 'The row filter is ignored for writes but enforced for reads', explain: 'The combination isn’t allowed in one role.' },
      { id: 'd', text: 'The role converts to a SQL security policy', explain: 'OneLake roles aren’t converted to SQL objects.' },
    ],
    answer: 'b',
  },

  // ── Seal & Stamp: M1.4 sensitivity labels ───────────────────────────
  {
    id: 'SL-01',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A lakehouse is labeled Highly Confidential. A semantic model and report are later built on it. You want the label to flow to those items without manual labeling. Which capability does this?',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'Mandatory labeling', explain: 'Mandatory labeling forces users to pick a label; it doesn’t copy one.' },
      { id: 'b', text: 'Endorsement as Certified', explain: 'Endorsement signals trust and has nothing to do with labels.' },
      { id: 'c', text: 'Default labeling', explain: 'Default labeling applies a preset label to new items, not the source item’s label.' },
      { id: 'd', text: 'Downstream inheritance', explain: 'Correct. A label propagates downstream to items that depend on the labeled item.' },
    ],
    answer: 'd',
  },
  {
    id: 'SL-02',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'A report has a sensitivity label with an encryption (publishing) policy. For each export, select Yes if the label’s protection stays with the exported file. Otherwise, select No.',
    sources: [S.infoProtection],
    statements: [
      { id: 's1', text: 'Export to PDF', answer: true, explain: 'Yes. Export to Excel, PDF, and PowerPoint are supported export paths.' },
      { id: 's2', text: 'Export of visual data to a .csv file', answer: false, explain: 'No. Access control in other export paths, such as .csv or .txt, is unsupported.' },
      { id: 's3', text: 'Export to PowerPoint', answer: true, explain: 'Yes. PowerPoint is a supported export path.' },
    ],
  },
  {
    id: 'SL-03',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A user with a Microsoft Fabric Free license can’t apply sensitivity labels to Power BI reports, although the labels are published to them. What do they need, according to Learn?',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'A Power BI Pro or Premium Per User license', explain: 'Correct. Labeling Power BI items needs Pro or PPU in addition to the Purview licensing.' },
      { id: 'b', text: 'The workspace Admin role', explain: 'Role isn’t the documented requirement.' },
      { id: 'c', text: 'A Fabric capacity of F64 or larger', explain: 'Capacity size isn’t the documented requirement.' },
      { id: 'd', text: 'Certification rights from the Fabric admin', explain: 'Certification is endorsement, not labeling.' },
    ],
    answer: 'a',
  },
  {
    id: 'SL-04',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A governance team must apply sensitivity labels to 800 existing items in bulk, without opening each one. What should they use?',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'Downstream inheritance from one labeled item', explain: 'Inheritance only reaches items that depend on the labeled item.' },
      { id: 'b', text: 'Endorse all items as Master data', explain: 'Endorsement isn’t labeling.' },
      { id: 'c', text: 'The Power BI admin REST APIs', explain: 'Correct. Labels can be added, changed, or deleted programmatically through the admin REST APIs.' },
      { id: 'd', text: 'A deployment pipeline rule', explain: 'Deployment rules change data sources and parameters, not labels.' },
    ],
    answer: 'c',
  },
  {
    id: 'SL-05',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A semantic model imports data from an Azure SQL table that carries a Confidential label. Which labeling capability can apply that label to the semantic model automatically?',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'Inheritance from data sources', explain: 'Correct. It’s currently supported for Power BI semantic models only.' },
      { id: 'b', text: 'Downstream inheritance', explain: 'Downstream inheritance flows from Fabric items to items built on them, not from external sources.' },
      { id: 'c', text: 'Mandatory labeling', explain: 'Mandatory labeling requires users to choose a label.' },
      { id: 'd', text: 'Promotion', explain: 'Promotion is endorsement.' },
    ],
    answer: 'a',
  },
  {
    id: 'SL-06',
    machineId: ss,
    bulletIds: ['M1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A labeled semantic model is shared with a partner organization through cross-tenant external data sharing. Does the label’s access control protect the data in the partner tenant?',
    sources: [S.infoProtection],
    options: [
      { id: 'a', text: 'Yes, labels are enforced in every tenant that opens the data', explain: 'Learn says access control only applies in the tenant where the label was applied and in supported exports.' },
      { id: 'b', text: 'Yes, but only when both tenants use Premium capacities', explain: 'Capacity type doesn’t change cross-tenant behavior.' },
      { id: 'c', text: 'Only if the partner has the same label names', explain: 'Matching names doesn’t make access control work across tenants.' },
      { id: 'd', text: 'No, label access control isn’t supported across tenants', explain: 'Correct. Access control in cross-tenant scenarios is unsupported.' },
    ],
    answer: 'd',
  },

  // ── Seal & Stamp: M1.5 endorsement ──────────────────────────────────
  {
    id: 'SL-07',
    machineId: ss,
    bulletIds: ['M1.5'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'endorse-vs-label',
    stem: 'A lakehouse holds the company’s official customer list, which every team should use as the single source of truth. Which endorsement fits best?',
    sources: [S.endorsement],
    options: [
      { id: 'a', text: 'Promoted', explain: 'Promoted says the creator thinks it’s ready to share, not that it’s authoritative.' },
      { id: 'b', text: 'Master data', explain: 'Correct. Master data marks a data item as the authoritative source for core data such as customer lists.' },
      { id: 'c', text: 'Certified', explain: 'Certified means it meets quality standards; Master data is specific to authoritative core data.' },
      { id: 'd', text: 'A Confidential sensitivity label', explain: 'A label states sensitivity, not authority.' },
    ],
    answer: 'b',
  },
  {
    id: 'SL-08',
    machineId: ss,
    bulletIds: ['M1.5'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'Your organization is rolling out endorsement in Fabric. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.endorsement],
    statements: [
      { id: 's1', text: 'Any user with write permission on an item can promote it.', answer: true, explain: 'Yes. Promotion needs only write permission.' },
      { id: 's2', text: 'Any user can request certification, but only users specified by a Fabric admin can certify.', answer: true, explain: 'Yes. Learn states both.' },
      { id: 's3', text: 'Power BI dashboards can be certified.', answer: false, explain: 'No. Any item except Power BI dashboards can be promoted or certified.' },
    ],
  },
  {
    id: 'SL-10',
    machineId: ss,
    bulletIds: ['M1.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Users report that the Certified option is greyed out for every item, even for the data governance lead. What is the most likely cause?',
    sources: [S.endorsement],
    options: [
      { id: 'a', text: 'Certification isn’t enabled by a Fabric admin', explain: 'Correct. Certification must be enabled by a Fabric admin, who also specifies the certifiers.' },
      { id: 'b', text: 'The items aren’t labeled', explain: 'Certification doesn’t depend on labels.' },
      { id: 'c', text: 'The items must be promoted for 30 days first', explain: 'There’s no waiting period.' },
      { id: 'd', text: 'Only dashboards can be certified', explain: 'It’s the opposite: dashboards can’t be certified.' },
    ],
    answer: 'a',
  },
  {
    id: 'SL-11',
    machineId: ss,
    bulletIds: ['M1.5'],
    format: 'match',
    difficulty: 1,
    placement: true,
    trapPairId: 'endorse-vs-label',
    stem: 'Match each governance signal to who can apply it.',
    sources: [S.endorsement],
    prompts: [
      { id: 'p1', text: 'Promoted' },
      { id: 'p2', text: 'Certified' },
      { id: 'p3', text: 'Master data' },
    ],
    choices: [
      { id: 'c1', text: 'Any user with write permission on the item' },
      { id: 'c2', text: 'Users specified by a Fabric admin, after anyone requests it' },
      { id: 'c3', text: 'Users specified by a Fabric admin, for items that contain data' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Promotion needs only write permission.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Anyone can request certification; designated users certify.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Master data applies to data items and only admin-specified users can apply it.' },
    ],
  },
  {
    id: 'SL-12',
    machineId: ss,
    bulletIds: ['M1.5'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    trapPairId: 'endorse-vs-label',
    stem: 'Which two statements correctly contrast endorsement with sensitivity labels? Choose two.',
    sources: [S.endorsement, S.infoProtection],
    options: [
      { id: 'a', text: 'Endorsement helps people find trustworthy items; labels classify how sensitive data is', explain: 'Correct. They answer different questions.' },
      { id: 'b', text: 'Endorsement encrypts exported files', explain: 'Encryption on export comes from labels with publishing policies.' },
      { id: 'c', text: 'Labels can only be applied to semantic models', explain: 'Manual labeling is supported for all Fabric items.' },
      { id: 'd', text: 'Labels come from Microsoft Purview and can propagate downstream', explain: 'Correct. Labels are Purview classifications with downstream inheritance.' },
    ],
    answers: ['a', 'd'],
  },
]
