import { S } from '../sources'
import type { Question } from '../types'

const pl = 'pattern-ledger'
const dt = 'draft-table'
const cv = 'conveyor'
const rm = 'ripple-map'
const rl = 'remote-loom-control'
const pb = 'pattern-book'

export const lifecycleQuestions: Question[] = [
  // ── Pattern Ledger: M2.1 version control ────────────────────────────
  {
    id: 'PL-01',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 1,
    stem: 'Your team wants version history, branching, and the ability to revert changes for the items in a Fabric workspace. What should you configure?',
    sources: [S.gitIntro],
    options: [
      { id: 'a', text: 'A deployment pipeline with three stages', explain: 'Deployment pipelines promote content between stages; they don’t provide version history.' },
      { id: 'b', text: 'Git integration with an Azure DevOps or GitHub branch', explain: 'Correct. Git integration versions item definitions in a connected branch.' },
      { id: 'c', text: 'Workspace folders with dates in their names', explain: 'Folders organize items; they don’t keep history.' },
      { id: 'd', text: 'A OneLake shortcut to a backup lakehouse', explain: 'A shortcut references data; it doesn’t version item definitions.' },
    ],
    answer: 'b',
  },
  {
    id: 'PL-02',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'commit-vs-update',
    stem: 'A teammate merged changes into the Git branch connected to your workspace. The Source control pane shows those items as Update required. What should you do to bring the changes into the workspace?',
    sources: [S.gitIntro, S.gitProcess],
    options: [
      { id: 'a', text: 'Select Commit', explain: 'Commit sends workspace changes to Git, the opposite direction.' },
      { id: 'b', text: 'Disconnect and reconnect the workspace', explain: 'Reconnecting isn’t needed to pull changes.' },
      { id: 'c', text: 'Select Update', explain: 'Correct. Update brings the branch’s latest commit into the workspace.' },
      { id: 'd', text: 'Deploy the items with a deployment pipeline', explain: 'Pipelines copy between stage workspaces, not from Git.' },
    ],
    answer: 'c',
  },
  {
    id: 'PL-03',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are setting up Git integration for a Fabric workspace. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.gitIntro, S.gitProcess],
    statements: [
      { id: 's1', text: 'Only a workspace Admin can connect the workspace to a Git repository.', answer: true, explain: 'Yes. After the connection, Members and Contributors can commit and update.' },
      { id: 's2', text: 'Git integration works with on-premises Git servers.', answer: false, explain: 'No. Supported providers are cloud-based only: Azure DevOps, GitHub, and GitHub Enterprise.' },
      { id: 's3', text: 'Empty workspace folders are copied to Git.', answer: false, explain: 'No. Empty folders aren’t copied.' },
    ],
  },
  {
    id: 'PL-04',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'order',
    difficulty: 2,
    stem: 'You need to start versioning a Fabric workspace in GitHub. Put the steps in order.',
    sources: [S.gitIntro, S.gitProcess],
    items: [
      { id: 'i2', text: 'A workspace Admin connects the workspace to a repository branch and folder', explain: 'Second. The connection needs the tenant setting and the Admin role.' },
      { id: 'i4', text: 'Developers commit workspace changes to the branch', explain: 'Last. Ongoing work flows through commits and updates.' },
      { id: 'i1', text: 'A Fabric admin enables Git integration for the organization', explain: 'First. The organization’s admin must enable the feature.' },
      { id: 'i3', text: 'Choose the direction of the initial sync', explain: 'Third. When both sides have content, you choose which overwrites the other.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'PL-05',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'commit-vs-update',
    stem: 'You connect a workspace that already contains items to a Git branch that also contains different items. You choose to sync from Git to the workspace. What is the risk?',
    sources: [S.gitProcess],
    options: [
      { id: 'a', text: 'Workspace items are overwritten irreversibly', explain: 'Correct. Updating overwrites the workspace, and unlike a Git branch the workspace can’t be rolled back.' },
      { id: 'b', text: 'The Git branch is deleted and recreated', explain: 'Updating the workspace doesn’t change the branch.' },
      { id: 'c', text: 'Both versions are merged automatically', explain: 'Fabric doesn’t merge; one side overwrites the other.' },
      { id: 'd', text: 'Nothing happens until a deployment pipeline runs', explain: 'Pipelines are unrelated to Git sync.' },
    ],
    answer: 'a',
  },
  {
    id: 'PL-06',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'single',
    difficulty: 2,
    stem: 'A Contributor wants to switch the workspace to a different connected Git branch, but the option is blocked. The workspace Admin wants to allow it. What should the Admin do?',
    sources: [S.gitProcess],
    options: [
      { id: 'a', text: 'Make the Contributor a pipeline admin', explain: 'Pipeline admin has nothing to do with Git branches.' },
      { id: 'b', text: 'Disconnect Git so anyone can reconnect', explain: 'Only Admins can connect, so this wouldn’t help.' },
      { id: 'c', text: 'Grant the Contributor Build permission on every item', explain: 'Build permission is for semantic models.' },
      { id: 'd', text: 'Enable the workspace setting that lets Contributors change branch', explain: 'Correct. This workspace setting lets Members and Contributors switch the connected branch.' },
    ],
    answer: 'd',
  },
  {
    id: 'PL-07',
    machineId: pl,
    bulletIds: ['M2.1'],
    format: 'match',
    difficulty: 1,
    trapPairId: 'commit-vs-update',
    stem: 'Match each Git status in the Source control pane to what it means.',
    sources: [S.gitIntro, S.gitProcess],
    prompts: [
      { id: 'p1', text: 'Uncommitted changes' },
      { id: 'p2', text: 'Update required' },
      { id: 'p3', text: 'Conflict' },
    ],
    choices: [
      { id: 'c1', text: 'The workspace item changed and should be committed' },
      { id: 'c2', text: 'The branch has a newer version to bring into the workspace' },
      { id: 'c3', text: 'The item changed in both the workspace and Git' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Commit sends the change to Git.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Update brings the branch’s version into the workspace.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Changes on both sides must be resolved.' },
    ],
  },

  // ── Draft Table: M2.2 Power BI Desktop projects ─────────────────────
  {
    id: 'DT-01',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'pbi-files',
    stem: 'Developers want to review changes to a Power BI report and its semantic model as text diffs in pull requests. How should they save their work in Power BI Desktop?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'As a Power BI template (.pbit)', explain: 'A template is a starting point without data, not a source-control format.' },
      { id: 'b', text: 'As a .pbix file', explain: 'A .pbix is a single binary file that doesn’t diff well.' },
      { id: 'c', text: 'As a Power BI project (.pbip)', explain: 'Correct. A project stores definitions as plain-text files designed for source control.' },
      { id: 'd', text: 'As a .pbids file', explain: 'A .pbids file holds only a data source connection.' },
    ],
    answer: 'c',
  },
  {
    id: 'DT-02',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'pbi-files',
    stem: 'You saved a report named Sales as a Power BI project. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.pbip],
    statements: [
      { id: 's1', text: 'The project includes Sales.Report and Sales.SemanticModel folders.', answer: true, explain: 'Yes. Saving as a project creates the report and semantic model folders.' },
      { id: 's2', text: 'The generated .gitignore excludes the local data cache, so data isn’t committed.', answer: true, explain: 'Yes. cache.abf and localSettings.json are ignored.' },
      { id: 's3', text: 'The Sales.pbip file contains the full report definition.', answer: false, explain: 'No. The .pbip only points to the report folder; the definition files hold the content.' },
    ],
  },
  {
    id: 'DT-03',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 2,
    stem: 'In a Power BI project, in which format is the semantic model’s metadata stored so that it can be edited in VS Code?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'TMDL files', explain: 'Correct. Model metadata is stored as TMDL files.' },
      { id: 'b', text: 'A binary cache.abf file', explain: 'cache.abf is the local data cache, and it’s git-ignored.' },
      { id: 'c', text: 'One XML file per table', explain: 'This isn’t the project format.' },
      { id: 'd', text: 'CSV exports of each table', explain: 'Projects don’t store data as CSV.' },
    ],
    answer: 'a',
  },
  {
    id: 'DT-04',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 2,
    stem: 'A developer tries to save a Power BI project directly to a SharePoint document library from Power BI Desktop. What should you tell them?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'Save it as a .pbit instead', explain: 'A template doesn’t solve source control or storage.' },
      { id: 'b', text: 'It isn’t supported; save to a local folder', explain: 'Correct. Learn lists this limitation, and synced OneDrive folders can cause sync failures.' },
      { id: 'c', text: 'Turn on the large storage format first', explain: 'Storage format doesn’t affect where Desktop saves projects.' },
      { id: 'd', text: 'Publish the project to a workspace and download it', explain: 'This doesn’t give a project in SharePoint.' },
    ],
    answer: 'b',
  },
  {
    id: 'DT-05',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 3,
    stem: 'A semantic model from a Power BI project reaches the service through Fabric Git integration, not through Desktop Publish. Reports on it show no data. Why?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'Only metadata was deployed; refresh the model', explain: 'Correct. Other deployment paths deploy metadata only; Desktop Publish also sends the data cache.' },
      { id: 'b', text: 'The .gitignore deleted the report pages', explain: 'The .gitignore excludes only the cache and local settings.' },
      { id: 'c', text: 'Projects can’t contain Import tables', explain: 'Projects support Import models.' },
      { id: 'd', text: 'The workspace needs a deployment pipeline first', explain: 'Pipelines aren’t required.' },
    ],
    answer: 'a',
  },
  {
    id: 'DT-06',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'multi',
    difficulty: 2,
    stem: 'Which two files does Power BI Desktop’s generated .gitignore exclude from a project? Choose two.',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'definition.pbir', explain: 'The report definition is what you want in source control.' },
      { id: 'b', text: 'cache.abf', explain: 'Correct. The local data cache isn’t committed.' },
      { id: 'c', text: 'localSettings.json', explain: 'Correct. User-specific local settings aren’t committed.' },
      { id: 'd', text: 'The TMDL files', explain: 'TMDL holds the model metadata that should be committed.' },
    ],
    answers: ['b', 'c'],
  },
  {
    id: 'DT-07',
    machineId: dt,
    bulletIds: ['M2.2'],
    format: 'single',
    difficulty: 1,
    stem: 'A developer deleted the Sales.pbip file from a project folder by mistake. The Sales.Report and Sales.SemanticModel folders are intact. How can they open the report?',
    sources: [S.pbip],
    options: [
      { id: 'a', text: 'They can’t; the .pbip file is required', explain: 'The .pbip is optional, only a shortcut to the report folder.' },
      { id: 'b', text: 'Restore it from the cache.abf file', explain: 'The cache holds data, not the pointer file.' },
      { id: 'c', text: 'Open definition.pbir in the report folder', explain: 'Correct. You can open the report directly from its definition.pbir.' },
      { id: 'd', text: 'Download the report from the service as .pbix', explain: 'That works only for published content and isn’t needed here.' },
    ],
    answer: 'c',
  },

  // ── Conveyor: M2.3 deployment pipelines ─────────────────────────────
  {
    id: 'CV-01',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'A pipeline admin with no role in the Test workspace tries to deploy a notebook from Development to Test and can’t. What else do they need?',
    sources: [S.pipelinesProcess],
    options: [
      { id: 'a', text: 'At least Contributor in both the source and target workspaces', explain: 'Correct. Deploying between stages needs pipeline admin plus Contributor, Member, or Admin on both workspaces.' },
      { id: 'b', text: 'Nothing; pipeline admin covers all stages', explain: 'Pipeline access doesn’t grant permissions on workspace content.' },
      { id: 'c', text: 'Viewer in the target workspace', explain: 'Viewer isn’t enough to deploy.' },
      { id: 'd', text: 'Fabric administrator rights', explain: 'Tenant admin isn’t the documented requirement.' },
    ],
    answer: 'a',
  },
  {
    id: 'CV-02',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 3,
    stem: 'You deploy a Direct Lake semantic model from Development to Test. Test reports still show Development lakehouse data. What should you do?',
    sources: [S.pipelinesProcess, S.pipelinesRules],
    options: [
      { id: 'a', text: 'Refresh the model in Test', explain: 'Refresh reframes against the lakehouse it’s bound to, which is still Development.' },
      { id: 'b', text: 'Redeploy the reports only', explain: 'Reports autobind to the Test model; the model is the problem.' },
      { id: 'c', text: 'Add a datasource rule in Test, then redeploy', explain: 'Correct. Direct Lake models don’t autobind to the target stage’s items; use datasource rules.' },
      { id: 'd', text: 'Switch the model to Import before deploying', explain: 'This changes the design instead of fixing the binding.' },
    ],
    answer: 'c',
  },
  {
    id: 'CV-03',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'pipelines-vs-git',
    stem: 'You are creating a deployment pipeline. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.pipelinesIntro, S.pipelinesProcess],
    statements: [
      { id: 's1', text: 'A pipeline can have between 2 and 10 stages.', answer: true, explain: 'Yes. You set the number of stages when you create the pipeline.' },
      { id: 's2', text: 'Deploying copies the data in lakehouses and semantic models to the next stage.', answer: false, explain: 'No. Deployment copies item definitions (metadata), not data.' },
      { id: 's3', text: 'A deployment pipeline requires the workspace to be connected to Git.', answer: false, explain: 'No. Deployment pipelines and Git integration are independent.' },
    ],
  },
  {
    id: 'CV-04',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'A notebook in Development uses the Development lakehouse as its default lakehouse. After deployment to Production, it must use the Production lakehouse. What should you configure?',
    sources: [S.pipelinesRules],
    options: [
      { id: 'a', text: 'A parameter rule on the semantic model', explain: 'Parameter rules change model or dataflow parameters, not a notebook’s lakehouse.' },
      { id: 'b', text: 'A default lakehouse rule for the notebook in the Production stage', explain: 'Correct. Default lakehouse rules change the notebook’s lakehouse per stage.' },
      { id: 'c', text: 'A OneLake shortcut in Production to the Development lakehouse', explain: 'This keeps Production reading Development data.' },
      { id: 'd', text: 'Git integration on the Production workspace', explain: 'Git doesn’t change per-stage settings.' },
    ],
    answer: 'b',
  },
  {
    id: 'CV-05',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'You try to deploy only a report from Test to Production. The deployment fails. The report’s semantic model isn’t in Production yet. Why?',
    sources: [S.pipelinesProcess],
    options: [
      { id: 'a', text: 'Reports can only be deployed with a deployment plan', explain: 'Deployment plans are optional.' },
      { id: 'b', text: 'Production stages can’t receive reports', explain: 'Any supported item can be deployed.' },
      { id: 'c', text: 'The report must be certified first', explain: 'Endorsement isn’t a deployment requirement.' },
      { id: 'd', text: 'Its semantic model must be deployed too', explain: 'Correct. Deploy the semantic model too, or first.' },
    ],
    answer: 'd',
  },
  {
    id: 'CV-06',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'match',
    difficulty: 3,
    stem: 'Match each deployment pipeline action to the permissions it needs.',
    sources: [S.pipelinesProcess],
    prompts: [
      { id: 'p1', text: 'Deploy a notebook from Development to an existing Test workspace' },
      { id: 'p2', text: 'Deploy to an empty stage' },
      { id: 'p3', text: 'Assign a workspace to a stage' },
    ],
    choices: [
      { id: 'c1', text: 'Pipeline admin + at least Contributor on source and target workspaces' },
      { id: 'c2', text: 'Pipeline admin + at least Contributor on the source workspace' },
      { id: 'c3', text: 'Pipeline admin + Admin of the workspace being assigned' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Deploying between stages needs a role on both workspaces.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Only the source workspace matters when the target is empty.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Assigning needs Admin of that workspace.' },
    ],
  },
  {
    id: 'CV-07',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'pipelines-vs-git',
    stem: 'A team needs to promote tested content from a Development workspace to Test and then to Production inside Fabric, changing data sources per stage. Which feature should they use?',
    sources: [S.pipelinesIntro],
    options: [
      { id: 'a', text: 'Deployment pipelines', explain: 'Correct. Pipelines promote content through stages and apply rules per stage.' },
      { id: 'b', text: 'Data pipelines in Data Factory', explain: 'Data pipelines orchestrate data movement, not content release.' },
      { id: 'c', text: 'Git integration only', explain: 'Git versions content but doesn’t promote it between stage workspaces with rules.' },
      { id: 'd', text: 'Impact analysis', explain: 'Impact analysis lists dependents; it doesn’t deploy.' },
    ],
    answer: 'a',
  },
  {
    id: 'CV-08',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'A data source rule should switch a semantic model from an Azure SQL database in Test to a Snowflake database in Production. The rule can’t be applied. Why?',
    sources: [S.pipelinesRules],
    options: [
      { id: 'a', text: 'Rules can only be set on the Development stage', explain: 'Rules are set on target stages such as Production.' },
      { id: 'b', text: 'Rules only switch between same-type sources', explain: 'Correct. Learn: data source rules work only when switching between data sources of the same type.' },
      { id: 'c', text: 'Snowflake isn’t supported in semantic models', explain: 'The limitation is about switching source types in a rule.' },
      { id: 'd', text: 'Rules take effect only after Git commits', explain: 'Rules take effect on the next deployment.' },
    ],
    answer: 'b',
  },
  {
    id: 'CV-09',
    machineId: cv,
    bulletIds: ['M2.3'],
    format: 'order',
    difficulty: 2,
    stem: 'You are setting up a new deployment pipeline. A semantic model must use the production database in the Production stage. Put the steps in order.',
    sources: [S.pipelinesStart, S.pipelinesRules],
    items: [
      { id: 'i4', text: 'Define a data source rule for the semantic model in the Production stage', explain: 'Fourth. Rules are created under an item in the stage where they apply.' },
      { id: 'i1', text: 'Create the pipeline and name its stages', explain: 'First. The number of stages is fixed at creation.' },
      { id: 'i5', text: 'Deploy from Test to Production again', explain: 'Last. Learn: rules don’t apply until you deploy to the stage where they were created.' },
      { id: 'i2', text: 'Assign a workspace to each stage', explain: 'Second. Each stage is backed by one workspace.' },
      { id: 'i3', text: 'Deploy the content through to the Production stage', explain: 'Third. The semantic model must exist in Production before a rule can be set on it.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4', 'i5'],
  },

  // ── Ripple Map: M2.4 impact analysis ────────────────────────────────
  {
    id: 'RM-01',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'lineage-vs-impact',
    stem: 'Before you drop a column from a lakehouse table, you need to list every downstream item that depends on the lakehouse, including items in other workspaces. What should you use?',
    sources: [S.impact, S.lineage],
    options: [
      { id: 'a', text: 'Lineage view of the workspace', explain: 'Lineage view doesn’t show downstream items in other workspaces.' },
      { id: 'b', text: 'Impact analysis on the lakehouse', explain: 'Correct. Impact analysis lists downstream items across workspaces.' },
      { id: 'c', text: 'The deployment pipeline compare view', explain: 'Compare shows differences between stages, not dependents.' },
      { id: 'd', text: 'The Git Source control pane', explain: 'Git status shows changes, not dependents.' },
    ],
    answer: 'b',
  },
  {
    id: 'RM-02',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 2,
    stem: 'Impact analysis on a warehouse shows downstream reports in workspaces you can’t access. You need to warn their owners about a schema change. What should you do?',
    sources: [S.impact],
    options: [
      { id: 'a', text: 'Ask a Fabric admin to grant you access to each workspace', explain: 'Not needed: notifications reach workspaces you can’t access.' },
      { id: 'b', text: 'Endorse the warehouse as Certified', explain: 'Endorsement doesn’t notify anyone.' },
      { id: 'c', text: 'Select Notify contacts and describe the change', explain: 'Correct. It emails the contact lists of all affected workspaces, even ones you can’t access.' },
      { id: 'd', text: 'Add a sensitivity label so it propagates downstream', explain: 'Labels don’t send change notices.' },
    ],
    answer: 'c',
  },
  {
    id: 'RM-03',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'lineage-vs-impact',
    stem: 'You are planning a change to a semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.impact, S.lineage],
    statements: [
      { id: 's1', text: 'You need write permission on the semantic model to run impact analysis on it.', answer: true, explain: 'Yes. Impact analysis requires write permission on the item.' },
      { id: 's2', text: 'Impact analysis can show either direct children or all downstream items.', answer: true, explain: 'Yes. You switch between Child items and All downstream items.' },
      { id: 's3', text: 'Workspace Viewers can see data sources in lineage view.', answer: false, explain: 'No. Viewers can open lineage view but don’t see data sources.' },
    ],
  },
  {
    id: 'RM-04',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'lineage-vs-impact',
    stem: 'You want one diagram of every item in a workspace and how data flows between them, including upstream sources one level outside the workspace. What should you open?',
    sources: [S.lineage],
    options: [
      { id: 'a', text: 'Lineage view', explain: 'Correct. Lineage view shows the workspace’s items, their connections, and upstream sources one level out.' },
      { id: 'b', text: 'Impact analysis on each item', explain: 'Impact analysis starts from one item and lists downstream dependents.' },
      { id: 'c', text: 'The OneLake catalog Govern tab', explain: 'The Govern tab shows governance insights, not a data-flow diagram.' },
      { id: 'd', text: 'The Monitor hub', explain: 'The Monitor hub tracks activity runs, not lineage.' },
    ],
    answer: 'a',
  },
  {
    id: 'RM-05',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 3,
    stem: 'You run impact analysis on a data source (a SQL Server database) rather than on a Fabric item. What does it show?',
    sources: [S.impact],
    options: [
      { id: 'a', text: 'All downstream items in every workspace, grouped by type and by workspace', explain: 'For data sources, only direct children are shown.' },
      { id: 'b', text: 'Nothing; impact analysis doesn’t support data sources', explain: 'Impact analysis does support data sources, with limits.' },
      { id: 'c', text: 'The tables and columns used by each report', explain: 'Impact analysis lists items, not column usage.' },
      { id: 'd', text: 'Only its direct children, along with the connection string', explain: 'Correct. For data sources it shows direct children and the connection string.' },
    ],
    answer: 'd',
  },
  {
    id: 'RM-06',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'single',
    difficulty: 2,
    stem: 'In an impact analysis, some downstream items appear as “Limited access”. What does this mean?',
    sources: [S.impact],
    options: [
      { id: 'a', text: 'The items are in a workspace on a paused capacity', explain: 'Capacity state isn’t what the label means.' },
      { id: 'b', text: 'You don’t have access to those items', explain: 'Correct. Items you can’t access appear as Limited access.' },
      { id: 'c', text: 'The items are protected by RLS', explain: 'RLS is unrelated to impact analysis labels.' },
      { id: 'd', text: 'The items aren’t endorsed', explain: 'Endorsement isn’t shown this way.' },
    ],
    answer: 'b',
  },
  {
    id: 'RM-07',
    machineId: rm,
    bulletIds: ['M2.4'],
    format: 'multi',
    difficulty: 2,
    stem: 'You plan to rename a column in a Dataflow Gen2 output. Which two ways can you open impact analysis for the dataflow? Choose two.',
    sources: [S.impact],
    options: [
      { id: 'a', text: 'From the dataflow’s card in lineage view', explain: 'Correct. Impact analysis opens from the item card in lineage view.' },
      { id: 'b', text: 'From Lineage on the dataflow’s details page', explain: 'Correct. It also opens from the item’s details page.' },
      { id: 'c', text: 'From the dataflow’s refresh history', explain: 'Refresh history shows runs, not dependents.' },
      { id: 'd', text: 'From the workspace’s Manage access pane', explain: 'Manage access controls roles.' },
    ],
    answers: ['a', 'b'],
  },

  // ── Remote Loom Control: M2.5 XMLA endpoint ─────────────────────────
  {
    id: 'RL-01',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'xmla-read-vs-readwrite',
    stem: 'Deploying a semantic model from Tabular Editor to a Fabric capacity workspace fails, while DAX queries from DAX Studio work. What should a capacity admin check?',
    sources: [S.xmla],
    options: [
      { id: 'a', text: 'That the XMLA Endpoint setting is Read Write for the capacity', explain: 'Correct. Read-only is the default; writes need Read Write.' },
      { id: 'b', text: 'That the model has Large storage format turned off', explain: 'Learn recommends large format on for XMLA writes.' },
      { id: 'c', text: 'That the workspace is connected to Git', explain: 'Git isn’t required for XMLA.' },
      { id: 'd', text: 'That DAX Studio is closed', explain: 'Other connections don’t block deployment.' },
    ],
    answer: 'a',
  },
  {
    id: 'RL-02',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 1,
    stem: 'You need the server address to connect SSMS to a workspace’s semantic models over XMLA. Where do you find it?',
    sources: [S.xmla],
    options: [
      { id: 'a', text: 'In the semantic model’s refresh history', explain: 'Refresh history doesn’t contain the connection URL.' },
      { id: 'b', text: 'In the lakehouse’s SQL analytics endpoint settings', explain: 'That’s a T-SQL connection string, not XMLA.' },
      { id: 'c', text: 'In Workspace settings, as the workspace connection URL', explain: 'Correct. The powerbi:// URL is under the workspace’s connection settings.' },
      { id: 'd', text: 'In the tenant admin portal’s audit logs', explain: 'Audit logs don’t provide connection URLs.' },
    ],
    answer: 'c',
  },
  {
    id: 'RL-03',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 2,
    stem: 'In SSMS connected to a workspace’s XMLA endpoint, you send a TMSL refresh command for the FactSales table. You need to reload its data and recalculate all dependents. Which refresh type should the command use?',
    sources: [S.tmslRefresh, S.xmla],
    options: [
      { id: 'a', text: 'calculate', explain: 'calculate recalculates without reloading data.' },
      { id: 'b', text: 'full', explain: 'Correct. full refreshes data and recalculates all dependents.' },
      { id: 'c', text: 'clearValues', explain: 'clearValues empties the object’s values instead of reloading them.' },
      { id: 'd', text: 'defragment', explain: 'defragment cleans unused dictionary values; it doesn’t reload data.' },
    ],
    answer: 'b',
  },
  {
    id: 'RL-04',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'xmla-read-vs-readwrite',
    stem: 'You are planning XMLA-based management of semantic models. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.xmla, S.largeModels],
    statements: [
      { id: 's1', text: 'Semantic models in Pro workspaces support XMLA write operations.', answer: false, explain: 'No. Pro workspaces don’t support XMLA writes; you need a capacity or PPU.' },
      { id: 's2', text: 'The XMLA Endpoint setting applies to all workspaces on the capacity.', answer: true, explain: 'Yes. It’s a capacity-level setting.' },
      { id: 's3', text: 'Workspace Contributors have Write permission on semantic models over XMLA.', answer: true, explain: 'Yes. Contributor and above have Write, effectively Analysis Services database admin.' },
    ],
  },
  {
    id: 'RL-05',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 3,
    stem: 'A model has an incremental refresh policy. An administrator must reload one specific historical partition outside the policy’s refresh window. What can they use?',
    sources: [S.tmslRefresh, S.xmla],
    options: [
      { id: 'a', text: 'A scheduled refresh in the service', explain: 'Scheduled refresh follows the policy’s windows.' },
      { id: 'b', text: 'A TMSL refresh command over the XMLA endpoint', explain: 'Correct. TMSL refresh over XMLA can target objects and override the incremental refresh policy.' },
      { id: 'c', text: 'Publishing the .pbix again', explain: 'Republishing isn’t a partition refresh.' },
      { id: 'd', text: 'Changing the archive period temporarily', explain: 'This changes the policy and can drop partitions.' },
    ],
    answer: 'b',
  },
  {
    id: 'RL-06',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'match',
    difficulty: 2,
    trapPairId: 'xmla-read-vs-readwrite',
    stem: 'Match each task to the XMLA endpoint setting it needs. A choice may be used more than once or not at all.',
    sources: [S.xmla],
    prompts: [
      { id: 'p1', text: 'Run DAX queries from DAX Studio' },
      { id: 'p2', text: 'Deploy a tabular project from Visual Studio' },
      { id: 'p3', text: 'Save metadata changes from Tabular Editor' },
    ],
    choices: [
      { id: 'c1', text: 'Read-only is enough' },
      { id: 'c2', text: 'Read Write is required' },
      { id: 'c3', text: 'XMLA isn’t used' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Queries only need read access.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Deployment writes metadata.' },
      { promptId: 'p3', choiceId: 'c2', explain: 'Saving changes is a write operation.' },
    ],
  },
  {
    id: 'RL-07',
    machineId: rl,
    bulletIds: ['M2.5'],
    format: 'single',
    difficulty: 1,
    stem: 'Which tool can query and manage a semantic model through the XMLA endpoint, outside Power BI Desktop?',
    sources: [S.xmla],
    options: [
      { id: 'a', text: 'A KQL queryset', explain: 'KQL querysets connect to KQL databases.' },
      { id: 'b', text: 'The visual query editor', explain: 'It connects to warehouses and endpoints.' },
      { id: 'c', text: 'Data Wrangler', explain: 'Data Wrangler works on notebook DataFrames.' },
      { id: 'd', text: 'SQL Server Management Studio (SSMS)', explain: 'Correct. SSMS connects to the workspace XMLA URL like an Analysis Services server.' },
    ],
    answer: 'd',
  },

  // ── Pattern Book: M2.6 reusable assets ──────────────────────────────
  {
    id: 'PB-01',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'pbi-files',
    stem: 'Report authors should start every new report from a standard layout, model, and set of queries, but without anyone else’s data. What should you distribute?',
    sources: [S.templates],
    options: [
      { id: 'a', text: 'A .pbix file', explain: 'A .pbix includes the imported data.' },
      { id: 'b', text: 'A Power BI template (.pbit)', explain: 'Correct. A template has report pages, the model definition, and queries but no data.' },
      { id: 'c', text: 'A .pbids file', explain: 'A .pbids holds only a connection.' },
      { id: 'd', text: 'A Power BI project (.pbip)', explain: 'A project is a source-control format, and its data cache is excluded only from Git.' },
    ],
    answer: 'b',
  },
  {
    id: 'PB-02',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'pbi-files',
    stem: 'New analysts struggle to find the right server and database. You want a file they double-click to open Power BI Desktop’s Get data for that source, with no credentials stored. What should you create?',
    sources: [S.pbids],
    options: [
      { id: 'a', text: 'A .pbids data source file', explain: 'Correct. It describes one connection and prompts for credentials when opened.' },
      { id: 'b', text: 'A .pbit template', explain: 'A template includes a whole report and model.' },
      { id: 'c', text: 'A shortcut in a lakehouse', explain: 'Shortcuts don’t open Power BI Desktop.' },
      { id: 'd', text: 'A deployment pipeline rule', explain: 'Rules change sources between stages.' },
    ],
    answer: 'a',
  },
  {
    id: 'PB-03',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    trapPairId: 'pbi-files',
    stem: 'You are creating reusable files for report authors. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.templates, S.pbids],
    statements: [
      { id: 's1', text: 'A single .pbids file can describe connections to three different data sources.', answer: false, explain: 'No. A .pbids supports one data source; more causes an error.' },
      { id: 's2', text: 'Filter values saved in report metadata remain in a .pbit file even though it has no data.', answer: true, explain: 'Yes. Learn warns that such values stay in the template.' },
      { id: 's3', text: 'Opening a .pbit prompts for parameter values and data source credentials.', answer: true, explain: 'Yes. The template loads data after you supply them.' },
    ],
  },
  {
    id: 'PB-04',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Report authors in five workspaces should reuse one certified Sales semantic model instead of building their own. What must each author have on the model?',
    sources: [S.sharedModels],
    options: [
      { id: 'a', text: 'Workspace Admin on the model’s workspace', explain: 'More than needed; Build is enough to create content.' },
      { id: 'b', text: 'Build permission', explain: 'Correct. Build controls who can create content on a shared model.' },
      { id: 'c', text: 'A copy of the model in their workspace', explain: 'Copies defeat the purpose of a shared model.' },
      { id: 'd', text: 'A sensitivity label on the model', explain: 'Labels don’t grant permissions.' },
    ],
    answer: 'b',
  },
  {
    id: 'PB-05',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A user with only a free license has Build permission on a shared semantic model, but can’t create a report from it. According to Learn, when can free users build reports from shared models?',
    sources: [S.sharedModels],
    options: [
      { id: 'a', text: 'Never; free users can only view', explain: 'Learn describes a case where free users can build reports.' },
      { id: 'b', text: 'When the model is certified', explain: 'Endorsement doesn’t change licensing.' },
      { id: 'c', text: 'When the model is on Premium or an F64-or-larger capacity', explain: 'Correct. Free users can build from shared models with Build permission on those capacities.' },
      { id: 'd', text: 'When the model is shared through a .pbids file', explain: 'A .pbids only describes a connection.' },
    ],
    answer: 'c',
  },
  {
    id: 'PB-06',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'order',
    difficulty: 1,
    placement: true,
    stem: 'You need to create a Power BI template from an existing report and use it to start a new report. Put the steps in order.',
    sources: [S.templates],
    items: [
      { id: 'i2', text: 'Add a description for the template', explain: 'Second. Describe the template for authors.' },
      { id: 'i4', text: 'Enter parameter values and credentials to load data', explain: 'Last. The template has no data until loaded.' },
      { id: 'i1', text: 'Select File > Export > Power BI template', explain: 'First. Export the report as a .pbit.' },
      { id: 'i3', text: 'Open the .pbit with File > Import > Power BI template', explain: 'Third. Importing starts a new report from it.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'PB-07',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You want to export a .pbids file for a SQL Server source that you already use in Power BI Desktop. Where do you do this?',
    sources: [S.pbids],
    options: [
      { id: 'a', text: 'File > Export > Power BI template', explain: 'That exports a .pbit, not a .pbids.' },
      { id: 'b', text: 'The Publish dialog', explain: 'Publish sends a report to the service.' },
      { id: 'c', text: 'Model view > Manage relationships', explain: 'Relationships aren’t data sources.' },
      { id: 'd', text: 'Data source settings > Export PBIDS', explain: 'Correct. Export PBIDS is in Data source settings.' },
    ],
    answer: 'd',
  },
  {
    id: 'PB-08',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'pbi-files',
    stem: 'Match each Power BI file type to what it contains.',
    sources: [S.templates, S.pbids, S.pbip],
    prompts: [
      { id: 'p1', text: '.pbix' },
      { id: 'p2', text: '.pbit' },
      { id: 'p3', text: '.pbids' },
      { id: 'p4', text: '.pbip' },
    ],
    choices: [
      { id: 'c1', text: 'Report, model, and imported data in one file' },
      { id: 'c2', text: 'Report, model, and queries, but no data' },
      { id: 'c3', text: 'One data source connection, as JSON' },
      { id: 'c4', text: 'A pointer to a folder of plain-text report and model definitions' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'The standard single-file report.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'A template for new reports.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Opens Get data for that source.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'The project file points to the report folder.' },
    ],
  },
  {
    id: 'PB-09',
    machineId: pb,
    bulletIds: ['M2.6'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'You want report authors across the organization to find and reuse your shared semantic model. Which two actions help? Choose two.',
    sources: [S.sharedModels, S.endorsement],
    options: [
      { id: 'a', text: 'Export the model as a .pbids file', explain: 'A .pbids describes a data source connection, not a shared model.' },
      { id: 'b', text: 'Turn off the XMLA endpoint', explain: 'This doesn’t help reuse.' },
      { id: 'c', text: 'Endorse the model as Promoted or Certified', explain: 'Correct. Endorsement helps people find trustworthy content.' },
      { id: 'd', text: 'Grant Build permission to the authors', explain: 'Correct. Build lets them create content on the model.' },
    ],
    answers: ['c', 'd'],
  },
]
