import { S } from '../sources'
import type { Question } from '../types'

/** Step 7: difficulty-3 scenario questions for Implement and manage semantic models. */

const lg = 'loom-gearbox'
const wf = 'warp-frame'
const pc = 'punch-card-reader'
const jh = 'jacquard-head'
const wb = 'wide-beam'
const dl = 'double-loom'
const sg = 'speed-governor'
const ds = 'direct-lake-shuttle'
const bw = 'batch-winder'

export const semanticHardQuestions: Question[] = [
  {
    id: 'LG-H1',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'storage-modes',
    stem: 'A Direct Lake on OneLake semantic model reads an IT-managed lakehouse. A finance analyst has no write permission on that lakehouse but must add a small budget table from a spreadsheet, cleaned with Power Query, and relate it to the existing tables. What should the analyst do?',
    sources: [S.directLake, S.composite],
    options: [
      { id: 'a', text: 'Write the budget data into the lakehouse with a notebook so it becomes a Direct Lake table', explain: 'The analyst can’t modify the lakehouse, so this isn’t possible here.' },
      { id: 'b', text: 'Switch the whole model to Direct Lake on SQL analytics endpoints and add the spreadsheet there', explain: 'Direct Lake on SQL can’t mix storage modes in the same model, so it can’t hold a spreadsheet table alongside its Direct Lake tables.' },
      { id: 'c', text: 'Add the budget as an Import table to the model, making it a composite model', explain: 'Correct. Learn suggests Import tables when the author can’t modify the source item, because Import supports Power Query preparation inside the model, and Direct Lake on OneLake tables can be combined with Import tables.' },
      { id: 'd', text: 'Add the spreadsheet as a DirectQuery table so it always shows the latest values', explain: 'DirectQuery queries the source on every visual and is limited to M that can be translated; Learn’s suggestion for Power Query preparation inside the model is an Import table.' },
    ],
    answer: 'c',
  },
  {
    id: 'WF-H1',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'single',
    difficulty: 3,
    stem: 'An imported model has Product, Subcategory, and Category tables related in a chain, and a Sales fact with OrderDateKey and ShipDateKey columns. Report authors need a Category > Subcategory > Product hierarchy and must analyze sales by order date and by ship date with a single Date table. What should you do?',
    sources: [S.star, S.relationships],
    options: [
      { id: 'a', text: 'Keep the three product tables and set every relationship to Both; relate Date to Sales twice, both active', explain: 'A hierarchy can’t span tables, and only one relationship between two tables can be active.' },
      { id: 'b', text: 'Flatten the product tables into one Product table; make the order-date relationship active and the ship-date one inactive, used through USERELATIONSHIP in ship-date measures', explain: 'Correct. Flattening lets the hierarchy come from one table, and a role-playing Date table keeps one active relationship while measures activate the inactive one with USERELATIONSHIP.' },
      { id: 'c', text: 'Flatten the product tables, and duplicate the Sales fact so each copy has one active date relationship', explain: 'Duplicating the fact doubles its size and splits measures; USERELATIONSHIP handles the second date role.' },
      { id: 'd', text: 'Relate Date to Sales on ShipDateKey only, and build the order-date analysis with a calculated column', explain: 'That makes order-date analysis depend on per-row workarounds instead of the role-playing pattern Learn describes.' },
    ],
    answer: 'b',
  },
  {
    id: 'WF-H2',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'yesno',
    difficulty: 3,
    stem: 'You are reviewing a star schema semantic model before it goes to production. Some analysts use Analyze in Excel. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.star, S.relationships, S.calcGroups],
    statements: [
      { id: 's1', text: 'Analysts using Analyze in Excel can only aggregate numbers through explicit DAX measures.', answer: true, explain: 'Yes. Learn notes MDX clients such as Analyze in Excel need explicit measures.' },
      { id: 's2', text: 'Setting every dimension-to-fact relationship to Both is the recommended default for a star schema.', answer: false, explain: 'No. Keep cross-filter direction single unless a specific pattern, such as a bridge table, needs Both.' },
      { id: 's3', text: 'Two relationships between Date and Sales can both be active if they use different columns.', answer: false, explain: 'No. Only one relationship between two tables can be active; the others are inactive and used with USERELATIONSHIP.' },
    ],
  },
  {
    id: 'WF-H3',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'regular-vs-limited',
    stem: 'Sales targets are stored by product category and month, but the Product dimension is at product level and the Date dimension is at day level. Targets must filter correctly when users slice by category and by month. How should you relate the Target table on the Category column?',
    sources: [S.manyToMany, S.relationships],
    options: [
      { id: 'a', text: 'Use a many-to-many relationship between Product[Category] and Target[Category] that filters in a single direction, from Product to Target', explain: 'Correct. For higher-grain facts on a non-date column, Learn uses a many-to-many relationship filtering from the dimension to the fact.' },
      { id: 'b', text: 'Use a many-to-many relationship between Product[Category] and Target[Category] with cross-filter direction set to Both', explain: 'Learn’s guidance for this case filters in a single direction, from the dimension to the fact.' },
      { id: 'c', text: 'Add a bridge table of all category–product pairs and relate it with one-to-many relationships', explain: 'A bridge resolves many-to-many dimensions; for a higher-grain fact, Learn relates the fact on the category column directly.' },
      { id: 'd', text: 'Relate Target to Product on ProductKey after copying each target to every product in its category', explain: 'Spreading targets across products duplicates the target amounts and gives wrong totals.' },
    ],
    answer: 'a',
  },
  {
    id: 'PC-H1',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 3,
    stem: "A developer writes this measure to return last year's sales: Sales LY = VAR CurrentSales = [Total Sales] RETURN CALCULATE(CurrentSales, SAMEPERIODLASTYEAR('Date'[Date])). In a visual by year it shows the same values as Total Sales. Why, and what is the fix?",
    sources: [S.varBP, S.varRef, S.calculate],
    options: [
      { id: 'a', text: 'SAMEPERIODLASTYEAR needs a marked date table; mark Date as a date table', explain: 'Marking the date table doesn’t change how the variable is evaluated, which is the cause here.' },
      { id: 'b', text: 'VAR can’t hold a measure value; use a calculated column instead', explain: 'Variables can hold any value, including a measure result.' },
      { id: 'c', text: 'The variable is evaluated once, before CALCULATE applies its filter; put CALCULATE([Total Sales], SAMEPERIODLASTYEAR(…)) inside the variable or the RETURN', explain: 'Correct. A variable is evaluated once, outside the filters the RETURN expression applies, so CALCULATE can’t change a value that was already computed.' },
      { id: 'd', text: 'CALCULATE ignores time intelligence filters; use FILTER over the Date table', explain: 'CALCULATE accepts table filter functions such as SAMEPERIODLASTYEAR; the problem is the variable’s evaluation.' },
    ],
    answer: 'c',
  },
  {
    id: 'PC-H2',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 3,
    stem: 'A matrix shows sales by month for each product category. You need a measure that shows the previous month’s sales on each row, restarting for every category. Which DAX function family fits best, and how?',
    sources: [S.offset, S.window, S.index],
    options: [
      { id: 'a', text: 'INDEX, with position 1, ORDERBY month, and PARTITIONBY category', explain: 'INDEX returns a row by absolute position, so position 1 is always the first month of the category.' },
      { id: 'b', text: 'OFFSET, with -1, ORDERBY month, and PARTITIONBY category', explain: 'Correct. OFFSET returns the row a given distance before or after the current row; -1 is the previous month, and PARTITIONBY restarts it for each category.' },
      { id: 'c', text: 'WINDOW, from the first row to the current row, ORDERBY month', explain: 'That window covers every month up to the current one, which suits a running total, not the previous month.' },
      { id: 'd', text: 'HASONEVALUE on the month column, then subtract one from the month number', explain: 'HASONEVALUE only tests whether one value is filtered; it doesn’t navigate rows.' },
    ],
    answer: 'b',
  },
  {
    id: 'JH-H1',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'calcgroup-vs-fieldparam',
    stem: 'You add a time intelligence calculation group to a model that previously relied on report authors dragging numeric columns into visuals. Which two effects should you warn the authors about? Choose two.',
    sources: [S.calcGroups, S.fieldParams],
    options: [
      { id: 'a', text: 'Existing field parameters stop working until they are rebuilt', explain: 'Learn lists no such effect; field parameter limits concern implicit measures, AI visuals, drillthrough, and live connections.' },
      { id: 'b', text: 'Every measure in reports changes to the variant data type', explain: 'Correct. Adding any calculation group changes measures to the variant data type; removing all calculation groups reverts them.' },
      { id: 'c', text: 'Dragging a numeric column to sum it no longer works, so they need explicit measures', explain: 'Correct. Calculation groups need Discourage implicit measures turned on, so implicit aggregations stop working.' },
      { id: 'd', text: 'The calculation items can only apply to one measure, chosen when the group is created', explain: 'Calculation items use SELECTEDMEASURE(), so they apply to whatever measure is in the visual.' },
    ],
    answers: ['b', 'c'],
  },
  {
    id: 'JH-H2',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dfs-vs-format',
    stem: 'Readers must switch one column chart between Sales, Margin, and Units with a slicer. A Year-over-Year calculation item must show as a percentage while staying numeric so the chart can plot it. Which design meets both requirements?',
    sources: [S.fieldParams, S.dynamicFormat, S.calcGroups],
    options: [
      { id: 'a', text: 'A field parameter for the three measures, and a dynamic format string on the Year-over-Year calculation item', explain: 'Correct. A field parameter lets readers swap which measure the visual shows, and a dynamic format string changes the display format while the value stays numeric.' },
      { id: 'b', text: 'A calculation group with Sales, Margin, and Units items, and FORMAT() in the Year-over-Year item', explain: 'A calculation group changes how measures are calculated rather than which measure is shown, and FORMAT() returns text the chart can’t plot.' },
      { id: 'c', text: 'Three bookmarks with three charts, and FORMAT() in the Year-over-Year item', explain: 'FORMAT() turns the result into text, which breaks charts that need numbers.' },
      { id: 'd', text: 'A field parameter for the three measures, and a static percentage format on every base measure', explain: 'A static percentage format would also display Sales and Units as percentages.' },
    ],
    answer: 'a',
  },
  {
    id: 'WB-H1',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 3,
    stem: 'An Import model is 8 GB in Power BI Desktop. With incremental refresh in a workspace on a Fabric F capacity, it is expected to grow to about 25 GB, and a CI/CD tool deploys metadata changes through the XMLA endpoint. What should you do?',
    sources: [S.largeModels, S.xmla],
    options: [
      { id: 'a', text: 'Keep the default storage format; it grows automatically to the capacity limit', explain: 'The default format is limited (1 GB by default in the service); large models beyond 10 GB require the large semantic model storage format.' },
      { id: 'b', text: 'Publish the full 25 GB file from Power BI Desktop after loading all history locally', explain: 'Publishing from Desktop is still capped at 10 GB; large models grow beyond that through refresh in the service.' },
      { id: 'c', text: 'Move the model to a Pro workspace to remove the size limit', explain: 'Pro workspaces don’t lift the limit and don’t support XMLA write operations.' },
      { id: 'd', text: 'Turn on large semantic model storage format, publish the smaller file, and let refreshes in the service grow it', explain: 'Correct. The large format is required beyond 10 GB and recommended for XMLA write operations, and the model grows through refresh after publishing.' },
    ],
    answer: 'd',
  },
  {
    id: 'DL-H1',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dual-vs-hybrid',
    stem: 'A composite model has a large Sales fact in DirectQuery from a SQL source and a Customer dimension in Import mode from the same source. Sales rows whose customer key has no match silently disappear from visuals, and queries that filter by customer are slow. Which change addresses both issues?',
    sources: [S.modes, S.composite, S.relationships],
    options: [
      { id: 'a', text: 'Change the Customer table to Import partitions plus a DirectQuery partition (a hybrid table)', explain: 'Hybrid tables come from an incremental refresh policy and are typically facts; they don’t change how this dimension relates to the fact.' },
      { id: 'b', text: 'Set the relationship’s cross-filter direction to Both', explain: 'Direction doesn’t change the cross-source-group relationship, which stays limited.' },
      { id: 'c', text: 'Set the Customer table to Dual storage mode', explain: 'Correct. Dual is typically used for dimensions in a composite model so relationships with DirectQuery facts stay regular, and the engine can send one efficient native query joining the fact to the filtered dimension.' },
      { id: 'd', text: 'Change the Sales fact to Import and drop the DirectQuery source', explain: 'That gives up the DirectQuery fact the design needs for its freshness or size, rather than fixing the relationship.' },
    ],
    answer: 'c',
  },
  {
    id: 'SG-H1',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'perf-categories',
    stem: 'Performance Analyzer shows that an unfiltered scatter chart takes most of its time in Visual display, while its DAX query time is small. The chart plots every one of tens of thousands of customers. What should you change first?',
    sources: [S.perfAnalyzer, S.optimization],
    options: [
      { id: 'a', text: 'Rewrite the chart’s measures with variables', explain: 'The DAX query time is already small; rewriting DAX targets the wrong category.' },
      { id: 'b', text: 'Reduce what the visual draws, for example with a Top N filter or by summarizing to fewer points', explain: 'Correct. Visual display is rendering time, fixed by report design such as fewer data points, and Learn suggests restrictive filters such as Top N.' },
      { id: 'c', text: 'Switch the model’s tables to DirectQuery', explain: 'DirectQuery adds source query time; it doesn’t reduce rendering.' },
      { id: 'd', text: 'Turn on large semantic model storage format', explain: 'Storage format affects model size limits, not how long a visual takes to draw.' },
    ],
    answer: 'b',
  },
  {
    id: 'SG-H2',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'yesno',
    difficulty: 3,
    stem: 'You are diagnosing slow visuals on a Direct Lake on SQL analytics endpoints model with Performance Analyzer and SQL Server Profiler. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.dlAnalyze, S.perfAnalyzer, S.dataReduction],
    statements: [
      { id: 's1', text: 'Every DirectQuery Begin/End event in a Profiler trace means a query fell back to DirectQuery.', answer: false, explain: 'No. EngineEdition and OLS check queries always use DirectQuery and don’t mean fallback.' },
      { id: 's2', text: 'A Direct query line under a visual in Performance Analyzer means that visual’s query fell back.', answer: true, explain: 'Yes. For a Direct Lake model, a Direct query duration shows the visual’s query was answered through DirectQuery.' },
      { id: 's3', text: 'Turning off auto date/time usually makes an Import model larger.', answer: false, explain: 'No. Learn lists disabling auto date/time as a way to reduce Import model size.' },
    ],
  },
  {
    id: 'SG-H3',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'dropdown',
    difficulty: 3,
    stem: 'You are rewriting three slow measures to follow Learn’s DAX guidance. Complete the definitions.',
    sources: [S.bpFilter, S.bpDivide, S.bpCountrows],
    language: 'dax',
    code: 'Red Sales = CALCULATE([Sales], [[1]](Product[Color] = "Red"))\n\nMargin % = [[2]]([Profit], [Sales])\n\nOrder Lines = [[3]](Sales)',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'KEEPFILTERS', explain: 'Correct. A Boolean filter on one column, optionally wrapped in KEEPFILTERS to keep existing filters, is preferred over FILTER over a whole table.' },
          { id: 'b', text: 'FILTER(Product, ', explain: 'FILTER over the whole Product table is the pattern Learn advises against when a Boolean column filter works.' },
          { id: 'c', text: 'ALL', explain: 'ALL removes filters; it doesn’t take a Boolean expression.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'IFERROR', explain: 'IFERROR catches errors after they happen; DIVIDE handles zero and blank denominators directly and is better optimized.' },
          { id: 'b', text: 'DIVIDE', explain: 'Correct. DIVIDE handles zero or blank denominators and is better optimized than testing the denominator with IF.' },
          { id: 'c', text: 'SUMX', explain: 'SUMX iterates a table; it doesn’t divide two values.' },
        ],
        answer: 'b',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'COUNT', explain: 'COUNT needs a column and counts its non-blank values; COUNTROWS counts table rows more efficiently.' },
          { id: 'b', text: 'DISTINCTCOUNT', explain: 'DISTINCTCOUNT counts distinct values of a column, not rows.' },
          { id: 'c', text: 'COUNTROWS', explain: 'Correct. COUNTROWS counts the rows of a table and is more efficient than COUNT on a column.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'DLS-H1',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'framing-vs-import-refresh',
    stem: 'A nightly ETL rewrites several Delta tables over two hours. While it runs, users of a Direct Lake model see a mix of new and old data in the same report. Business users must only see the data once the whole load has finished. What should you do?',
    sources: [S.dlHow, S.directLake],
    options: [
      { id: 'a', text: 'Set DirectLakeBehavior to DirectQueryOnly during the load', explain: 'DirectQuery reads the latest data from the source, so users would see the half-finished load even sooner.' },
      { id: 'b', text: 'Schedule an Import refresh of the model after the load', explain: 'A Direct Lake model’s refresh is framing, not a data copy; turning the model into Import isn’t needed.' },
      { id: 'c', text: 'Increase the capacity SKU so the ETL finishes faster', explain: 'A faster ETL still exposes partial data to users while it runs.' },
      { id: 'd', text: 'Turn off “Keep your Direct Lake data up to date” and refresh (reframe) the model when the ETL completes', explain: 'Correct. Automatic updates reframe whenever Delta tables change; turning them off and framing after the load fixes the point in time users see.' },
    ],
    answer: 'd',
  },
  {
    id: 'DLS-H2',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'match',
    difficulty: 3,
    trapPairId: 'dl-fallback',
    stem: 'A team uses a Direct Lake on SQL analytics endpoints model in development, test, and production. Match each goal to the DirectLakeBehavior setting Learn suggests for it.',
    sources: [S.dlHow],
    prompts: [
      { id: 'p1', text: 'In production, keep reports working even if a query can’t use Direct Lake' },
      { id: 'p2', text: 'In development, make any query that can’t use Direct Lake fail so it gets fixed' },
      { id: 'p3', text: 'Measure how fast the model would be if every query used DirectQuery' },
    ],
    choices: [
      { id: 'c1', text: 'Automatic' },
      { id: 'c2', text: 'DirectLakeOnly' },
      { id: 'c3', text: 'DirectQueryOnly' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Automatic (the default) silently falls back to DirectQuery, so reports keep working.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'DirectLakeOnly makes such queries fail with an error, which surfaces problems during development.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'DirectQueryOnly forces DirectQuery for every query, which lets you measure fallback performance.' },
    ],
  },
  {
    id: 'DLS-H3',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'A new Direct Lake model must combine Delta tables from two lakehouses with a KQL database that has OneLake availability turned on, and it must also hold a small Import table. No SQL views are used. Which option fits?',
    sources: [S.directLake, S.dlHow],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints, one model per source item', explain: 'Direct Lake on SQL uses a single source item, doesn’t support KQL databases, and can’t mix storage modes in one model.' },
      { id: 'b', text: 'Direct Lake on OneLake', explain: 'Correct. It can use Delta tables from more than one Fabric item, supports KQL databases with OneLake availability, and can be combined with Import tables.' },
      { id: 'c', text: 'Direct Lake on SQL analytics endpoints with DirectLakeBehavior set to Automatic', explain: 'The setting only controls fallback; it doesn’t add multiple sources, KQL data, or Import tables.' },
      { id: 'd', text: 'DirectQuery to each lakehouse’s SQL analytics endpoint', explain: 'DirectQuery sends every query to the source, giving up the in-memory performance the Direct Lake requirement asks for.' },
    ],
    answer: 'b',
  },
  {
    id: 'BW-H1',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 3,
    stem: 'A model already has an incremental refresh policy on Sales that uses RangeStart and RangeEnd. A developer adds a policy to the Returns table, filtering it with two new Date/Time parameters named ReturnsFrom and ReturnsTo so it can keep a different history length. What should you do?',
    sources: [S.incrementalCfg, S.incremental],
    options: [
      { id: 'a', text: 'Filter Returns with the same RangeStart and RangeEnd parameters, and set its different periods in its own policy', explain: 'Correct. Every table with a policy must use the same RangeStart and RangeEnd parameters (reserved, case-sensitive names), even when their archive and refresh periods differ.' },
      { id: 'b', text: 'Keep ReturnsFrom and ReturnsTo; the service overrides any Date/Time parameters for each partition', explain: 'The service overrides only the reserved RangeStart and RangeEnd parameters.' },
      { id: 'c', text: 'Rename the parameters to rangestart and rangeend in lowercase', explain: 'The names are case-sensitive, so they must be RangeStart and RangeEnd.' },
      { id: 'd', text: 'Move Returns into a separate model so it can use its own parameters', explain: 'Splitting the model isn’t needed; both tables can share the parameters and keep different periods.' },
    ],
    answer: 'a',
  },
  {
    id: 'BW-H2',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'archive-vs-refresh-period',
    stem: 'You are reviewing an incremental refresh setup on a Sales table partitioned by OrderDate. Which two settings will cause problems? Choose two.',
    sources: [S.incrementalCfg, S.incremental],
    options: [
      { id: 'a', text: 'Archive data starting 5 years before refresh date, and incrementally refresh data starting 3 days before refresh date', explain: 'This is a normal policy: a long archive period and a short refresh window.' },
      { id: 'b', text: 'A filter of OrderDate >= RangeStart and OrderDate <= RangeEnd', explain: 'Correct. Equal-to on both parameters can put a boundary row in two partitions and duplicate data.' },
      { id: 'c', text: 'Only refresh complete days turned on', explain: 'This is an optional setting that doesn’t cause the problems described.' },
      { id: 'd', text: 'Detect data changes set to the OrderDate column', explain: 'Correct. The Detect data changes column must be different from the column used for RangeStart/RangeEnd partitioning.' },
    ],
    answers: ['b', 'd'],
  },
]
