import { S } from '../sources'
import type { Question } from '../types'

const lg = 'loom-gearbox'
const wf = 'warp-frame'
const pc = 'punch-card-reader'
const jh = 'jacquard-head'

export const modelAQuestions: Question[] = [
  // ── Loom Gearbox: S1.1 storage mode ─────────────────────────────────
  {
    id: 'LG-01',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'storage-modes',
    stem: 'Data engineers maintain several billion-row Delta tables in a Fabric lakehouse. You need a semantic model with VertiPaq query performance, without copying the data into the model, and with refreshes that finish in seconds. Which storage mode should you use?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Import', explain: 'Import copies the whole data volume into the model, and its refresh can take considerable time and capacity.' },
      { id: 'b', text: 'DirectQuery', explain: 'DirectQuery doesn’t copy data, but it federates every query to the source instead of using VertiPaq.' },
      { id: 'c', text: 'Direct Lake', explain: 'Correct. Direct Lake loads Delta columns into VertiPaq on demand, and its refresh copies only metadata (framing), which takes seconds.' },
      { id: 'd', text: 'Dual', explain: 'Dual acts as Import or DirectQuery per query, so it still needs an Import copy of the data.' },
    ],
    answer: 'c',
  },
  {
    id: 'LG-02',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A self-service analyst builds a Direct Lake model on a lakehouse that IT manages. The analyst has no write permission on the lakehouse but needs to add a small lookup table that requires data preparation. What does Learn suggest?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Ask IT for Contributor access and write the table with Spark', explain: 'Learn’s suggestion keeps the analyst out of the IT-managed lakehouse.' },
      { id: 'b', text: 'Add a calculated column to an existing Direct Lake table', explain: 'This doesn’t give the analyst a separate table with data preparation.' },
      { id: 'c', text: 'Convert the whole model to DirectQuery', explain: 'DirectQuery doesn’t add data preparation and would give up VertiPaq performance.' },
      { id: 'd', text: 'Add an Import table and prepare the data with Power Query', explain: 'Correct. Learn: when the author can’t modify the source item, augmenting the model with Import tables might be a good choice because Import supports Power Query.' },
    ],
    answer: 'd',
  },
  {
    id: 'LG-03',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'framing-vs-import-refresh',
    stem: 'A pipeline appends new rows to the Delta tables behind a Direct Lake semantic model and then refreshes the model. What does that refresh do?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'It updates metadata to point at the latest Delta table version', explain: 'Correct. A Direct Lake refresh (framing) analyzes the latest Delta metadata and updates references to the latest files.' },
      { id: 'b', text: 'It reloads every table into a cached copy inside the model', explain: 'That describes an Import refresh, which replicates the data.' },
      { id: 'c', text: 'It sends a native query to the SQL analytics endpoint for each table', explain: 'Refresh doesn’t run DirectQuery; it updates metadata.' },
      { id: 'd', text: 'It rebuilds the Delta tables’ Parquet files in OneLake', explain: 'Refresh reads Delta metadata; it doesn’t rewrite the files.' },
    ],
    answer: 'a',
  },
  {
    id: 'LG-04',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    trapPairId: 'storage-modes',
    stem: 'You are comparing storage modes for a new Fabric semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.directLake],
    statements: [
      { id: 's1', text: 'Direct Lake requires a Fabric capacity (SKU), while Import and DirectQuery work with any Fabric or Power BI license.', answer: true, explain: 'Yes. Learn’s comparison lists Fabric capacity subscriptions only for Direct Lake and any license for Import and DirectQuery.' },
      { id: 's2', text: 'Direct Lake tables support hybrid tables and model table partitions.', answer: false, explain: 'No. Hybrid tables and model table partitions aren’t supported in Direct Lake; partition the Delta tables instead.' },
      { id: 's3', text: 'Direct Lake and Import queries are both processed by the VertiPaq engine.', answer: true, explain: 'Yes. DirectQuery is the mode that federates queries to the source.' },
    ],
  },
  {
    id: 'LG-05',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'storage-modes',
    stem: 'Match each requirement to the storage mode that best fits it.',
    sources: [S.directLake, S.modes, S.storageMode],
    prompts: [
      { id: 'p1', text: 'An analyst must shape spreadsheet data with Power Query inside the model' },
      { id: 'p2', text: 'Reports must show near-real-time data from a large external SQL database, beyond scheduled refresh limits' },
      { id: 'p3', text: 'Large Delta tables already prepared in a Fabric warehouse must be queried without copying them' },
      { id: 'p4', text: 'A Date table must relate to both Import and DirectQuery fact tables while keeping relationships regular' },
    ],
    choices: [
      { id: 'c1', text: 'Import' },
      { id: 'c2', text: 'DirectQuery' },
      { id: 'c3', text: 'Direct Lake' },
      { id: 'c4', text: 'Dual' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Import supports Power Query data preparation defined in the model.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'DirectQuery queries the source each time, so data is current without waiting for a refresh.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Direct Lake reads Delta tables in OneLake without replicating them.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Dual tables can act as Import or DirectQuery, which helps keep relationships regular.' },
    ],
  },
  {
    id: 'LG-06',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A Direct Lake model’s fact table holds ten years of sales. You want to manage the data by year, the way you used partitions in Import models. What should you do?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Add model table partitions by year in Tabular Editor', explain: 'Direct Lake doesn’t support model table partitions.' },
      { id: 'b', text: 'Configure incremental refresh to create a hybrid table', explain: 'Direct Lake doesn’t support hybrid tables.' },
      { id: 'c', text: 'Partition the Delta table in the lakehouse', explain: 'Correct. Partitioning belongs at the Delta table level, because Direct Lake models can’t have model partitions.' },
      { id: 'd', text: 'Switch the fact table to Dual storage mode', explain: 'Dual doesn’t partition anything and isn’t a Direct Lake option.' },
    ],
    answer: 'c',
  },
  {
    id: 'LG-07',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In October 2026, you create a new lakehouse. A report author asks where its default semantic model is so they can build a report. What should you tell them?',
    sources: [S.semanticModels],
    options: [
      { id: 'a', text: 'It appears in the workspace a few minutes after the lakehouse', explain: 'Default semantic models are no longer created automatically.' },
      { id: 'b', text: 'It is hidden under the lakehouse’s SQL analytics endpoint', explain: 'There’s no hidden default model; none is created.' },
      { id: 'c', text: 'It is created the first time someone runs a SQL query', explain: 'Querying doesn’t create a semantic model.' },
      { id: 'd', text: 'None is created, so create a semantic model on the lakehouse', explain: 'Correct. Since September 5, 2025, default semantic models aren’t created when a warehouse, lakehouse, or mirrored item is created.' },
    ],
    answer: 'd',
  },
  {
    id: 'LG-08',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 1,
    stem: 'An Import semantic model is on a Premium capacity. Business users ask for more frequent scheduled refreshes. What is the maximum number of scheduled refreshes per day?',
    sources: [S.modes],
    options: [
      { id: 'a', text: '8', explain: 'Eight per day is the limit on shared capacity.' },
      { id: 'b', text: '48', explain: 'Correct. Learn: 48 times a day for a Premium capacity.' },
      { id: 'c', text: '24', explain: 'This isn’t one of the documented limits.' },
      { id: 'd', text: '96', explain: 'This isn’t one of the documented limits.' },
    ],
    answer: 'b',
  },
  {
    id: 'LG-09',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'In Power BI Desktop you change a DirectQuery table to Import, then decide you want it back in DirectQuery. You aren’t using web modeling or live editing. What happens?',
    sources: [S.storageMode],
    options: [
      { id: 'a', text: 'You select DirectQuery again in the table’s storage mode property', explain: 'After changing to Import or Dual, the mode can’t be set back to DirectQuery in this case.' },
      { id: 'b', text: 'Power BI switches it back automatically at the next refresh', explain: 'Storage mode never changes on its own at refresh.' },
      { id: 'c', text: 'It can’t be set back to DirectQuery', explain: 'Correct. Learn: after you change a DirectQuery table to Import or Dual, you can’t set it back to DirectQuery (except with web modeling or live editing).' },
      { id: 'd', text: 'You set it to Dual first, then to DirectQuery', explain: 'Dual can’t be set back to DirectQuery either.' },
    ],
    answer: 'c',
  },
  {
    id: 'LG-10',
    machineId: lg,
    bulletIds: ['S1.1'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'Your organization is weighing Direct Lake for an IT-managed analytics project on OneLake. Which two statements describe benefits Learn lists for Direct Lake? Choose two.',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Power Query transformations run inside the model for every Direct Lake table', explain: 'Power Query preparation is an Import feature; Direct Lake relies on upstream preparation.' },
      { id: 'b', text: 'Analyzed data volumes can exceed the capacity’s max memory, because only the data needed for a query is loaded', explain: 'Correct. Learn lists this as an ROI benefit of Direct Lake.' },
      { id: 'c', text: 'It works with any Power BI license, including Free', explain: 'Direct Lake requires a Fabric capacity subscription.' },
      { id: 'd', text: 'Data preparation moves upstream to OneLake, using Spark, T-SQL, dataflows, and pipelines', explain: 'Correct. Direct Lake depends on preparation in the lake, which maximizes reuse.' },
    ],
    answers: ['b', 'd'],
  },

  // ── Warp Frame: S1.2 star schema in the model ───────────────────────
  {
    id: 'WF-01',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'dropdown',
    difficulty: 2,
    stem: 'The Sales table has OrderDate and ShipDate columns, both related to the Date table. The OrderDate relationship is active. You need a measure that totals sales by ship date. Complete the DAX.',
    sources: [S.star, S.calculate],
    language: 'dax',
    code: "Sales by Ship Date =\n[[1]](\n    [Sales],\n    [[2]](Sales[ShipDate], [[3]])\n)",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'CALCULATE', explain: 'Correct. CALCULATE evaluates [Sales] with the modified relationship.' },
          { id: 'b', text: 'SUMX', explain: 'SUMX iterates a table; it can’t take a relationship modifier.' },
          { id: 'c', text: 'FILTER', explain: 'FILTER returns a table; it doesn’t evaluate a measure with modifiers.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'TREATAS', explain: 'TREATAS applies values as filters to unrelated columns; the relationship already exists.' },
          { id: 'b', text: 'USERELATIONSHIP', explain: 'Correct. The only way to use an inactive relationship is a DAX expression with USERELATIONSHIP.' },
          { id: 'c', text: 'RELATED', explain: 'RELATED fetches a value from the one side in row context.' },
        ],
        answer: 'b',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: "'Date'[Date]", explain: 'Correct. The inactive relationship is between Sales[ShipDate] and the Date table’s date column.' },
          { id: 'b', text: 'Sales[OrderDate]', explain: 'That column is on the active relationship, not the ship date one.' },
          { id: 'c', text: '[Sales]', explain: 'USERELATIONSHIP takes two columns, not a measure.' },
        ],
        answer: 'a',
      },
    ],
  },
  {
    id: 'WF-02',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Report authors build visuals by dragging numeric columns and letting Power BI sum them. You plan to add a calculation group for time intelligence. What must change in how authors work?',
    sources: [S.calcGroups],
    options: [
      { id: 'a', text: 'They must switch every visual to DirectQuery', explain: 'Calculation groups don’t depend on storage mode changes.' },
      { id: 'b', text: 'They must use explicit DAX measures', explain: 'Correct. Calculation groups need Discourage implicit measures; calculation items only apply to explicit measures.' },
      { id: 'c', text: 'They must build reports from a field parameter only', explain: 'Field parameters are separate and not required by calculation groups.' },
      { id: 'd', text: 'They must remove all relationships to the Date table', explain: 'Calculation groups work with normal relationships.' },
    ],
    answer: 'b',
  },
  {
    id: 'WF-03',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'single',
    difficulty: 1,
    stem: 'A model table holds OrderQuantity, SalesAmount, and keys for Product, Customer, and Date. Which role should it play in a star schema?',
    sources: [S.star],
    options: [
      { id: 'a', text: 'A fact table', explain: 'Correct. It stores events with measures to summarize and dimension keys.' },
      { id: 'b', text: 'A dimension table', explain: 'Dimension tables describe entities for filtering and grouping, not numeric events.' },
      { id: 'c', text: 'A bridging table', explain: 'A bridging table stores key pairs to resolve a many-to-many relationship.' },
      { id: 'd', text: 'A disconnected table', explain: 'A disconnected table has no relationships and accepts user input.' },
    ],
    answer: 'a',
  },
  {
    id: 'WF-04',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are building relationships in a semantic model on Fabric data. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.star, S.relationships, S.directLake],
    statements: [
      { id: 's1', text: 'Only one relationship between two model tables can be active at a time.', answer: true, explain: 'Yes. Learn: there can only be one active relationship between two semantic model tables.' },
      { id: 's2', text: 'You can relate an EmployeeID column to a ManagerID column in the same table to build a hierarchy.', answer: false, explain: 'No. It isn’t possible to relate a column to a different column in the same table; use the parent and child DAX functions.' },
      { id: 's3', text: 'In a Direct Lake model, the columns on both sides of a relationship need matching data types.', answer: true, explain: 'Yes. Learn’s Direct Lake guidance requires the data types of related columns to match.' },
    ],
  },
  {
    id: 'WF-05',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Visuals in a Direct Lake model start failing after a load. You find duplicate ProductKey values in the Product table, which is the one side of its relationship to Sales. What should you do?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Change the relationship to many-to-many in the model', explain: 'That hides a data problem and makes the relationship limited; fix the dimension instead.' },
      { id: 'b', text: 'Set the relationship’s cross-filter direction to Both', explain: 'Filter direction doesn’t fix a non-unique one side.' },
      { id: 'c', text: 'Make ProductKey unique in the Product Delta table', explain: 'Correct. Duplicates on the one side make Direct Lake queries fail, so the key must be unique in the source table.' },
      { id: 'd', text: 'Switch the Product table to Dual storage mode', explain: 'Direct Lake tables don’t use Dual, and the duplicates would remain.' },
    ],
    answer: 'c',
  },
  {
    id: 'WF-06',
    machineId: wf,
    bulletIds: ['S1.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'star-vs-snowflake',
    stem: 'A semantic model imports Product, Subcategory, and Category as three related tables. Report authors want one Category > Subcategory > Product hierarchy in the Data pane. What should you do?',
    sources: [S.star, S.dimTables],
    options: [
      { id: 'a', text: 'Create the hierarchy across the three related tables', explain: 'A model hierarchy can only be based on columns from a single table.' },
      { id: 'b', text: 'Set all relationships among the three tables to Both', explain: 'Filter direction doesn’t let a hierarchy span tables.' },
      { id: 'c', text: 'Add a calculation group with one item per level', explain: 'Calculation groups change measure logic; they don’t build hierarchies.' },
      { id: 'd', text: 'Flatten them into one Product table, such as a view', explain: 'Correct. Denormalize the snowflake into one table so the hierarchy can use its columns.' },
    ],
    answer: 'd',
  },

  // ── Warp Frame: S1.3 relationships ──────────────────────────────────
  {
    id: 'WF-07',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A bank model has Customer and Account dimension tables. A customer can hold many accounts, and joint accounts have several customers. Transactions relate to Account. How should you model Customer and Account?',
    sources: [S.manyToMany],
    options: [
      { id: 'a', text: 'Add a bridging table of customer-account pairs', explain: 'Correct. Learn: add a bridging table and set the filter direction so Customer filters reach the Transaction table.' },
      { id: 'b', text: 'Relate Customer to Account directly with a many-to-many relationship', explain: 'Learn doesn’t recommend relating many-to-many dimension tables directly.' },
      { id: 'c', text: 'Merge Customer and Account into one table in Power Query', explain: 'Merging duplicates rows per pair and breaks both dimensions’ keys.' },
      { id: 'd', text: 'Relate Customer directly to the Transaction table', explain: 'Transactions belong to accounts, not customers, so there’s no customer key to relate on.' },
    ],
    answer: 'a',
  },
  {
    id: 'WF-08',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'order',
    difficulty: 2,
    placement: true,
    stem: 'You are implementing a many-to-many relationship between Customer and Account by using the bridging pattern. Put the steps in order.',
    sources: [S.manyToMany],
    items: [
      { id: 'i3', text: 'Set the cross-filter direction of the Account-to-bridge relationship to Both', explain: 'Third. Filters from Customer must flow back through the bridge to Account and on to the facts.' },
      { id: 'i1', text: 'Add the bridging table that stores one row per customer-account pair', explain: 'First. The bridge holds the associations the two dimensions share.' },
      { id: 'i2', text: 'Create one-to-many relationships from Customer and from Account to the bridge', explain: 'Second. Each dimension’s unique ID is the one side.' },
    ],
    answerOrder: ['i1', 'i2', 'i3'],
  },
  {
    id: 'WF-09',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A Target table stores sales targets by month and product category. Product has one row per product, so Category repeats in both Product and Target. How should you relate Target to Product?',
    sources: [S.manyToMany],
    options: [
      { id: 'a', text: 'One-to-many from Product[Category] to Target[Category]', explain: 'Product[Category] has duplicate values, so it can’t be the one side.' },
      { id: 'b', text: 'Many-to-many on Category, single direction from Product', explain: 'Correct. Learn: with no one side, use many-to-many that propagates filters from the dimension to the fact.' },
      { id: 'c', text: 'Many-to-many on Category with cross-filter direction Both', explain: 'Learn says the relationship should filter in a single direction, from dimension to fact.' },
      { id: 'd', text: 'No relationship; use TREATAS in every target measure', explain: 'Learn’s recommended design for this case is a many-to-many relationship that filters from the dimension to the fact.' },
    ],
    answer: 'b',
  },
  {
    id: 'WF-10',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'regular-vs-limited',
    stem: 'A composite model relates an Import Product table to a DirectQuery Sales table from a different source group. A calculated column on Sales uses RELATED(Product[Category]) and fails. Why?',
    sources: [S.relationships],
    options: [
      { id: 'a', text: 'RELATED only works in measures, not calculated columns', explain: 'RELATED is designed for row context, such as calculated columns.' },
      { id: 'b', text: 'The relationship needs cross-filter direction Both', explain: 'Direction isn’t the issue; the relationship type is.' },
      { id: 'c', text: 'Product[Category] must be the key column of the relationship', explain: 'RELATED can return any column from the one side of a regular relationship.' },
      { id: 'd', text: 'The relationship is limited, so RELATED can’t use it', explain: 'Correct. Cross source group relationships are limited, and the RELATED function can’t be used across them.' },
    ],
    answer: 'd',
  },
  {
    id: 'WF-11',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'yesno',
    difficulty: 3,
    placement: true,
    trapPairId: 'regular-vs-limited',
    stem: 'You are reviewing relationships in a composite semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.relationships],
    statements: [
      { id: 's1', text: 'A relationship with many-to-many cardinality is a limited relationship.', answer: true, explain: 'Yes. A relationship is limited when it is many-to-many or crosses source groups.' },
      { id: 's2', text: 'For a limited relationship, a blank virtual row is added to the one side for unmatched keys.', answer: false, explain: 'No. Limited relationships use INNER JOIN semantics, so no blank row is added and unmatched rows drop out.' },
      { id: 's3', text: 'A one-to-many relationship between an Import table and a DirectQuery table from another source is limited.', answer: true, explain: 'Yes. It crosses source groups, so it’s limited. (Dual storage mode is only available when the Import and DirectQuery tables come from the same source.)' },
    ],
  },
  {
    id: 'WF-12',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Order and Fulfillment fact tables share an OrderID column with duplicate values in both. A developer related them directly with many-to-many cardinality. What does Learn recommend instead?',
    sources: [S.manyToMany],
    options: [
      { id: 'a', text: 'Set the relationship’s cross-filter direction to Both', explain: 'The design problem remains: visuals can still only filter by OrderID.' },
      { id: 'b', text: 'Merge both fact tables into one wide table', explain: 'Learn recommends a star schema, not merging facts of different grains.' },
      { id: 'c', text: 'Relate both facts to shared dimension tables', explain: 'Correct. A star schema lets visuals filter or group by any dimension column and summarize either fact.' },
      { id: 'd', text: 'Turn on Assume referential integrity for the relationship', explain: 'That property applies to one-to-many relationships between DirectQuery tables in the same source group.' },
    ],
    answer: 'c',
  },
  {
    id: 'WF-13',
    machineId: wf,
    bulletIds: ['S1.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'In a bank model with a customer-account bridging table, a matrix shows each customer’s balance. The grand total is lower than the sum of the customer rows. What explains this?',
    sources: [S.manyToMany],
    options: [
      { id: 'a', text: 'The bridge relationship should be set to single direction', explain: 'Single direction would stop customer filters from reaching the facts at all.' },
      { id: 'b', text: 'Values through the bridge aren’t additive', explain: 'Correct. A joint account’s balance appears under each customer, but only once in the total.' },
      { id: 'c', text: 'Limited relationships drop rows from the grand total only', explain: 'The total is right; it’s the customer rows that each include shared balances.' },
      { id: 'd', text: 'The model needs an Unknown customer member', explain: 'There are no unmatched keys here; the difference comes from shared accounts.' },
    ],
    answer: 'b',
  },

  // ── Punch-Card Reader: S1.4 DAX ─────────────────────────────────────
  {
    id: 'PC-01',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'You are rewriting a year-over-year growth measure so the prior-year value is calculated once and reused. Complete the DAX.',
    sources: [S.varBP, S.bpDivide],
    language: 'dax',
    code: "Sales YoY Growth % =\n[[1]] SalesPriorYear =\n    CALCULATE([Sales], PARALLELPERIOD('Date'[Date], -12, MONTH))\n[[2]]\n    [[3]]([Sales] - SalesPriorYear, SalesPriorYear)",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'DEFINE', explain: 'DEFINE starts the definitions block of a DAX query, not a variable inside a measure.' },
          { id: 'b', text: 'VAR', explain: 'Correct. VAR stores the prior-year result in a named variable.' },
          { id: 'c', text: 'MEASURE', explain: 'MEASURE belongs in a query’s DEFINE block.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'RETURN', explain: 'Correct. RETURN gives the result expression that uses the variable.' },
          { id: 'b', text: 'EVALUATE', explain: 'EVALUATE runs a DAX query; measures use RETURN.' },
          { id: 'c', text: 'THEN', explain: 'THEN isn’t a DAX keyword.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'FORMAT', explain: 'FORMAT would turn the result into text.' },
          { id: 'b', text: 'SUMX', explain: 'SUMX needs a table to iterate.' },
          { id: 'c', text: 'DIVIDE', explain: 'Correct. DIVIDE handles a zero or blank denominator safely.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'PC-02',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: "A measure is defined as VAR AllSales = [Sales] RETURN CALCULATE(AllSales, 'Product'[Color] = \"Red\"). In a visual with no other filters, what does it return?",
    sources: [S.varBP, S.varRef],
    options: [
      { id: 'a', text: 'Sales of red products only', explain: 'The variable was already evaluated before CALCULATE applied the Red filter.' },
      { id: 'b', text: 'Total sales, unaffected by the Red filter', explain: 'Correct. Variables are always evaluated outside the filters the RETURN expression applies.' },
      { id: 'c', text: 'BLANK, because variables can’t be used inside CALCULATE', explain: 'Variables can be used in CALCULATE; they just don’t respond to its filters.' },
      { id: 'd', text: 'An error, because a variable can’t hold a measure', explain: 'A variable can store any scalar or table expression, including a measure.' },
    ],
    answer: 'b',
  },
  {
    id: 'PC-03',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'The Sales table has Quantity and UnitPrice columns but no amount column. You need a measure that returns the total revenue. Which expression should you use?',
    sources: [S.sumx],
    options: [
      { id: 'a', text: 'SUM(Sales[Quantity]) * SUM(Sales[UnitPrice])', explain: 'Multiplying two totals isn’t the same as summing each row’s product.' },
      { id: 'b', text: 'SUMX(Sales, Sales[Quantity] * Sales[UnitPrice])', explain: 'Correct. SUMX evaluates the expression for each row and then sums the results.' },
      { id: 'c', text: 'SUM(Sales[Quantity] * Sales[UnitPrice])', explain: 'SUM takes a single column, not an expression.' },
      { id: 'd', text: 'CALCULATE(SUM(Sales[Quantity]), Sales[UnitPrice])', explain: 'This sums Quantity only; it never multiplies by price, so it isn’t a sales amount.' },
    ],
    answer: 'b',
  },
  {
    id: 'PC-04',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: "You need a running total of [Total Sales] by month that restarts each fiscal year. Rows are ALLSELECTED('Date'[Fiscal Year], 'Date'[Month Number Of Year]). Which WINDOW arguments define the window?",
    sources: [S.window],
    options: [
      { id: 'a', text: "WINDOW(0, REL, 1, ABS, <rows>, PARTITIONBY('Date'[Fiscal Year]))", explain: 'This starts at the current row and ends at the first row, which reverses the window.' },
      { id: 'b', text: "WINDOW(1, ABS, -1, ABS, <rows>, PARTITIONBY('Date'[Fiscal Year]))", explain: 'This covers the whole year for every month, so it returns a full-year total, not a running total.' },
      { id: 'c', text: "WINDOW(1, ABS, 0, REL, <rows>, PARTITIONBY('Date'[Fiscal Year]))", explain: 'Correct. The window starts at the first row of the partition (1, ABS) and ends at the current row (0, REL), restarting each fiscal year.' },
      { id: 'd', text: "WINDOW(1, ABS, 0, REL, <rows>, PARTITIONBY('Date'[Month Number Of Year]))", explain: 'Partitioning by month groups each month across fiscal years, so it accumulates the same month across years instead of restarting each fiscal year.' },
    ],
    answer: 'c',
  },
  {
    id: 'PC-05',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You need a measure that returns the previous calendar year’s sales next to each year in a table visual, by using a window function. Which function should you use?',
    sources: [S.offset],
    options: [
      { id: 'a', text: 'INDEX(1, …, ORDERBY(DimDate[CalendarYear]))', explain: 'INDEX returns the row at an absolute position, such as the first year, not the prior one.' },
      { id: 'b', text: 'WINDOW(1, ABS, 0, REL, …)', explain: 'This returns all years up to the current one, which gives a running total.' },
      { id: 'c', text: 'RANK(…, ORDERBY(DimDate[CalendarYear]))', explain: 'RANK returns a position number, not another row’s value.' },
      { id: 'd', text: 'OFFSET(-1, …, ORDERBY(DimDate[CalendarYear]))', explain: 'Correct. OFFSET returns the row a given distance from the current row; -1 is the previous year.' },
    ],
    answer: 'd',
  },
  {
    id: 'PC-06',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'hasonevalue-vs-isinscope',
    stem: 'A matrix shows Category > Product. You need a measure that returns one calculation on product rows and a different one on category subtotals. Which function should you test?',
    sources: [S.isinscope, S.hasonevalue],
    options: [
      { id: 'a', text: "HASONEVALUE('Product'[Product])", explain: 'HASONEVALUE is also TRUE when a slicer filters to one product, even at the subtotal level.' },
      { id: 'b', text: "ISFILTERED('Product'[Product])", explain: 'ISFILTERED reports any filter on the column, including slicers, not the grouping level.' },
      { id: 'c', text: "ISINSCOPE('Product'[Product])", explain: 'Correct. ISINSCOPE is TRUE when the visual is grouping by that column at the current level.' },
      { id: 'd', text: "SELECTEDVALUE('Product'[Product])", explain: 'SELECTEDVALUE returns a value, and it also returns one under a single-product slicer.' },
    ],
    answer: 'c',
  },
  {
    id: 'PC-07',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'hasonevalue-vs-isinscope',
    stem: 'A card must show the region chosen in a slicer, or the text Multiple when more than one region (or none) is selected. Which expression should you use?',
    sources: [S.selectedvalue],
    options: [
      { id: 'a', text: "SELECTEDVALUE('Geo'[Region], \"Multiple\")", explain: 'Correct. SELECTEDVALUE returns the single value in context, or the alternate result otherwise.' },
      { id: 'b', text: "VALUES('Geo'[Region])", explain: 'This doesn’t give the fallback text Learn’s SELECTEDVALUE pattern provides when several regions are selected.' },
      { id: 'c', text: "ISINSCOPE('Geo'[Region])", explain: 'ISINSCOPE returns TRUE or FALSE about grouping, not the selected value.' },
      { id: 'd', text: "FIRSTNONBLANK('Geo'[Region], \"Multiple\")", explain: 'This doesn’t show a fallback when several regions are selected; SELECTEDVALUE returns the alternate result in that case.' },
    ],
    answer: 'a',
  },
  {
    id: 'PC-08',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'match',
    difficulty: 1,
    placement: true,
    stem: 'The DP-600 skills outline names several families of DAX functions. Match each function to its family.',
    sources: [S.sumx, S.window, S.infoFuncs, S.filterFuncs],
    prompts: [
      { id: 'p1', text: 'SUMX' },
      { id: 'p2', text: 'OFFSET' },
      { id: 'p3', text: 'ISINSCOPE' },
      { id: 'p4', text: 'REMOVEFILTERS' },
    ],
    choices: [
      { id: 'c1', text: 'Iterator' },
      { id: 'c2', text: 'Windowing' },
      { id: 'c3', text: 'Information function' },
      { id: 'c4', text: 'Table filtering (CALCULATE filter modifier)' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'SUMX evaluates an expression for each row of a table, then sums.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'OFFSET returns a row relative to the current row, using ORDERBY and PARTITIONBY.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'ISINSCOPE tests the evaluation context.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'REMOVEFILTERS clears filters, typically as a CALCULATE modifier.' },
    ],
  },
  {
    id: 'PC-09',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are reviewing DAX measures that use variables. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.varRef, S.varBP],
    statements: [
      { id: 's1', text: 'A measure can reference a variable that was defined in a different measure.', answer: false, explain: 'No. Measures can’t refer to variables defined outside the measure expression.' },
      { id: 's2', text: 'If a variable stores a table, you can read its columns with VariableName[Column] syntax.', answer: false, explain: 'No. You can’t reference columns in table variables by using TableName[ColumnName] syntax.' },
      { id: 's3', text: 'Using a variable can remove the need for the EARLIER or EARLIEST functions.', answer: true, explain: 'Yes. Because variables are evaluated outside the RETURN filters, EARLIER and EARLIEST can be avoided.' },
    ],
  },
  {
    id: 'PC-10',
    machineId: pc,
    bulletIds: ['S1.4'],
    format: 'single',
    difficulty: 2,
    stem: 'You need a measure that shows each product’s sales as a percentage of sales for all products, regardless of any product filter in the visual. Which denominator should you use?',
    sources: [S.calculate, S.filterFuncs],
    options: [
      { id: 'a', text: "CALCULATE([Sales], KEEPFILTERS('Product'))", explain: 'KEEPFILTERS adds to existing filters; it doesn’t remove the product filter.' },
      { id: 'b', text: "CALCULATE([Sales], REMOVEFILTERS('Product'))", explain: 'Correct. REMOVEFILTERS clears the product filters so the denominator is all products.' },
      { id: 'c', text: "SUMX('Product', [Sales])", explain: 'This iterates only the products in the current filter context.' },
      { id: 'd', text: "CALCULATE([Sales], VALUES('Product'[Product]))", explain: 'VALUES keeps the current product selection as the filter.' },
    ],
    answer: 'b',
  },

  // ── Jacquard Head: S1.5 calc groups, format strings, field params ───
  {
    id: 'JH-01',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'calcgroup-vs-fieldparam',
    stem: 'A model has 30 base measures. The business wants YTD, prior year, and YoY% versions of every one, without creating 90 more measures. What should you implement?',
    sources: [S.calcGroups],
    options: [
      { id: 'a', text: 'A field parameter listing the 30 measures', explain: 'A field parameter lets readers switch fields; it doesn’t change how measures calculate.' },
      { id: 'b', text: 'A dynamic format string on each measure', explain: 'Format strings change display formatting, not the calculation.' },
      { id: 'c', text: 'A calculation group', explain: 'Correct. Calculation items apply their logic to whatever measure is in context.' },
      { id: 'd', text: 'A disconnected table with three rows', explain: 'A disconnected table alone would still need logic in every measure.' },
    ],
    answer: 'c',
  },
  {
    id: 'JH-02',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'calcgroup-vs-fieldparam',
    stem: 'Report readers want to choose with a slicer whether a line chart shows Sales, Profit, or Margin, without bookmarks or duplicate visuals. What should you create?',
    sources: [S.fieldParams],
    options: [
      { id: 'a', text: 'A calculation group with one item per measure', explain: 'Calculation groups change how the selected measure is calculated, not which field a visual shows.' },
      { id: 'b', text: 'A field parameter containing the three measures', explain: 'Correct. Field parameters let readers switch the measures or columns a visual uses.' },
      { id: 'c', text: 'A dynamic format string that returns the measure name', explain: 'A format string only changes how a value is displayed.' },
      { id: 'd', text: 'A what-if parameter with values 1 to 3', explain: 'What-if parameters supply numeric input values, not field choices.' },
    ],
    answer: 'b',
  },
  {
    id: 'JH-03',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'dfs-vs-format',
    stem: 'A sales measure must display in each country’s currency format. It is also used in a line chart. A developer used FORMAT() and the chart stopped plotting. What should you use instead?',
    sources: [S.dynamicFormat],
    options: [
      { id: 'a', text: 'A dynamic format string for the measure', explain: 'Correct. The measure keeps its numeric data type while the format changes by context.' },
      { id: 'b', text: 'A calculated column that stores the formatted text', explain: 'Text values still can’t be plotted as numbers.' },
      { id: 'c', text: 'CONVERT() around the FORMAT() result', explain: 'Converting formatted text back to a number loses the currency format.' },
      { id: 'd', text: 'A separate measure per country', explain: 'This multiplies measures and still doesn’t switch format by context in one visual.' },
    ],
    answer: 'a',
  },
  {
    id: 'JH-04',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: "A calculation group named 'Time Intelligence' has a column [Time Calculation] with a YOY% item. You need an [Orders YOY%] measure that applies that item to [Orders]. Complete the DAX.",
    sources: [S.calcGroups],
    language: 'dax',
    code: "Orders YOY% =\n[[1]](\n    [[2]],\n    'Time Intelligence'[Time Calculation] = [[3]]\n)",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'SELECTEDMEASURE', explain: 'SELECTEDMEASURE is used inside calculation items; it takes no arguments.' },
          { id: 'b', text: 'CALCULATE', explain: 'Correct. CALCULATE evaluates the measure with the calculation item as a filter.' },
          { id: 'c', text: 'SWITCH', explain: 'SWITCH chooses between values; it doesn’t apply a calculation item.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: '[Orders]', explain: 'Correct. The measure the calculation item should modify.' },
          { id: 'b', text: 'SELECTEDMEASURE()', explain: 'In a regular measure there’s no selected measure to refer to.' },
          { id: 'c', text: "'Time Intelligence'", explain: 'The calculation group is the filter, not the expression.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: '[YOY%]', explain: 'Square brackets reference a measure, not a text value.' },
          { id: 'b', text: 'SELECTEDVALUE()', explain: 'This returns a value from context rather than naming the item.' },
          { id: 'c', text: '"YOY%"', explain: 'Correct. Filter the calculation group column to the item’s name as text.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'JH-05',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'After you add a calculation group to a semantic model, a report developer notices that every measure now shows a different data type in reports. What happened, and how is it reversed?',
    sources: [S.calcGroups],
    options: [
      { id: 'a', text: 'Measures became text; set each measure’s format back to Number', explain: 'They change to variant, not text, and changing formats doesn’t reverse it.' },
      { id: 'b', text: 'Measures became variant; they revert only if all calculation groups are removed', explain: 'Correct. Learn: reports use variant for all measures once a calculation group exists, and revert when all calculation groups are removed.' },
      { id: 'c', text: 'Measures became decimal; turn off Discourage implicit measures', explain: 'The property must stay on for calculation groups, and the type change is to variant.' },
      { id: 'd', text: 'Only measures used in calculation items changed; recreate those measures', explain: 'All measures change, not just the ones the items touch.' },
    ],
    answer: 'b',
  },
  {
    id: 'JH-06',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'You plan to use a field parameter in a report. Which two limitations apply? Choose two.',
    sources: [S.fieldParams],
    options: [
      { id: 'a', text: 'AI visuals and Q&A aren’t supported with field parameters', explain: 'Correct. Learn lists this limitation.' },
      { id: 'b', text: 'A field parameter can’t be placed on a slicer', explain: 'Using the field parameter on a slicer is how readers choose fields.' },
      { id: 'c', text: 'A field parameter can contain measures or columns, never both', explain: 'Learn’s guidance doesn’t restrict a parameter to one kind of field.' },
      { id: 'd', text: 'A field parameter can’t include implicit measures', explain: 'Correct. Create explicit measures for aggregated columns you want to include.' },
    ],
    answers: ['a', 'd'],
  },
  {
    id: 'JH-07',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    trapPairId: 'dfs-vs-format',
    stem: 'You are adding format strings to a semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.dynamicFormat, S.calcGroups],
    statements: [
      { id: 's1', text: 'A calculation item can have its own dynamic format string, for example to show YOY% as a percentage.', answer: true, explain: 'Yes. Turn on Dynamic format string for the calculation item and return a format such as #,##0.00%.' },
      { id: 's2', text: 'A measure that uses a dynamic format string keeps its numeric data type.', answer: true, explain: 'Yes. Unlike FORMAT(), a dynamic format string doesn’t change the measure to text.' },
      { id: 's3', text: 'FORMAT() is the recommended way to format a measure used in charts, because it keeps numbers numeric.', answer: false, explain: 'No. FORMAT returns all results as strings, which causes problems for charts that need numbers.' },
    ],
  },
  {
    id: 'JH-08',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A model has a Time Intelligence calculation group and a Currency Conversion calculation group. Both apply to the same measure, and results differ depending on which applies first. Which setting controls the order?',
    sources: [S.calcGroups],
    options: [
      { id: 'a', text: 'The order of the calculation items in each group', explain: 'Item order controls how items are listed, not the order the groups apply.' },
      { id: 'b', text: 'The Sort by column on each group’s column', explain: 'Sort by column affects display order in visuals.' },
      { id: 'c', text: 'The calculation group precedence property', explain: 'Correct. Precedence specifies the order in which calculation groups apply to a measure.' },
      { id: 'd', text: 'The measure’s dynamic format string', explain: 'Format strings don’t change how calculation groups combine.' },
    ],
    answer: 'c',
  },
  {
    id: 'JH-09',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'In Power BI Desktop, you want to add a dynamic format string to an existing measure. What should you do first?',
    sources: [S.dynamicFormat],
    options: [
      { id: 'a', text: 'Create a calculation group and add the measure to it', explain: 'Measures can have their own dynamic format strings without a calculation group.' },
      { id: 'b', text: 'Wrap the measure’s expression in FORMAT()', explain: 'FORMAT returns text; dynamic format strings are set separately.' },
      { id: 'c', text: 'Open TMDL view and add a formatString property', explain: 'The documented path starts from Measure tools in the ribbon.' },
      { id: 'd', text: 'Choose Dynamic in the measure’s Format list', explain: 'Correct. A drop-down then switches the formula bar to the format string DAX expression.' },
    ],
    answer: 'd',
  },
  {
    id: 'JH-10',
    machineId: jh,
    bulletIds: ['S1.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You are writing a field parameter table by hand in DAX. Each row lists a display name, a field reference, and a sort order. Which function should provide the field reference?',
    sources: [S.fieldParams],
    options: [
      { id: 'a', text: 'NAMEOF', explain: 'Correct. Learn’s field parameter definition uses NAMEOF(\'Product\'[Category]) for each field.' },
      { id: 'b', text: 'SELECTEDMEASURE', explain: 'SELECTEDMEASURE belongs in calculation items.' },
      { id: 'c', text: 'RELATED', explain: 'RELATED returns a value from the one side of a relationship.' },
      { id: 'd', text: 'VALUES', explain: 'VALUES returns the distinct values of a column, not a reference to the column.' },
    ],
    answer: 'a',
  },
]
