import { S } from '../sources'
import type { Question } from '../types'

const wb = 'wide-beam'
const dl = 'double-loom'
const sg = 'speed-governor'
const ds = 'direct-lake-shuttle'
const bw = 'batch-winder'

export const modelBQuestions: Question[] = [
  // ── Wide Beam: S1.6 large semantic model storage format ─────────────
  {
    id: 'WB-01',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 1,
    stem: 'An Import semantic model on a Fabric F64 capacity is expected to grow to 25 GB through incremental refresh. Refreshes will fail once the model passes the default size limit. What should you configure?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'Large semantic model storage format', explain: 'Correct. It’s required for models to grow beyond 10 GB and lifts the default 1 GB limit up to the capacity limit.' },
      { id: 'b', text: 'Switch the model to Dual storage mode', explain: 'Dual is a per-table storage mode; it doesn’t change the model size limit.' },
      { id: 'c', text: 'Turn on query caching for the model', explain: 'Query caching speeds up repeated queries; it doesn’t raise the size limit.' },
      { id: 'd', text: 'Move the model to a Pro workspace on shared capacity', explain: 'Shared capacity has lower limits and doesn’t support the large format.' },
    ],
    answer: 'a',
  },
  {
    id: 'WB-02',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 2,
    stem: 'A 300 MB semantic model is deployed and updated by a CI/CD tool through the XMLA endpoint. The team wants better XMLA write performance. What does Learn recommend?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'Leave the default format, because the model is under 1 GB', explain: 'Learn recommends the large format for XMLA write operations even for models you wouldn’t call large.' },
      { id: 'b', text: 'Publish the model from Power BI Desktop instead of XMLA', explain: 'Publishing from Desktop doesn’t improve XMLA write performance.' },
      { id: 'c', text: 'Enable the large storage format anyway', explain: 'Correct. The large storage format can improve XMLA write performance.' },
      { id: 'd', text: 'Turn on the read-only XMLA endpoint for the capacity', explain: 'A read-only endpoint blocks the write operations the tool needs.' },
    ],
    answer: 'c',
  },
  {
    id: 'WB-03',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are planning to use Large semantic model storage format. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.largeModels],
    statements: [
      { id: 's1', text: 'With the large format enabled, you can publish a 15 GB model directly from Power BI Desktop.', answer: false, explain: 'No. The Desktop upload size is still limited to 10 GB; the model grows larger through refresh in the service.' },
      { id: 's2', text: 'On-demand load is enabled by default for large semantic models.', answer: true, explain: 'Yes. It loads only the data pages a query needs and speeds up loading evicted models.' },
      { id: 's3', text: 'The large format can be enabled for models in Premium Per User (PPU) workspaces.', answer: true, explain: 'Yes. Learn lists F SKUs, P SKUs, A SKUs, PPU, and Pro workspaces on Reserved Capacity for Pro Workspaces.' },
    ],
  },
  {
    id: 'WB-04',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 1,
    stem: 'You want every new semantic model published to a Fabric capacity workspace to use the large storage format automatically. Where do you set this?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'In each report’s settings, under Query caching', explain: 'Report settings don’t control model storage format.' },
      { id: 'b', text: 'In the workspace settings, under Default storage format', explain: 'Correct. Set Default storage format to Large semantic model storage format.' },
      { id: 'c', text: 'In Power BI Desktop options, under Data load', explain: 'Desktop options don’t set the service storage format.' },
      { id: 'd', text: 'In the lakehouse settings, under Delta table maintenance', explain: 'Delta maintenance affects tables in OneLake, not semantic model storage.' },
    ],
    answer: 'b',
  },
  {
    id: 'WB-05',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 2,
    stem: 'Learn lists several capacities and licenses that support Large semantic model storage format. Which of these environments does NOT support it?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'A workspace on a Fabric F SKU capacity', explain: 'Fabric F SKUs support the large format.' },
      { id: 'b', text: 'A Premium Per User (PPU) workspace', explain: 'PPU supports the large format.' },
      { id: 'c', text: 'A workspace on an Embedded A SKU capacity', explain: 'Embedded A SKUs support the large format.' },
      { id: 'd', text: 'A Pro workspace on shared capacity, not assigned to Reserved Capacity for Pro Workspaces', explain: 'Correct. Only Pro workspaces assigned to Reserved Capacity for Pro Workspaces are listed; a Pro workspace on shared capacity isn’t.' },
    ],
    answer: 'd',
  },
  {
    id: 'WB-06',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 3,
    stem: 'A team plans a 40 GB model. One architect proposes Direct Lake on a lakehouse; another proposes Import with the large storage format. Which statement about size limits is correct?',
    sources: [S.largeModels, S.directLake],
    options: [
      { id: 'a', text: 'Both are limited only by the 1 GB default size limit', explain: 'The large format lifts the 1 GB default, and Direct Lake is governed by capacity guardrails.' },
      { id: 'b', text: 'Direct Lake needs the large storage format setting to pass 10 GB', explain: 'The large format setting is about Import model size; Direct Lake has its own guardrails.' },
      { id: 'c', text: 'Import uses the large format limit; Direct Lake uses guardrails', explain: 'Correct. Large format lets Import models grow to the capacity limit, while Direct Lake depends on SKU guardrails and only loads the columns queries need.' },
      { id: 'd', text: 'Import models can’t exceed 10 GB on any capacity', explain: 'With the large format, Import models can grow beyond 10 GB through refresh in the service.' },
    ],
    answer: 'c',
  },
  {
    id: 'WB-07',
    machineId: wb,
    bulletIds: ['S1.6'],
    format: 'single',
    difficulty: 2,
    stem: 'An admin wants to enable Large semantic model storage format for one existing model without opening the service UI, by using PowerShell. Which setting does the cmdlet change?',
    sources: [S.largeModels],
    options: [
      { id: 'a', text: 'Set-PowerBIDataset with -TargetStorageMode PremiumFiles', explain: 'Correct. Learn: Set-PowerBIDataset -TargetStorageMode PremiumFiles enables the large format.' },
      { id: 'b', text: 'Set-PowerBIWorkspace with -Capacity F64', explain: 'Assigning a capacity doesn’t change a model’s storage format.' },
      { id: 'c', text: 'Set-PowerBIDataset with -StorageMode DirectLake', explain: 'Storage mode is a per-table property, not the large storage format.' },
      { id: 'd', text: 'Invoke-PowerBIRestMethod with a refresh request', explain: 'A refresh doesn’t change the storage format.' },
    ],
    answer: 'a',
  },

  // ── Double Loom: S1.7 composite models ──────────────────────────────
  {
    id: 'DL-01',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 2,
    stem: 'An analyst is live-connected to a certified Sales semantic model in Power BI Desktop. They need to add a Targets Excel sheet and relate it to the model. What should they do?',
    sources: [S.composite],
    options: [
      { id: 'a', text: 'Download the Sales model as a .pbix and add the sheet', explain: 'This creates a disconnected copy instead of extending the shared model.' },
      { id: 'b', text: 'Select Make changes to this model, then add the sheet', explain: 'Correct. This converts the live connection to DirectQuery and creates a local composite model.' },
      { id: 'c', text: 'Ask the model owner to switch the Sales model to Dual', explain: 'Dual is a table storage mode; it doesn’t let a report author add tables.' },
      { id: 'd', text: 'Use a field parameter to bring in the Targets sheet', explain: 'Field parameters switch fields in a visual; they don’t add data sources.' },
    ],
    answer: 'b',
  },
  {
    id: 'DL-02',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'regular-vs-limited',
    stem: 'A composite model has Import dimension tables and a DirectQuery Sales fact table. Queries that filter Sales by dimension attributes are slow. Which change helps the engine send one efficient native query?',
    sources: [S.storageMode],
    options: [
      { id: 'a', text: 'Set the dimension tables to Dual storage mode', explain: 'Correct. Dual dimensions keep relationships with DirectQuery facts regular and let JOIN logic be pushed to the source.' },
      { id: 'b', text: 'Set the Sales table to Import with a one-day refresh', explain: 'That gives up the DirectQuery freshness the design was chosen for.' },
      { id: 'c', text: 'Set every relationship to cross-filter direction Both', explain: 'Bi-directional filtering adds work and doesn’t fix limited relationships.' },
      { id: 'd', text: 'Add a calculated table that copies the Sales table', explain: 'A calculated table uses Import storage and duplicates the fact data.' },
    ],
    answer: 'a',
  },
  {
    id: 'DL-03',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'dual-vs-hybrid',
    stem: 'A FactSales table must serve history from Import partitions and the most recent rows in real time through DirectQuery, in one table. What kind of table is this?',
    sources: [S.incremental, S.composite, S.modes],
    options: [
      { id: 'a', text: 'A Dual table', explain: 'A Dual table is served from cache or DirectQuery per query, not split into partitions by date.' },
      { id: 'b', text: 'A calculated table', explain: 'A calculated table is defined by DAX and stored as Import.' },
      { id: 'c', text: 'A hybrid table', explain: 'Correct. A hybrid table has Import partitions plus a DirectQuery partition for the latest data, created by an incremental refresh policy.' },
      { id: 'd', text: 'A bridging table', explain: 'A bridging table resolves many-to-many relationships.' },
    ],
    answer: 'c',
  },
  {
    id: 'DL-04',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are designing a composite model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.composite, S.relationships],
    statements: [
      { id: 's1', text: 'All Import tables in a model belong to the same source group.', answer: true, explain: 'Yes. A source group is the items from one DirectQuery source, or all Import sources involved in the model.' },
      { id: 's2', text: 'A relationship between tables in different source groups is always regular.', answer: false, explain: 'No. Relationships that cross source groups are limited relationships.' },
      { id: 's3', text: 'A calculated table can reference both Import and DirectQuery tables.', answer: true, explain: 'Yes. The DAX that defines a calculated table can reference imported or DirectQuery tables, or both.' },
    ],
  },
  {
    id: 'DL-05',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 3,
    stem: 'You create a composite model that combines a confidential SQL Server source with a product list in an Excel file. Power BI shows a security warning. What risk does the warning describe?',
    sources: [S.composite],
    options: [
      { id: 'a', text: 'Users of the report bypass RLS defined on the SQL Server source', explain: 'The warning is about data moving between sources, not RLS.' },
      { id: 'b', text: 'Values from one source can be included in queries sent to the other source', explain: 'Correct. Learn: data from one source can be sent inside queries to another, so check whether that data movement is acceptable.' },
      { id: 'c', text: 'The Excel file will be uploaded to OneLake as a Delta table', explain: 'Composite models don’t convert sources into Delta tables.' },
      { id: 'd', text: 'The SQL Server data will be imported into the model at every refresh', explain: 'DirectQuery tables aren’t imported, and that isn’t the warning.' },
    ],
    answer: 'b',
  },
  {
    id: 'DL-06',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'You need one semantic model that combines Direct Lake tables from a lakehouse with an Import table from an external Excel source. Which Direct Lake option allows this?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints, by mixing modes in the model', explain: 'Direct Lake on SQL can’t be mixed with other storage modes in the same model.' },
      { id: 'b', text: 'Neither; Direct Lake tables can never share a model with Import tables', explain: 'Direct Lake on OneLake models can have Import tables added.' },
      { id: 'c', text: 'Direct Lake on OneLake, adding the Import table to the model', explain: 'Correct. Semantic models with Direct Lake on OneLake tables can also have Import tables from other sources.' },
      { id: 'd', text: 'Either option, as long as the Excel file is stored in OneLake', explain: 'Where the file is stored doesn’t change Direct Lake on SQL’s restriction.' },
    ],
    answer: 'c',
  },
  {
    id: 'DL-07',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'single',
    difficulty: 2,
    stem: 'Model C is a composite model built on published model A. Model A has no RLS on its Customer table. A report on model C uses only C’s new tables. What can that report query?',
    sources: [S.composite],
    options: [
      { id: 'a', text: 'Only the tables added in model C', explain: 'A report on C can query tables in A that aren’t protected by RLS.' },
      { id: 'b', text: 'Only the A tables that C’s visuals already use', explain: 'Learn says any table in A without RLS can be queried, not just used ones.' },
      { id: 'c', text: 'Nothing in A until A’s owner grants Build to the report', explain: 'The point is what C’s reports can reach once C includes A’s tables.' },
      { id: 'd', text: 'Any table in model A that isn’t protected by RLS', explain: 'Correct. Learn: a report on C can query any table in A that isn’t protected by RLS.' },
    ],
    answer: 'd',
  },
  {
    id: 'DL-08',
    machineId: dl,
    bulletIds: ['S1.7'],
    format: 'match',
    difficulty: 2,
    trapPairId: 'dual-vs-hybrid',
    stem: 'Match each composite model term to its description.',
    sources: [S.composite, S.storageMode, S.incremental],
    prompts: [
      { id: 'p1', text: 'Source group' },
      { id: 'p2', text: 'Dual table' },
      { id: 'p3', text: 'Hybrid table' },
      { id: 'p4', text: 'Chaining' },
    ],
    choices: [
      { id: 'c1', text: 'Items from one DirectQuery source, or all Import sources, in a model' },
      { id: 'c2', text: 'A table served from cache or by DirectQuery, chosen per query' },
      { id: 'c3', text: 'A table with Import partitions and a DirectQuery partition for the newest data' },
      { id: 'c4', text: 'Building semantic models on top of other semantic models' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'This is Learn’s definition of a source group.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Dual tables can act as Import or DirectQuery depending on the query.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Hybrid tables come from incremental refresh with real-time DirectQuery.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Chained models depend on upstream models, so upstream changes affect them.' },
    ],
  },

  // ── Speed Governor: S2.1 queries and visuals ────────────────────────
  {
    id: 'SG-01',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'dl-fallback',
    stem: 'In Performance Analyzer, a visual on a Direct Lake on SQL semantic model shows a Direct query duration line. What does this indicate?',
    sources: [S.dlAnalyze],
    options: [
      { id: 'a', text: 'The visual’s query fell back from Direct Lake to DirectQuery', explain: 'Correct. A Direct query line on a Direct Lake model means that visual’s query fell back.' },
      { id: 'b', text: 'Columns were transcoded into memory for the first time', explain: 'Transcoding is Direct Lake loading; it isn’t reported as Direct query.' },
      { id: 'c', text: 'The visual is using a field parameter', explain: 'Field parameters are reported under Evaluated parameters.' },
      { id: 'd', text: 'The report is waiting for other visuals to complete', explain: 'Waiting on other visuals is part of Other.' },
    ],
    answer: 'a',
  },
  {
    id: 'SG-02',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You trace a Direct Lake on SQL model with SQL Server Profiler to find fallback. You see DirectQuery events for an EngineEdition check query. What should you conclude?',
    sources: [S.dlAnalyze],
    options: [
      { id: 'a', text: 'The whole model has fallen back because of a guardrail', explain: 'Guardrail fallback shows on report queries; this system query always uses DirectQuery.' },
      { id: 'b', text: 'This query always uses DirectQuery and doesn’t indicate fallback', explain: 'Correct. Learn: EngineEdition and OLS check queries always use DirectQuery and don’t mean fallback.' },
      { id: 'c', text: 'The SQL analytics endpoint has RLS on the table', explain: 'RLS fallback would appear on report queries against that table.' },
      { id: 'd', text: 'The model needs a manual refresh to reframe', explain: 'Reframing doesn’t change how this system query runs.' },
    ],
    answer: 'b',
  },
  {
    id: 'SG-03',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'perf-categories',
    stem: 'In Performance Analyzer, a scatter chart with 30,000 points shows a fast DAX query time but a long Visual display time. What should you change?',
    sources: [S.perfAnalyzer, S.optimization],
    options: [
      { id: 'a', text: 'Rewrite the visual’s measures with variables', explain: 'The DAX query is already fast; the time goes into drawing the visual.' },
      { id: 'b', text: 'Switch the model to Direct Lake', explain: 'Storage mode affects query time, not rendering time.' },
      { id: 'c', text: 'Reduce the points the visual draws', explain: 'Correct. Visual display is time spent rendering, which you fix with report design.' },
      { id: 'd', text: 'Add an index to the source table', explain: 'Source indexes affect query time, not drawing time.' },
    ],
    answer: 'c',
  },
  {
    id: 'SG-04',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A report page has a table visual with no filters over a 400-million-row fact table, and it loads slowly. What does Learn suggest as a fix?',
    sources: [S.optimization],
    options: [
      { id: 'a', text: 'Turn on the large semantic model storage format', explain: 'The format raises size limits; it doesn’t limit rows in a visual.' },
      { id: 'b', text: 'Set the fact table to Dual storage mode', explain: 'The visual would still try to load every row.' },
      { id: 'c', text: 'Add a field parameter to the table visual', explain: 'Field parameters switch fields; they don’t reduce rows.' },
      { id: 'd', text: 'Apply a Top N filter to limit the rows the table displays', explain: 'Correct. Learn: use the Top N filter to reduce the max number of items the table displays.' },
    ],
    answer: 'd',
  },
  {
    id: 'SG-05',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'multi',
    difficulty: 2,
    stem: 'An Import model is larger than it needs to be. Which two changes does Learn recommend to reduce its size? Choose two.',
    sources: [S.dataReduction],
    options: [
      { id: 'a', text: 'Remove columns that reports and the model don’t use', explain: 'Correct. Removing unnecessary columns is a key data reduction technique.' },
      { id: 'b', text: 'Disable auto date/time in Power BI Desktop', explain: 'Correct. Auto date/time creates a hidden date table for each date column.' },
      { id: 'c', text: 'Set every relationship to cross-filter direction Both', explain: 'Filter direction doesn’t reduce stored data.' },
      { id: 'd', text: 'Convert numeric columns to text', explain: 'Text uses hash encoding and generally compresses worse than numbers.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'SG-06',
    machineId: sg,
    bulletIds: ['S2.1'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'perf-categories',
    stem: 'Match each Performance Analyzer duration to what it measures.',
    sources: [S.perfAnalyzer],
    prompts: [
      { id: 'p1', text: 'DAX query' },
      { id: 'p2', text: 'Direct query' },
      { id: 'p3', text: 'Visual display' },
      { id: 'p4', text: 'Other' },
    ],
    choices: [
      { id: 'c1', text: 'Time for the semantic model to produce the visual’s results' },
      { id: 'c2', text: 'Time for the external source to answer a DirectQuery request' },
      { id: 'c3', text: 'Time to draw the visual on screen' },
      { id: 'c4', text: 'Time preparing queries and waiting for other visuals' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Fix slow DAX query time in the model or the DAX.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'On a Direct Lake model, this line also reveals fallback.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Fix it with report design, such as fewer data points.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Other covers preparing queries, waiting, and background processing.' },
    ],
  },

  // ── Speed Governor: S2.2 DAX performance ────────────────────────────
  {
    id: 'SG-07',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: "A measure is defined as CALCULATE([Sales], FILTER('Product', 'Product'[Color] = \"Red\")). It is slow on a large Product table. Which rewrite follows Learn’s guidance?",
    sources: [S.bpFilter],
    options: [
      { id: 'a', text: "CALCULATE([Sales], FILTER(ALL('Product'), 'Product'[Color] = \"Red\"))", explain: 'This still iterates a whole table and also removes all Product filters.' },
      { id: 'b', text: "CALCULATE([Sales], KEEPFILTERS('Product'[Color] = \"Red\"))", explain: 'Correct. A Boolean filter on one column is optimized by the column store, and KEEPFILTERS keeps existing Color filters.' },
      { id: 'c', text: "SUMX(FILTER('Product', 'Product'[Color] = \"Red\"), [Sales])", explain: 'This iterates products and evaluates the measure per row, which is slower.' },
      { id: 'd', text: "IF(SELECTEDVALUE('Product'[Color]) = \"Red\", [Sales])", explain: 'This returns BLANK unless exactly Red is selected, which changes the result.' },
    ],
    answer: 'b',
  },
  {
    id: 'SG-08',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'A margin measure is written as IF([Sales] = 0, BLANK(), [Profit] / [Sales]). How should you rewrite it for better performance and safe division?',
    sources: [S.bpDivide],
    options: [
      { id: 'a', text: 'IFERROR([Profit] / [Sales], BLANK())', explain: 'IFERROR catches errors after they happen and isn’t the recommended pattern.' },
      { id: 'b', text: 'DIVIDE([Profit], [Sales])', explain: 'Correct. DIVIDE handles zero or blank denominators and is better optimized than testing with IF.' },
      { id: 'c', text: '[Profit] / ([Sales] + 0)', explain: 'Adding zero doesn’t prevent division by zero.' },
      { id: 'd', text: 'SUMX(Sales, [Profit] / [Sales])', explain: 'Row-by-row division changes the result and adds iteration.' },
    ],
    answer: 'b',
  },
  {
    id: 'SG-09',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You need a measure that counts the rows in the Sales table. Which expression does Learn recommend?',
    sources: [S.bpCountrows],
    options: [
      { id: 'a', text: 'COUNT(Sales[OrderID])', explain: 'COUNT over a column works but is less efficient, and it skips blank values in that column.' },
      { id: 'b', text: 'COUNTX(Sales, Sales[OrderID])', explain: 'COUNTX adds an iterator for no benefit.' },
      { id: 'c', text: 'COUNTROWS(Sales)', explain: 'Correct. Learn recommends COUNTROWS to count table rows; it is more efficient.' },
      { id: 'd', text: 'DISTINCTCOUNT(Sales[OrderID])', explain: 'This counts distinct values, which differs when an order has several lines.' },
    ],
    answer: 'c',
  },
  {
    id: 'SG-10',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'yesno',
    difficulty: 3,
    placement: true,
    stem: 'You are tuning DAX measures in a semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.bpFilter, S.varBP],
    statements: [
      { id: 's1', text: 'A Boolean filter argument in CALCULATE can compare a column to a measure, such as Sales[Amount] > [Average Amount].', answer: false, explain: 'No. Boolean filter expressions can’t reference a measure or columns from several tables; use FILTER for those cases.' },
      { id: 's2', text: 'Storing a repeated sub-expression in a variable means it is evaluated once instead of several times.', answer: true, explain: 'Yes. Learn’s variables article shows a YoY measure running in about half the time.' },
      { id: 's3', text: 'FILTER over a whole table is the most efficient way to filter a single column in CALCULATE.', answer: false, explain: 'No. In-memory column stores are optimized for Boolean column filters.' },
    ],
  },
  {
    id: 'SG-11',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'order',
    difficulty: 2,
    placement: true,
    stem: 'A visual is slow and you suspect one measure. Put the steps in order to diagnose and fix it.',
    sources: [S.perfAnalyzer, S.daxQueryView],
    items: [
      { id: 'i2', text: 'Copy the visual’s DAX query into DAX query view', explain: 'Second. The query lets you reproduce the slow request outside the report.' },
      { id: 'i4', text: 'Use Update model to save the improved measure', explain: 'Last. Promote the faster DEFINE MEASURE into the model.' },
      { id: 'i1', text: 'Record the page in Performance Analyzer and find the slow visual', explain: 'First. Measure before changing anything.' },
      { id: 'i3', text: 'Rewrite the measure as a DEFINE MEASURE and run the query to check it', explain: 'Third. Test the new formula in the query without changing the model.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'SG-12',
    machineId: sg,
    bulletIds: ['S2.2'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You need a measure that returns [Sales] only for months that achieved a profit, where profit is the [Profit] measure. You want to follow Learn’s guidance on filter arguments. Which expression should you use?',
    sources: [S.bpFilter],
    options: [
      { id: 'a', text: 'CALCULATE([Sales], [Profit] > 0)', explain: 'A Boolean filter argument can’t reference a measure.' },
      { id: 'b', text: 'CALCULATE([Sales], KEEPFILTERS([Profit] > 0))', explain: 'KEEPFILTERS still wraps a Boolean expression, which can’t reference a measure.' },
      { id: 'c', text: "CALCULATE([Sales], FILTER(VALUES('Date'[Month]), [Profit] > 0))", explain: 'Correct. FILTER is needed here because the condition evaluates a measure for each month.' },
      { id: 'd', text: 'CALCULATE([Sales], FILTER(ALL(Sales), [Profit] > 0))', explain: 'This iterates every fact row, removes all Sales filters, and tests profit per row rather than per month.' },
    ],
    answer: 'c',
  },

  // ── Direct Lake Shuttle: S2.3 configure Direct Lake ─────────────────
  {
    id: 'DLS-01',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'framing-vs-import-refresh',
    stem: 'A nightly ETL loads several Delta tables over two hours. Users of a Direct Lake model sometimes see half-loaded data. You need them to see only completed loads. What should you do?',
    sources: [S.dlHow, S.directLake],
    options: [
      { id: 'a', text: 'Switch the model to Import and refresh it hourly', explain: 'This gives up Direct Lake instead of controlling framing.' },
      { id: 'b', text: 'Set DirectLakeBehavior to DirectQueryOnly', explain: 'DirectQuery always reads the latest data, including half-finished loads.' },
      { id: 'c', text: 'Turn off automatic updates; refresh after the ETL', explain: 'Correct. Turning off automatic updates lets you frame the model only after the load completes.' },
      { id: 'd', text: 'Enable the large semantic model storage format', explain: 'Storage format doesn’t control when the model reframes.' },
    ],
    answer: 'c',
  },
  {
    id: 'DLS-02',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'dl-fallback',
    stem: 'A Direct Lake on SQL model must never silently switch to DirectQuery in development, so problems are found early. Which DirectLakeBehavior setting should you use?',
    sources: [S.dlHow, S.dlAnalyze],
    options: [
      { id: 'a', text: 'Automatic', explain: 'Automatic is the default and falls back silently.' },
      { id: 'b', text: 'DirectQueryOnly', explain: 'This forces every query to DirectQuery, for measuring fallback cost.' },
      { id: 'c', text: 'Import', explain: 'Import isn’t a DirectLakeBehavior value.' },
      { id: 'd', text: 'DirectLakeOnly', explain: 'Correct. Queries that can’t run in Direct Lake fail instead of falling back.' },
    ],
    answer: 'd',
  },
  {
    id: 'DLS-03',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'dl-fallback',
    stem: 'A Direct Lake on SQL analytics endpoint model with DirectLakeBehavior set to Automatic sends some queries to DirectQuery. Which two conditions cause fallback? Choose two.',
    sources: [S.dlHow, S.directLake],
    options: [
      { id: 'a', text: 'A model table is based on a SQL view in the endpoint that isn’t materialized', explain: 'Correct. Views can only be read by falling back to DirectQuery.' },
      { id: 'b', text: 'A table the model uses has row-level security defined in the SQL analytics endpoint', explain: 'Correct. SQL RLS on a table is a fallback condition.' },
      { id: 'c', text: 'A column is loaded into memory for the first time', explain: 'First load is transcoding, a normal Direct Lake operation.' },
      { id: 'd', text: 'The model includes a field parameter', explain: 'Field parameters are allowed calculated tables in Direct Lake on SQL models.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'DLS-04',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You manage refresh for a Direct Lake semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.dlHow, S.directLake],
    statements: [
      { id: 's1', text: 'Data written to the Delta tables after the last framing is not visible to Direct Lake queries until the model is framed again.', answer: true, explain: 'Yes. Framing fixes the point in time that queries see.' },
      { id: 's2', text: 'Automatic updates are off by default for new Direct Lake models.', answer: false, explain: 'No. Keep your Direct Lake data up to date is on by default.' },
      { id: 's3', text: 'Power BI suspends automatic updates after a non-recoverable refresh error.', answer: true, explain: 'Yes. They resume after a successful on-demand refresh.' },
    ],
  },
  {
    id: 'DLS-06',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 1,
    stem: 'A user opens a Direct Lake report for the first time after framing. The first visuals are slightly slower; later ones are fast. What explains this?',
    sources: [S.dlHow],
    options: [
      { id: 'a', text: 'Columns are transcoded from OneLake into memory when first queried', explain: 'Correct. Columns load on first use and then stay resident in memory.' },
      { id: 'b', text: 'Each first query falls back to DirectQuery by design', explain: 'Fallback only happens under specific conditions, not on first use.' },
      { id: 'c', text: 'The model performs an Import refresh before the first query', explain: 'Direct Lake doesn’t import data at refresh.' },
      { id: 'd', text: 'The SQL analytics endpoint builds indexes on first access', explain: 'Direct Lake reads Delta files directly; this isn’t the mechanism.' },
    ],
    answer: 'a',
  },
  {
    id: 'DLS-07',
    machineId: ds,
    bulletIds: ['S2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'You try to create a Direct Lake semantic model from a lakehouse in West Central US, with the model in a workspace in another region. What does Learn say?',
    sources: [S.directLake, S.dlHow],
    options: [
      { id: 'a', text: 'It works, but every query falls back to DirectQuery', explain: 'Region mismatch isn’t a fallback condition; the model must be in the same region.' },
      { id: 'b', text: 'It works after you enable large semantic model storage format', explain: 'Storage format doesn’t change region requirements.' },
      { id: 'c', text: 'The model and source must be in the same region', explain: 'Correct. Learn requires the same region; a shortcut in a lakehouse in the model’s region is the workaround.' },
      { id: 'd', text: 'It works only with Direct Lake on SQL analytics endpoints', explain: 'The region requirement applies regardless of flavor.' },
    ],
    answer: 'c',
  },

  // ── Direct Lake Shuttle: S2.4 OneLake vs SQL endpoint ───────────────
  {
    id: 'DLS-08',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'A new Direct Lake model must combine Delta tables from two lakehouses and a KQL database that has OneLake availability turned on. Which Direct Lake option should you choose?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints', explain: 'This option uses a single Fabric source and doesn’t support KQL databases.' },
      { id: 'b', text: 'Direct Lake on OneLake', explain: 'Correct. It can use Delta tables from one or more Fabric items, including KQL databases with OneLake availability.' },
      { id: 'c', text: 'Either option, because both read any Delta table', explain: 'Only Direct Lake on OneLake supports several sources and KQL databases.' },
      { id: 'd', text: 'Neither; KQL data needs a separate DirectQuery model', explain: 'Direct Lake on OneLake supports KQL databases with OneLake availability on.' },
    ],
    answer: 'b',
  },
  {
    id: 'DLS-09',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'A team must build a Direct Lake model on business logic that exists only as non-materialized SQL views in a warehouse, and they accept DirectQuery fallback for those views. Which option fits?',
    sources: [S.directLake, S.dlHow],
    options: [
      { id: 'a', text: 'Direct Lake on OneLake, pointing tables at the views', explain: 'You can’t build a Direct Lake on OneLake table on a non-materialized SQL view.' },
      { id: 'b', text: 'Direct Lake on OneLake with DirectLakeBehavior set to Automatic', explain: 'On OneLake runs only as DirectLakeOnly and never falls back.' },
      { id: 'c', text: 'Direct Lake on SQL analytics endpoints', explain: 'Correct. It can read SQL views by falling back to DirectQuery.' },
      { id: 'd', text: 'Either option, after shortcuts to the views are created', explain: 'Shortcuts reference Delta data, not SQL view definitions.' },
    ],
    answer: 'c',
  },
  {
    id: 'DLS-10',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'You are comparing Direct Lake on OneLake with Direct Lake on SQL analytics endpoints. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.directLake],
    statements: [
      { id: 's1', text: 'Direct Lake on OneLake never falls back to DirectQuery.', answer: true, explain: 'Yes. It runs exclusively in DirectLakeOnly mode.' },
      { id: 's2', text: 'Direct Lake on SQL analytics endpoints can combine Delta tables from several Fabric items in one model.', answer: false, explain: 'No. It uses a single Fabric source; multiple sources need Direct Lake on OneLake.' },
      { id: 's3', text: 'Row-level security defined in the SQL analytics endpoint is enforced for Direct Lake on OneLake models.', answer: false, explain: 'No. On OneLake ignores SQL endpoint security; use semantic model RLS or OneLake security.' },
    ],
  },
  {
    id: 'DLS-11',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'A Direct Lake on OneLake model has a table that exceeds the capacity guardrail for row groups. What happens?',
    sources: [S.dlHow, S.directLake],
    options: [
      { id: 'a', text: 'Refresh fails and the model can’t be queried until the table is optimized', explain: 'Correct. Direct Lake on OneLake behaves like Import over a guardrail: it doesn’t fall back.' },
      { id: 'b', text: 'Queries fall back to DirectQuery and refresh succeeds with a warning', explain: 'That describes Direct Lake on SQL, not on OneLake.' },
      { id: 'c', text: 'Only that table’s queries fall back to DirectQuery', explain: 'Direct Lake on OneLake never falls back.' },
      { id: 'd', text: 'The table is automatically repartitioned during framing', explain: 'Framing reads metadata; it doesn’t optimize tables.' },
    ],
    answer: 'a',
  },
  {
    id: 'DLS-12',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'You are creating a brand-new Direct Lake semantic model with no special requirements for SQL views or SQL endpoint security. Which option does Learn recommend?',
    sources: [S.directLake, S.dlHow],
    options: [
      { id: 'a', text: 'Direct Lake on SQL analytics endpoints', explain: 'This option is for cases that need SQL views or SQL endpoint security and accept fallback.' },
      { id: 'b', text: 'Import mode with incremental refresh', explain: 'This isn’t a Direct Lake option.' },
      { id: 'c', text: 'DirectQuery to the SQL analytics endpoint', explain: 'This isn’t a Direct Lake option either.' },
      { id: 'd', text: 'Direct Lake on OneLake', explain: 'Correct. Learn recommends Direct Lake on OneLake for new models.' },
    ],
    answer: 'd',
  },
  {
    id: 'DLS-13',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'multi',
    difficulty: 2,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'Which two requirements can be met only by Direct Lake on SQL analytics endpoints, not by Direct Lake on OneLake? Choose two.',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Use a SQL view in the SQL analytics endpoint as a model table', explain: 'Correct. On SQL can read SQL views by falling back to DirectQuery; Direct Lake on OneLake can’t use SQL views that aren’t materialized.' },
      { id: 'b', text: 'Respect RLS defined in the SQL analytics endpoint by falling back to DirectQuery', explain: 'Correct. On SQL checks permissions through the endpoint and falls back for SQL RLS; on OneLake ignores it.' },
      { id: 'c', text: 'Add Import tables from Excel to the same model', explain: 'Only on OneLake can mix with Import tables; on SQL can’t mix modes.' },
      { id: 'd', text: 'Read a KQL database with OneLake availability turned on', explain: 'Only on OneLake supports KQL databases.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'DLS-14',
    machineId: ds,
    bulletIds: ['S2.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'dl-onelake-vs-sql',
    stem: 'Analysts using a Direct Lake on OneLake model get access errors, even though they have SELECT permission in the lakehouse’s SQL analytics endpoint. What do they need?',
    sources: [S.directLake],
    options: [
      { id: 'a', text: 'Access to the data in OneLake', explain: 'Correct. On OneLake reads the Delta files directly, so users need access to the OneLake data, not SQL endpoint permissions.' },
      { id: 'b', text: 'Membership in a SQL endpoint database role', explain: 'SQL endpoint permissions aren’t used by Direct Lake on OneLake.' },
      { id: 'c', text: 'DirectLakeBehavior set to DirectQueryOnly', explain: 'On OneLake doesn’t fall back, so this setting doesn’t apply.' },
      { id: 'd', text: 'A Pro license in addition to the capacity', explain: 'The error is about data access, not licensing.' },
    ],
    answer: 'a',
  },

  // ── Batch Winder: S2.5 incremental refresh ──────────────────────────
  {
    id: 'BW-01',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 1,
    stem: 'You are setting up incremental refresh in Power BI Desktop. Which two parameter names must the date filter use?',
    sources: [S.incremental, S.incrementalCfg],
    options: [
      { id: 'a', text: 'StartDate and EndDate', explain: 'The names are reserved and specific; these aren’t them.' },
      { id: 'b', text: 'rangestart and rangeend', explain: 'The names are case-sensitive.' },
      { id: 'c', text: 'RangeStart and RangeEnd', explain: 'Correct. Reserved, case-sensitive Date/Time parameters that the service overrides per partition.' },
      { id: 'd', text: 'WindowStart and WindowEnd', explain: 'These aren’t the reserved names.' },
    ],
    answer: 'c',
  },
  {
    id: 'BW-02',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 2,
    stem: 'An incremental refresh filter uses [OrderDate] >= RangeStart and [OrderDate] <= RangeEnd. Some orders appear twice in the model. What should you change?',
    sources: [S.incrementalCfg],
    options: [
      { id: 'a', text: 'Use < RangeEnd instead of <= RangeEnd', explain: 'Correct. Equality on both sides puts boundary rows in two partitions.' },
      { id: 'b', text: 'Use > RangeStart and > RangeEnd', explain: 'This drops the start boundary and loads rows after RangeEnd instead of before it.' },
      { id: 'c', text: 'Turn on Detect data changes on OrderDate', explain: 'Detect data changes needs a different column and doesn’t fix overlap.' },
      { id: 'd', text: 'Set the refresh period to one day', explain: 'Period length doesn’t fix overlapping filters.' },
    ],
    answer: 'a',
  },
  {
    id: 'BW-03',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'archive-vs-refresh-period',
    stem: 'A policy must keep five years of sales history and reload only the last 10 days on each refresh. How should you configure it?',
    sources: [S.incrementalCfg],
    options: [
      { id: 'a', text: 'Archive data starting 10 days before; incrementally refresh 5 years before', explain: 'This swaps the two settings.' },
      { id: 'b', text: 'Archive data starting 5 years before; incrementally refresh 10 days before', explain: 'Correct. The archive period keeps history; the refresh period is the window reloaded each time.' },
      { id: 'c', text: 'Archive data starting 5 years before; turn on Only refresh complete days', explain: 'Complete days doesn’t define the 10-day refresh window.' },
      { id: 'd', text: 'Incrementally refresh 5 years before; turn on Detect data changes', explain: 'This reloads five years of data each time.' },
    ],
    answer: 'b',
  },
  {
    id: 'BW-04',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You published a semantic model with an incremental refresh policy to a Fabric capacity workspace. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.incremental, S.incrementalCfg],
    statements: [
      { id: 's1', text: 'You can download the published model back to Power BI Desktop as a .pbix file.', answer: false, explain: 'No. After incremental refresh partitions are created, the model can’t be downloaded as a .pbix.' },
      { id: 's2', text: 'The first refresh in the service creates the partitions defined by the policy.', answer: true, explain: 'Yes. Publish, then run the first refresh to build the partitions.' },
      { id: 's3', text: 'If two tables have policies, each can use its own pair of range parameters.', answer: false, explain: 'No. All tables with policies must use the same RangeStart and RangeEnd parameters.' },
    ],
  },
  {
    id: 'BW-05',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'An Import fact table with incremental refresh reloads 30 days each night, but most days don’t change. The table has a LastUpdated audit column and a partitioning column, OrderDate. How can you refresh only periods that changed?',
    sources: [S.incrementalCfg],
    options: [
      { id: 'a', text: 'Turn on Detect data changes and choose OrderDate', explain: 'The column must differ from the one used for RangeStart and RangeEnd.' },
      { id: 'b', text: 'Turn on Detect data changes and choose LastUpdated', explain: 'Correct. Only periods whose LastUpdated maximum changed are refreshed, and it differs from the partitioning column.' },
      { id: 'c', text: 'Turn on Only refresh complete days', explain: 'This skips today’s partial day; it doesn’t detect changes.' },
      { id: 'd', text: 'Shorten the archive period to 30 days', explain: 'That drops history instead of skipping unchanged periods.' },
    ],
    answer: 'b',
  },
  {
    id: 'BW-06',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'dual-vs-hybrid',
    stem: 'Reports must show today’s orders in real time while history stays in Import. The model is in a Premium Per User workspace. Which incremental refresh option should you turn on?',
    sources: [S.incremental, S.incrementalCfg, S.modes],
    options: [
      { id: 'a', text: 'Only refresh complete days', explain: 'This excludes the current day instead of making it real time.' },
      { id: 'b', text: 'Detect data changes', explain: 'This skips unchanged periods; it doesn’t add real-time data.' },
      { id: 'c', text: 'Get the latest data in real time with DirectQuery', explain: 'Correct. It adds a DirectQuery partition for the newest data, making a hybrid table; PPU supports it.' },
      { id: 'd', text: 'Large semantic model storage format', explain: 'Storage format affects size limits, not freshness.' },
    ],
    answer: 'c',
  },
  {
    id: 'BW-07',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A team wants incremental refresh partitions on a Direct Lake model’s fact table to speed up refresh. What should you tell them?',
    sources: [S.directLake, S.incremental],
    options: [
      { id: 'a', text: 'Define RangeStart and RangeEnd on the Direct Lake table', explain: 'Direct Lake tables don’t use incremental refresh partitions.' },
      { id: 'b', text: 'Switch on hybrid mode for the Direct Lake table', explain: 'Direct Lake doesn’t support hybrid tables.' },
      { id: 'c', text: 'Use XMLA to add model partitions to the table', explain: 'Direct Lake doesn’t support model table partitions.' },
      { id: 'd', text: 'Partition the Delta table instead, if needed', explain: 'Correct. Direct Lake refresh copies only metadata, and partitioning belongs at the Delta table level.' },
    ],
    answer: 'd',
  },
  {
    id: 'BW-08',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'order',
    difficulty: 2,
    placement: true,
    stem: 'You are implementing incremental refresh on an Import Sales table. Put the steps in order.',
    sources: [S.incrementalCfg],
    items: [
      { id: 'i3', text: 'Define the incremental refresh policy on the table', explain: 'Third. The policy uses the filtered table.' },
      { id: 'i1', text: 'Create the RangeStart and RangeEnd parameters', explain: 'First. The filter needs the parameters.' },
      { id: 'i4', text: 'Publish and run the first refresh in the service', explain: 'Last. The first refresh creates the partitions.' },
      { id: 'i2', text: 'Filter the date column with >= RangeStart and < RangeEnd', explain: 'Second. The filter defines what each partition loads.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'BW-09',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'An incremental refresh policy on a source that doesn’t support query folding of the date filter refreshes much slower than expected. What is the most likely cause?',
    sources: [S.incremental, S.incrementalCfg],
    options: [
      { id: 'a', text: 'Each partition query reads all source rows', explain: 'Correct. Without folding, the RangeStart and RangeEnd filter can’t be pushed to the source.' },
      { id: 'b', text: 'The archive period is longer than the refresh period', explain: 'That is the normal configuration.' },
      { id: 'c', text: 'The model doesn’t use the large storage format', explain: 'Storage format doesn’t affect how filters reach the source.' },
      { id: 'd', text: 'Detect data changes is turned off', explain: 'It’s optional and doesn’t explain full source scans.' },
    ],
    answer: 'a',
  },
  {
    id: 'BW-10',
    machineId: bw,
    bulletIds: ['S2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'The source column for incremental refresh is an integer date key, OrderDateKey (yyyymmdd). RangeStart and RangeEnd must stay Date/Time. How should the filter work?',
    sources: [S.incrementalCfg],
    options: [
      { id: 'a', text: 'Change RangeStart and RangeEnd to Whole Number parameters', explain: 'The parameters must be Date/Time.' },
      { id: 'b', text: 'Use Detect data changes on OrderDateKey instead of a filter', explain: 'A range filter is still required.' },
      { id: 'c', text: 'Convert their values to yyyymmdd integers in the filter step', explain: 'Correct. Convert the Date/Time parameters to the same integer form before comparing.' },
      { id: 'd', text: 'Incremental refresh can’t be used with integer keys', explain: 'Learn documents the integer key pattern.' },
    ],
    answer: 'c',
  },
]
