import { S } from '../sources'
import type { Question } from '../types'

export const discoverChooseQuestions: Question[] = [
  // ── Bale Catalog (P1.2) ──────────────────────────────────────────────
  {
    id: 'BC-01',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'catalog-vs-rthub',
    stem: 'You need to find all certified lakehouses and semantic models in the Finance domain that you have access to, and review each item’s owner, schema, and lineage. Where should you start?',
    sources: [S.catalogExplore, S.onelake],
    options: [
      { id: 'a', text: 'The Real-Time hub', explain: 'The Real-Time hub lists streams and KQL tables for data in motion, not lakehouses and semantic models with endorsement filters.' },
      { id: 'b', text: 'The Explore tab of the OneLake catalog', explain: 'Correct. Explore lists items you can access, filters by domain, item type, and endorsement, and shows details such as owner, schema, and lineage.' },
      { id: 'c', text: 'The workspace lineage view', explain: 'Lineage view shows one workspace’s items and connections; it doesn’t search across domains by endorsement.' },
      { id: 'd', text: 'The Monitoring hub', explain: 'Monitoring tracks activities and runs; it isn’t a discovery catalog for data items.' },
    ],
    answer: 'b',
  },
  {
    id: 'BC-02',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'catalog-vs-rthub',
    stem: 'Your organization streams change data capture (CDC) events from an Azure SQL Database and telemetry from Azure IoT Hub. You need a single tenant-wide place to discover these streams and ingest them into Fabric. What should you use?',
    sources: [S.rtHub],
    options: [
      { id: 'a', text: 'The OneLake catalog', explain: 'The OneLake catalog discovers and governs items such as lakehouses and semantic models, not data in motion.' },
      { id: 'b', text: 'A mirrored database', explain: 'Mirroring replicates a database into OneLake; it isn’t a hub for discovering streams such as IoT Hub telemetry.' },
      { id: 'c', text: 'The Real-Time hub', explain: 'Correct. The Real-Time hub is the tenant-wide place for streaming data, with connectors for Azure SQL Database CDC and Azure IoT Hub.' },
      { id: 'd', text: 'A KQL queryset', explain: 'A KQL queryset runs queries against a KQL database; it doesn’t discover or connect stream sources.' },
    ],
    answer: 'c',
  },
  {
    id: 'BC-03',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'match',
    difficulty: 2,
    stem: 'The OneLake catalog has three tabs. Match each task to the tab you should use.',
    sources: [S.catalog],
    prompts: [
      { id: 'p1', text: 'Browse and filter Fabric items, then open an item’s details without losing the list' },
      { id: 'p2', text: 'See governance insights and recommended actions for the data you own' },
      { id: 'p3', text: 'Review workspace roles and OneLake security roles across items in one view' },
    ],
    choices: [
      { id: 'c1', text: 'Explore' },
      { id: 'c2', text: 'Govern' },
      { id: 'c3', text: 'Secure' },
      { id: 'c4', text: 'Monitor' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Explore has the items list with an in-context item details view, plus filters and selectors.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Govern shows governance insights and recommended actions for data you own.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Secure gives a unified view of workspace roles and OneLake security roles. "Monitor" isn’t one of the catalog’s three tabs.' },
    ],
  },
  {
    id: 'BC-04',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are introducing the OneLake catalog to report authors. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.catalog, S.catalogExplore],
    statements: [
      { id: 's1', text: 'The OneLake catalog is also available inside Microsoft Teams and Microsoft Excel.', answer: true, explain: 'Yes. Learn says the catalog is embedded in Teams, Excel, and Copilot Studio.' },
      { id: 's2', text: 'Finding an item in the OneLake catalog automatically grants you read access to its data.', answer: false, explain: 'No. Explore lists items you already have access to or can request access to; it doesn’t grant access.' },
      { id: 's3', text: 'You can discover catalog metadata programmatically with a REST API.', answer: true, explain: 'Yes. Learn mentions the Microsoft Fabric Catalog Search REST API.' },
    ],
  },
  {
    id: 'BC-05',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 2,
    stem: 'You found an IoT stream in the Real-Time hub. You need to run KQL queries over the stream’s data. According to Learn, what should you do?',
    sources: [S.rtHub],
    options: [
      { id: 'a', text: 'Open the stream’s eventstream, add a KQL database destination, then query the KQL table', explain: 'Correct. To analyze a stream, Learn says to add a KQL Database destination to the eventstream and run queries against the KQL table.' },
      { id: 'b', text: 'Create a OneLake shortcut to the stream in a lakehouse', explain: 'Shortcuts point to stored data in OneLake or external storage, not to a live stream.' },
      { id: 'c', text: 'Connect a Dataflow Gen2 to the stream, load it into a warehouse table, and query it with T-SQL', explain: 'This isn’t the path Learn describes for analyzing a Real-Time hub stream with KQL.' },
      { id: 'd', text: 'Enable OneLake availability on the stream', explain: 'OneLake availability is set on KQL databases or tables, not on the stream itself.' },
    ],
    answer: 'a',
  },
  {
    id: 'BC-06',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'multi',
    difficulty: 2,
    stem: 'You plan event-driven automation in Fabric. Which two kinds of events does the Real-Time hub list so you can react to them? Choose two.',
    sources: [S.rtHub],
    options: [
      { id: 'a', text: 'Fabric workspace item events', explain: 'Correct. Fabric events include workspace item events, OneLake events, job events, and capacity overview events.' },
      { id: 'b', text: 'Azure Blob Storage events', explain: 'Correct. Azure storage account events are listed under Azure events.' },
      { id: 'c', text: 'Semantic model DAX query events', explain: 'DAX query events aren’t among the Fabric or Azure event sources listed in the Real-Time hub.' },
      { id: 'd', text: 'Power BI report page view events', explain: 'Report page views aren’t listed as Real-Time hub event sources.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'BC-07',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 1,
    stem: 'A new analyst opens the OneLake catalog for the first time. Which tab opens by default?',
    sources: [S.catalog],
    options: [
      { id: 'a', text: 'Govern', explain: 'Govern is for governance status and actions; it isn’t the default tab.' },
      { id: 'b', text: 'Secure', explain: 'Secure is for reviewing roles; it isn’t the default tab.' },
      { id: 'c', text: 'Home', explain: 'Home is the Fabric home page, not a OneLake catalog tab.' },
      { id: 'd', text: 'Explore', explain: 'Correct. Learn: "By default, OneLake catalog opens on the Explore tab."' },
    ],
    answer: 'd',
  },
  {
    id: 'BC-08',
    machineId: 'bale-catalog',
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 2,
    stem: 'You need to filter a stream from the Real-Time hub and group events before sending them to a destination. Where do you add these transformations?',
    sources: [S.rtHub],
    options: [
      { id: 'a', text: 'In the KQL queryset attached to the stream', explain: 'A queryset queries data already in a KQL database; it doesn’t transform the stream in flight.' },
      { id: 'b', text: 'In the parent eventstream’s editor', explain: 'Correct. Learn: open the parent eventstream and add transformations such as Filter, Aggregate, and Group by.' },
      { id: 'c', text: 'In the OneLake catalog’s item details', explain: 'Item details show metadata; they don’t transform streams.' },
      { id: 'd', text: 'In a Copy job', explain: 'Copy job moves batch data with incremental or CDC copy; it isn’t the stream processing editor.' },
    ],
    answer: 'b',
  },

  // ── Vat Selector (P1.4) ──────────────────────────────────────────────
  {
    id: 'VS-01',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'stores',
    stem: 'A data engineering team works in PySpark notebooks and stores JSON, images, and Parquet files alongside tables. Analysts only need to read curated tables with T-SQL. Which data store should the team create?',
    sources: [S.decisionLhWh, S.decisionStore],
    options: [
      { id: 'a', text: 'A lakehouse', explain: 'Correct. A lakehouse suits Spark developers and structured plus unstructured data, and its SQL analytics endpoint lets analysts read tables with T-SQL.' },
      { id: 'b', text: 'A warehouse', explain: 'A warehouse is T-SQL-first for structured data; it isn’t the fit for Spark developers working with unstructured files.' },
      { id: 'c', text: 'An eventhouse', explain: 'An eventhouse is for streaming, time-based event data queried with KQL.' },
      { id: 'd', text: 'A SQL database in Fabric', explain: 'SQL database in Fabric targets operational OLTP workloads, not Spark-based data engineering over files.' },
    ],
    answer: 'a',
  },
  {
    id: 'VS-02',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'warehouse-vs-sql-database',
    stem: 'An application team needs a database for a new order-entry app with high concurrency, strongly enforced foreign keys, and automatic index tuning. The data must also be available for analytics in Fabric. Which Fabric data store should they use?',
    sources: [S.decisionStore],
    options: [
      { id: 'a', text: 'A warehouse', explain: 'A warehouse is for analytical workloads (enterprise warehousing, SQL-based BI), not an OLTP order-entry app.' },
      { id: 'b', text: 'A lakehouse', explain: 'A lakehouse targets data engineering and big data, not high-concurrency transactional apps.' },
      { id: 'c', text: 'An eventhouse', explain: 'An eventhouse is for streaming event analytics, not transactional order entry.' },
      { id: 'd', text: 'A SQL database in Fabric', explain: 'Correct. Learn’s scenario picks SQL database in Fabric for operational OLTP needs like enforced foreign keys and automatic index tuning; its SQL analytics endpoint serves analytics.' },
    ],
    answer: 'd',
  },
  {
    id: 'VS-03',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'stores',
    stem: 'You need to store billions of rows of high-granularity telemetry and run interactive time-series and geospatial analysis within seconds, with fast queries from Power BI. Which data store does Learn recommend?',
    sources: [S.decisionStore, S.eventhouse],
    options: [
      { id: 'a', text: 'A lakehouse with Spark notebooks', explain: 'A lakehouse suits data engineering and ML; Learn recommends an eventhouse for high-granularity streaming event analytics.' },
      { id: 'b', text: 'An eventhouse', explain: 'Correct. Learn recommends an eventhouse for streaming event data and high-granularity interactive analytics, including time series and geospatial functions.' },
      { id: 'c', text: 'A warehouse', explain: 'A warehouse targets enterprise SQL-based BI over structured data, not streaming telemetry analytics.' },
      { id: 'd', text: 'Cosmos DB in Fabric', explain: 'Cosmos DB in Fabric is for NoSQL application data, not telemetry analytics.' },
    ],
    answer: 'b',
  },
  {
    id: 'VS-04',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'stores',
    stem: 'You are comparing a lakehouse and a warehouse for a new project. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.decisionLhWh],
    statements: [
      { id: 's1', text: 'Both store their tables in Delta format in OneLake.', answer: true, explain: 'Yes. Both store data in Delta Lake format in OneLake and share the same SQL engine.' },
      { id: 's2', text: 'Only the warehouse supports multi-table transactions.', answer: true, explain: 'Yes. The decision guide maps "need multi-table transactions" to the warehouse.' },
      { id: 's3', text: 'The lakehouse’s SQL analytics endpoint can run INSERT and UPDATE statements against its Delta tables.', answer: false, explain: 'No. The SQL analytics endpoint is read-only for data; it only reads Delta tables.' },
    ],
  },
  {
    id: 'VS-05',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 2,
    stem: 'A team of experienced SQL Server developers is moving to Fabric. They want to reuse their existing T-SQL code, use SQL Server Management Studio, and query lakehouse Delta tables from the same queries. Which data store should they choose?',
    sources: [S.decisionStore],
    options: [
      { id: 'a', text: 'A lakehouse with Spark SQL notebooks', explain: 'Spark SQL isn’t T-SQL, and the team wants to reuse T-SQL and SSMS.' },
      { id: 'b', text: 'An eventhouse with KQL querysets', explain: 'KQL is a different language; this doesn’t reuse the team’s T-SQL code.' },
      { id: 'c', text: 'A warehouse', explain: 'Correct. Learn’s scenario: a warehouse lets SQL developers reuse T-SQL and SSMS, and query lakehouse Delta tables with three-part names.' },
      { id: 'd', text: 'A mirrored database', explain: 'A mirrored database replicates an external database read-only; it isn’t where the team develops new T-SQL logic.' },
    ],
    answer: 'c',
  },
  {
    id: 'VS-06',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'match',
    difficulty: 2,
    trapPairId: 'stores',
    stem: 'Match each developer persona to the primary language Learn associates with the Fabric data store they’re most likely to use.',
    sources: [S.decisionStore],
    prompts: [
      { id: 'p1', text: 'Data engineer building a lakehouse' },
      { id: 'p2', text: 'Data warehouse developer building a warehouse' },
      { id: 'p3', text: 'App developer analyzing events in an eventhouse' },
    ],
    choices: [
      { id: 'c1', text: 'Spark (PySpark, Scala, Spark SQL, R)' },
      { id: 'c2', text: 'T-SQL' },
      { id: 'c3', text: 'KQL' },
      { id: 'c4', text: 'DAX' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Lakehouses are developed primarily with Spark languages.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Warehouses are developed primarily with T-SQL.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Eventhouses are queried primarily with KQL. DAX (unused) is the semantic model language, not a data store language.' },
    ],
  },
  {
    id: 'VS-07',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 3,
    stem: 'A team stores several terabytes in Fabric. Most of the people running T-SQL only read data and never write INSERT, UPDATE, or DELETE statements. The developers who load data work in notebooks. Which data store does Learn’s decision guide pick in this scenario?',
    sources: [S.decisionStore],
    options: [
      { id: 'a', text: 'A warehouse, because the team uses T-SQL', explain: 'The T-SQL users only consume data, so they don’t need warehouse write capabilities.' },
      { id: 'b', text: 'An eventhouse, because the data volume is large and grows quickly every day', explain: 'Volume alone doesn’t point to an eventhouse; that’s for streaming event data.' },
      { id: 'c', text: 'A SQL database in Fabric, because it supports T-SQL', explain: 'SQL database in Fabric is for OLTP workloads, not a notebook-loaded analytics store.' },
      { id: 'd', text: 'A lakehouse, using its SQL analytics endpoint for the T-SQL readers', explain: 'Correct. Learn’s scenario chooses a lakehouse: engineers use notebooks and T-SQL consumers read through the SQL analytics endpoint.' },
    ],
    answer: 'd',
  },
  {
    id: 'VS-08',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'multi',
    difficulty: 2,
    stem: 'You are deciding between a lakehouse and a warehouse. Which two requirements point to a warehouse? Choose two.',
    sources: [S.decisionLhWh],
    options: [
      { id: 'a', text: 'The team develops with T-SQL', explain: 'Correct. T-SQL development maps to the warehouse in the decision guide.' },
      { id: 'b', text: 'Loads must update several tables in one transaction', explain: 'Correct. Multi-table transactions map to the warehouse.' },
      { id: 'c', text: 'The data includes unstructured files such as images', explain: 'Unstructured or mixed data maps to the lakehouse.' },
      { id: 'd', text: 'The team develops with PySpark', explain: 'Spark development maps to the lakehouse.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'VS-09',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 2,
    stem: 'You need to store a product catalog as JSON documents for a web app, using a NoSQL API, while keeping the data available in OneLake. Which Fabric data store fits?',
    sources: [S.decisionStore],
    options: [
      { id: 'a', text: 'A warehouse', explain: 'A warehouse is a relational T-SQL store for analytics, not a NoSQL document database.' },
      { id: 'b', text: 'Cosmos DB in Fabric', explain: 'Correct. Learn recommends Cosmos DB in Fabric for NoSQL databases; its data is available in OneLake.' },
      { id: 'c', text: 'An eventhouse', explain: 'Eventhouses handle semistructured event data for analytics, not a NoSQL application database.' },
      { id: 'd', text: 'A KQL database shortcut', explain: 'A database shortcut shares an existing KQL database; it isn’t an application data store.' },
    ],
    answer: 'b',
  },
  {
    id: 'VS-10',
    machineId: 'vat-selector',
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'stores',
    stem: 'All Fabric data stores make their data available in OneLake in open table format by default, except one, where it is an opt-in setting. Which one?',
    sources: [S.decisionStore],
    options: [
      { id: 'a', text: 'A KQL database in an eventhouse', explain: 'Correct. Learn: for a KQL database in an eventhouse, OneLake availability is an opt-in feature.' },
      { id: 'b', text: 'A warehouse', explain: 'Warehouse data is stored as Delta in OneLake by default.' },
      { id: 'c', text: 'A lakehouse', explain: 'Lakehouse tables are Delta in OneLake by default.' },
      { id: 'd', text: 'A SQL database in Fabric', explain: 'Learn lists SQL database in Fabric as available in OneLake by default.' },
    ],
    answer: 'a',
  },

  // ── Shared Spool (P1.5) ──────────────────────────────────────────────
  {
    id: 'SS-01',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'onelake-availability-vs-integration',
    stem: 'Telemetry lands in a KQL database in an eventhouse. Data engineers want to read the same data from a lakehouse through a shortcut, in Delta format, without building a copy pipeline. What should you do first?',
    sources: [S.eventhouseOneLake],
    options: [
      { id: 'a', text: 'Turn on OneLake integration in the semantic model settings', explain: 'That setting exports semantic model import tables, not KQL database data.' },
      { id: 'b', text: 'Create a mirrored database from the eventhouse', explain: 'Mirroring replicates external operational databases; it isn’t how KQL data is exposed as Delta.' },
      { id: 'c', text: 'Turn on OneLake availability for the KQL database or table', explain: 'Correct. OneLake availability exposes KQL data as Delta in OneLake, which a lakehouse can reach through a shortcut.' },
      { id: 'd', text: 'Add a Copy job from the eventhouse to the lakehouse', explain: 'A Copy job makes a physical copy, which the requirement wants to avoid.' },
    ],
    answer: 'c',
  },
  {
    id: 'SS-02',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'yesno',
    difficulty: 3,
    stem: 'OneLake availability is turned on for a KQL database. For each task, select Yes if you can do it without first turning OneLake availability off. Otherwise, select No.',
    sources: [S.eventhouseOneLake],
    statements: [
      { id: 's1', text: 'Add a new column to a table.', answer: true, explain: 'Yes. Adding or deleting a column is supported while OneLake availability is on.' },
      { id: 's2', text: 'Rename a table.', answer: false, explain: 'No. Renaming tables isn’t allowed while OneLake availability is on.' },
      { id: 's3', text: 'Apply row-level security to a table.', answer: false, explain: 'No. Applying RLS to tables isn’t allowed while OneLake availability is on.' },
    ],
  },
  {
    id: 'SS-03',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'onelake-availability-vs-integration',
    stem: 'You turned on OneLake integration for an import-mode semantic model. A data scientist reports that no Delta tables appear in the model’s OneLake folder. What should you do?',
    sources: [S.modelOneLake],
    options: [
      { id: 'a', text: 'Switch the model’s tables to Direct Lake', explain: 'OneLake integration applies to import tables; switching modes doesn’t trigger the export.' },
      { id: 'b', text: 'Run a manual or scheduled refresh of the semantic model', explain: 'Correct. Import data is written to Delta tables in OneLake only when at least one manual or scheduled refresh runs.' },
      { id: 'c', text: 'Enable large semantic model storage format', explain: 'Large model format affects model size limits, not whether OneLake integration exports data.' },
      { id: 'd', text: 'Turn on OneLake availability for the workspace', explain: 'OneLake availability is an eventhouse setting; it doesn’t trigger a semantic model export.' },
    ],
    answer: 'b',
  },
  {
    id: 'SS-04',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 2,
    stem: 'You want to turn on OneLake integration for an import semantic model so its tables are written to Delta in OneLake. On which kind of workspace is this supported?',
    sources: [S.modelOneLake],
    options: [
      { id: 'a', text: 'A Power BI Pro workspace', explain: 'OneLake integration isn’t supported on Power BI Pro.' },
      { id: 'b', text: 'A Premium Per User (PPU) workspace', explain: 'OneLake integration isn’t supported on Premium Per User.' },
      { id: 'c', text: 'A Power BI Embedded A SKU workspace', explain: 'OneLake integration isn’t supported on Embedded A/EM SKUs.' },
      { id: 'd', text: 'A workspace on a Fabric F SKU capacity', explain: 'Correct. OneLake integration for semantic models is supported on Premium P and Fabric F SKUs only.' },
    ],
    answer: 'd',
  },
  {
    id: 'SS-05',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'order',
    difficulty: 2,
    stem: 'You need lakehouse users to query the tables of an import semantic model through a shortcut. Put the steps in order.',
    sources: [S.modelOneLake],
    items: [
      { id: 'i1', text: 'In Lakehouse explorer, create a Microsoft OneLake shortcut under Tables and select the semantic model’s tables', explain: 'Last: the shortcut points to the exported Delta tables.' },
      { id: 'i2', text: 'Turn on OneLake integration in the semantic model settings', explain: 'First: the model must be configured to export import tables.' },
      { id: 'i3', text: 'Run a manual or scheduled refresh of the semantic model', explain: 'Second: data is written to Delta only during a refresh.' },
    ],
    answerOrder: ['i2', 'i3', 'i1'],
  },
  {
    id: 'SS-06',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 3,
    stem: 'You just turned on OneLake availability for a busy KQL table that receives a trickle of small events. Analysts query the Delta copy a few minutes later and see fewer rows than the KQL table. Why?',
    sources: [S.eventhouseOneLake],
    options: [
      { id: 'a', text: 'The eventhouse batches writes to OneLake and can delay them until it has enough data for well-sized Parquet files', explain: 'Correct. The adaptive behavior can delay writes (by default up to 3 hours) to avoid many small files.' },
      { id: 'b', text: 'The table’s retention policy removed the rows from OneLake only', explain: 'The retention policy applies to both the KQL table and OneLake, so it doesn’t explain a gap between them.' },
      { id: 'c', text: 'OneLake availability copies only the data that was ingested before it was turned on, so newer rows are skipped until the next rebuild', explain: 'It’s the opposite. Learn: turning on availability at the table level makes that table and its data available in OneLake.' },
      { id: 'd', text: 'The SQL analytics endpoint caches results for 24 hours', explain: 'This isn’t the documented reason; the delay comes from the eventhouse’s write batching.' },
    ],
    answer: 'a',
  },
  {
    id: 'SS-07',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'onelake-availability-vs-integration',
    stem: 'You need to temporarily turn off OneLake availability on a KQL database to truncate a table. What happens to the data already in OneLake when you turn it off?',
    sources: [S.eventhouseOneLake],
    options: [
      { id: 'a', text: 'It stays in OneLake but stops updating', explain: 'Learn says turning it off soft deletes the data from OneLake; it doesn’t remain as a frozen copy.' },
      { id: 'b', text: 'It is moved into the lakehouse that has a shortcut to it', explain: 'Data isn’t moved into lakehouses; shortcuts only point to it.' },
      { id: 'c', text: 'It is soft deleted from OneLake', explain: 'Correct. Turning off OneLake availability soft deletes the data from OneLake; turning it back on makes it available again, including historic backfill.' },
      { id: 'd', text: 'It is converted to Parquet files in the Files area', explain: 'This isn’t a documented behavior.' },
    ],
    answer: 'c',
  },
  {
    id: 'SS-08',
    machineId: 'shared-spool',
    bulletIds: ['P1.5'],
    format: 'multi',
    difficulty: 2,
    stem: 'A KQL database has OneLake availability turned on. Which two Fabric engines or features can then read its data in Delta format? Choose two.',
    sources: [S.eventhouseOneLake],
    options: [
      { id: 'a', text: 'Power BI Direct Lake mode', explain: 'Correct. Learn lists Direct Lake mode in Power BI among the engines that can query the Delta data.' },
      { id: 'b', text: 'Spark notebooks', explain: 'Correct. Notebooks are listed among the engines that can query the data.' },
      { id: 'c', text: 'Power BI Desktop live connection to Analysis Services', explain: 'A live connection to Analysis Services doesn’t read OneLake Delta tables.' },
      { id: 'd', text: 'The XMLA endpoint', explain: 'The XMLA endpoint exposes semantic models, not KQL database data in OneLake.' },
    ],
    answers: ['a', 'b'],
  },
]
