import { S } from '../sources'
import type { Question } from '../types'

/** Step 7: difficulty-3 scenario questions for Prepare data. Each combines two or more Learn facts. */

const ti = 'thread-intake'
const bc = 'bale-catalog'
const vs = 'vat-selector'
const rb = 'recipe-book'
const dv = 'dye-vat'
const wp = 'weave-planner'
const tf = 'twisting-frame'
const cm = 'carding-machine'
const ib = 'inspection-bench'
const kt = 'tension-meter'

export const prepareHardQuestions: Question[] = [
  {
    id: 'TI-H1',
    machineId: ti,
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 3,
    stem: 'A Fabric administrator creates a cloud connection to an Azure SQL database under Settings > Manage connections and gateways, and a pipeline’s Copy activity uses it successfully. A data engineer then builds a Dataflow Gen2 against the same database and expects to pick that connection. What should the engineer do?',
    sources: [S.connections],
    options: [
      { id: 'a', text: 'Install an on-premises data gateway so the dataflow can reuse the cloud connection', explain: 'A gateway is for sources behind a firewall or on-premises. The database here is a cloud source, and a gateway doesn’t change which items can use a cloud connection.' },
      { id: 'b', text: 'Create the dataflow’s connection through Power Query Online’s Get data experience', explain: 'Correct. Learn says cloud connections created under Manage connections and gateways currently work with pipelines and Kusto; for dataflows and semantic models, you create connections through Get data.' },
      { id: 'c', text: 'Set a privacy level on the existing connection so dataflows can see it', explain: 'A privacy level controls how data from sources can be combined. It doesn’t make a connection available to other item types.' },
      { id: 'd', text: 'Share the existing connection with the engineer; every connection works in every Fabric item', explain: 'Sharing gives the engineer permission to use the connection, but Learn limits these cloud connections to pipelines and Kusto for now.' },
    ],
    answer: 'b',
  },
  {
    id: 'TI-H2',
    machineId: ti,
    bulletIds: ['P1.3'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'A retailer has two requirements. Product reference files in Azure Data Lake Storage Gen2 must be queryable from a Fabric lakehouse without copying them, always reading the current files at the source. An operational Azure SQL database must be replicated continuously into OneLake as read-only Delta tables for reporting, without anyone building or scheduling a pipeline. Which two features should you use? Choose two.',
    sources: [S.shortcuts, S.mirroring, S.movement],
    options: [
      { id: 'a', text: 'A Copy job with incremental loads for the database', explain: 'A Copy job makes and maintains a physical copy that you configure and run. Learn recommends mirroring when you mainly need data replicated for reporting without building a pipeline.' },
      { id: 'b', text: 'A OneLake shortcut to the ADLS Gen2 folder', explain: 'Correct. A shortcut behaves like a symbolic link: it references the data in place, with no copy.' },
      { id: 'c', text: 'T-SQL COPY INTO from the ADLS Gen2 files into a warehouse', explain: 'COPY INTO loads a copy into a warehouse table, which breaks the "without copying" requirement.' },
      { id: 'd', text: 'Mirroring for the Azure SQL database', explain: 'Correct. Mirroring continuously replicates the database into OneLake as Delta tables, which Learn’s movement guide calls read-only, with no pipeline to build.' },
    ],
    answers: ['b', 'd'],
  },
  {
    id: 'BC-H1',
    machineId: bc,
    bulletIds: ['P1.2'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'catalog-vs-rthub',
    stem: 'A finance analyst must find certified lakehouses in the Finance domain and see who owns each one. On the same day, an IoT team must find out whether a stream fed by Kafka already exists before building a new one. Which approach meets both needs?',
    sources: [S.catalogExplore, S.catalog, S.rtHub],
    options: [
      { id: 'a', text: 'The OneLake catalog’s Govern tab for the analyst, and the Secure tab for the IoT team', explain: 'Govern shows governance insights for data you own, and Secure shows roles. Neither lists data streams.' },
      { id: 'b', text: 'The Real-Time hub for both teams, filtered by domain and by source', explain: 'The Real-Time hub lists data streams, KQL tables, and events, not lakehouses with their endorsement.' },
      { id: 'c', text: 'The OneLake catalog’s Explore tab, filtered by domain and endorsement, for the analyst; the Real-Time hub for the IoT team', explain: 'Correct. Explore filters items by domain, endorsement, and more, and shows owner details. The Real-Time hub is the tenant-wide place to find data streams and their sources.' },
      { id: 'd', text: 'The OneLake catalog’s Explore tab for both teams, filtered by item type', explain: 'The catalog is for data items at rest. Streams and their sources are discovered in the Real-Time hub.' },
    ],
    answer: 'c',
  },
  {
    id: 'BC-H2',
    machineId: bc,
    bulletIds: ['P1.2'],
    format: 'yesno',
    difficulty: 3,
    stem: 'A new analyst is learning how discovery works in Fabric. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.catalogExplore, S.catalog, S.rtHub],
    statements: [
      { id: 's1', text: 'Finding a lakehouse in the OneLake catalog’s Explore tab gives you read access to its data.', answer: false, explain: 'No. The catalog shows items you can access or can request access to. It doesn’t grant access by itself.' },
      { id: 's2', text: 'The OneLake catalog’s Secure tab shows workspace roles and OneLake security roles in one place.', answer: true, explain: 'Yes. Learn lists Secure as the tab that brings workspace roles and OneLake security roles together.' },
      { id: 's3', text: 'A tenant admin must provision the Real-Time hub before anyone can browse streams.', answer: false, explain: 'No. Every tenant gets a Real-Time hub automatically; there is nothing to provision.' },
    ],
  },
  {
    id: 'VS-H1',
    machineId: vs,
    bulletIds: ['P1.4'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'stores',
    stem: 'A data engineering team writes all its transformations in PySpark and stores JSON logs and product images alongside tabular sales data. Report authors only read the curated data with T-SQL. No process needs multi-table transactions. A team lead argues that a warehouse is required because the report authors use T-SQL. Which store should you recommend?',
    sources: [S.decisionStore, S.decisionLhWh, S.endpoint],
    options: [
      { id: 'a', text: 'A warehouse, because the report authors query with T-SQL', explain: 'T-SQL readers don’t require a warehouse. Learn’s scenario picks a lakehouse when developers use PySpark and T-SQL users only consume data through the SQL analytics endpoint.' },
      { id: 'b', text: 'A lakehouse, with the report authors reading through its SQL analytics endpoint', explain: 'Correct. Spark-first development, semi-structured and unstructured files, and no multi-table transactions all point to a lakehouse; its read-only SQL analytics endpoint serves the T-SQL readers.' },
      { id: 'c', text: 'An eventhouse, because the JSON logs are semi-structured', explain: 'An eventhouse is for streaming events and KQL analytics. Semi-structured files alone don’t call for one.' },
      { id: 'd', text: 'A SQL database in Fabric, so report authors get a SQL analytics endpoint', explain: 'SQL database in Fabric is for operational (OLTP) workloads, not a Spark-based analytics team with files.' },
    ],
    answer: 'b',
  },
  {
    id: 'RB-H1',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'endpoint-vs-warehouse',
    stem: 'Curated tables live in a lakehouse. You want a T-SQL stored procedure, run nightly by a pipeline, that reads those tables and writes a monthly summary table. You first try to create it on the lakehouse’s SQL analytics endpoint. What should you do?',
    sources: [S.endpoint, S.tsqlSurface, S.queryWarehouse, S.createProc],
    options: [
      { id: 'a', text: 'Create the procedure on the SQL analytics endpoint; it can insert into lakehouse tables when a pipeline runs it', explain: 'You can create a procedure on the endpoint, but the endpoint is read-only for INSERT, UPDATE, and DELETE, whoever runs it.' },
      { id: 'b', text: 'Create the procedure in a warehouse in the same workspace, read the lakehouse tables with three-part names, and write the summary to a warehouse table', explain: 'Correct. A warehouse supports full DML, and cross-database queries read lakehouse tables in the same workspace by three-part name.' },
      { id: 'c', text: 'Create an inline table-valued function on the endpoint and save its result as a table', explain: 'Functions return results; they can’t write tables on the read-only endpoint.' },
      { id: 'd', text: 'Create a view on the endpoint and grant the pipeline INSERT on the view', explain: 'A view doesn’t store data, and the endpoint still won’t accept INSERT.' },
    ],
    answer: 'b',
  },
  {
    id: 'RB-H2',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'star-vs-snowflake',
    stem: 'A warehouse stores the product dimension as three normalized tables: Product, Subcategory, and Category. A semantic model needs a Category > Subcategory > Product hierarchy, and a regional team must be able to query the product data without being granted access to the base tables. What should you create?',
    sources: [S.dimTables, S.createView, S.whGranular],
    options: [
      { id: 'a', text: 'Three model tables related in a chain, with the hierarchy built across them', explain: 'A model hierarchy can only use columns from one table, so a chain of three tables can’t hold it.' },
      { id: 'b', text: 'A stored procedure that returns the joined rows each time the model refreshes', explain: 'A semantic model reads tables or views, not procedure results, and this doesn’t give the team a secured slice.' },
      { id: 'c', text: 'Primary and foreign key constraints between the tables so the model detects the hierarchy', explain: 'Constraints in a warehouse are NOT ENFORCED metadata. They don’t flatten the dimension or limit what users see.' },
      { id: 'd', text: 'A view that joins the three tables into one denormalized product result, with permissions granted on the view', explain: 'Correct. Learn suggests exposing a snowflake dimension through a view that joins it back into one table, and a view lets users read data through it without permissions on the underlying base tables.' },
    ],
    answer: 'd',
  },
  {
    id: 'DV-H1',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 3,
    stem: 'A GrossRevenue column (unit price × quantity) is needed by Spark notebooks, by analysts using the lakehouse’s SQL analytics endpoint, and by two different semantic models. Each consumer must get the same value. Where should you add the column?',
    sources: [S.loadTables, S.lakehousePrep, S.onelake],
    options: [
      { id: 'a', text: 'As a DAX calculated column in each semantic model', explain: 'A DAX calculated column exists only inside one semantic model. Notebooks and the SQL endpoint wouldn’t see it, and two models could drift apart.' },
      { id: 'b', text: 'In the notebook that writes the Delta table, with withColumn() before the write', explain: 'Correct. A column derived in the ETL is stored once in the table, so every engine that reads OneLake gets the same value.' },
      { id: 'c', text: 'As a measure in each report', explain: 'Report measures live in a report and aren’t visible to notebooks or the SQL endpoint.' },
      { id: 'd', text: 'In a KQL queryset that every consumer runs first', explain: 'A KQL queryset queries KQL databases. It doesn’t add a stored column to lakehouse tables.' },
    ],
    answer: 'b',
  },
  {
    id: 'WP-H1',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'order',
    difficulty: 3,
    trapPairId: 'scd1-vs-scd2',
    stem: 'You are building the nightly load for a warehouse star schema. The customer dimension uses SCD type 2 and has generated surrogate keys. Put the load steps in order.',
    sources: [S.loadTables, S.dimTables],
    items: [
      { id: 'i1', text: 'Load new fact rows, looking up each dimension’s current surrogate key', explain: 'Fourth. Facts are loaded after the dimensions so every lookup finds the current version of the member.' },
      { id: 'i2', text: 'Land the source extracts in a staging schema that business users never see', explain: 'First. Learn recommends staging source data in a separate schema.' },
      { id: 'i3', text: 'Process the customer dimension: expire changed rows and insert new versions', explain: 'Third. Type 2 changes expire the current row and insert a new versioned row with a new surrogate key.' },
      { id: 'i4', text: 'Clean and conform the staged data: types, nulls, and duplicates', explain: 'Second. Fix the data in staging before it reaches the dimensional tables.' },
    ],
    answerOrder: ['i2', 'i4', 'i3', 'i1'],
  },
  {
    id: 'WP-H2',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'multi',
    difficulty: 3,
    stem: 'A warehouse receives normalized source tables for customers, cities, and countries. Analysts and a semantic model need one denormalized customer dimension. Which two approaches meet the need? Choose two.',
    sources: [S.dimTables, S.loadTables, S.tsqlSurface],
    options: [
      { id: 'a', text: 'Load a customer dimension table with CREATE TABLE AS SELECT that joins the three tables', explain: 'Correct. Joining in the ETL (CTAS or INSERT…SELECT) flattens the levels into one dimension table.' },
      { id: 'b', text: 'Add NOT ENFORCED foreign keys from customer to city and country', explain: 'Constraints are metadata only. The data stays normalized across three tables.' },
      { id: 'c', text: 'Create a view that joins the three tables into one result', explain: 'Correct. Learn also suggests a view over normalized tables to present one denormalized dimension.' },
      { id: 'd', text: 'Truncate and reload the three tables every night', explain: 'Reloading doesn’t change the structure, and Learn warns against truncating dimensions with generated surrogate keys.' },
    ],
    answers: ['a', 'c'],
  },
  {
    id: 'WP-H3',
    machineId: wp,
    bulletIds: ['P2.4', 'P2.3'],
    format: 'single',
    difficulty: 3,
    stem: 'A source system deletes discontinued products. The warehouse product dimension uses generated surrogate keys and SCD type 2 history, and years of sales facts reference it. A developer proposes truncating and reloading the dimension nightly from the source so that deleted products disappear. What should you do instead?',
    sources: [S.loadTables, S.dimTables],
    options: [
      { id: 'a', text: 'Keep the rows and record source deletions as soft deletes in a column such as IsDeleted', explain: 'Correct. Learn says never to truncate and reload a dimension with generated surrogate keys, because it breaks fact references and type 2 history; record deletions as soft deletes.' },
      { id: 'b', text: 'Truncate and reload, then rebuild the fact table so the keys line up again', explain: 'Rebuilding facts to match regenerated keys loses the type 2 history and is the full reload Learn calls a last resort.' },
      { id: 'c', text: 'Delete the product rows and their fact rows in one transaction', explain: 'Deleting facts removes real sales history from reports.' },
      { id: 'd', text: 'Convert the dimension to SCD type 3 so deleted products move to a previous-value column', explain: 'Type 3 tracks limited history in extra columns; it isn’t a way to handle deletions, and Learn suggests type 2 over type 3 for semantic models.' },
    ],
    answer: 'a',
  },
  {
    id: 'TF-H1',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 2,
    stem: 'A sales fact table has one row per order line. Most reports only need monthly totals by product and store, and the team wants faster summary queries. Auditors still occasionally look up single orders by sales order number. What should you do?',
    sources: [S.loadTables, S.ingestWarehouse],
    options: [
      { id: 'a', text: 'Replace the fact table with a monthly aggregate grouped by product and store', explain: 'Aggregating raises the grain and loses the order detail for good, which the auditors still need.' },
      { id: 'b', text: 'Drop the sales order number column to reduce the table size', explain: 'That removes exactly the column the auditors use.' },
      { id: 'c', text: 'Keep the detail fact table, and build a separate monthly aggregate table with CREATE TABLE AS SELECT … GROUP BY', explain: 'Correct. A CTAS with GROUP BY materializes the summary for fast reporting while the detail table keeps the grain that order lookups need.' },
      { id: 'd', text: 'Add a calculated column with the monthly total to every order line', explain: 'Repeating totals on every row doesn’t reduce what summary queries scan and duplicates the aggregation logic.' },
    ],
    answer: 'c',
  },
  {
    id: 'TF-H2',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'single',
    difficulty: 3,
    stem: 'A warehouse in the Sales workspace must join its fact table to a customer table that lives in a lakehouse in the CRM workspace. A cross-database query with a three-part name fails. What should you do so the warehouse can join the data without copying it?',
    sources: [S.queryWarehouse, S.shortcuts, S.ingestWarehouse],
    options: [
      { id: 'a', text: 'Use a four-part name that includes the CRM workspace', explain: 'Fabric cross-database queries use three-part names, and they work only within the same workspace.' },
      { id: 'b', text: 'Grant the warehouse’s users the Viewer role on the CRM workspace', explain: 'Permissions don’t remove the same-workspace limit on cross-database queries.' },
      { id: 'c', text: 'Run COPY INTO from the CRM lakehouse’s Tables folder every night', explain: 'COPY INTO makes a copy, which the requirement rules out.' },
      { id: 'd', text: 'Create a OneLake shortcut to the CRM customer table in a lakehouse in the Sales workspace, then join to that lakehouse with a three-part name', explain: 'Correct. A shortcut references the data in place from another workspace, and the warehouse can then join the local lakehouse by three-part name.' },
    ],
    answer: 'd',
  },
  {
    id: 'CM-H1',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'dropdown',
    difficulty: 3,
    trapPairId: 'where-having-qualify',
    stem: 'A staging table holds several versions of each customer, and some rows have a NULL region. Load one row per CustomerID (the most recently modified version) and show missing regions as Unknown. Complete the T-SQL.',
    sources: [S.qualify, S.coalesce],
    language: 'tsql',
    code: "SELECT CustomerID,\n       [[1]](Region, 'Unknown') AS Region,\n       ModifiedAt\nFROM staging.Customer\n[[2]] ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY ModifiedAt [[3]]) = 1;",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'TRY_CAST', explain: 'TRY_CAST converts one value to a data type; it doesn’t replace NULL with a default.' },
          { id: 'b', text: 'COALESCE', explain: 'Correct. COALESCE returns the first non-NULL argument, so a NULL region becomes Unknown.' },
          { id: 'c', text: 'CONCAT', explain: 'CONCAT joins strings, so it would append Unknown to every region, not replace only the NULL ones.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'QUALIFY', explain: 'Correct. QUALIFY filters after window functions are evaluated, so it can keep row number 1 without a subquery.' },
          { id: 'b', text: 'WHERE', explain: 'WHERE runs before window functions, so it can’t reference ROW_NUMBER().' },
          { id: 'c', text: 'HAVING', explain: 'HAVING filters groups after GROUP BY; there is no GROUP BY here, and it runs before window functions.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'ASC', explain: 'Ascending would number the oldest version 1 and keep it.' },
          { id: 'b', text: 'DESC', explain: 'Correct. Descending order numbers the most recently modified version 1.' },
          { id: 'c', text: 'NULLS LAST', explain: 'NULLS LAST only controls where NULLs sort; it doesn’t make the newest version row number 1, which needs DESC.' },
        ],
        answer: 'b',
      },
    ],
  },
  {
    id: 'CM-H2',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'yesno',
    difficulty: 3,
    stem: 'You are cleaning sales data before loading a warehouse star schema. Some fact rows reference customers that aren’t in the customer dimension, and the source has duplicate rows. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.qualify, S.dimTables, S.loadTables, S.dataWrangler],
    statements: [
      { id: 's1', text: 'Mapping fact rows whose customer lookup fails to an Unknown member keeps them in the fact table with a valid key.', answer: true, explain: 'Yes. Learn recommends special members such as Unknown so a failed lookup still gets a valid dimension key.' },
      { id: 's2', text: 'WHERE ROW_NUMBER() OVER (PARTITION BY OrderID ORDER BY LoadedAt DESC) = 1 removes the duplicates in one SELECT.', answer: false, explain: 'No. WHERE runs before window functions, so it can’t reference ROW_NUMBER(). Use QUALIFY, a CTE, or a subquery.' },
      { id: 's3', text: 'In a notebook, Data Wrangler’s Drop duplicate rows operation generates code you can export back to the notebook.', answer: true, explain: 'Yes. Data Wrangler operations generate pandas or PySpark code that you can export to the notebook.' },
    ],
  },
  {
    id: 'CM-H3',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 3,
    stem: 'You are recreating a SQL Server table in a Fabric warehouse. The source columns are Amount money, CreatedAt datetime, Notes nvarchar(200), and Priority tinyint. Which column definitions follow Learn’s guidance for warehouse tables?',
    sources: [S.dataTypes],
    options: [
      { id: 'a', text: 'Amount decimal(19,4), CreatedAt datetime2(6), Notes varchar(200), Priority smallint', explain: 'Correct. Learn maps money to decimal, datetime to datetime2 (up to 6 fractional digits), nvarchar to varchar, and tinyint to smallint.' },
      { id: 'b', text: 'Amount money, CreatedAt datetime2(6), Notes varchar(200), Priority smallint', explain: 'money isn’t supported in warehouse tables; use decimal.' },
      { id: 'c', text: 'Amount decimal(19,4), CreatedAt datetime, Notes varchar(200), Priority smallint', explain: 'datetime isn’t supported in warehouse tables; use datetime2.' },
      { id: 'd', text: 'Amount decimal(19,4), CreatedAt datetime2(7), Notes nvarchar(200), Priority tinyint', explain: 'nvarchar and tinyint aren’t supported, and datetime2 is limited to 6 fractional-second digits.' },
    ],
    answer: 'a',
  },
  {
    id: 'CM-H4',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'match',
    difficulty: 3,
    trapPairId: 'where-having-qualify',
    stem: 'A warehouse query must apply three filters. Match each filter to the T-SQL clause that applies it at the right point in query processing.',
    sources: [S.qualify, S.groupBy],
    prompts: [
      { id: 'p1', text: 'Keep only orders placed in 2026, before anything is grouped' },
      { id: 'p2', text: 'Keep only customers whose order count is above 5 after GROUP BY' },
      { id: 'p3', text: 'Keep each customer’s newest row after ROW_NUMBER() is calculated' },
    ],
    choices: [
      { id: 'c1', text: 'WHERE' },
      { id: 'c2', text: 'HAVING' },
      { id: 'c3', text: 'QUALIFY' },
      { id: 'c4', text: 'ORDER BY' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'WHERE filters individual rows before grouping and window functions.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'HAVING filters grouped results after GROUP BY.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'QUALIFY filters after window functions are evaluated. ORDER BY (unused) only sorts and filters nothing.' },
    ],
  },
  {
    id: 'IB-H1',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 3,
    trapPairId: 'visual-vs-sql-editor',
    stem: 'An analyst who doesn’t write SQL builds a visual query that merges two warehouse tables and groups the result. She must save the result as a new table, and later a colleague wants to tweak the logic in T-SQL. Which approach meets both needs?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'Add a DDL step to the visual query that inserts the result into a table', explain: 'The visual query editor runs read-only SELECT queries; it can’t run DDL or DML steps.' },
      { id: 'b', text: 'Visualize the results with an ORDER BY step, then export the chart data', explain: 'Visualize results doesn’t support queries with ORDER BY, and exporting a chart doesn’t create a table.' },
      { id: 'c', text: 'Save the visual query as a view, then insert from the view in the visual editor', explain: 'A view stores no data, and the visual editor can’t run INSERT.' },
      { id: 'd', text: 'Use Save as table, and give the colleague the T-SQL from View SQL to open in the SQL editor', explain: 'Correct. Save as table creates the table with CREATE TABLE AS SELECT, and View SQL shows the generated T-SQL that can be opened in the SQL editor.' },
    ],
    answer: 'd',
  },
  {
    id: 'IB-H2',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 3,
    stem: 'In the Sales workspace, a warehouse named SalesWH holds dbo.FactSales, and a lakehouse named RefLake holds dbo.Store. In SalesWH’s SQL query editor you must return total sales per store name. Which query works?',
    sources: [S.queryWarehouse, S.groupBy],
    options: [
      { id: 'a', text: 'SELECT s.StoreName, SUM(f.Amount) AS Sales FROM dbo.FactSales AS f JOIN dbo.Store AS s ON f.StoreKey = s.StoreKey GROUP BY s.StoreName;', explain: 'dbo.Store without an item name refers to SalesWH, which has no Store table.' },
      { id: 'b', text: 'SELECT s.StoreName, SUM(f.Amount) AS Sales FROM dbo.FactSales AS f JOIN RefLake.dbo.Store AS s ON f.StoreKey = s.StoreKey GROUP BY s.StoreName;', explain: 'Correct. A three-part name (item.schema.table) reads the lakehouse table in the same workspace, and GROUP BY returns one row per store.' },
      { id: 'c', text: 'SELECT s.StoreName, SUM(f.Amount) AS Sales FROM dbo.FactSales AS f JOIN Sales.RefLake.dbo.Store AS s ON f.StoreKey = s.StoreKey GROUP BY s.StoreName;', explain: 'Fabric cross-database queries use three-part names; a workspace prefix isn’t part of the syntax.' },
      { id: 'd', text: 'SELECT s.StoreName, SUM(f.Amount) AS Sales FROM dbo.FactSales AS f JOIN RefLake.dbo.Store AS s ON f.StoreKey = s.StoreKey;', explain: 'Without GROUP BY, a query that mixes StoreName with SUM() fails.' },
    ],
    answer: 'b',
  },
  {
    id: 'KT-H1',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'dropdown',
    difficulty: 2,
    trapPairId: 'project-vs-extend',
    stem: 'In a KQL queryset you need the number of error events per hour over the last day, busiest hour first. Complete the query.',
    sources: [S.kqlSummarize, S.kqlBin, S.kqlSort],
    language: 'kql',
    code: 'AppEvents\n| where Timestamp > ago(1d)\n| [[1]] Errors = countif(Level == "Error") by [[2]](Timestamp, 1h)\n| [[3]] Errors desc',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'extend', explain: 'extend adds a column to every row; it doesn’t group rows or support by.' },
          { id: 'b', text: 'summarize', explain: 'Correct. summarize groups rows by the by expressions and computes the aggregation for each group.' },
          { id: 'c', text: 'project', explain: 'project chooses or computes columns per row; it doesn’t aggregate.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'bin', explain: 'Correct. bin() rounds each timestamp down to a 1-hour range, which you must state explicitly in summarize.' },
          { id: 'b', text: 'ago', explain: 'ago() returns a point in time relative to now; it doesn’t group values into ranges.' },
          { id: 'c', text: 'count', explain: 'count is an aggregation, not a grouping expression.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'take', explain: 'take returns arbitrary rows; it doesn’t sort.' },
          { id: 'b', text: 'distinct', explain: 'distinct removes duplicate rows; it doesn’t order them.' },
          { id: 'c', text: 'sort by', explain: 'Correct. sort by orders the rows; desc puts the busiest hour first.' },
        ],
        answer: 'c',
      },
    ],
  },
]
