import { S } from '../sources'
import type { Question } from '../types'

const kt = 'tension-meter'
const ds = 'dax-scale'

export const kqlDaxQuestions: Question[] = [
  // ── Kusto Tension Meter: P3.3 KQL ───────────────────────────────────
  {
    id: 'KT-01',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'sql-vs-kql',
    stem: 'You are querying the StormEvents table in a KQL database. You need to keep only the rows where State is TEXAS. Which line should follow the table name?',
    sources: [S.kqlWhere, S.sqlToKql],
    options: [
      { id: 'a', text: "WHERE State = 'TEXAS'", explain: 'This is SQL syntax. KQL pipes the table into the where operator and uses == for equality.' },
      { id: 'b', text: "| where State == 'TEXAS'", explain: 'Correct. where filters rows on a predicate, and == is equality in KQL.' },
      { id: 'c', text: "| extend State == 'TEXAS'", explain: 'extend adds a calculated column; it doesn’t remove rows.' },
      { id: 'd', text: "| project State == 'TEXAS'", explain: 'project chooses or computes columns; it doesn’t filter rows.' },
    ],
    answer: 'b',
  },
  {
    id: 'KT-02',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'dropdown',
    difficulty: 2,
    stem: 'You need the number of Texas storm events per hour, oldest hour first, from a KQL database. Complete the KQL query.',
    sources: [S.kqlSummarize, S.kqlBin, S.kqlSort],
    language: 'kql',
    code: "StormEvents\n| where State == 'TEXAS'\n| [[1]] EventCount = count() by [[2]](StartTime, 1h)\n| [[3]] by StartTime asc",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'extend', explain: 'extend adds a column to every row; it doesn’t group rows or aggregate.' },
          { id: 'b', text: 'summarize', explain: 'Correct. summarize groups rows by the by expressions and computes count() per group.' },
          { id: 'c', text: 'project', explain: 'project chooses columns; it can’t group by.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'bin', explain: 'Correct. bin(StartTime, 1h) rounds each time down to its hour bucket.' },
          { id: 'b', text: 'ago', explain: 'ago() returns a time relative to now; it doesn’t bucket values.' },
          { id: 'c', text: 'between', explain: 'between tests whether a value falls in a range inside a where filter.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'top', explain: 'top needs a row count, such as top 10 by StartTime.' },
          { id: 'b', text: 'take', explain: 'take returns arbitrary rows and doesn’t accept by.' },
          { id: 'c', text: 'sort', explain: 'Correct. sort by StartTime asc orders the buckets oldest first.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'KT-03',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'project-vs-extend',
    stem: 'You need to add a Duration column (EndTime minus StartTime) to the StormEvents results while keeping every existing column. Which KQL line should you use?',
    sources: [S.kqlExtend, S.kqlOperators],
    options: [
      { id: 'a', text: '| project Duration = EndTime - StartTime', explain: 'project returns only the columns listed, so every other column would be dropped.' },
      { id: 'b', text: '| summarize Duration = EndTime - StartTime', explain: 'summarize needs an aggregation function and changes the grain.' },
      { id: 'c', text: '| extend Duration = EndTime - StartTime', explain: 'Correct. extend appends the calculated column and keeps all existing columns.' },
      { id: 'd', text: '| where Duration = EndTime - StartTime', explain: 'where filters rows on a condition; it can’t define a column.' },
    ],
    answer: 'c',
  },
  {
    id: 'KT-04',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 2,
    stem: 'You need the five storm events with the highest DamageProperty from a KQL table. Which query returns them?',
    sources: [S.kqlTop, S.kqlTake],
    options: [
      { id: 'a', text: 'StormEvents | take 5 | sort by DamageProperty', explain: 'take picks 5 arbitrary rows first, then sorts only those five.' },
      { id: 'b', text: 'StormEvents | top 5 by DamageProperty', explain: 'Correct. top returns the first 5 rows by DamageProperty, descending by default.' },
      { id: 'c', text: 'StormEvents | sort by DamageProperty asc | take 5', explain: 'Sorting ascending puts the lowest damage first, so this returns the smallest five.' },
      { id: 'd', text: 'StormEvents | where DamageProperty > 5', explain: 'This keeps every row with damage above 5, not the top five rows.' },
    ],
    answer: 'b',
  },
  {
    id: 'KT-05',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'sql-vs-kql',
    stem: 'A SQL developer writes StormEvents | sort by StartTime in a KQL queryset and expects the oldest events first. What does the query return?',
    sources: [S.kqlOperators, S.kqlSort],
    options: [
      { id: 'a', text: 'The oldest events first, like ORDER BY in SQL', explain: 'Unlike SQL ORDER BY, KQL sort defaults to descending.' },
      { id: 'b', text: 'An error, because sort needs asc or desc', explain: 'The direction is optional; the query runs with the default.' },
      { id: 'c', text: 'Rows in arbitrary order, because sort needs a top', explain: 'sort works on its own and orders every row.' },
      { id: 'd', text: 'The newest events first', explain: 'Correct. The default sort order is descending; add asc for oldest first.' },
    ],
    answer: 'd',
  },
  {
    id: 'KT-06',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 3,
    stem: 'A KQL query joins Orders to Shipments on OrderId with | join Shipments on OrderId and no kind. Orders has several rows per OrderId, and the result has fewer rows than expected. What explains this, and what should you change?',
    sources: [S.kqlJoin],
    options: [
      { id: 'a', text: 'The default flavor is innerunique, which de-duplicates the left side’s keys; specify kind=inner', explain: 'Correct. Learn: the default join is innerunique (inner join with left-side deduplication). kind=inner keeps every matching row.' },
      { id: 'b', text: 'The default flavor is leftanti, which keeps only the left rows without a match; specify kind=leftouter', explain: 'leftanti isn’t the default; Learn names innerunique as the default.' },
      { id: 'c', text: 'Joins need a summarize before them; add summarize by OrderId', explain: 'Summarizing first would reduce the left rows even more.' },
      { id: 'd', text: 'KQL joins only on datetime columns; convert OrderId with todatetime()', explain: 'KQL joins on any matching columns; there’s no datetime requirement.' },
    ],
    answer: 'a',
  },
  {
    id: 'KT-07',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 2,
    stem: 'You join a small DeviceInfo table (500 rows) to a large Telemetry table (2 billion rows) in KQL. You want the best join performance. How should you write the join?',
    sources: [S.kqlJoin],
    options: [
      { id: 'a', text: 'Put Telemetry on the left and DeviceInfo on the right', explain: 'Learn recommends the opposite: the smaller table on the left.' },
      { id: 'b', text: 'Put DeviceInfo on the left side of the join', explain: 'Correct. Learn: if one table is always smaller, use it as the left side of the join.' },
      { id: 'c', text: 'Run take 500 on Telemetry before the join', explain: 'take returns arbitrary rows, which would silently lose data.' },
      { id: 'd', text: 'Use kind=fullouter so both sides are scanned once', explain: 'Changing the flavor changes the results; it isn’t a performance setting.' },
    ],
    answer: 'b',
  },
  {
    id: 'KT-08',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'match',
    difficulty: 1,
    trapPairId: 'sql-vs-kql',
    stem: 'A SQL developer is moving to KQL. Match each SQL construct to its KQL equivalent.',
    sources: [S.sqlToKql],
    prompts: [
      { id: 'p1', text: 'SELECT name, type' },
      { id: 'p2', text: 'WHERE type = \'blob\'' },
      { id: 'p3', text: 'GROUP BY name with COUNT(*)' },
      { id: 'p4', text: 'SELECT TOP 100 … ORDER BY Count DESC' },
    ],
    choices: [
      { id: 'c1', text: '| project name, type' },
      { id: 'c2', text: '| where type == "blob"' },
      { id: 'c3', text: '| summarize count() by name' },
      { id: 'c4', text: '| top 100 by Count desc' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'project chooses the output columns, like a SELECT list.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'where filters rows; KQL uses == for equality.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'summarize combines the aggregation and the grouping in one operator.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'top n by replaces SELECT TOP with ORDER BY.' },
    ],
  },
  {
    id: 'KT-09',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'sql-vs-kql',
    stem: 'You know SQL well and want a KQL queryset to show you the KQL equivalent of a SQL query you wrote. What should you do?',
    sources: [S.sqlToKql],
    options: [
      { id: 'a', text: 'Run the SQL query in the warehouse SQL query editor and select View SQL', explain: 'View SQL belongs to the visual query editor and shows SQL, not KQL.' },
      { id: 'b', text: 'Wrap the SQL query in a summarize operator', explain: 'summarize is a KQL operator; it can’t contain a SQL query.' },
      { id: 'c', text: 'Put a comment line (--) and the keyword explain before the SQL query', explain: 'Correct. Learn: preface the SQL query with a comment line and explain, and the output shows the KQL version.' },
      { id: 'd', text: 'Open the query in DAX query view', explain: 'DAX query view runs DAX against semantic models.' },
    ],
    answer: 'c',
  },
  {
    id: 'KT-10',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are reviewing KQL queries written by a new team member. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.kqlTake, S.kqlSummarize, S.kqlOperators],
    statements: [
      { id: 's1', text: 'take 10 returns up to ten rows with no guarantee which rows are returned.', answer: true, explain: 'Yes. take returns up to the specified number of rows with no guarantee which ones; it suits a quick look at the data.' },
      { id: 's2', text: 'Aggregation functions such as sum() and avg() in summarize ignore null values.', answer: true, explain: 'Yes. Learn: null values are ignored by these aggregates (the standard count() is the exception and includes nulls).' },
      { id: 's3', text: 'summarize count() by StartTime automatically groups a datetime column into hourly bins.', answer: false, explain: 'No. Automatic hourly bins are no longer supported; use bin(StartTime, 1h) explicitly.' },
    ],
  },
  {
    id: 'KT-11',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'order',
    difficulty: 2,
    stem: 'You need flood events counted per 30-day bucket, oldest bucket first. Put the lines of the KQL query in order.',
    sources: [S.kqlOperators, S.kqlSummarize],
    items: [
      { id: 'i3', text: '| summarize Events = count() by bin(StartTime, 30d)', explain: 'Third. Aggregate the filtered rows into 30-day buckets. After this, EventType no longer exists, so the filter must come first.' },
      { id: 'i4', text: '| sort by StartTime asc', explain: 'Last. Sort the buckets oldest first; sort defaults to descending without asc.' },
      { id: 'i1', text: 'StormEvents', explain: 'First. A KQL query starts from the table and pipes it through operators.' },
      { id: 'i2', text: "| where EventType == 'Flood'", explain: 'Second. Filter to flood events while the EventType column still exists.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'KT-12',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'multi',
    difficulty: 3,
    trapPairId: 'sql-vs-kql',
    stem: 'For each name in the dependencies table, you need the number of distinct type values. A fast estimate is acceptable. Which two KQL queries meet the goal? Choose two.',
    sources: [S.sqlToKql, S.kqlDcount],
    options: [
      { id: 'a', text: 'dependencies | summarize count() by name, type', explain: 'This counts rows per name and type pair, not distinct types per name.' },
      { id: 'b', text: 'dependencies | summarize dcount(type) by name', explain: 'Correct. dcount() returns an estimate of the distinct values per group, which the stem allows; Learn’s cheat sheet maps COUNT(DISTINCT) to it.' },
      { id: 'c', text: 'dependencies | summarize by name, type | summarize count() by name', explain: 'Correct. The first summarize leaves one row per name and type; the second counts them per name, giving an exact count.' },
      { id: 'd', text: 'dependencies | distinct name | count', explain: 'This returns the number of distinct names, a single value.' },
    ],
    answers: ['b', 'c'],
  },
  {
    id: 'KT-13',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 1,
    stem: 'You need the storm events that started between 00:00:00 on August 1, 2007, and 23:59:59 on August 30, 2007. Which KQL filter should you use?',
    sources: [S.kqlWhere, S.kqlOperators],
    options: [
      { id: 'a', text: '| where StartTime > ago(30d)', explain: 'ago() is relative to now, so this returns the last 30 days, not August 2007.' },
      { id: 'b', text: '| summarize by bin(StartTime, 30d)', explain: 'This groups rows into buckets; it doesn’t filter a date range.' },
      { id: 'c', text: '| where StartTime in (datetime(2007-08-01 00:00:00), datetime(2007-08-30 00:00:00))', explain: 'in keeps only rows equal to one of the listed values, so this matches just those two exact instants.' },
      { id: 'd', text: '| where StartTime between (datetime(2007-08-01 00:00:00) .. datetime(2007-08-30 23:59:59))', explain: 'Correct. between filters on an inclusive range of values.' },
    ],
    answer: 'd',
  },
  {
    id: 'KT-14',
    machineId: kt,
    bulletIds: ['P3.3'],
    format: 'single',
    difficulty: 1,
    stem: 'Your team needs a Fabric item in which to write, save, and run KQL queries against a KQL database in an eventhouse. What should you create?',
    sources: [S.kqlQueryset],
    options: [
      { id: 'a', text: 'A KQL queryset', explain: 'Correct. A KQL queryset is where you write, save, and run KQL queries against KQL databases.' },
      { id: 'b', text: 'A SQL query in a warehouse', explain: 'The warehouse SQL editor runs T-SQL against warehouses and endpoints.' },
      { id: 'c', text: 'A DAX query in DAX query view', explain: 'DAX query view runs DAX against semantic models.' },
      { id: 'd', text: 'A Data Wrangler session in a notebook', explain: 'Data Wrangler cleans pandas or Spark DataFrames in notebooks.' },
    ],
    answer: 'a',
  },

  // ── DAX Scale: P3.4 DAX queries ─────────────────────────────────────
  {
    id: 'DS-01',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You are writing your first DAX query in DAX query view to inspect a semantic model table. Which keyword must every DAX query contain?',
    sources: [S.daxQueries],
    options: [
      { id: 'a', text: 'DEFINE', explain: 'DEFINE is optional; it adds query-scoped definitions.' },
      { id: 'b', text: 'ORDER BY', explain: 'ORDER BY is optional; it sorts the result.' },
      { id: 'c', text: 'EVALUATE', explain: 'Correct. EVALUATE followed by a table expression is the one required keyword.' },
      { id: 'd', text: 'START AT', explain: 'START AT is optional and only used inside ORDER BY.' },
    ],
    answer: 'c',
  },
  {
    id: 'DS-02',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    trapPairId: 'query-measure-vs-model-measure',
    stem: 'You need to test a new measure against a semantic model without changing the model, returning orders by month in calendar order. Complete the DAX query.',
    sources: [S.daxQueries],
    language: 'dax',
    code: "[[1]]\n  MEASURE Sales[Avg Profit per Order] = DIVIDE([Total Sales Profit], [Orders])\n[[2]]\nSUMMARIZECOLUMNS(\n  'Date'[Month Name], 'Date'[Month of Year],\n  \"Avg Profit per Order\", [Avg Profit per Order]\n)\n[[3]] 'Date'[Month of Year] ASC",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'DEFINE', explain: 'Correct. DEFINE introduces query-scoped definitions such as MEASURE.' },
          { id: 'b', text: 'VAR', explain: 'VAR defines a variable inside DEFINE or an expression; it can’t introduce a MEASURE.' },
          { id: 'c', text: 'CALCULATE', explain: 'CALCULATE is a function that modifies filter context, not a query keyword.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'RETURN', explain: 'RETURN ends a VAR block in an expression; queries use EVALUATE.' },
          { id: 'b', text: 'EVALUATE', explain: 'Correct. EVALUATE runs the table expression and returns its result.' },
          { id: 'c', text: 'SELECT', explain: 'SELECT is SQL; DAX queries use EVALUATE.' },
        ],
        answer: 'b',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'START AT', explain: 'START AT sets where results begin and must be used inside ORDER BY.' },
          { id: 'b', text: 'SORT BY', explain: 'SORT BY isn’t a DAX query keyword.' },
          { id: 'c', text: 'ORDER BY', explain: 'Correct. ORDER BY sorts the query result by Month of Year.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'DS-03',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In DAX query view, you want to see the value of the [Total Sales] measure for the whole model as a one-cell result. Which query should you run?',
    sources: [S.daxQueries],
    options: [
      { id: 'a', text: 'EVALUATE [Total Sales]', explain: 'EVALUATE needs a table expression; a measure returns a scalar.' },
      { id: 'b', text: 'EVALUATE {[Total Sales]}', explain: 'Correct. Curly braces make a table constructor, so the scalar is shown as a result table.' },
      { id: 'c', text: 'DEFINE [Total Sales]', explain: 'DEFINE holds definitions and must be followed by EVALUATE; it doesn’t return results itself.' },
      { id: 'd', text: 'SELECT [Total Sales]', explain: 'SELECT is SQL syntax, not DAX.' },
    ],
    answer: 'b',
  },
  {
    id: 'DS-04',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In the semantic model, Month Name is sorted by Month of Year. Your DAX query groups by Month Name, and the result lists April, August, December. You need calendar order. What should you do?',
    sources: [S.daxQueries],
    options: [
      { id: 'a', text: 'Set the Sort by column property on Month Name again', explain: 'Sort by column settings don’t apply to DAX query results, so this changes nothing.' },
      { id: 'b', text: 'Add ORDER BY \'Date\'[Month Name] ASC to the end of the query', explain: 'Sorting by the name itself is still alphabetical.' },
      { id: 'c', text: 'Wrap the query in TOPN with 12 rows', explain: 'TOPN limits rows; it doesn’t produce calendar order.' },
      { id: 'd', text: 'Include \'Date\'[Month of Year] in the query and ORDER BY it', explain: 'Correct. Learn: the sort-by column must be included in the DAX query and used in ORDER BY.' },
    ],
    answer: 'd',
  },
  {
    id: 'DS-05',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'query-measure-vs-model-measure',
    stem: 'A model already has a measure named [Margin]. In DAX query view, you write DEFINE MEASURE Sales[Margin] with a different formula and run the query. What happens?',
    sources: [S.daxQueries, S.daxQueryView],
    options: [
      { id: 'a', text: 'The query uses your formula and the model measure is unchanged', explain: 'Correct. DEFINE MEASURE is query-scoped: the query uses its formula, and the model changes only if you choose Update model.' },
      { id: 'b', text: 'The model measure is overwritten with your formula as soon as the query runs', explain: 'Running the query doesn’t change the model; CodeLens or Update model with changes does.' },
      { id: 'c', text: 'The query fails because the name already exists', explain: 'Overriding an existing measure for testing is a documented scenario.' },
      { id: 'd', text: 'The query ignores your formula and uses the model measure', explain: 'When the measure exists, the query uses the formula defined in the query.' },
    ],
    answer: 'a',
  },
  {
    id: 'DS-06',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'query-measure-vs-model-measure',
    stem: 'You tested three new measures in a DEFINE block in DAX query view and want to add all of them to the semantic model at once. What should you use?',
    sources: [S.daxQueryView],
    options: [
      { id: 'a', text: 'The Update model with changes button', explain: 'Correct. It adds or overwrites model measures with all the query-scoped measures in the DEFINE block.' },
      { id: 'b', text: 'Performance Analyzer’s Copy query action', explain: 'Copy query copies the DAX a visual sent; it doesn’t add measures.' },
      { id: 'c', text: 'A new EVALUATE statement for each measure', explain: 'More EVALUATE statements return more results but never change the model.' },
      { id: 'd', text: 'Save the query in the My queries folder', explain: 'Saving the query keeps the text; the measures stay query-scoped.' },
    ],
    answer: 'a',
  },
  {
    id: 'DS-07',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You work on a Mac and can’t run Power BI Desktop. You need to run DAX queries against a published semantic model from the browser. What should you do?',
    sources: [S.daxQueryView],
    options: [
      { id: 'a', text: 'Open the lakehouse SQL analytics endpoint and write the query in T-SQL instead of DAX', explain: 'The endpoint runs T-SQL against lakehouse tables, not DAX against a semantic model.' },
      { id: 'b', text: 'Open a KQL queryset and paste the DAX', explain: 'KQL querysets run KQL, not DAX.' },
      { id: 'c', text: 'Select Write DAX queries for the model in the workspace or on its details page', explain: 'Correct. Learn: in the Power BI service or Fabric portal, select Write DAX queries from the context menu or the details page.' },
      { id: 'd', text: 'Create a visual query in the warehouse editor', explain: 'The visual query editor builds SQL queries against warehouses and endpoints.' },
    ],
    answer: 'c',
  },
  {
    id: 'DS-08',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: "You run EVALUATE TOPN(5, 'Product', [Total Sales], DESC) ORDER BY 'Product'[Product Name] ASC. What does the query return?",
    sources: [S.daxQueries],
    options: [
      { id: 'a', text: 'The first five products alphabetically by name', explain: 'ORDER BY doesn’t choose TOPN’s rows; TOPN ranks by its own argument.' },
      { id: 'b', text: 'The five best-selling products, sorted by Total Sales descending', explain: 'TOPN picks the best sellers, but ORDER BY then sorts them by name.' },
      { id: 'c', text: 'An error, because ORDER BY must match TOPN’s order', explain: 'The query is valid; the two orders are independent.' },
      { id: 'd', text: 'The five best-selling products, sorted by product name', explain: 'Correct. TOPN picks rows by [Total Sales]; ORDER BY only sorts the rows TOPN returned.' },
    ],
    answer: 'd',
  },
  {
    id: 'DS-09',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are writing a DAX query script for a semantic model. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.daxQueries],
    statements: [
      { id: 's1', text: 'A DAX query can contain several EVALUATE statements.', answer: true, explain: 'Yes. Learn contrasts EVALUATE, which can repeat, with DEFINE, which can appear only once.' },
      { id: 's2', text: 'Each EVALUATE statement can have its own DEFINE block placed right before it.', answer: false, explain: 'No. There can be only one DEFINE block; it must come before the first EVALUATE and applies to all of them.' },
      { id: 's3', text: 'Definitions in a DEFINE block exist only for the duration of the query.', answer: true, explain: 'Yes. DEFINE introduces calculated entities that exist only while the query runs.' },
    ],
  },
  {
    id: 'DS-10',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You are writing a SUMMARIZECOLUMNS query that groups by month, keeps only the Clothing category with FILTER(VALUES(\'Product\'[Category]), [Category] = "Clothing"), and returns an "Orders" column. Where does the FILTER argument go?',
    sources: [S.summarizeColumns, S.daxQueries],
    options: [
      { id: 'a', text: 'After the group-by columns and before the "Orders", [Orders] pair', explain: 'Correct. The syntax is group-by columns, then filter tables, then name/expression pairs.' },
      { id: 'b', text: 'After the "Orders", [Orders] pair, as the last argument of SUMMARIZECOLUMNS', explain: 'Name/expression pairs come last; a filter table can’t follow them.' },
      { id: 'c', text: 'Before the group-by columns, as the first argument', explain: 'Group-by columns come first in SUMMARIZECOLUMNS.' },
      { id: 'd', text: 'In the ORDER BY clause after EVALUATE', explain: 'ORDER BY sorts results; it doesn’t filter them.' },
    ],
    answer: 'a',
  },
  {
    id: 'DS-11',
    machineId: ds,
    bulletIds: ['P3.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A data engineer needs to run a DAX query against a semantic model from a Fabric notebook and work with the result in Python. What should they use?',
    sources: [S.daxQueries],
    options: [
      { id: 'a', text: 'Data Wrangler', explain: 'Data Wrangler cleans DataFrames; it doesn’t query semantic models.' },
      { id: 'b', text: 'A Spark SQL cell against the model', explain: 'Spark SQL queries lakehouse tables, not semantic models.' },
      { id: 'c', text: 'The lakehouse SQL analytics endpoint', explain: 'The endpoint runs T-SQL over lakehouse tables.' },
      { id: 'd', text: 'Semantic link', explain: 'Correct. Learn: DAX queries can run in Fabric notebooks using semantic link to read semantic model data with Python.' },
    ],
    answer: 'd',
  },
]
