import { S } from '../sources'
import type { Question } from '../types'

const ib = 'inspection-bench'
const rb = 'recipe-book'

export const queryQuestions: Question[] = [
  // ── Inspection Bench: P3.1 visual query editor ──────────────────────
  {
    id: 'IB-01',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'visual-vs-sql-editor',
    stem: 'An analyst built a visual query on a Fabric warehouse that finds test orders. They now want the same editor to delete those rows from the table. What should you tell them?',
    sources: [S.visualQuery, S.queryWarehouse],
    options: [
      { id: 'a', text: 'Add a Remove rows step to the visual query, then select Save as table', explain: 'Save as table creates a new table with CTAS; it doesn’t delete rows from the source table.' },
      { id: 'b', text: 'Write the DELETE in the SQL query editor instead', explain: 'Correct. The visual query editor runs only read-only SELECT queries. Learn: the visual query editor supports only DQL (read-only SELECT); DDL and DML aren’t supported.' },
      { id: 'c', text: 'Select View SQL and run the generated script', explain: 'View SQL shows the SELECT generated from the steps; it doesn’t produce a DELETE.' },
      { id: 'd', text: 'Enable load on the query, then refresh it', explain: 'Enable load picks which query appears in the SQL script; it doesn’t change data.' },
    ],
    answer: 'b',
  },
  {
    id: 'IB-02',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 1,
    stem: 'You built a visual query on a warehouse that filters and groups sales. A colleague wants to see the T-SQL that your steps produce so they can learn from it. Which feature should you use?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'Visualize results', explain: 'Visualize results creates a report on the results; it doesn’t show the SQL.' },
      { id: 'b', text: 'Download Excel file', explain: 'This exports the results to Excel, not the query text.' },
      { id: 'c', text: 'View SQL', explain: 'Correct. View SQL shows the SQL query based on the applied steps of the visual query.' },
      { id: 'd', text: 'Save as table', explain: 'Save as table writes the results into a table; it isn’t a way to read the SQL.' },
    ],
    answer: 'c',
  },
  {
    id: 'IB-03',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 2,
    stem: 'You need to persist the results of a visual query as a new table in a Fabric warehouse by using Save as table. Which T-SQL statement does the feature use to load the results?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'CREATE TABLE AS SELECT', explain: 'Correct. Learn: Save as table loads the results into a table by using a CREATE TABLE AS SELECT statement.' },
      { id: 'b', text: 'COPY INTO', explain: 'COPY INTO ingests files from storage, not the result of a query.' },
      { id: 'c', text: 'SELECT … INTO a new table', explain: 'SELECT … INTO also creates a table, but Learn says Save as table uses CREATE TABLE AS SELECT.' },
      { id: 'd', text: 'INSERT … VALUES', explain: 'INSERT … VALUES adds literal rows, not a query result.' },
    ],
    answer: 'a',
  },
  {
    id: 'IB-04',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 3,
    stem: 'In the visual query editor, Save as view is blocked and a banner says: “The query is not supported as a warehouse view, since it cannot be fully translated to SQL.” What is the most likely cause?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'Your role doesn’t allow creating views in any schema', explain: 'A permission problem would surface when choosing a schema, not as a translation banner.' },
      { id: 'b', text: 'The query has an ORDER BY clause', explain: 'The ORDER BY limitation applies to Visualize results, not to saving a view.' },
      { id: 'c', text: 'The editor is open on a SQL analytics endpoint, not a warehouse', explain: 'The visual query editor and saving views work on SQL analytics endpoints too.' },
      { id: 'd', text: 'A step in the query can’t be folded into SQL', explain: 'Correct. Only Power Query operations that support query folding are supported, and steps that can’t be translated block the view.' },
    ],
    answer: 'd',
  },
  {
    id: 'IB-05',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'visual-vs-sql-editor',
    stem: 'Your team is adopting the visual query editor in Microsoft Fabric. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.visualQuery],
    statements: [
      { id: 's1', text: 'The visual query editor is available for warehouses, SQL analytics endpoints, and mirrored databases.', answer: true, explain: 'Yes. Learn’s article applies to the SQL analytics endpoint, Warehouse, and Mirrored Database.' },
      { id: 's2', text: 'Visualize results supports queries that include an ORDER BY clause.', answer: false, explain: 'No. Learn: Visualize results currently doesn’t support SQL queries with an ORDER BY clause.' },
      { id: 's3', text: 'A user in the workspace Viewer role can move their visual query into the Shared queries folder.', answer: false, explain: 'No. Viewers and shared recipients can save in My queries but are restricted from moving queries to Shared queries.' },
    ],
  },
  {
    id: 'IB-06',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 2,
    stem: 'Without writing SQL, you need to combine a store_sales table in the Sales warehouse with an item table in the Marketing warehouse. Both are in the same workspace. What should you do in the visual query editor?',
    sources: [S.visualQuery, S.queryWarehouse],
    options: [
      { id: 'a', text: 'Create a OneLake shortcut to item inside the Sales warehouse first', explain: 'A shortcut isn’t needed; the editor can query both warehouses once the second is added.' },
      { id: 'b', text: 'Add the Marketing warehouse with + Warehouses, then merge the tables', explain: 'Correct. Learn: add the other warehouse to the Explorer, drag tables from both, and add a merge.' },
      { id: 'c', text: 'Type the three-part name Marketing.dbo.item on the canvas', explain: 'Three-part names are for SQL queries; the visual editor works by dragging tables.' },
      { id: 'd', text: 'Open the OneLake catalog, select the item table, and choose Merge from its menu', explain: 'The OneLake catalog is for discovering items, not building queries.' },
    ],
    answer: 'b',
  },
  {
    id: 'IB-07',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'visual-vs-sql-editor',
    stem: 'A PL-300-trained analyst opens the visual query editor on a Fabric warehouse and finds it familiar. Which experience is the editor based on?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'DAX query view', explain: 'DAX query view runs DAX against semantic models, not visual steps against a warehouse.' },
      { id: 'b', text: 'The KQL queryset', explain: 'A KQL queryset runs KQL against KQL databases.' },
      { id: 'c', text: 'Power Query diagram view', explain: 'Correct. Learn: the editor uses the Power Query diagram view experience.' },
      { id: 'd', text: 'Data Wrangler', explain: 'Data Wrangler cleans DataFrames inside notebooks.' },
    ],
    answer: 'c',
  },
  {
    id: 'IB-08',
    machineId: ib,
    bulletIds: ['P3.1'],
    format: 'multi',
    difficulty: 1,
    stem: 'You ran a visual query on a Fabric warehouse and see the results. Which two actions does the editor offer directly on the results? Choose two.',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'Download Excel file', explain: 'Correct. You can download the results to view them in Excel.' },
      { id: 'b', text: 'Visualize results', explain: 'Correct. Visualize results creates a report on the results.' },
      { id: 'c', text: 'Publish to an eventstream', explain: 'Eventstreams process streaming events; query results aren’t published to them.' },
      { id: 'd', text: 'Export as a Spark DataFrame', explain: 'The results pane doesn’t export Spark DataFrames.' },
    ],
    answers: ['a', 'b'],
  },

  // ── Inspection Bench: P3.2 SQL ──────────────────────────────────────
  {
    id: 'IB-09',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'dropdown',
    difficulty: 2,
    trapPairId: 'sql-vs-kql',
    stem: 'You need total 2026 revenue per region from a Fabric warehouse, returning only regions above 10,000, highest first. Complete the T-SQL query.',
    sources: [S.queryWarehouse, S.groupBy, S.kqlSortOp],
    language: 'tsql',
    code: "SELECT Region, SUM(Amount) AS Revenue\nFROM dbo.Sales\nWHERE OrderDate >= '2026-01-01'\n[[1]] Region\n[[2]] SUM(Amount) > 10000\n[[3]] Revenue DESC;",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'PARTITION BY', explain: 'PARTITION BY belongs inside an OVER clause for window functions.' },
          { id: 'b', text: 'GROUP BY', explain: 'Correct. GROUP BY returns one row per region for the SUM.' },
          { id: 'c', text: 'ORDER BY', explain: 'ORDER BY sorts rows; it doesn’t create groups.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'HAVING', explain: 'Correct. HAVING filters groups on an aggregate after grouping.' },
          { id: 'b', text: 'WHERE', explain: 'WHERE filters rows before grouping and can’t use SUM().' },
          { id: 'c', text: 'QUALIFY', explain: 'QUALIFY filters on window function results, not on group aggregates.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'SORT BY', explain: 'sort by is the KQL operator; T-SQL uses ORDER BY.' },
          { id: 'b', text: 'TOP', explain: 'TOP limits the row count and goes after SELECT, not at the end.' },
          { id: 'c', text: 'ORDER BY', explain: 'Correct. ORDER BY Revenue DESC sorts the highest revenue first.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'IB-10',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 2,
    stem: 'You run this query in a Fabric warehouse: SELECT Region, Territory, SUM(Sales) AS TotalSales FROM dbo.SalesByTerritory GROUP BY ALL; How are the rows grouped?',
    sources: [S.groupBy, S.tsqlSurface],
    options: [
      { id: 'a', text: 'By Region only, the first column in the SELECT list', explain: 'GROUP BY ALL uses every non-aggregated SELECT expression, not just the first.' },
      { id: 'b', text: 'By every column in the table, even unselected ones', explain: 'Only expressions in the SELECT list are used.' },
      { id: 'c', text: 'By Region and Territory, the non-aggregated columns', explain: 'Correct. In Fabric, GROUP BY ALL groups by all non-aggregated expressions in the SELECT list.' },
      { id: 'd', text: 'Not at all; it returns one grand total row', explain: 'A grand total would need no grouping columns; GROUP BY ALL adds Region and Territory as keys.' },
    ],
    answer: 'c',
  },
  {
    id: 'IB-11',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 2,
    stem: 'In the SQL query editor of the SalesWH warehouse, you need to join dbo.Orders to the Customer table of ContosoLakehouse, which is in the same workspace. You already added the lakehouse with + Warehouses. How should you reference the lakehouse table?',
    sources: [S.queryWarehouse],
    options: [
      { id: 'a', text: 'ContosoLakehouse.dbo.Customer', explain: 'Correct. Learn: reference tables in added databases by using three-part naming.' },
      { id: 'b', text: 'OPENROWSET over the lakehouse Files path', explain: 'OPENROWSET reads files; the lakehouse table is reachable directly by name.' },
      { id: 'c', text: 'workspace.ContosoLakehouse.dbo.Customer', explain: 'Cross-database queries in the same workspace use three-part, not four-part, names.' },
      { id: 'd', text: 'dbo.Customer, after a USE ContosoLakehouse statement', explain: 'Switching databases loses the reference to SalesWH’s dbo.Orders in the same query.' },
    ],
    answer: 'a',
  },
  {
    id: 'IB-12',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'yesno',
    difficulty: 3,
    preview: true,
    stem: 'You are writing T-SQL for a Fabric warehouse and its lakehouse’s SQL analytics endpoint. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.tsqlSurface, S.groupBy],
    statements: [
      { id: 's1', text: 'Both support GROUP BY ALL and ORDER BY ALL without a column list.', answer: true, explain: 'Yes. Learn’s T-SQL surface area lists GROUP BY ALL and ORDER BY ALL for both.' },
      { id: 's2', text: 'Both support FROM-first query syntax as well as SELECT-first syntax.', answer: true, explain: 'Yes. Learn: Fabric Data Warehouse and the SQL analytics endpoint support SELECT-first and FROM-first syntax.' },
      { id: 's3', text: 'Nested common table expressions are generally available.', answer: false, explain: 'No. Standard and sequential CTEs are generally available, but nested CTEs are a preview feature.' },
    ],
  },
  {
    id: 'IB-13',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 1,
    stem: 'You open a Fabric warehouse and want a quick look at the first rows of DimCustomer without typing a query. What should you do in the Explorer?',
    sources: [S.queryWarehouse],
    options: [
      { id: 'a', text: 'Select New visual query and add a Keep top rows step', explain: 'That works but needs several steps; the Explorer offers a one-click option.' },
      { id: 'b', text: 'Right-click the table and select Select TOP 100 rows', explain: 'Correct. Learn: right-click the table in the Explorer and select Select TOP 100 rows.' },
      { id: 'c', text: 'Open the table in the OneLake catalog preview', explain: 'The catalog shows item details; the warehouse Explorer is where you preview table rows.' },
      { id: 'd', text: 'Select the table and choose View SQL', explain: 'View SQL belongs to the visual query editor and shows generated SQL.' },
    ],
    answer: 'b',
  },
  {
    id: 'IB-14',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'single',
    difficulty: 1,
    stem: 'A developer wants to query a Fabric warehouse from SQL Server Management Studio (SSMS) instead of the browser. What do they use to connect?',
    sources: [S.queryWarehouse],
    options: [
      { id: 'a', text: 'The KQL database query URI', explain: 'That URI connects to a KQL database, not a warehouse.' },
      { id: 'b', text: 'The ABFS path of the warehouse folder in OneLake', explain: 'An ABFS path reads files through OneLake APIs, not T-SQL sessions.' },
      { id: 'c', text: 'The warehouse’s T-SQL connection string', explain: 'Correct. Learn: tools such as SSMS connect to a SQL analytics endpoint or warehouse through a T-SQL connection string.' },
      { id: 'd', text: 'The semantic model’s XMLA endpoint', explain: 'XMLA connects tools to semantic models, not warehouses.' },
    ],
    answer: 'c',
  },
  {
    id: 'IB-15',
    machineId: ib,
    bulletIds: ['P3.2'],
    format: 'multi',
    difficulty: 2,
    trapPairId: 'endpoint-vs-warehouse',
    stem: 'You are connected to the SQL analytics endpoint of a lakehouse in the SQL query editor. Which two statements can you run successfully? Choose two.',
    sources: [S.endpoint, S.queryWarehouse],
    options: [
      { id: 'a', text: 'UPDATE dbo.Orders SET Status = \'Closed\' WHERE OrderID = 5', explain: 'The endpoint is read-only over Delta tables; you can’t update data through it.' },
      { id: 'b', text: 'INSERT INTO dbo.Orders SELECT * FROM staging_orders', explain: 'Inserting isn’t possible through the endpoint. Use Spark to modify lakehouse data.' },
      { id: 'c', text: 'A CREATE VIEW statement over two lakehouse tables', explain: 'Correct. You can create views, functions, and procedures in the SQL analytics endpoint.' },
      { id: 'd', text: 'A SELECT that joins to another warehouse in the workspace by its three-part name', explain: 'Correct. Cross-database queries work from SQL analytics endpoints and warehouses in the same workspace.' },
    ],
    answers: ['c', 'd'],
  },

  // ── Recipe Book: P2.1 views, functions, stored procedures ───────────
  {
    id: 'RB-01',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 2,
    stem: 'Analysts repeatedly query orders for one region at a time from a Fabric warehouse. You need a reusable object that takes the region as a parameter and can be used in the FROM clause of their queries. What should you create?',
    sources: [S.createFunction, S.createView, S.cte],
    options: [
      { id: 'a', text: 'A view with a WHERE clause on Region', explain: 'A view can be used in FROM but can’t take parameters, so the region would be fixed.' },
      { id: 'b', text: 'A stored procedure', explain: 'A procedure can take parameters but can’t be used in the FROM clause of a SELECT.' },
      { id: 'c', text: 'A common table expression', explain: 'A CTE exists only within one statement, so it isn’t reusable.' },
      { id: 'd', text: 'An inline table-valued function', explain: 'Correct. An inline TVF accepts parameters and returns a table defined by a single SELECT.' },
    ],
    answer: 'd',
  },
  {
    id: 'RB-02',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 1,
    stem: 'A nightly ETL step inserts rows from staging tables into a warehouse fact table. A pipeline must run the step on a schedule. Where should the T-SQL logic live?',
    sources: [S.loadTables, S.createProc],
    options: [
      { id: 'a', text: 'In a view that selects from the staging tables', explain: 'A view returns data; it can’t insert rows into the fact table.' },
      { id: 'b', text: 'In a stored procedure that the pipeline runs', explain: 'Correct. Learn: pipelines can execute SQL scripts and stored procedures to orchestrate ETL.' },
      { id: 'c', text: 'In an inline table-valued function', explain: 'An inline TVF returns a single SELECT’s result and can’t insert data.' },
      { id: 'd', text: 'In a query saved to the Shared queries folder', explain: 'Saved queries are for people running them in the editor, not for scheduled ETL.' },
    ],
    answer: 'b',
  },
  {
    id: 'RB-03',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'endpoint-vs-warehouse',
    stem: 'You created a stored procedure in the SQL analytics endpoint of a lakehouse. It runs an INSERT into a lakehouse table and fails. You need the load to work. What should you do?',
    sources: [S.endpoint, S.warehouse],
    options: [
      { id: 'a', text: 'Grant the user who runs the procedure the db_owner role on the SQL analytics endpoint', explain: 'Permissions don’t help: the endpoint is read-only for data.' },
      { id: 'b', text: 'Convert the procedure into a view', explain: 'A view can’t insert data either.' },
      { id: 'c', text: 'Load the data with Spark, or move the table and procedure into a warehouse', explain: 'Correct. The endpoint can’t insert, update, or delete. Use Spark to modify lakehouse data, or use a warehouse for T-SQL DML.' },
      { id: 'd', text: 'Wrap the INSERT in an explicit transaction', explain: 'A transaction doesn’t make the read-only endpoint writable.' },
    ],
    answer: 'c',
  },
  {
    id: 'RB-04',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'dropdown',
    difficulty: 2,
    stem: 'A warehouse customer dimension uses SCD type 2 (IsCurrent) and soft deletes (IsDeleted). You need an object that always returns only current, non-deleted customers for reports. Complete the T-SQL statement.',
    sources: [S.createView, S.loadTables],
    language: 'tsql',
    code: 'CREATE [[1]] dbo.vActiveCustomer AS\nSELECT CustomerID, CustomerName, Region\nFROM dbo.DimCustomer\nWHERE [[2]] [[3]] IsDeleted = 0;',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'TABLE', explain: 'CREATE TABLE … AS would copy the rows once; it wouldn’t stay current.' },
          { id: 'b', text: 'PROCEDURE', explain: 'A procedure can’t be queried like a table by reports.' },
          { id: 'c', text: 'VIEW', explain: 'Correct. A view stores the query, so reports always see the current filter result.' },
        ],
        answer: 'c',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'IsCurrent = 1', explain: 'Correct. The current version row of each member has IsCurrent set to 1.' },
          { id: 'b', text: 'IsCurrent = 0', explain: 'This returns only expired historical versions.' },
          { id: 'c', text: 'IsDeleted = 1', explain: 'This returns soft-deleted members, the opposite of the goal.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'OR', explain: 'OR would return rows meeting either condition, including deleted or expired ones.' },
          { id: 'b', text: 'AND', explain: 'Correct. Both conditions must be true.' },
          { id: 'c', text: 'UNION', explain: 'UNION combines two queries; it isn’t a condition operator.' },
        ],
        answer: 'b',
      },
    ],
  },
  {
    id: 'RB-05',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'dropdown',
    difficulty: 3,
    stem: 'You need an inline table-valued function in a Fabric warehouse that returns the sales rows for a region passed as a parameter. Complete the T-SQL statement.',
    sources: [S.createFunction],
    language: 'tsql',
    code: 'CREATE FUNCTION dbo.fnSalesByRegion (@Region varchar(50))\n[[1]] TABLE\nAS\n[[2]] SELECT OrderID, Amount\n  FROM dbo.FactSales\n  WHERE Region = [[3]];',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'RETURN', explain: 'RETURN introduces the SELECT that defines the result, not the return type.' },
          { id: 'b', text: 'OUTPUT', explain: 'OUTPUT marks procedure output parameters; it doesn’t declare a function’s return type.' },
          { id: 'c', text: 'RETURNS', explain: 'Correct. RETURNS TABLE declares an inline table-valued function.' },
        ],
        answer: 'c',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'RETURN', explain: 'Correct. In an inline TVF, RETURN is followed by the single SELECT that defines the table.' },
          { id: 'b', text: 'BEGIN', explain: 'An inline TVF has no function body block; it returns a single SELECT.' },
          { id: 'c', text: 'EXEC', explain: 'EXEC runs a procedure or command; it doesn’t define a function result.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: "'@Region'", explain: 'Quoting the name compares Region to the literal text @Region.' },
          { id: 'b', text: '@Region', explain: 'Correct. The parameter supplies the region to filter on.' },
          { id: 'c', text: 'Region', explain: 'Comparing the column to itself returns every row with a non-NULL region.' },
        ],
        answer: 'b',
      },
    ],
  },
  {
    id: 'RB-06',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'yesno',
    difficulty: 2,
    trapPairId: 'endpoint-vs-warehouse',
    stem: 'You are planning reusable SQL logic over lakehouse data in Microsoft Fabric. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.endpoint, S.tsqlSurface, S.visualQuery],
    statements: [
      { id: 's1', text: 'You can create T-SQL views, functions, and stored procedures in a lakehouse’s SQL analytics endpoint.', answer: true, explain: 'Yes. Learn: you can create views, functions, and procedures over Delta tables in the SQL analytics endpoint.' },
      { id: 's2', text: 'Permissions granted on a view in the SQL analytics endpoint also restrict users who read the same Delta tables from Spark.', answer: false, explain: 'No. SQL security rules on the endpoint apply only when data is accessed through the endpoint, not through Spark or other tools.' },
      { id: 's3', text: 'The visual query editor can save a query as a view.', answer: true, explain: 'Yes. Save as view creates a view from the visual query.' },
    ],
  },
  {
    id: 'RB-07',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 1,
    stem: 'Your Delta tables live in a Fabric lakehouse. You want to define a T-SQL view over two of them without copying data anywhere. Where should you create the view?',
    sources: [S.endpoint, S.tsqlSurface],
    options: [
      { id: 'a', text: 'In the lakehouse’s SQL analytics endpoint', explain: 'Correct. Learn: you can create T-SQL views on top of lakehouse Delta tables in the SQL analytics endpoint.' },
      { id: 'b', text: 'In the Files section of the lakehouse', explain: 'Files holds unmanaged files; T-SQL objects aren’t created there.' },
      { id: 'c', text: 'In a warehouse, after copying both tables into it', explain: 'Copying isn’t needed; the endpoint can host the view directly.' },
      { id: 'd', text: 'In a KQL queryset attached to the lakehouse', explain: 'KQL querysets run KQL against KQL databases, not T-SQL views.' },
    ],
    answer: 'a',
  },
  {
    id: 'RB-08',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'single',
    difficulty: 1,
    stem: 'A stored procedure named dbo.LoadDailySales exists in a Fabric warehouse. You need to run it from the SQL query editor. Which statement should you use?',
    sources: [S.execute, S.createProc, S.createProc],
    options: [
      { id: 'a', text: 'SELECT * FROM dbo.LoadDailySales;', explain: 'Learn runs procedures with EXEC (or EXECUTE), not by selecting from them.' },
      { id: 'b', text: 'CALL dbo.LoadDailySales();', explain: 'Learn’s T-SQL statement for running a procedure is EXEC (or EXECUTE).' },
      { id: 'c', text: 'RUN PROCEDURE dbo.LoadDailySales;', explain: 'Learn’s T-SQL statement for running a procedure is EXEC (or EXECUTE).' },
      { id: 'd', text: 'EXEC dbo.LoadDailySales;', explain: 'Correct. EXEC (or EXECUTE) runs a user-defined stored procedure.' },
    ],
    answer: 'd',
  },
  {
    id: 'RB-09',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'match',
    difficulty: 2,
    stem: 'You are choosing T-SQL objects for a Fabric warehouse. Match each requirement to the object that meets it.',
    sources: [S.createView, S.createFunction, S.createProc, S.loadTables],
    prompts: [
      { id: 'p1', text: 'Hide a three-table join behind a name reports can query like a table, with no parameters' },
      { id: 'p2', text: 'Return a table filtered by a parameter, usable in a FROM clause' },
      { id: 'p3', text: 'Run INSERT and UPDATE statements for an ETL step called by a pipeline' },
    ],
    choices: [
      { id: 'c1', text: 'View' },
      { id: 'c2', text: 'Inline table-valued function' },
      { id: 'c3', text: 'Stored procedure' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'A view is a virtual table defined by a query.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'An inline TVF accepts parameters and returns a table from a single SELECT.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Procedures can modify data, and pipelines can run them to orchestrate ETL.' },
    ],
  },
  {
    id: 'RB-10',
    machineId: rb,
    bulletIds: ['P2.1'],
    format: 'multi',
    difficulty: 2,
    stem: 'You are writing a SELECT in a Fabric warehouse. Which two kinds of user-defined objects can you reference in its FROM clause? Choose two.',
    sources: [S.createView, S.createFunction, S.createProc],
    options: [
      { id: 'a', text: 'A view', explain: 'Correct. A view behaves like a virtual table.' },
      { id: 'b', text: 'A stored procedure', explain: 'Procedures are run with EXEC; views and table-valued functions are what you query in FROM.' },
      { id: 'c', text: 'An inline table-valued function', explain: 'Correct. A TVF returns a table and is queried in FROM.' },
      { id: 'd', text: 'A pipeline', explain: 'A pipeline is a Data Factory item that orchestrates activities, not a SQL object.' },
    ],
    answers: ['a', 'c'],
  },
]
