import { S } from '../sources'
import type { Question } from '../types'

const m = 'thread-intake'

export const threadIntakeQuestions: Question[] = [
  {
    id: 'TI-01',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 1,
    stem: 'You need to create a reusable cloud connection to an Azure SQL database so that several Fabric pipelines can use it. Where should you create the connection?',
    sources: [S.connections],
    options: [
      { id: 'a', text: 'Settings > Manage connections and gateways', explain: 'Correct. New cloud connections are created on the Connections tab of Manage connections and gateways.' },
      { id: 'b', text: 'Workspace settings > Azure connections', explain: 'Workspace Azure connections settings don’t define reusable data source connections for pipelines.' },
      { id: 'c', text: 'The lakehouse’s SQL analytics endpoint settings', explain: 'The SQL analytics endpoint is a read-only query surface over Delta tables, not a place to define source connections.' },
      { id: 'd', text: 'The OneLake catalog Govern tab', explain: 'Govern shows governance insights and admin settings; it doesn’t create data source connections.' },
    ],
    answer: 'a',
  },
  {
    id: 'TI-02',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'You are creating a new cloud connection to a SQL Server data source in Manage connections and gateways. Which two authentication methods can you choose for this connection type? Choose two.',
    sources: [S.connections],
    options: [
      { id: 'a', text: 'Workspace identity in the CREDENTIAL clause', explain: 'Workspace identity in CREDENTIAL belongs to the T-SQL COPY statement, not to creating a cloud connection.' },
      { id: 'b', text: 'OAuth2', explain: 'Correct. OAuth2 is listed, with the caveat that long-running queries can fail when the token expires.' },
      { id: 'c', text: 'Row-level security role', explain: 'RLS roles restrict rows in a model or warehouse; they aren’t an authentication method for a connection.' },
      { id: 'd', text: 'Service Principal', explain: 'Correct. Service Principal is one of the listed authentication methods.' },
    ],
    answers: ['b', 'd'],
  },
  {
    id: 'TI-03',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 1,
    stem: 'Your company stores sales data in a SQL Server database in its own datacenter, behind the corporate firewall. You need a Dataflow Gen2 in Fabric to read this data. What should you set up?',
    sources: [S.gateway],
    options: [
      { id: 'a', text: 'A OneLake shortcut to the SQL Server database', explain: 'Shortcuts point to storage locations such as OneLake, ADLS, or S3; they don’t reach an on-premises SQL Server instance.' },
      { id: 'b', text: 'An on-premises data gateway', explain: 'Correct. The on-premises data gateway connects Fabric to data sources inside your network.' },
      { id: 'c', text: 'An eventstream with a custom endpoint', explain: 'Eventstreams ingest streaming events; they aren’t used to query an on-premises relational database for a dataflow.' },
      { id: 'd', text: 'The XMLA endpoint of the workspace', explain: 'The XMLA endpoint exposes semantic models to client tools; it doesn’t connect Fabric to on-premises sources.' },
    ],
    answer: 'b',
  },
  {
    id: 'TI-04',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You manage connections for a Fabric tenant. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.connections],
    statements: [
      { id: 's1', text: 'Removing a connection from Manage connections and gateways can stop items that depend on it from working.', answer: true, explain: 'Yes. Learn warns that when you remove a data source, any items that depend on it stop working.' },
      { id: 's2', text: 'The privacy level set on a cloud connection also applies to DirectQuery connections.', answer: false, explain: 'No. Learn notes that the privacy level setting doesn’t affect DirectQuery connections.' },
      { id: 's3', text: 'OAuth2 connections can fail for long-running queries that exceed the token’s lifetime.', answer: true, explain: 'Yes. Long-running queries might fail if they exceed the OAuth token expiration.' },
    ],
  },
  {
    id: 'TI-05',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 2,
    stem: 'A developer wants to check whether a specific SaaS source can be used as a destination as well as a source before choosing an ingestion tool. Which Learn resource lists, per connector, whether Dataflow Gen2, the pipeline Copy activity, and Copy job support it as a source or destination?',
    sources: [S.connectors],
    options: [
      { id: 'a', text: 'The T-SQL surface area article for Fabric Data Warehouse', explain: 'That article lists supported T-SQL syntax, not connector capabilities.' },
      { id: 'b', text: 'The Microsoft Fabric decision guide for choosing a data store', explain: 'That guide compares lakehouse, warehouse, eventhouse, and databases, not connectors.' },
      { id: 'c', text: 'The Data Factory connector overview', explain: 'Correct. The connector overview table shows source/destination support for Dataflow Gen2, pipelines, and Copy job per connector.' },
      { id: 'd', text: 'The OneLake shortcuts article', explain: 'The shortcuts article lists shortcut targets (OneLake, ADLS, S3, and so on), not Data Factory connectors.' },
    ],
    answer: 'c',
  },
  {
    id: 'TI-06',
    machineId: m,
    bulletIds: ['P1.1'],
    format: 'single',
    difficulty: 2,
    stem: 'You created a cloud connection in Manage connections and gateways. A colleague now needs a connection to the same source for a semantic model. According to Learn, how do cloud connections for semantic models and dataflows get created today?',
    sources: [S.connections],
    options: [
      { id: 'a', text: 'Through Power Query Online’s Get data experience', explain: 'Correct. Learn notes that cloud connections currently work with pipelines and Kusto, and that semantic models and dataflows use Power Query Online’s Get data experience to create personal cloud connections.' },
      { id: 'b', text: 'By creating a OneLake shortcut in the workspace', explain: 'A shortcut references storage; it isn’t how a semantic model’s connection is defined.' },
      { id: 'c', text: 'By enabling XMLA read-write on the capacity', explain: 'XMLA read-write governs tool access to semantic models, not how their source connections are created.' },
      { id: 'd', text: 'By assigning the colleague the Member workspace role', explain: 'A workspace role grants permissions on items; it doesn’t create a data source connection.' },
    ],
    answer: 'a',
  },
  {
    id: 'TI-07',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'Another team stores curated Delta tables in an ADLS Gen2 account. You need your lakehouse to query those tables without copying the data, and changes at the source must be visible immediately. What should you create?',
    sources: [S.shortcuts, S.onelake],
    options: [
      { id: 'a', text: 'A Copy job that runs every 15 minutes', explain: 'A Copy job makes a physical copy on a schedule, so it duplicates data and isn’t immediate.' },
      { id: 'b', text: 'A mirrored database', explain: 'Mirroring replicates operational databases into OneLake; it isn’t used to reference Delta files already in ADLS.' },
      { id: 'c', text: 'A OneLake shortcut in the Tables folder', explain: 'Correct. A shortcut references the data in place without copying, and source changes are visible immediately.' },
      { id: 'd', text: 'A Dataflow Gen2 with a lakehouse destination', explain: 'A dataflow copies data into the destination when it runs, which duplicates the data.' },
    ],
    answer: 'c',
  },
  {
    id: 'TI-08',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'Your company runs an operational Azure SQL Database. Analysts need near real-time copies of its tables in OneLake for reporting, with minimal setup and no pipelines to build or maintain. What should you use?',
    sources: [S.mirroring, S.movement],
    options: [
      { id: 'a', text: 'A pipeline with a Copy activity on a schedule', explain: 'A scheduled Copy activity works but needs you to build and manage the pipeline and incremental state yourself.' },
      { id: 'b', text: 'Mirroring', explain: 'Correct. Mirroring continuously replicates the database into OneLake as Delta tables with minimal setup and no pipelines.' },
      { id: 'c', text: 'A notebook that reads the database with JDBC', explain: 'A notebook is custom code you must schedule and maintain, which is the opposite of minimal setup.' },
      { id: 'd', text: 'An eventstream', explain: 'Eventstreams are for streaming events, not for replicating a relational database’s tables.' },
    ],
    answer: 'b',
  },
  {
    id: 'TI-09',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'You are ingesting raw (bronze) data from many sources into Fabric. You need incremental copies and change data capture without building pipelines, and you want more control than mirroring offers. Which data movement option does Learn recommend?',
    sources: [S.movement, S.dataFactory],
    options: [
      { id: 'a', text: 'Copy job', explain: 'Correct. Learn recommends starting with Copy job for bronze ingestion; it supports bulk, incremental, and CDC copy without pipelines.' },
      { id: 'b', text: 'Mirroring', explain: 'Mirroring is the simple choice for replicating curated data with fixed behavior; it offers less control than Copy job.' },
      { id: 'c', text: 'Eventstreams', explain: 'Eventstreams are for real-time streaming events, not batch ingestion from many sources.' },
      { id: 'd', text: 'A OneLake shortcut', explain: 'A shortcut references data without copying it, so it doesn’t provide incremental copies or CDC.' },
    ],
    answer: 'a',
  },
  {
    id: 'TI-10',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In a notebook, df holds data read from a Parquet file in the Files area of the default lakehouse. You need to save it as a new Delta table named sales in the Tables section, replacing any existing data. Which line should you run?',
    sources: [S.notebookLoad],
    options: [
      { id: 'a', text: 'df.write.mode("overwrite").format("delta").saveAsTable("sales")', explain: 'Correct. Learn’s example writes a Delta table to the Tables section with saveAsTable; overwrite replaces existing data.' },
      { id: 'b', text: 'df.write.mode("append").format("delta").saveAsTable("sales")', explain: 'append adds rows to an existing table instead of replacing its data.' },
      { id: 'c', text: 'df.write.mode("overwrite").format("csv").save("Files/sales")', explain: 'This writes CSV files to the Files area, not a Delta table in the Tables section.' },
      { id: 'd', text: 'df.write.mode("overwrite").format("parquet").save("Files/sales")', explain: 'This writes Parquet files to the Files area; it doesn’t create a Delta table.' },
    ],
    answer: 'a',
  },
  {
    id: 'TI-11',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You need to load about 1.5 billion rows from Parquet files in an Azure storage account into a Fabric warehouse table as part of a T-SQL script, with the highest ingestion throughput. What should you use?',
    sources: [S.ingestWarehouse, S.copyInto],
    options: [
      { id: 'a', text: 'INSERT ... SELECT from OPENROWSET', explain: 'OPENROWSET can read the files, but Learn notes it can be slower than loading; COPY is the high-throughput statement.' },
      { id: 'b', text: 'A Dataflow Gen2', explain: 'Dataflow Gen2 is a low-code option for smaller data with transformations, not the highest-throughput T-SQL load.' },
      { id: 'c', text: 'Batches of INSERT … VALUES statements', explain: 'INSERT … VALUES adds literal rows supplied in the script, which isn’t a way to load billions of rows from files; Learn names COPY as the highest-throughput option.' },
      { id: 'd', text: 'The COPY statement (COPY INTO)', explain: 'Correct. COPY provides the highest ingestion throughput and runs inside T-SQL.' },
    ],
    answer: 'd',
  },
  {
    id: 'TI-12',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'You need to bulk-load Parquet files from an Azure Blob Storage container into the existing warehouse table dbo.Trips. Complete the T-SQL statement.',
    sources: [S.copyInto],
    language: 'tsql',
    code: "[[1]] dbo.Trips\nFROM 'https://<account>.blob.core.windows.net/<container>/trips/'\nWITH ([[2]] = 'PARQUET');",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'COPY INTO', explain: 'Correct. COPY INTO loads files from Azure storage into a warehouse table.' },
          { id: 'b', text: 'INSERT INTO', explain: 'INSERT INTO needs a VALUES list or SELECT, not a file URL with WITH options.' },
          { id: 'c', text: 'MERGE INTO', explain: 'MERGE synchronizes a target with a source table; it doesn’t read files from a URL.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'DATA_SOURCE', explain: 'DATA_SOURCE isn’t the COPY option that declares the file format.' },
          { id: 'b', text: 'FORMAT_TYPE', explain: 'FORMAT_TYPE isn’t the COPY argument used in Learn’s example.' },
          { id: 'c', text: 'FILE_TYPE', explain: 'Correct. Learn’s Parquet example specifies only FILE_TYPE = \'PARQUET\'.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'TI-13',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'yesno',
    difficulty: 3,
    placement: true,
    stem: 'You are adding OneLake shortcuts to a lakehouse that doesn’t use schemas. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.shortcuts],
    statements: [
      { id: 's1', text: 'You can create a shortcut in a subfolder of the Tables folder, for example Tables/finance/budget.', answer: false, explain: 'No. In the Tables folder, shortcuts can only be created at the top level.' },
      { id: 's2', text: 'Deleting a shortcut also deletes the data at its target.', answer: false, explain: 'No. Shortcuts behave like symbolic links; deleting one leaves the target unaffected.' },
      { id: 's3', text: 'A shortcut named "sales orders" (with a space) is recognized as a Delta table in the Tables folder.', answer: false, explain: 'No. Delta doesn’t support spaces in table names, so OneLake doesn’t recognize such a shortcut as a table.' },
    ],
  },
  {
    id: 'TI-14',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 3,
    stem: 'A data engineer used Spark to write a Delta table to an external location outside the lakehouse’s Tables area. Analysts can’t see the table in the lakehouse’s SQL analytics endpoint. You need the table to appear there without copying it. What should you do?',
    sources: [S.loadLakehouse, S.endpoint],
    options: [
      { id: 'a', text: 'Grant the analysts ReadData on the lakehouse', explain: 'Permissions don’t make an external table visible; external Delta tables written by Spark aren’t surfaced by the endpoint at all.' },
      { id: 'b', text: 'Create a shortcut to the table in the Tables section', explain: 'Correct. Learn says to use shortcuts in the Tables section to make external Delta tables visible to the SQL analytics endpoint.' },
      { id: 'c', text: 'Refresh the SQL analytics endpoint metadata', explain: 'Metadata sync only picks up tables in the lakehouse’s Tables area; it won’t surface an external location.' },
      { id: 'd', text: 'Move the table into the Files folder', explain: 'Tables in the Files folder aren’t exposed by the SQL analytics endpoint either.' },
    ],
    answer: 'b',
  },
  {
    id: 'TI-15',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'match',
    difficulty: 2,
    placement: true,
    trapPairId: 'dataflow-pipeline-notebook',
    stem: 'You are choosing how to get data into a lakehouse for four scenarios. Match each scenario to the approach Learn recommends.',
    sources: [S.loadLakehouse],
    prompts: [
      { id: 'p1', text: 'A few small CSV files on your laptop, no transformation' },
      { id: 'p2', text: 'Small to medium data that needs visual, low-code transformations' },
      { id: 'p3', text: 'Large volumes copied on a schedule and chained with other activities' },
      { id: 'p4', text: 'Complex transformation logic or a source the other tools don’t support' },
    ],
    choices: [
      { id: 'c1', text: 'Upload files in Lakehouse explorer' },
      { id: 'c2', text: 'Dataflow Gen2' },
      { id: 'c3', text: 'Pipeline with a Copy activity' },
      { id: 'c4', text: 'Notebook code' },
      { id: 'c5', text: 'Eventstream' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'Uploading through Lakehouse explorer suits small local files with no transformation.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'Dataflow Gen2 is the low-code, visual option for small to medium data.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'Pipelines provide scalable copy, scheduling, triggers, and chained activities. Eventstream (unused) is for real-time events.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'Notebook code is the most flexible option for complex logic or unsupported sources.' },
    ],
  },
  {
    id: 'TI-16',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A notebook attached to lakehouse LH_Sales needs to read a Parquet file stored in a different lakehouse, LH_Marketing, in the same workspace. What path should the Spark code use?',
    sources: [S.notebookLoad],
    options: [
      { id: 'a', text: 'A relative path such as Files/sample.parquet', explain: 'Relative paths resolve against the notebook’s default lakehouse (LH_Sales), not LH_Marketing.' },
      { id: 'b', text: 'The /lakehouse/default/Files mount path', explain: 'The default mount points to the notebook’s default lakehouse only.' },
      { id: 'c', text: 'The file’s ABFS path (abfss://…)', explain: 'Correct. Learn says to use the absolute ABFS path when the data is in a different lakehouse.' },
      { id: 'd', text: 'A three-part name such as LH_Marketing.dbo.sample', explain: 'Three-part names are T-SQL cross-database references, not Spark file paths.' },
    ],
    answer: 'c',
  },
  {
    id: 'TI-17',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'multi',
    difficulty: 2,
    stem: 'You need to load data into a Fabric warehouse from a table in a lakehouse in the same workspace, using only T-SQL. Which two statements can you use? Choose two.',
    sources: [S.ingestWarehouse],
    options: [
      { id: 'a', text: 'CREATE TABLE AS SELECT (CTAS)', explain: 'Correct. CTAS can read from lakehouse tables in the same workspace using three-part names.' },
      { id: 'b', text: 'CREATE EXTERNAL TABLE', explain: 'Learn’s ingestion options for the warehouse list COPY, INSERT...SELECT, SELECT INTO, and CTAS, not external tables.' },
      { id: 'c', text: 'BACKUP DATABASE', explain: 'Backup isn’t a data ingestion statement in Fabric Data Warehouse.' },
      { id: 'd', text: 'INSERT ... SELECT', explain: 'Correct. INSERT...SELECT reads from other warehouses, lakehouses, or mirrored databases in the same workspace.' },
    ],
    answers: ['a', 'd'],
  },
  {
    id: 'TI-18',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'shortcut-mirror-copy',
    stem: 'You set up mirroring for an operational database. Which item does mirroring create in your workspace so analysts can query the replicated tables with T-SQL?',
    sources: [S.mirroring],
    options: [
      { id: 'a', text: 'A Dataflow Gen2', explain: 'Mirroring doesn’t create dataflows; it runs a managed replication process.' },
      { id: 'b', text: 'A warehouse', explain: 'Mirroring doesn’t create a read-write warehouse; it creates a read-only query surface.' },
      { id: 'c', text: 'A KQL database', explain: 'KQL databases live in eventhouses; mirroring lands Delta tables queried with T-SQL.' },
      { id: 'd', text: 'A SQL analytics endpoint', explain: 'Correct. Mirroring creates the replication process plus a SQL analytics endpoint over the replicated Delta tables.' },
    ],
    answer: 'd',
  },
  {
    id: 'TI-19',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'You use the T-SQL COPY statement to load files from OneLake into a warehouse. Security requires that COPY authenticate to the source as the Fabric workspace’s identity rather than with a key or SAS token. What should you specify?',
    sources: [S.ingestWarehouse],
    options: [
      { id: 'a', text: "CREDENTIAL = (IDENTITY = 'Workspace Identity')", explain: 'Correct. Learn: specify Workspace Identity in the CREDENTIAL clause to impersonate the workspace identity when accessing the source.' },
      { id: 'b', text: 'EXECUTE AS OWNER', explain: 'EXECUTE AS changes the execution context of modules; it doesn’t set COPY’s source credential.' },
      { id: 'c', text: 'A Service Principal connection in Manage connections and gateways', explain: 'Cloud connections are used by pipelines and Kusto; COPY uses its own CREDENTIAL clause.' },
      { id: 'd', text: 'A OneLake security role with ReadWrite', explain: 'OneLake security roles govern data-plane access for users; they don’t set how COPY authenticates.' },
    ],
    answer: 'a',
  },
  {
    id: 'TI-20',
    machineId: m,
    bulletIds: ['P1.3'],
    format: 'order',
    difficulty: 2,
    stem: 'You need to load Parquet files into a new warehouse table with the COPY statement and confirm the result. Put the steps in order.',
    sources: [S.copyInto],
    items: [
      { id: 'i1', text: 'Run SELECT COUNT_BIG(*) against the table', explain: 'Last: count the rows to confirm the load.' },
      { id: 'i2', text: 'Run COPY INTO with the source URL and FILE_TYPE', explain: 'Second: COPY loads the files into the existing table.' },
      { id: 'i3', text: 'Create the destination table with CREATE TABLE', explain: 'First: COPY needs the destination table to exist.' },
    ],
    answerOrder: ['i3', 'i2', 'i1'],
  },
]
