import { S } from '../sources'
import type { Question } from '../types'

const dv = 'dye-vat'
const wp = 'weave-planner'

export const transformBQuestions: Question[] = [
  // ── Dye Vat: P2.2 enrich data with new columns or tables ────────────
  {
    id: 'DV-01',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'In a Fabric notebook you load raw sales files into a DataFrame named df. Before you write the Delta table, you need to add a Year column derived from the OrderDate column. Which PySpark call should you use?',
    sources: [S.lakehousePrep, S.notebookClean, S.notebookCombine],
    options: [
      { id: 'a', text: 'df.withColumn("Year", year(col("OrderDate")))', explain: 'Correct. withColumn() adds a new column computed from an expression, as Learn’s lakehouse tutorial does for Year, Quarter, and Month.' },
      { id: 'b', text: 'df.groupBy(year(col("OrderDate")))', explain: 'groupBy() starts an aggregation and changes the grain; it doesn’t add a column to each row.' },
      { id: 'c', text: 'df.withColumnRenamed("OrderDate", "Year")', explain: 'This only renames OrderDate. The values stay full dates and the original column is gone.' },
      { id: 'd', text: 'df.filter(year(col("OrderDate")) > 0)', explain: 'filter() removes rows that fail a condition; it doesn’t add a column.' },
    ],
    answer: 'a',
  },
  {
    id: 'DV-02',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'You are loading an employee dimension in a Fabric warehouse from a staging table. The dimension must store a FullName column built from FirstName and LastName. Complete the T-SQL statement.',
    sources: [S.ingestWarehouse, S.loadTables, S.concat],
    language: 'tsql',
    code: "CREATE TABLE dbo.DimEmployee\n[[1]]\nSELECT EmployeeID,\n       [[2]](FirstName, ' ', LastName) AS FullName,\n       HireDate\n[[3]] staging.Employee;",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'WITH', explain: 'WITH introduces a common table expression or table options, not the query of a CREATE TABLE AS SELECT.' },
          { id: 'b', text: 'AS', explain: 'Correct. CREATE TABLE … AS SELECT (CTAS) creates the table from the query result.' },
          { id: 'c', text: 'INTO', explain: 'INTO belongs to SELECT … INTO, which has a different word order.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'CONCAT', explain: 'Correct. CONCAT joins two or more string values end to end, so the space separates the names.' },
          { id: 'b', text: 'COALESCE', explain: 'COALESCE returns the first non-NULL argument; it doesn’t join strings.' },
          { id: 'c', text: 'TRY_CAST', explain: 'TRY_CAST converts one value to a data type; it takes a single expression.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'USING', explain: 'USING names the source of a MERGE statement, not of a SELECT.' },
          { id: 'b', text: 'INTO', explain: 'INTO names a target table, not the table being read.' },
          { id: 'c', text: 'FROM', explain: 'Correct. FROM names the staging table the SELECT reads.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'DV-03',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A Fabric warehouse stores sales facts up to today and a new budget fact table with monthly targets for the next fiscal year. You are building the date dimension table. Which date range should it cover?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'Only the dates on which at least one sale was recorded', explain: 'Gaps would break date filtering, and budget dates in the future would have no dimension row.' },
      { id: 'b', text: 'The current calendar year, rebuilt every January', explain: 'Rebuilding to one year drops the history the sales facts still reference.' },
      { id: 'c', text: 'Every date used by all fact tables, plus future dates for the budget', explain: 'Correct. Learn: cover the known range used by all fact tables, and include future dates when the warehouse stores targets, budgets, or forecasts.' },
      { id: 'd', text: 'The dates in the sales fact table only; budgets get their own date table', explain: 'One date dimension should serve every fact table so they can be analyzed together.' },
    ],
    answer: 'c',
  },
  {
    id: 'DV-04',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Each January, your team must extend the warehouse date dimension a fixed number of years ahead and refresh fiscal attributes. A pipeline will run the step. According to Learn, how should you implement the extension logic?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'As a DAX calculated table in each semantic model', explain: 'A calculated table lives in one semantic model, so other models and SQL queries wouldn’t see it.' },
      { id: 'b', text: 'As a T-SQL stored procedure in the warehouse', explain: 'Correct. Learn recommends writing the logic to extend or update the date dimension in T-SQL and encapsulating it in a stored procedure.' },
      { id: 'c', text: 'As a OneLake shortcut to a calendar file', explain: 'A shortcut references data in place; it doesn’t generate or extend rows.' },
      { id: 'd', text: 'As a manual upload of a CSV of dates', explain: 'A manual upload can’t run on the pipeline’s schedule and isn’t what Learn recommends.' },
    ],
    answer: 'b',
  },
  {
    id: 'DV-05',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are deciding where to add derived columns in a Fabric solution. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.loadTables, S.ingestWarehouse, S.lakehousePrep],
    statements: [
      { id: 's1', text: 'Learn lists computing gross sales revenue (unit price multiplied by quantity) as a calculation that an ETL process can do for a fact table.', answer: true, explain: 'Yes. Learn’s load-tables article gives gross sales revenue as an example calculation for the sales fact table.' },
      { id: 's2', text: 'Dataflow Gen2 can only copy columns as they are and can’t produce calculated columns before loading a warehouse.', answer: false, explain: 'No. Learn: dataflow transformations include changing data types, adding or removing columns, and using functions to produce calculated columns.' },
      { id: 's3', text: 'Learn’s lakehouse tutorial adds Year and Quarter columns in a notebook and then partitions the Delta table by them.', answer: true, explain: 'Yes. The tutorial adds Year, Quarter, and Month with withColumn() and writes fact_sale partitioned by Year and Quarter.' },
    ],
  },
  {
    id: 'DV-06',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A notebook adds Year and Quarter columns to a sales DataFrame. You need the Delta table to be written split into folders by the values of those two columns. Which call should you add to the write chain?',
    sources: [S.lakehousePrep],
    options: [
      { id: 'a', text: '.orderBy("Year", "Quarter")', explain: 'orderBy() sorts rows; it doesn’t split the table into folders by value.' },
      { id: 'b', text: '.groupBy("Year", "Quarter")', explain: 'groupBy() is a DataFrame aggregation, not a writer option.' },
      { id: 'c', text: '.mode("append")', explain: 'mode() controls whether the write overwrites or appends; it doesn’t partition.' },
      { id: 'd', text: '.partitionBy("Year", "Quarter")', explain: 'Correct. Learn’s tutorial writes fact_sale with partitionBy("Year","Quarter").' },
    ],
    answer: 'd',
  },
  {
    id: 'DV-07',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'You need a GrossRevenue column stored in a Fabric warehouse fact table so that every report and SQL query uses the same value. Which two approaches meet the goal? Choose two.',
    sources: [S.ingestWarehouse, S.loadTables],
    options: [
      { id: 'a', text: 'Add a DAX calculated column to one semantic model', explain: 'The column would exist only in that model, not in the warehouse table that SQL queries read.' },
      { id: 'b', text: 'Create a OneLake shortcut to the staging table', explain: 'A shortcut references data where it is; it doesn’t add columns.' },
      { id: 'c', text: 'Compute UnitPrice * Quantity in the SELECT of a CREATE TABLE AS SELECT statement', explain: 'Correct. The column is computed during the load and stored in the warehouse table.' },
      { id: 'd', text: 'Add the calculated column in a Dataflow Gen2 that loads the fact table', explain: 'Correct. Dataflows can use functions to produce calculated columns before ingestion.' },
    ],
    answers: ['c', 'd'],
  },
  {
    id: 'DV-08',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'Analysts need a FullName column for the warehouse Customer table today. The table is reloaded only once a month, and you must not store a second copy of the data. What should you create?',
    sources: [S.createView, S.loadTables],
    options: [
      { id: 'a', text: 'A view that selects the table’s columns plus CONCAT(FirstName, \' \', LastName)', explain: 'Correct. A view is a virtual table defined by a query, so the derived column is available at once without storing data again.' },
      { id: 'b', text: 'A new table loaded with CREATE TABLE AS SELECT that includes the FullName column', explain: 'CTAS stores a second copy of the data, which the requirement forbids.' },
      { id: 'c', text: 'A stored procedure that returns no result set', explain: 'A procedure that returns nothing gives analysts no column to query.' },
      { id: 'd', text: 'A shortcut from a lakehouse to the Customer table', explain: 'A shortcut exposes the same columns; it can’t add a derived column.' },
    ],
    answer: 'a',
  },
  {
    id: 'DV-09',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A teammate prefers Spark SQL to PySpark. In a lakehouse with schemas enabled, you need one statement that reads raw parquet sales files, adds Year and Quarter columns from InvoiceDateKey, and writes a Delta table partitioned by those columns. Which statement should you use?',
    sources: [S.lakehousePrep],
    options: [
      { id: 'a', text: 'CREATE OR REPLACE VIEW sales PARTITIONED BY (Year, Quarter) AS SELECT * FROM parquet.`Files/raw/sales`', explain: 'Learn’s tutorial writes a partitioned Delta table, not a view, and this query adds no Year or Quarter column.' },
      { id: 'b', text: 'CREATE OR REPLACE TABLE delta.`Tables/dbo/sales` PARTITIONED BY (Year, Quarter) AS SELECT *, year(InvoiceDateKey) AS Year, quarter(InvoiceDateKey) AS Quarter FROM parquet.`Files/raw/sales`', explain: 'Correct. This mirrors the Spark SQL version in Learn’s lakehouse tutorial.' },
      { id: 'c', text: 'INSERT INTO delta.`Tables/dbo/sales` SELECT year(InvoiceDateKey) AS Year, quarter(InvoiceDateKey) AS Quarter, SUM(Quantity) AS Quantity FROM parquet.`Files/raw/sales` GROUP BY year(InvoiceDateKey), quarter(InvoiceDateKey)', explain: 'This aggregates the sales to one row per quarter instead of enriching each sale with Year and Quarter.' },
      { id: 'd', text: 'CREATE TABLE sales PARTITIONED BY (InvoiceDateKey) AS SELECT * FROM parquet.`Files/raw/sales`', explain: 'This partitions by the raw date and never adds Year or Quarter columns.' },
    ],
    answer: 'b',
  },
  {
    id: 'DV-10',
    machineId: dv,
    bulletIds: ['P2.2'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'dataflow-pipeline-notebook',
    stem: 'A team of business analysts needs to add a calculated column to customer data while ingesting it into a Fabric warehouse. They prefer a code-free experience. What should they use?',
    sources: [S.ingestWarehouse],
    options: [
      { id: 'a', text: 'The COPY INTO statement', explain: 'COPY INTO is a code-rich T-SQL ingestion statement, not a code-free transformation tool.' },
      { id: 'b', text: 'Mirroring', explain: 'Mirroring replicates a source database into OneLake; it doesn’t add calculated columns.' },
      { id: 'c', text: 'A dataflow (Dataflow Gen2)', explain: 'Correct. Learn: dataflows give a code-free experience with transformations such as using functions to produce calculated columns.' },
      { id: 'd', text: 'A OneLake shortcut', explain: 'A shortcut references data in place without transforming it.' },
    ],
    answer: 'c',
  },

  // ── Weave Planner: P2.3 star schema ─────────────────────────────────
  {
    id: 'WP-01',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You are designing DimCustomer in a Fabric warehouse. The source system identifies customers by CustomerID, and the business wants to keep a history of each customer’s region with new rows per change. Which key should the fact table reference?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'The CustomerID natural key from the source system', explain: 'Once history is kept, the same CustomerID appears on several rows, so it can’t identify one version.' },
      { id: 'b', text: 'A composite key of CustomerID and Region', explain: 'Learn recommends a single-column key; a composite key is less efficient and still ambiguous if a region repeats.' },
      { id: 'c', text: 'A warehouse-generated integer surrogate key', explain: 'Correct. Learn: a surrogate key is required for SCD type 2 because natural keys repeat across versions.' },
      { id: 'd', text: 'The customer’s email address', explain: 'An email is a changing attribute, not a stable, meaningless key.' },
    ],
    answer: 'c',
  },
  {
    id: 'WP-02',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'scd1-vs-scd2',
    stem: 'A salesperson moves from the Australia region to the United Kingdom region. Reports must keep showing past sales under Australia and new sales under the United Kingdom. How should the warehouse ETL handle the change in the salesperson dimension?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'Apply an SCD type 1 change that overwrites the region', explain: 'Type 1 overwrites the row, so all past sales would roll up to the United Kingdom as if the move always applied.' },
      { id: 'b', text: 'Apply an SCD type 2 change that adds a new version row', explain: 'Correct. Type 2 expires the current version and inserts a new one, so old facts keep the Australia version.' },
      { id: 'c', text: 'Apply an SCD type 3 change with a PreviousRegion column', explain: 'Type 3 tracks limited history in columns and is hard to use in a semantic model. Learn suggests considering type 2.' },
      { id: 'd', text: 'Mark the existing row with IsDeleted = 1', explain: 'A soft delete records a deletion in the source, not an attribute change.' },
    ],
    answer: 'b',
  },
  {
    id: 'WP-03',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'scd1-vs-scd2',
    stem: 'A customer’s email address was entered with a typo, and the source system has corrected it. Nobody needs to analyze the old value. How should the warehouse ETL apply the change to the customer dimension?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'Overwrite the attribute with an SCD type 1 change', explain: 'Correct. Learn: type 1 overwrites the row, can be used to correct errors, and suits most attributes like name and email.' },
      { id: 'b', text: 'Insert a new version with an SCD type 2 change', explain: 'Type 2 keeps history that nobody needs and adds a version row for a typo.' },
      { id: 'c', text: 'Truncate and fully reload the customer dimension', explain: 'Learn says never truncate and reload a dimension with generated surrogate keys; it invalidates fact references.' },
      { id: 'd', text: 'Soft delete the existing row and insert a new customer member', explain: 'That would split one customer into two members and orphan existing facts.' },
    ],
    answer: 'a',
  },
  {
    id: 'WP-04',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'match',
    difficulty: 2,
    placement: true,
    stem: 'You are designing fact tables in a Fabric warehouse. Match each requirement to the fact table type Learn recommends.',
    sources: [S.factTables],
    prompts: [
      { id: 'p1', text: 'Store every sales order line as it happens' },
      { id: 'p2', text: 'Store the end-of-day stock balance of every product' },
      { id: 'p3', text: 'Track each order through ordered, shipped, and delivered dates, updating the row at each milestone' },
    ],
    choices: [
      { id: 'c1', text: 'Transaction fact table' },
      { id: 'c2', text: 'Periodic snapshot fact table' },
      { id: 'c3', text: 'Accumulating snapshot fact table' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'A transaction fact table stores business events at the lowest grain; Learn’s example is a sales fact storing every order line.' },
      { promptId: 'p2', choiceId: 'c2', explain: 'A periodic snapshot stores measurements at set intervals; Learn’s example is a daily end-of-day inventory balance.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'An accumulating snapshot records milestones of a process, with several date keys, and the row is updated as each milestone occurs.' },
    ],
  },
  {
    id: 'WP-05',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A product was deleted in the source system. The warehouse product dimension has generated surrogate keys, and existing fact rows reference the product. What should the ETL process do?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Delete the product row from the dimension table', explain: 'Deleting the row would leave fact rows pointing at a key that no longer exists.' },
      { id: 'b', text: 'Truncate the dimension and reload it from the source', explain: 'Learn says never truncate and reload a dimension with generated surrogate keys; it invalidates the facts.' },
      { id: 'c', text: 'Set the product’s surrogate key to NULL', explain: 'The key must stay valid so fact rows still join to the member.' },
      { id: 'd', text: 'Set an IsDeleted bit column to 1 for the product', explain: 'Correct. Learn: record source deletions as soft deletes with a bit column such as IsDeleted, and filter them out in reports.' },
    ],
    answer: 'd',
  },
  {
    id: 'WP-06',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'dropdown',
    difficulty: 3,
    placement: true,
    trapPairId: 'scd1-vs-scd2',
    stem: 'You need to apply SCD type 1 changes to the Email attribute of a warehouse customer dimension and add customers that are new in staging. Complete the T-SQL statement.',
    sources: [S.merge, S.tsqlSurface, S.loadTables],
    language: 'tsql',
    code: 'MERGE dbo.DimCustomer AS tgt\nUSING staging.Customer AS src\nON tgt.[[1]] = src.CustomerID\nWHEN [[2]] THEN UPDATE SET tgt.Email = src.Email\nWHEN NOT MATCHED BY [[3]] THEN\n  INSERT (CustomerID, Email) VALUES (src.CustomerID, src.Email);',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'Customer_SK', explain: 'The staging data comes from the source system and has no warehouse surrogate key to match on.' },
          { id: 'b', text: 'CustomerID', explain: 'Correct. ETL matches incoming rows to members on the natural (business) key.' },
          { id: 'c', text: 'Email', explain: 'Email is the attribute being changed, so it can’t identify the member.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'MATCHED', explain: 'Correct. Rows that exist in both get the type 1 overwrite.' },
          { id: 'b', text: 'NOT MATCHED', explain: 'NOT MATCHED rows don’t exist in the target, so there’s nothing to update.' },
          { id: 'c', text: 'NOT MATCHED BY SOURCE', explain: 'This targets dimension rows missing from staging, not changed rows.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'SOURCE', explain: 'NOT MATCHED BY SOURCE finds target rows missing from the source; you can’t INSERT for those.' },
          { id: 'b', text: 'KEY', explain: 'KEY isn’t a MERGE keyword.' },
          { id: 'c', text: 'TARGET', explain: 'Correct. NOT MATCHED BY TARGET finds source rows the dimension doesn’t have yet, which are inserted.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'WP-07',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    stem: 'You are reviewing a design for a star schema in a Fabric warehouse. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.tsqlSurface, S.loadTables],
    statements: [
      { id: 's1', text: 'A PRIMARY KEY constraint can be added to a warehouse table only if NOT ENFORCED is specified.', answer: true, explain: 'Yes. Learn: PRIMARY KEY, UNIQUE, and FOREIGN KEY constraints are supported only with NOT ENFORCED.' },
      { id: 's2', text: 'Whenever possible, a fact table should be loaded incrementally rather than truncated and reloaded.', answer: true, explain: 'Yes. Learn calls incremental loads more scalable; truncating and reloading a large fact table is a last resort.' },
      { id: 's3', text: 'Truncating and fully reloading a dimension with generated surrogate keys is the recommended way to apply source changes.', answer: false, explain: 'No. Learn says you should never do this, because it invalidates fact references and can lose SCD type 2 history.' },
    ],
  },
  {
    id: 'WP-08',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'order',
    difficulty: 2,
    placement: true,
    stem: 'A pipeline runs the nightly ETL for a Fabric warehouse star schema. Put the steps in the order Learn recommends.',
    sources: [S.loadTables],
    items: [
      { id: 'i3', text: 'Process the dimension tables, applying SCD changes', explain: 'Third. Dimensions are processed before facts so every new member exists.' },
      { id: 'i1', text: 'Truncate the staging tables', explain: 'First. Learn: staging table contents should be removed at the start of the ETL process.' },
      { id: 'i4', text: 'Load the fact table, looking up the surrogate key for each dimension', explain: 'Last. Each fact row needs the current surrogate key of members that now exist.' },
      { id: 'i2', text: 'Load the staging tables with source data', explain: 'Second. Source data is staged before it is transformed into the dimensional model.' },
    ],
    answerOrder: ['i1', 'i2', 'i3', 'i4'],
  },
  {
    id: 'WP-09',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'A periodic snapshot fact table in a Fabric warehouse is loaded every night with the AgeInDays of every inventory item on each shelf. How should AgeInDays be aggregated?',
    sources: [S.factTables],
    options: [
      { id: 'a', text: 'Summed across the items on a shelf for one night, but not summed across nights', explain: 'Correct. Periodic snapshot measures are semi-additive: they can’t be summed across time periods. Learn’s own example: don’t sum an item’s age sampled nightly, but you could sum the age of all items on a shelf each night.' },
      { id: 'b', text: 'Summed across every dimension, including dates', explain: 'A measure in a periodic snapshot can’t be summed across other time periods.' },
      { id: 'c', text: 'Never summed across any dimension', explain: 'That describes a non-additive measure, such as a temperature reading. Item ages on a shelf can be summed for one night.' },
      { id: 'd', text: 'Summed only across nights, never across items in the same snapshot', explain: 'This reverses the rule: time is the dimension a snapshot measure can’t be summed across.' },
    ],
    answer: 'a',
  },
  {
    id: 'WP-10',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'Orders in a SQL Server source aren’t numbered in sequence and have no reliable timestamp column. You need an incremental load of the warehouse fact table that detects new and changed rows efficiently. What should you do?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Store the highest order number loaded and read orders above it next time', explain: 'A high watermark only works when the source records orders in a reliable sequence.' },
      { id: 'b', text: 'Truncate and reload the fact table every night', explain: 'Learn calls truncate-and-reload of a large fact table a last resort.' },
      { id: 'c', text: 'Enable change data capture or change tracking on the source tables', explain: 'Correct. Learn: when source data can’t identify new facts, SQL Server features like CDC or change tracking can detect changed rows.' },
      { id: 'd', text: 'Compare every fact row to the source by order and line number', explain: 'Learn warns that correlating by attributes can be very expensive for large fact tables.' },
    ],
    answer: 'c',
  },
  {
    id: 'WP-11',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'endpoint-vs-warehouse',
    stem: 'You must build a star schema in a Fabric lakehouse, with a fact_sale table and several dimension tables loaded from raw parquet files. How should you create the tables?',
    sources: [S.lakehousePrep, S.endpoint],
    options: [
      { id: 'a', text: 'Run CREATE TABLE and INSERT statements in the lakehouse SQL analytics endpoint', explain: 'The SQL analytics endpoint is read-only over Delta tables; you can’t insert data through it.' },
      { id: 'b', text: 'Write each DataFrame as a Delta table under Tables from a notebook', explain: 'Correct. Learn’s tutorial writes fact_sale and the dimension_* tables as Delta tables from notebooks.' },
      { id: 'c', text: 'Save each table as a CSV file in the Files section', explain: 'Files holds unmanaged files; the star schema tables belong in Tables as Delta tables.' },
      { id: 'd', text: 'Define each table as a DAX calculated table in a model', explain: 'That builds tables in one semantic model, not in the lakehouse.' },
    ],
    answer: 'b',
  },
  {
    id: 'WP-12',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A sales fact row arrives for a customer whose details haven’t reached the warehouse yet. Only the customer’s natural key is known. The details will arrive in a later load. According to Learn, what should the fact load do?',
    sources: [S.loadTables, S.factTables],
    options: [
      { id: 'a', text: 'Keep the fact row in staging until the customer arrives', explain: 'Learn says the fact row must still be inserted, not held back.' },
      { id: 'b', text: 'Insert the fact row with a NULL customer key', explain: 'A valid dimension key must still be stored; Learn recommends NOT NULL dimension keys.' },
      { id: 'c', text: 'Create a customer member with Unknown attributes and IsInferredMember set to TRUE', explain: 'Correct. The inferred member gets a real surrogate key now, and the dimension load updates it when the details arrive.' },
      { id: 'd', text: 'Truncate and reload the customer dimension so the new customer is included before the facts', explain: 'Reloading wouldn’t add a customer the source hasn’t sent, and it would break existing fact references.' },
    ],
    answer: 'c',
  },
  {
    id: 'WP-13',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 1,
    stem: 'You are creating the surrogate key of the date dimension in a Fabric warehouse. Which format does Learn recommend?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'A GUID generated when each row is inserted', explain: 'A GUID is wide and meaningless; the date key is the exception that should be readable.' },
      { id: 'b', text: 'The date stored as an int in YYYYMMDD format', explain: 'Correct. Learn: the date surrogate key should store YYYYMMDD as int, which is efficient, sorted, and ISO 8601 compliant.' },
      { id: 'c', text: 'An IDENTITY integer that starts at 1', explain: 'An arbitrary sequence works for most dimensions, but Learn makes date and time keys the readable exception.' },
      { id: 'd', text: 'The date stored as text in DD/MM/YYYY format', explain: 'Text is larger and doesn’t sort in date order; Learn uses int YYYYMMDD.' },
    ],
    answer: 'b',
  },
  {
    id: 'WP-14',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    stem: 'A warehouse sales fact table has OrderDate_Date_FK and ShipDate_Date_FK columns. Both reference the same physical date dimension. What is this design called?',
    sources: [S.factTables],
    options: [
      { id: 'a', text: 'A junk dimension', explain: 'A junk dimension combines many small lookup attributes into one table.' },
      { id: 'b', text: 'A snowflake dimension', explain: 'A snowflake normalizes one dimension across several related tables.' },
      { id: 'c', text: 'A degenerate dimension', explain: 'A degenerate dimension is formed from a fact table attribute, such as an order number.' },
      { id: 'd', text: 'A role-playing dimension', explain: 'Correct. Learn: a fact table that references one dimension several times, each in a distinct role, uses a role-playing dimension.' },
    ],
    answer: 'd',
  },
  {
    id: 'WP-15',
    machineId: wp,
    bulletIds: ['P2.3'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'Analysts built a dimensional model in Power Query inside a semantic model. They now need to analyze past sales by each customer’s region at the time of sale, and regions change. What does Learn recommend?',
    sources: [S.dimOverview, S.dimTables],
    options: [
      { id: 'a', text: 'Configure incremental refresh on the semantic model', explain: 'Incremental refresh controls which partitions are refreshed; it doesn’t store versions of changed dimension attributes.' },
      { id: 'b', text: 'Add a DAX calculated column that stores the current region', explain: 'A calculated column is recomputed from current data, so it can’t recall a past region.' },
      { id: 'c', text: 'Load the customers with a Dataflow Gen2 that overwrites changed customer rows', explain: 'Overwriting is an SCD type 1 pattern, which loses the history that’s needed.' },
      { id: 'd', text: 'Create a data warehouse with periodic ETL that stores dimension changes', explain: 'Correct. Learn: Power Query can’t manage historical change, so use a warehouse whose ETL captures and stores dimension changes.' },
    ],
    answer: 'd',
  },

  // ── Weave Planner: P2.4 denormalize data ────────────────────────────
  {
    id: 'WP-16',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'star-vs-snowflake',
    stem: 'A Fabric warehouse stores products in three related tables: Product, Subcategory, and Category. A semantic model needs a Category > Subcategory > Product hierarchy. What should you provide to the model?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'A view that joins the three tables into one denormalized product result', explain: 'Correct. Learn: a model hierarchy can only use columns from one table, so a snowflake should be exposed through a joining view.' },
      { id: 'b', text: 'All three tables, related in the model, with one hierarchy spanning all of them', explain: 'A hierarchy can only be based on columns from a single model table.' },
      { id: 'c', text: 'A OneLake shortcut to each of the three tables', explain: 'Shortcuts still deliver three separate tables, so the hierarchy problem remains.' },
      { id: 'd', text: 'An SCD type 2 version of the Category table', explain: 'SCD type 2 tracks history; it doesn’t combine the hierarchy levels into one table.' },
    ],
    answer: 'a',
  },
  {
    id: 'WP-17',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    trapPairId: 'star-vs-snowflake',
    stem: 'You need to flatten a snowflaked product dimension in a Fabric warehouse so that each product row carries its subcategory and category names. Complete the T-SQL statement.',
    sources: [S.createView, S.dimTables, S.unionOp, S.exceptIntersect],
    language: 'tsql',
    code: '[[1]] dbo.vDimProduct\nAS\nSELECT p.Product_SK, p.ProductName, s.SubcategoryName, c.CategoryName\nFROM dbo.Product AS p\n[[2]] dbo.Subcategory AS s ON p.Subcategory_FK = s.Subcategory_SK\nJOIN dbo.Category AS c ON s.[[3]] = c.Category_SK;',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'CREATE PROCEDURE', explain: 'A procedure runs statements when executed; consumers can’t select from it like a table.' },
          { id: 'b', text: 'CREATE VIEW', explain: 'Correct. A view stores the joining query so consumers see one denormalized product table.' },
          { id: 'c', text: 'CREATE SCHEMA', explain: 'A schema is a container for objects, not a query.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'JOIN', explain: 'Correct. An inner join adds the subcategory columns to each product.' },
          { id: 'b', text: 'UNION', explain: 'UNION stacks rows from two queries; it doesn’t add columns.' },
          { id: 'c', text: 'EXCEPT', explain: 'EXCEPT returns rows from one query that aren’t in another.' },
        ],
        answer: 'a',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'Subcategory_SK', explain: 'That is the subcategory’s own key, already used in the previous join.' },
          { id: 'b', text: 'Product_SK', explain: 'Product keys don’t relate subcategories to categories.' },
          { id: 'c', text: 'Category_FK', explain: 'Correct. The subcategory’s foreign key references the category’s surrogate key.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'WP-18',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'single',
    difficulty: 1,
    trapPairId: 'star-vs-snowflake',
    stem: 'Every row of a warehouse product dimension repeats its subcategory name and category name, so the same category name appears on many rows. Which term describes this design?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'Normalization', explain: 'Normalization reduces repeated data, which is the opposite of this design.' },
      { id: 'b', text: 'A snowflake dimension', explain: 'A snowflake splits the hierarchy into separate related tables.' },
      { id: 'c', text: 'Denormalization', explain: 'Correct. Learn: denormalization stores precomputed redundant data, typically by flattening hierarchies.' },
      { id: 'd', text: 'SCD type 3', explain: 'SCD type 3 tracks limited history in extra columns.' },
    ],
    answer: 'c',
  },
  {
    id: 'WP-19',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'single',
    difficulty: 2,
    stem: 'A warehouse sales fact relates to six tiny dimensions, each holding a few values: payment type, order channel, promotion flag, gift-wrap flag, rush flag, and return flag. You want to simplify the model. What should you create?',
    sources: [S.dimTables],
    options: [
      { id: 'a', text: 'A role-playing dimension', explain: 'Role-playing describes one dimension referenced several times by a fact table.' },
      { id: 'b', text: 'A junk dimension', explain: 'Correct. Learn: when you have many small dimensions, consider consolidating them into a junk dimension.' },
      { id: 'c', text: 'A snowflake dimension', explain: 'A snowflake normalizes one dimension into more tables, which adds tables rather than removing them.' },
      { id: 'd', text: 'A periodic snapshot table', explain: 'A periodic snapshot is a fact table type, not a way to combine dimensions.' },
    ],
    answer: 'b',
  },
  {
    id: 'WP-20',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'yesno',
    difficulty: 2,
    placement: true,
    trapPairId: 'star-vs-snowflake',
    stem: 'You are designing dimensions for a Fabric warehouse that will feed Power BI semantic models. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.dimTables],
    statements: [
      { id: 's1', text: 'Learn says dimension tables should almost always be denormalized.', answer: true, explain: 'Yes. Learn: it’s almost always the case that dimension tables should be denormalized.' },
      { id: 's2', text: 'A hierarchy in a semantic model can combine columns from several related tables.', answer: false, explain: 'No. A hierarchy can only be based on columns from a single semantic model table.' },
      { id: 's3', text: 'A denormalized product dimension contains redundant data, such as category names repeated on many rows.', answer: true, explain: 'Yes. Redundant data comes from flattening hierarchies into the dimension.' },
    ],
  },
  {
    id: 'WP-21',
    machineId: wp,
    bulletIds: ['P2.4'],
    format: 'multi',
    difficulty: 2,
    placement: true,
    stem: 'Customer data in a Fabric warehouse is normalized into Customer, City, and Country tables. You need consumers to see one denormalized customer table. Which two approaches meet the goal? Choose two.',
    sources: [S.dimTables, S.loadTables, S.createView],
    options: [
      { id: 'a', text: 'Load a new table with CREATE TABLE AS SELECT that joins the three tables', explain: 'Correct. Joining in the ETL stores one flattened customer table.' },
      { id: 'b', text: 'Add NOT ENFORCED foreign key constraints between the tables', explain: 'Constraints describe relationships; they don’t combine the tables into one.' },
      { id: 'c', text: 'Create a view that joins the three tables', explain: 'Correct. A view delivers a denormalized result over the normalized tables.' },
      { id: 'd', text: 'Split Country into a separate Region table', explain: 'This normalizes further, adding another table instead of flattening.' },
    ],
    answers: ['a', 'c'],
  },
]
