import { S } from '../sources'
import type { Question } from '../types'

const cm = 'carding-machine'
const tf = 'twisting-frame'

export const transformAQuestions: Question[] = [
  // ── Carding Machine: P2.7 duplicates / missing / nulls ──────────────
  {
    id: 'CM-01',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 2,
    placement: true,
    trapPairId: 'where-having-qualify',
    stem: 'A warehouse staging table has several rows per CustomerID, each with a different ModifiedAt value. You need to keep only the most recent row for each customer, in a single SELECT, without a subquery. Which clause should you add?',
    sources: [S.qualify],
    options: [
      { id: 'a', text: 'QUALIFY ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY ModifiedAt DESC) = 1', explain: 'Correct. QUALIFY filters on the window function result after it is computed, keeping row 1 (the newest) per customer.' },
      { id: 'b', text: 'WHERE ROW_NUMBER() OVER (PARTITION BY CustomerID ORDER BY ModifiedAt DESC) = 1', explain: 'WHERE runs before window functions are computed, so it can’t filter on ROW_NUMBER().' },
      { id: 'c', text: 'GROUP BY CustomerID HAVING COUNT(*) = 1', explain: 'This keeps only customers that have exactly one row and drops every customer with duplicates.' },
      { id: 'd', text: 'SELECT DISTINCT on all columns', explain: 'Rows that differ in ModifiedAt aren’t identical, so DISTINCT keeps all of them.' },
    ],
    answer: 'a',
  },
  {
    id: 'CM-02',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'You need to return one row per OrderID from a warehouse table, keeping the row with the latest LoadDate. Complete the T-SQL query.',
    sources: [S.qualify],
    language: 'tsql',
    code: 'SELECT OrderID, Amount, LoadDate\nFROM staging.Orders\n[[1]] ROW_NUMBER() OVER ([[2]] OrderID ORDER BY LoadDate [[3]]) = 1;',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'QUALIFY', explain: 'Correct. QUALIFY filters on window function results.' },
          { id: 'b', text: 'HAVING', explain: 'HAVING filters grouped results after GROUP BY, not window function results.' },
          { id: 'c', text: 'WHERE', explain: 'WHERE runs before window functions, so it can’t use ROW_NUMBER().' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'GROUP BY', explain: 'GROUP BY isn’t valid inside an OVER clause.' },
          { id: 'b', text: 'PARTITION BY', explain: 'Correct. PARTITION BY restarts numbering for each OrderID.' },
          { id: 'c', text: 'ORDER BY', explain: 'ORDER BY sets the numbering order; the grouping into OrderID sets comes from PARTITION BY.' },
        ],
        answer: 'b',
      },
      {
        id: '3',
        options: [
          { id: 'a', text: 'ASC', explain: 'Ascending would number the oldest LoadDate as 1.' },
          { id: 'b', text: 'NULLS LAST', explain: 'This isn’t the sort direction that puts the latest row first.' },
          { id: 'c', text: 'DESC', explain: 'Correct. Descending puts the latest LoadDate first, so row 1 is the newest.' },
        ],
        answer: 'c',
      },
    ],
  },
  {
    id: 'CM-03',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'While loading a warehouse dimension, you need to replace NULL values in the Region column with the text Unknown. Which T-SQL expression should you use?',
    sources: [S.coalesce],
    options: [
      { id: 'a', text: "TRY_CAST(Region AS varchar(50))", explain: 'TRY_CAST converts types and returns NULL on failure; it doesn’t replace NULLs.' },
      { id: 'b', text: "COALESCE(Region, 'Unknown')", explain: 'Correct. COALESCE returns the first non-NULL argument, so NULL regions become Unknown.' },
      { id: 'c', text: "NULLIF(Region, 'Unknown')", explain: 'NULLIF returns NULL when the two values are equal; it creates NULLs rather than replacing them.' },
      { id: 'd', text: "CONCAT(Region, 'Unknown')", explain: 'CONCAT appends text to every value, which would corrupt the non-NULL regions.' },
    ],
    answer: 'b',
  },
  {
    id: 'CM-04',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You are cleaning a DataFrame in a Fabric notebook with Data Wrangler. You need to remove rows that repeat the same values in the OrderID and LineNumber columns. Which Data Wrangler operation should you apply?',
    sources: [S.dataWrangler],
    options: [
      { id: 'a', text: 'Drop missing values', explain: 'This removes rows with missing values, not duplicate rows.' },
      { id: 'b', text: 'Fill missing values', explain: 'This replaces missing cells with a value; it doesn’t remove duplicates.' },
      { id: 'c', text: 'Drop duplicate rows', explain: 'Correct. It drops rows that have duplicate values in one or more chosen columns.' },
      { id: 'd', text: 'Group by column and aggregate', explain: 'Grouping changes the grain and aggregates values; it isn’t the duplicate-removal operation.' },
    ],
    answer: 'c',
  },
  {
    id: 'CM-05',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are designing the cleaning stage of a warehouse ETL process. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.loadTables, S.dataWrangler],
    statements: [
      { id: 's1', text: 'Staging tables should be made available to business users so they can validate raw data.', answer: false, explain: 'No. Learn: data in staging tables should never be made available to business users.' },
      { id: 's2', text: 'When a fact row’s dimension lookup fails, Learn suggests storing a special dimension member such as Unknown so the row can still be inserted.', answer: true, explain: 'Yes. The fact row must still be inserted with a valid key; an Unknown member is one approach.' },
      { id: 's3', text: 'Data Wrangler can export the cleaning steps it generates back into the notebook as code.', answer: true, explain: 'Yes. You can copy the code or export it to the notebook as a function.' },
    ],
  },
  {
    id: 'CM-06',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'During a fact load, some sales rows reference a ProductCode that doesn’t exist yet in the product dimension. The business doesn’t want to lose these sales. What should the ETL process do, according to Learn?',
    sources: [S.loadTables, S.dimTables],
    options: [
      { id: 'a', text: 'Skip the rows for now and load them on the next run, after the product arrives', explain: 'Learn says the fact row must still be inserted, not skipped.' },
      { id: 'b', text: 'Insert the rows with a NULL product key', explain: 'Learn says a valid dimension key must still be stored.' },
      { id: 'c', text: 'Truncate and reload the product dimension', explain: 'Truncating a dimension with generated surrogate keys invalidates existing fact references.' },
      { id: 'd', text: 'Insert the rows with the key of a special Unknown product member', explain: 'Correct. Store a special member (like Unknown) and update the key later when it’s known.' },
    ],
    answer: 'd',
  },
  {
    id: 'CM-07',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'multi',
    difficulty: 1,
    stem: 'A DataFrame in a Fabric notebook has empty cells in the Discount column. Using Data Wrangler, which two operations can deal with the missing values? Choose two.',
    sources: [S.dataWrangler],
    options: [
      { id: 'a', text: 'One-hot encode', explain: 'One-hot encoding creates indicator columns per category; it doesn’t handle missing values.' },
      { id: 'b', text: 'Drop missing values', explain: 'Correct. It removes rows that have missing values.' },
      { id: 'c', text: 'Fill missing values', explain: 'Correct. It replaces missing cells with a value you choose.' },
      { id: 'd', text: 'Scale min/max values', explain: 'Scaling rescales numeric values; it doesn’t fill or remove missing ones.' },
    ],
    answers: ['b', 'c'],
  },
  {
    id: 'CM-08',
    machineId: cm,
    bulletIds: ['P2.7'],
    format: 'single',
    difficulty: 1,
    stem: 'Your lakehouse follows the medallion architecture. In which layer should you fix errors, standardize formats, and remove duplicates?',
    sources: [S.medallion],
    options: [
      { id: 'a', text: 'Bronze', explain: 'Bronze stores everything exactly as it arrives; no changes are allowed there.' },
      { id: 'b', text: 'Gold', explain: 'Gold organizes curated data for reports and dashboards, after cleaning.' },
      { id: 'c', text: 'Silver', explain: 'Correct. Silver (enriched) is where you fix errors, standardize formats, and remove duplicates.' },
      { id: 'd', text: 'Staging', explain: 'Staging tables support a warehouse ETL process; they aren’t one of the three medallion layers.' },
    ],
    answer: 'c',
  },

  // ── Carding Machine: P2.8 data types ─────────────────────────────────
  {
    id: 'CM-09',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You are creating a warehouse table for customer names that include accented and non-Latin characters. Which data type should you use for the name column?',
    sources: [S.dataTypes],
    options: [
      { id: 'a', text: 'varchar', explain: 'Correct. nchar and nvarchar aren’t supported in warehouse tables; Learn says to use char and varchar (UTF-8 collation) instead.' },
      { id: 'b', text: 'nvarchar', explain: 'nvarchar isn’t supported for persisted warehouse table columns.' },
      { id: 'c', text: 'ntext', explain: 'text and ntext aren’t supported; the alternative is varchar.' },
      { id: 'd', text: 'nchar', explain: 'nchar isn’t supported in warehouse tables; use char instead.' },
    ],
    answer: 'a',
  },
  {
    id: 'CM-10',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'match',
    difficulty: 2,
    placement: true,
    stem: 'You are migrating table definitions from SQL Server to a Fabric warehouse. Some source types aren’t supported in warehouse tables. Match each source type to the alternative Learn recommends.',
    sources: [S.dataTypes],
    prompts: [
      { id: 'p1', text: 'money' },
      { id: 'p2', text: 'datetime' },
      { id: 'p3', text: 'tinyint' },
      { id: 'p4', text: 'image' },
    ],
    choices: [
      { id: 'c1', text: 'decimal' },
      { id: 'c2', text: 'datetime2' },
      { id: 'c3', text: 'smallint' },
      { id: 'c4', text: 'varbinary' },
      { id: 'c5', text: 'float' },
    ],
    pairs: [
      { promptId: 'p1', choiceId: 'c1', explain: 'money → decimal (which can’t store the monetary unit).' },
      { promptId: 'p2', choiceId: 'c2', explain: 'datetime and smalldatetime → datetime2.' },
      { promptId: 'p3', choiceId: 'c3', explain: 'tinyint → smallint.' },
      { promptId: 'p4', choiceId: 'c4', explain: 'image → varbinary. float (unused) isn’t Learn’s alternative for any of these.' },
    ],
  },
  {
    id: 'CM-11',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A staging column stores order dates as text, and some values are invalid. You need to convert the column to date in a warehouse query so that invalid values become NULL instead of failing the query. Which function should you use?',
    sources: [S.tryCast],
    options: [
      { id: 'a', text: 'CAST(OrderDateText AS date)', explain: 'CAST raises an error when a value can’t be converted, failing the query.' },
      { id: 'b', text: 'COALESCE(OrderDateText, GETDATE())', explain: 'COALESCE replaces NULLs; it doesn’t convert text to date safely.' },
      { id: 'c', text: 'TRY_CAST(OrderDateText AS date)', explain: 'Correct. TRY_CAST returns the converted value, or NULL if the conversion fails.' },
      { id: 'd', text: "FORMAT(OrderDateText, 'yyyy-MM-dd')", explain: 'FORMAT produces formatted text; it doesn’t return a date type.' },
    ],
    answer: 'c',
  },
  {
    id: 'CM-12',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'yesno',
    difficulty: 3,
    stem: 'You are designing column types for a Fabric warehouse. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.dataTypes, S.tsqlSurface],
    statements: [
      { id: 's1', text: 'datetime2 columns in a warehouse table store at most 6 digits of fractional-second precision.', answer: true, explain: 'Yes. datetime2 and time are limited to 6 digits of fractional-second precision.' },
      { id: 's2', text: 'A uniqueidentifier column stored in the warehouse is read as a GUID through a lakehouse’s SQL analytics endpoint.', answer: false, explain: 'No. It’s stored as binary; the SQL analytics endpoint can’t read the values as uniqueidentifier.' },
      { id: 's3', text: 'You can use ALTER TABLE to add a nullable column of a supported type to an existing warehouse table.', answer: true, explain: 'Yes. ADD of nullable columns of supported types is a supported ALTER TABLE operation.' },
    ],
  },
  {
    id: 'CM-13',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 1,
    stem: 'In a Fabric notebook, a numeric column was loaded as text, so Data Wrangler shows no histogram for it. Which Data Wrangler operation fixes this?',
    sources: [S.dataWrangler],
    options: [
      { id: 'a', text: 'Change column type', explain: 'Correct. It changes the column’s data type; numeric statistics and histograms appear once the column is numeric.' },
      { id: 'b', text: 'Find and replace', explain: 'Find and replace changes cell contents, not the column’s type.' },
      { id: 'c', text: 'Strip whitespace', explain: 'Stripping whitespace cleans text but leaves the column as text.' },
      { id: 'd', text: 'Split text', explain: 'Split text creates several columns from a delimiter; it doesn’t change the type.' },
    ],
    answer: 'a',
  },
  {
    id: 'CM-14',
    machineId: cm,
    bulletIds: ['P2.8'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A warehouse table stores CustomerGuid as uniqueidentifier. A cross-database query joins it to a lakehouse table through the lakehouse’s SQL analytics endpoint on the same GUID, and returns no matches. What is the cause?',
    sources: [S.dataTypes],
    options: [
      { id: 'a', text: 'Cross-database queries can’t join a warehouse to a lakehouse', explain: 'Warehouses can query lakehouse tables in the same workspace with three-part names.' },
      { id: 'b', text: 'The SQL analytics endpoint reads uniqueidentifier values as binary', explain: 'Correct. uniqueidentifier has no Delta type and is stored as binary, so joins between a warehouse and an endpoint on it don’t work as expected.' },
      { id: 'c', text: 'The lakehouse table needs a primary key constraint', explain: 'Constraints don’t affect how the GUID values are read.' },
      { id: 'd', text: 'The warehouse must use nvarchar for GUIDs', explain: 'nvarchar isn’t supported in warehouse tables.' },
    ],
    answer: 'b',
  },

  // ── Carding Machine: P2.9 filter ─────────────────────────────────────
  {
    id: 'CM-15',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'single',
    difficulty: 1,
    placement: true,
    trapPairId: 'where-having-qualify',
    stem: 'You are writing the SELECT that loads a warehouse fact table from staging. You need to exclude rows that have no CustomerID before any grouping or window function runs. Where should the condition go?',
    sources: [S.qualify],
    options: [
      { id: 'a', text: 'In a HAVING clause', explain: 'HAVING filters groups after GROUP BY, not individual rows before grouping.' },
      { id: 'b', text: 'In a QUALIFY clause', explain: 'QUALIFY filters after window functions are computed, which is later than required.' },
      { id: 'c', text: 'In the ORDER BY clause', explain: 'ORDER BY sorts results; it doesn’t filter rows.' },
      { id: 'd', text: 'In a WHERE clause', explain: 'Correct. WHERE filters individual rows before grouping and before window functions.' },
    ],
    answer: 'd',
  },
  {
    id: 'CM-16',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'where-having-qualify',
    stem: 'A warehouse query groups sales by region with SUM(Amount). You need to return only the regions whose total exceeds 10,000. Which clause should contain the condition?',
    sources: [S.qualify],
    options: [
      { id: 'a', text: 'HAVING', explain: 'Correct. HAVING filters grouped results after GROUP BY aggregates are computed.' },
      { id: 'b', text: 'WHERE', explain: 'WHERE runs before grouping, so the total doesn’t exist yet.' },
      { id: 'c', text: 'QUALIFY', explain: 'QUALIFY is for filtering on window function results, not on GROUP BY aggregates.' },
      { id: 'd', text: 'PARTITION BY', explain: 'PARTITION BY divides rows for a window function; it doesn’t filter.' },
    ],
    answer: 'a',
  },
  {
    id: 'CM-17',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'order',
    difficulty: 3,
    trapPairId: 'where-having-qualify',
    stem: 'A Fabric warehouse query uses WHERE, GROUP BY, HAVING, a window function in the SELECT list, and QUALIFY. Put the clauses in the order they are evaluated.',
    sources: [S.qualify],
    items: [
      { id: 'i1', text: 'QUALIFY', explain: 'QUALIFY is evaluated after window functions are computed (and before ORDER BY).' },
      { id: 'i2', text: 'WHERE', explain: 'WHERE filters rows right after FROM.' },
      { id: 'i3', text: 'HAVING', explain: 'HAVING filters groups after GROUP BY.' },
      { id: 'i4', text: 'GROUP BY', explain: 'GROUP BY follows WHERE.' },
      { id: 'i5', text: 'Window functions are computed', explain: 'Window functions are computed after HAVING.' },
    ],
    answerOrder: ['i2', 'i4', 'i3', 'i5', 'i1'],
  },
  {
    id: 'CM-18',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'single',
    difficulty: 1,
    stem: 'You are exploring a pandas DataFrame in a Fabric notebook with Data Wrangler. You need to keep only rows where Country equals Canada. Which operation should you apply?',
    sources: [S.dataWrangler],
    options: [
      { id: 'a', text: 'Select column', explain: 'Select column keeps chosen columns, not rows.' },
      { id: 'b', text: 'Filter', explain: 'Correct. Filter keeps rows that match one or more conditions.' },
      { id: 'c', text: 'Sort', explain: 'Sort orders rows; it doesn’t remove any.' },
      { id: 'd', text: 'Drop column', explain: 'Drop column removes columns, not rows.' },
    ],
    answer: 'b',
  },
  {
    id: 'CM-19',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    trapPairId: 'where-having-qualify',
    stem: 'You need the regions with more than 100 orders in 2026 from a warehouse table, plus each region’s rank by order count. Complete the T-SQL query.',
    sources: [S.qualify],
    language: 'tsql',
    code: "SELECT Region, COUNT(*) AS Orders,\n       RANK() OVER (ORDER BY COUNT(*) DESC) AS RegionRank\nFROM dbo.Orders\n[[1]] OrderDate >= '2026-01-01'\nGROUP BY Region\n[[2]] COUNT(*) > 100;",
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'HAVING', explain: 'HAVING can’t come before GROUP BY; row filters go in WHERE.' },
          { id: 'b', text: 'WHERE', explain: 'Correct. WHERE filters individual rows (2026 orders) before grouping.' },
          { id: 'c', text: 'QUALIFY', explain: 'QUALIFY filters on window results and comes after HAVING, not before GROUP BY.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'HAVING', explain: 'Correct. HAVING filters the grouped regions on COUNT(*).' },
          { id: 'b', text: 'WHERE', explain: 'A second WHERE after GROUP BY isn’t valid, and WHERE can’t use aggregates.' },
          { id: 'c', text: 'QUALIFY', explain: 'QUALIFY is for window function filters; the condition is on a GROUP BY aggregate.' },
        ],
        answer: 'a',
      },
    ],
  },
  {
    id: 'CM-20',
    machineId: cm,
    bulletIds: ['P2.9'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In a warehouse, you need to return the single most expensive product in each color, filtering on a window function result without writing a CTE. Which clause makes this possible?',
    sources: [S.qualify],
    options: [
      { id: 'a', text: 'HAVING MAX(Price)', explain: 'HAVING filters groups, and would return the max price per group rather than the full product row.' },
      { id: 'b', text: 'GROUP BY Color, Product', explain: 'Grouping by color and product returns every product, not the top-priced one per color.' },
      { id: 'c', text: 'QUALIFY ROW_NUMBER() OVER (PARTITION BY Color ORDER BY Price DESC) = 1', explain: 'Correct. Learn’s own example uses QUALIFY with ROW_NUMBER to return the top-priced product per color.' },
      { id: 'd', text: 'WHERE Price = MAX(Price)', explain: 'Aggregates can’t be used in WHERE.' },
    ],
    answer: 'c',
  },

  // ── Twisting Frame: P2.6 merge or join ───────────────────────────────
  {
    id: 'TF-01',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'An analyst uses the visual query editor on a Fabric warehouse to combine DimCity and FactSale on CityKey, without writing SQL. Which action should they use?',
    sources: [S.visualQuery],
    options: [
      { id: 'a', text: 'Merge queries as new, with CityKey as the common key', explain: 'Correct. Learn’s example merges the two tables with Merge queries as new and picks the key and join kind.' },
      { id: 'b', text: 'Save as table', explain: 'Save as table writes results to a table; it doesn’t combine two tables.' },
      { id: 'c', text: 'View SQL', explain: 'View SQL shows the generated T-SQL; it doesn’t perform the join.' },
      { id: 'd', text: 'New SQL query with a JOIN clause', explain: 'That works but requires writing SQL, which the analyst wants to avoid.' },
    ],
    answer: 'a',
  },
  {
    id: 'TF-02',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'In the Reporting warehouse, you need to create a new table that joins the Sales table from the SalesLakehouse lakehouse (same workspace) to the warehouse’s Products table. Complete the T-SQL statement.',
    sources: [S.ingestWarehouse, S.queryWarehouse],
    language: 'tsql',
    code: 'CREATE TABLE Reporting.dbo.SalesByProduct\n[[1]]\nSELECT p.Category, s.Amount\nFROM [[2]] AS s\nJOIN Reporting.dbo.Products AS p ON s.ProductID = p.ProductID;',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'AS', explain: 'Correct. CREATE TABLE … AS SELECT (CTAS) creates and fills the table from the query.' },
          { id: 'b', text: 'WITH', explain: 'WITH introduces a CTE or table options, not CTAS.' },
          { id: 'c', text: 'INTO', explain: 'INTO belongs to SELECT … INTO, not CREATE TABLE.' },
        ],
        answer: 'a',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'Sales', explain: 'A one-part name resolves in the current warehouse, not in the lakehouse.' },
          { id: 'b', text: 'SalesLakehouse.dbo.Sales', explain: 'Correct. A three-part name (item.schema.table) references the lakehouse table in the same workspace.' },
          { id: 'c', text: "OPENROWSET(BULK 'SalesLakehouse/Sales')", explain: 'OPENROWSET reads files in Azure storage, not a lakehouse table by name.' },
        ],
        answer: 'b',
      },
    ],
  },
  {
    id: 'TF-03',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'single',
    difficulty: 2,
    trapPairId: 'merge-vs-append',
    stem: 'Sales data is stored in three regional systems with the same columns. You need a single table that contains all sales from all three systems. Which kind of combine operation should the ETL use?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Merge the tables on SalesOrderID', explain: 'Merging adds columns by matching keys; it doesn’t stack rows from systems with the same structure.' },
      { id: 'b', text: 'Aggregate the tables by region', explain: 'Aggregation summarizes rows; it doesn’t combine the systems’ detail rows.' },
      { id: 'c', text: 'Append the tables (a union)', explain: 'Correct. Learn: data that shares a common structure can be appended; a union of each system’s sales gives the full set.' },
      { id: 'd', text: 'Create a shortcut to each table', explain: 'Shortcuts expose each table separately; they don’t combine them into one.' },
    ],
    answer: 'c',
  },
  {
    id: 'TF-04',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'single',
    difficulty: 3,
    placement: true,
    stem: 'A warehouse in workspace A needs to join to a lakehouse table that lives in workspace B. A three-part-name query fails. You need to query both tables together without copying data. What should you do?',
    sources: [S.queryWarehouse, S.endpoint],
    options: [
      { id: 'a', text: 'Use a four-part name that includes the workspace', explain: 'Cross-database queries reference items in the current workspace; a workspace prefix isn’t the documented fix.' },
      { id: 'b', text: 'Grant the warehouse’s owner the Contributor role in workspace B, then rerun the three-part-name query', explain: 'Roles don’t change the scope of cross-database queries, which is limited to the same workspace.' },
      { id: 'c', text: 'Run COPY INTO from workspace B’s lakehouse', explain: 'COPY INTO copies the data, which the requirement wants to avoid.' },
      { id: 'd', text: 'Create a OneLake shortcut to the table in a lakehouse in workspace A, then join to it', explain: 'Correct. Learn: use OneLake shortcuts to reference tables in other workspaces, then join them in one query.' },
    ],
    answer: 'd',
  },
  {
    id: 'TF-05',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In a Fabric notebook, you have DataFrames df_sale and df_city. You need every sale row matched to its city on CityKey, keeping only matches. Which PySpark expression should you use?',
    sources: [S.lakehousePrep],
    options: [
      { id: 'a', text: 'df_sale.union(df_city)', explain: 'union appends rows of the same structure; it doesn’t match rows on a key.' },
      { id: 'b', text: 'df_sale.join(df_city, df_sale.CityKey == df_city.CityKey, "inner")', explain: 'Correct. Learn’s tutorial joins fact and dimension DataFrames this way with an inner join.' },
      { id: 'c', text: 'df_sale.groupBy("CityKey").sum()', explain: 'This aggregates sales by CityKey; it doesn’t bring in city columns.' },
      { id: 'd', text: 'df_sale.withColumn("City", df_city.City)', explain: 'withColumn can’t pull a column from a different DataFrame without a join.' },
    ],
    answer: 'b',
  },
  {
    id: 'TF-06',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'yesno',
    difficulty: 2,
    stem: 'You are planning joins in a Fabric warehouse ETL. For each statement, select Yes if it is true. Otherwise, select No.',
    sources: [S.loadTables, S.queryWarehouse, S.visualQuery],
    statements: [
      { id: 's1', text: 'Set-based statements such as CREATE TABLE AS SELECT with joins are likely the most efficient way to load dimensional tables from staging tables in the same workspace.', answer: true, explain: 'Yes. Learn calls these set-based operations likely the most efficient and fastest way.' },
      { id: 's2', text: 'Three-part names let a warehouse query join tables from any workspace in the tenant.', answer: false, explain: 'No. Cross-database queries work within the current workspace.' },
      { id: 's3', text: 'The visual query editor can run INSERT and UPDATE statements after a merge.', answer: false, explain: 'No. The visual query editor runs read-only SELECT queries only; DDL and DML aren’t supported.' },
    ],
  },
  {
    id: 'TF-07',
    machineId: tf,
    bulletIds: ['P2.6'],
    format: 'order',
    difficulty: 2,
    stem: 'In the warehouse visual query editor, you need to join two tables and keep the result as a reusable view. Put the steps in order.',
    sources: [S.visualQuery],
    items: [
      { id: 'i1', text: 'Select Save as view and confirm the SQL statement', explain: 'Last: Save as view creates the view from the query with load enabled.' },
      { id: 'i2', text: 'Use Merge queries as new and choose the key columns and join kind', explain: 'Second: merge the tables on the common key.' },
      { id: 'i3', text: 'Drag both tables from the Explorer onto the canvas', explain: 'First: tables must be on the canvas before you can merge them.' },
    ],
    answerOrder: ['i3', 'i2', 'i1'],
  },

  // ── Twisting Frame: P2.5 aggregate ───────────────────────────────────
  {
    id: 'TF-08',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'A warehouse fact table stores one row per sales order line. Reports never need order numbers, and you want a smaller table with one row per date, product, and store. What should the ETL do?',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Create a view that filters out the order number column', explain: 'A view hides the column but leaves the grain and row count unchanged.' },
      { id: 'b', text: 'Partition the fact table by OrderDate', explain: 'Partitioning organizes storage; it doesn’t reduce the grain.' },
      { id: 'c', text: 'Add a nonclustered index on the dimension keys', explain: 'Fabric warehouse handles performance automatically, and an index wouldn’t change the grain anyway.' },
      { id: 'd', text: 'Load an aggregated result grouped by all the dimension keys', explain: 'Correct. Learn: aggregation can raise the grain; group by the dimension keys and summarize the measures.' },
    ],
    answer: 'd',
  },
  {
    id: 'TF-09',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'dropdown',
    difficulty: 2,
    placement: true,
    stem: 'In a Fabric warehouse, you need a summary table with total sales and order count per store. Complete the T-SQL.',
    sources: [S.ingestWarehouse, S.loadTables],
    language: 'tsql',
    code: 'CREATE TABLE dbo.StoreSummary AS\nSELECT StoreKey, [[1]](Amount) AS TotalSales, COUNT(*) AS Orders\nFROM dbo.FactSales\n[[2]] StoreKey;',
    slots: [
      {
        id: '1',
        options: [
          { id: 'a', text: 'MAX', explain: 'MAX returns the largest single sale, not the total.' },
          { id: 'b', text: 'SUM', explain: 'Correct. SUM adds the amounts per store.' },
          { id: 'c', text: 'AVG', explain: 'AVG returns the average sale, not the total.' },
        ],
        answer: 'b',
      },
      {
        id: '2',
        options: [
          { id: 'a', text: 'GROUP BY', explain: 'Correct. GROUP BY StoreKey returns one row per store.' },
          { id: 'b', text: 'ORDER BY', explain: 'ORDER BY sorts; without GROUP BY the aggregates would be invalid alongside StoreKey.' },
          { id: 'c', text: 'PARTITION BY', explain: 'PARTITION BY is used inside OVER() for window functions, not to group a query.' },
        ],
        answer: 'a',
      },
    ],
  },
  {
    id: 'TF-10',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'In a Fabric notebook, you joined sales to dates and cities in a DataFrame named joined. You need total Profit per Date and City. Which PySpark expression should you use?',
    sources: [S.lakehousePrep],
    options: [
      { id: 'a', text: 'joined.groupBy("Date", "City").sum("Profit")', explain: 'Correct. Learn’s tutorial groups by the dimension columns and applies sum to the measures.' },
      { id: 'b', text: 'joined.orderBy("Date", "City").sum("Profit")', explain: 'orderBy sorts; DataFrames don’t aggregate with sum after orderBy alone.' },
      { id: 'c', text: 'joined.select("Date", "City", "Profit").distinct()', explain: 'distinct removes duplicate rows; it doesn’t total Profit.' },
      { id: 'd', text: 'joined.withColumn("Profit", "sum")', explain: 'withColumn adds or replaces a column with an expression; this doesn’t aggregate.' },
    ],
    answer: 'a',
  },
  {
    id: 'TF-11',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 2,
    placement: true,
    stem: 'You want to build a city-level aggregate table in a lakehouse with Spark SQL in a notebook, replacing the table if it exists. Which statement pattern does Learn’s lakehouse tutorial use?',
    sources: [S.lakehousePrep],
    options: [
      { id: 'a', text: 'COPY INTO … FROM a parquet file', explain: 'COPY INTO is a Fabric warehouse T-SQL statement, not the Spark SQL pattern in a notebook.' },
      { id: 'b', text: 'MERGE INTO … USING … WHEN MATCHED', explain: 'MERGE upserts into an existing table; the tutorial replaces the aggregate table.' },
      { id: 'c', text: 'A temporary view with GROUP BY, then CREATE OR REPLACE TABLE … AS SELECT from it', explain: 'Correct. The tutorial creates a temporary view with GROUP BY and then CREATE OR REPLACE TABLE … AS SELECT from it.' },
      { id: 'd', text: 'SELECT … INTO a new table', explain: 'SELECT INTO is a T-SQL pattern, not the Spark SQL pattern used in the tutorial.' },
    ],
    answer: 'c',
  },
  {
    id: 'TF-12',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'multi',
    difficulty: 2,
    stem: 'According to Learn’s dimensional modeling guidance, which two outcomes can aggregation achieve when loading a fact table? Choose two.',
    sources: [S.loadTables],
    options: [
      { id: 'a', text: 'Reduce the fact table’s dimensionality', explain: 'Correct. Learn: aggregation can be used to reduce fact table dimensionality.' },
      { id: 'b', text: 'Raise the granularity of the facts', explain: 'Correct. Learn: aggregation can raise the granularity of the facts.' },
      { id: 'c', text: 'Track historical changes to dimension members', explain: 'That’s what slowly changing dimensions do, not aggregation.' },
      { id: 'd', text: 'Enforce foreign key relationships', explain: 'Aggregation doesn’t enforce keys; warehouse FK constraints are NOT ENFORCED anyway.' },
    ],
    answers: ['a', 'b'],
  },
  {
    id: 'TF-13',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 3,
    stem: 'A product manager asks for a sales fact table aggregated to month and product. Later, analysts need to report sales by sales order number. What is the consequence of having aggregated?',
    sources: [S.loadTables, S.factTables],
    options: [
      { id: 'a', text: 'Order-level analysis isn’t possible from that table because the grain was raised', explain: 'Correct. Aggregating removes the order-level detail; the table’s grain no longer supports it.' },
      { id: 'b', text: 'The order numbers become a degenerate dimension automatically', explain: 'Grouping drops the order numbers; nothing converts them into a dimension.' },
      { id: 'c', text: 'Direct Lake reconstructs the order rows on demand', explain: 'Direct Lake reads the table as stored; it can’t restore detail that isn’t there.' },
      { id: 'd', text: 'The SQL analytics endpoint stores the original rows as history', explain: 'The endpoint is a read-only query surface over Delta tables; it doesn’t keep prior detail.' },
    ],
    answer: 'a',
  },
  {
    id: 'TF-14',
    machineId: tf,
    bulletIds: ['P2.5'],
    format: 'single',
    difficulty: 1,
    placement: true,
    stem: 'You need a low-code way to group rows and aggregate a DataFrame in a Fabric notebook, with the code generated for you. Which Data Wrangler operation should you use?',
    sources: [S.dataWrangler],
    options: [
      { id: 'a', text: 'Multi-label binarizer', explain: 'This splits values into category indicator columns; it doesn’t aggregate.' },
      { id: 'b', text: 'Flash Fill', explain: 'Flash Fill creates a new column from examples; it doesn’t group rows.' },
      { id: 'c', text: 'Scale min/max values', explain: 'Scaling rescales one numeric column; it doesn’t group or aggregate.' },
      { id: 'd', text: 'Group by column and aggregate', explain: 'Correct. Data Wrangler’s Group by column and aggregate operation groups and aggregates, generating code.' },
    ],
    answer: 'd',
  },
]
