/**
 * Service worker generator (Step 9; adapted from the AZ-900 study app), a tiny Vite plugin instead of vite-plugin-pwa/Workbox (no new dependencies).
 * At build time it writes dist/sw.js containing:
 *  - the list of every emitted file plus the public files (precached on install, so the app works offline), and
 *  - a cache name derived from a hash of all of them (a new deploy = a new cache = an "update available" prompt).
 * The worker itself is plain JS in SW_SOURCE below.
 */
import { createHash } from 'node:crypto'
import { readdirSync, readFileSync, statSync } from 'node:fs'
import { join, relative, sep } from 'node:path'
import type { Plugin } from 'vite'

/** Public files that must not be precached (server config, not app content). */
const SKIP = new Set(['staticwebapp.config.json', '404.html', 'robots.txt'])

function listFiles(dir: string, root = dir): string[] {
  let out: string[] = []
  for (const name of readdirSync(dir)) {
    const full = join(dir, name)
    if (statSync(full).isDirectory()) out = out.concat(listFiles(full, root))
    else out.push(relative(root, full).split(sep).join('/'))
  }
  return out
}

export function serviceWorker(publicDir = 'public'): Plugin {
  return {
    name: 'fabric-mill-service-worker',
    apply: 'build',
    enforce: 'post',
    generateBundle(_options, bundle) {
      const hash = createHash('sha256')
      const files: string[] = []
      for (const [fileName, item] of Object.entries(bundle).sort(([a], [b]) => a.localeCompare(b))) {
        if (fileName.endsWith('.map')) continue
        files.push(fileName)
        hash.update(fileName)
        hash.update(item.type === 'chunk' ? item.code : typeof item.source === 'string' ? item.source : Buffer.from(item.source))
      }
      for (const f of listFiles(publicDir).sort()) {
        if (SKIP.has(f)) continue
        files.push(f)
        hash.update(f)
        hash.update(readFileSync(join(publicDir, f)))
      }
      const version = hash.digest('hex').slice(0, 12)
      const precache = ['./', ...files.map((f) => `./${f}`)]
      this.emitFile({ type: 'asset', fileName: 'sw.js', source: SW_SOURCE.replace('__VERSION__', version).replace('__PRECACHE__', JSON.stringify(precache)) })
    },
  }
}

const SW_SOURCE = `/* Fabric Mill service worker (generated by scripts/sw-plugin.ts). */
const VERSION = '__VERSION__'
const CACHE = 'fabric-mill-' + VERSION
const PRECACHE = __PRECACHE__

self.addEventListener('install', (event) => {
  // Precache the whole app. A new version then WAITS (no skipWaiting here) until the page asks it to take over.
  event.waitUntil(caches.open(CACHE).then((cache) => cache.addAll(PRECACHE)))
})

self.addEventListener('activate', (event) => {
  event.waitUntil(
    caches
      .keys()
      .then((keys) => Promise.all(keys.filter((k) => k.startsWith('fabric-mill-') && k !== CACHE).map((k) => caches.delete(k))))
      .then(() => self.clients.claim()),
  )
})

self.addEventListener('message', (event) => {
  if (event.data === 'SKIP_WAITING') self.skipWaiting()
})

self.addEventListener('fetch', (event) => {
  const req = event.request
  if (req.method !== 'GET') return
  const url = new URL(req.url)
  if (url.origin !== self.location.origin) return
  if (req.mode === 'navigate') {
    // Cache the directory entry: Cloudflare redirects index.html, and a redirected response
    // cannot satisfy a navigation whose redirect mode is manual (especially while offline).
    event.respondWith(caches.match('./', { cacheName: CACHE }).then((hit) => hit || fetch(req)))
    return
  }
  event.respondWith(caches.match(req, { cacheName: CACHE }).then((hit) => hit || fetch(req)))
})
`
