import type { Lab } from './types'
import { P, ex, learn } from './sources'

const SECOND_USER =
  'Optional: needs a second account in your organization. Without one, skip it and read the exercise’s description of what that user sees.'

export const maintainLabs: Lab[] = [
  {
    id: 'L11',
    order: 11,
    title: 'Gatehouse: workspace roles, item permissions, and data-level security',
    goal: 'Review workspace roles and item permissions, then apply dynamic data masking, row-level security, and column-level security in a warehouse, a OneLake security role in a lakehouse, and a semantic model RLS role.',
    machineIds: ['gate-keys', 'item-locks', 'thread-sieves'],
    bulletIds: ['M1.1', 'M1.2', 'M1.3'],
    platform: 'browser',
    minutes: 90,
    prereqs: ['L02', 'L04', 'L07'],
    before:
      'Work in DP600-Dev. Step 9 is an optional Windows step; the rest runs in a browser. Create a new warehouse named Secure_Warehouse for the T-SQL parts, so Mill_Warehouse stays clean. Steps marked optional need a second account; you can finish the lab without them. Never put a real user name or email in a problem note.',
    steps: [
      {
        id: 's1',
        text: 'Open Manage access for DP600-Dev and compare the four workspace roles with Learn’s roles table.',
        sources: [learn(P.workspaces, 'give-users-access-to-your-workspace'), learn(P.roles)],
        checkpoint: 'You’re listed with the Admin role.',
        trapPairId: 'member-vs-contributor',
        trapNote: 'Member can add people and share; Contributor can create and edit content but can’t share or manage access.',
      },
      {
        id: 's2',
        optional: true,
        text: `Add a second user as Viewer, then check what they see from a private browser window. ${SECOND_USER}`,
        sources: [ex('19-secure-data-access', 'apply-workspace-access-controls')],
        checkpoint: 'The second user sees the workspace items but can’t create items.',
      },
      {
        id: 's3',
        text: 'Open Manage permissions on Mill_Warehouse (Lab 4) and look at the share options (Read, ReadData, ReadAll). Optional: share it with a second user with ReadData only.',
        sources: [ex('19-secure-data-access', 'apply-item-access-control'), learn(P.whShare, 'share-a-warehouse')],
        checkpoint: 'The share dialog lists the additional permissions you can grant.',
        trapPairId: 'access-layers',
        trapNote: 'Item permissions open one item; workspace roles open every item; RLS, CLS, and OLS narrow what’s inside.',
      },
      {
        id: 's4',
        text: 'Create Secure_Warehouse and run the dynamic data masking script.',
        sources: [ex('06d-secure-data-warehouse', 'apply-dynamic-data-masking-rules-to-columns-in-a-table'), learn(P.ddm, 'permissions-for-dynamic-data-masking')],
        checkpoint: 'Your own SELECT returns unmasked values, because Admin has CONTROL on the warehouse.',
        trapPairId: 'cls-vs-ols-vs-ddm',
        trapNote: 'Masking hides values from users without UNMASK or CONTROL, but the column still returns.',
      },
      {
        id: 's5',
        text: 'Run the row-level security script. Use your own sign-in name for one sales rep and a made-up name for the other.',
        sources: [ex('06d-secure-data-warehouse', 'apply-row-level-security'), learn(P.whRls, 'predicate-based-row-level-security')],
        checkpoint: 'After the policy is on, your SELECT returns only your own rows, even though you’re Admin.',
      },
      {
        id: 's6',
        optional: true,
        text: `Run the column-level security and granular permission scripts against your second user. ${SECOND_USER}`,
        sources: [ex('06d-secure-data-warehouse', 'implement-column-level-security'), ex('06d-secure-data-warehouse', 'configure-sql-granular-permissions-using-t-sql'), learn(P.whCls, 'restrict-access-to-certain-columns-to-certain-users')],
        checkpoint: 'A query by that user that includes the restricted column fails with a permission error.',
      },
      {
        id: 's7',
        text: 'In a lakehouse, create a OneLake security role that grants read on one folder or table only. If your lakehouse doesn’t offer OneLake security roles, report it and continue.',
        sources: [ex('19-secure-data-access', 'apply-onelake-security-in-a-lakehouse'), learn(P.oneLakeSecurity, 'manage-data-access-with-onelake-security-roles')],
        checkpoint: 'The role lists the folder or table you chose.',
      },
      {
        id: 's8',
        text: 'Open Sales Model in Editing mode, choose Manage roles, and create a role whose filter keeps one product category. Then, from the model’s Security page, use Test as role.',
        sources: [learn(P.editModels, 'define-row-level-security-roles-and-rules'), learn(P.smRls, 'validate-the-role-within-the-power-bi-service')],
        checkpoint: 'While testing as the role, Sales Report shows only the category you kept.',
      },
      {
        id: 's9',
        optional: true,
        windows: true,
        text: 'Open the model security exercise’s starter file in Power BI Desktop and create one of its static roles. Then, in TMDL view, add object-level security for one column to a new role (not the static one: a createOrReplace script replaces the whole role, including its row filter).',
        sources: [ex('17-enforce-model-security', 'set-up-the-environment'), ex('17-enforce-model-security', 'create-static-roles'), learn(P.smOls, 'configure-object-level-security-by-using-tmdl-view')],
        checkpoint: 'With View as on that role, a visual that uses the secured column no longer shows its data.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete Secure_Warehouse (this removes its masks, security policy, and grants). Delete the OneLake security role.',
        sources: [ex('06d-secure-data-warehouse', 'clean-up-resources')],
      },
      {
        id: 'c2',
        text: 'Delete the RLS role from Sales Model, and remove any second user you added to the workspace or items.',
        sources: [learn(P.editModels, 'define-row-level-security-roles-and-rules'), learn(P.workspaces, 'give-users-access-to-your-workspace')],
      },
    ],
  },
  {
    id: 'L12',
    order: 12,
    title: 'Seal and stamp: endorsement, labels, lineage, and impact analysis',
    goal: 'Promote and describe items, apply a sensitivity label if your tenant has labels, trace lineage, and run impact analysis on a lakehouse.',
    machineIds: ['seal-and-stamp', 'ripple-map'],
    bulletIds: ['M1.5', 'M1.4', 'M2.4'],
    platform: 'browser',
    minutes: 45,
    prereqs: ['L07'],
    before:
      'Work in DP600-Dev, using the lakehouse and Sales Model from Lab 7 in place of the exercise’s own items. Skip the exercise’s setup section.',
    steps: [
      {
        id: 's1',
        text: 'Promote the lakehouse and add a description, as the exercise shows.',
        sources: [ex('19b-govern-analytics-data', 'endorse-and-document-the-lakehouse'), learn(P.endorse, 'promote-items')],
        checkpoint: 'The lakehouse shows a Promoted badge in the workspace list.',
      },
      {
        id: 's2',
        text: 'Promote Sales Model and add a description.',
        sources: [ex('19b-govern-analytics-data', 'endorse-and-document-the-semantic-model')],
        checkpoint: 'The model shows a Promoted badge.',
      },
      {
        id: 's3',
        text: 'Read how certification works. Try Certified only if your admin made you an authorized reviewer, and don’t send a certification request.',
        sources: [learn(P.endorse, 'certify-items')],
        checkpoint: 'You can tell whether the Certified option is available to you.',
      },
      {
        id: 's4',
        text: 'Apply a sensitivity label to Sales Model. If your tenant has no labels, or the label menu is greyed out, report that here; that’s an expected outcome.',
        sources: [learn(P.labels, 'prerequisites'), learn(P.labels, 'apply-a-label')],
        checkpoint: 'The label shows in the item header, or you’ve recorded that labels aren’t available.',
        trapPairId: 'endorse-vs-label',
        trapNote: 'Endorsement says the item is trustworthy; a sensitivity label says how sensitive it is.',
      },
      {
        id: 's5',
        text: 'Explore your items in the OneLake catalog as the exercise shows.',
        sources: [ex('19b-govern-analytics-data', 'explore-governance-in-the-onelake-catalog')],
        checkpoint: 'The lakehouse details show the description you added.',
      },
      {
        id: 's6',
        text: 'Open the workspace’s lineage view and highlight the lakehouse’s lineage.',
        sources: [learn(P.lineage, 'open-lineage-view'), learn(P.lineage, 'highlight-an-items-lineage'), ex('19b-govern-analytics-data', 'view-lineage-and-run-impact-analysis')],
        checkpoint: 'Arrows connect the lakehouse to Sales Model, directly or through its SQL analytics endpoint.',
      },
      {
        id: 's7',
        text: 'Open impact analysis for the lakehouse and look at the All downstream items tab. Don’t use Notify contacts; it sends real emails.',
        sources: [learn(P.impact, 'open-impact-analysis-for-an-item'), learn(P.impact, 'impact-analysis-pane')],
        checkpoint: 'The pane counts downstream items and lists Sales Model among them.',
        trapPairId: 'lineage-vs-impact',
        trapNote: 'Lineage shows the whole flow; impact analysis lists what’s downstream of one item.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Nothing to delete. You can leave the endorsements, descriptions, and label in place.',
        sources: [ex('19b-govern-analytics-data', 'clean-up-resources')],
      },
    ],
  },
  {
    id: 'L13',
    order: 13,
    title: 'Pattern ledger and conveyor: Git integration and a deployment pipeline',
    goal: 'Connect DP600-Dev to a GitHub repository, commit and update, then deploy items from Dev to Test with a deployment pipeline.',
    machineIds: ['pattern-ledger', 'conveyor'],
    bulletIds: ['M2.1', 'M2.3'],
    platform: 'browser',
    minutes: 90,
    prereqs: ['L02', 'L07'],
    before:
      'You need a free GitHub account. You’ll create a personal access token: paste it only into Fabric, never into a problem note or anywhere in this app. If a tenant switch for Git integration is off and you can’t turn it on, report it and skip to step 7.',
    steps: [
      {
        id: 's1',
        text: 'Check the Fabric and Git prerequisites, including the tenant switches for syncing with GitHub.',
        sources: [learn(P.git, 'fabric-prerequisites'), learn(P.git, 'git-prerequisites')],
        checkpoint: 'You know whether the GitHub switch is on in your tenant.',
      },
      {
        id: 's2',
        text: 'Create a private GitHub repository with a README (so it has a main branch) and a fine-grained token with Contents read and write on that repository only. Don’t paste the repository URL or the token into a problem note.',
        sources: [learn(P.git, 'git-prerequisites')],
        checkpoint: 'The token page lists your repository with Contents: read and write.',
      },
      {
        id: 's3',
        text: 'Connect DP600-Dev to the repository’s main branch from workspace settings. Because the branch has no Fabric items, the first sync copies every workspace item into Git for you.',
        sources: [learn(P.git, 'connect-to-a-git-repo'), learn(P.git, 'connect-to-a-workspace')],
        checkpoint: 'Each item shows Synced, and the repository has a folder per item.',
      },
      {
        id: 's5',
        text: 'Change an item in the workspace (for example, a cell in the Lab 7 notebook) and commit again. Then edit a file for another item in GitHub and use Update in Fabric.',
        sources: [learn(P.git, 'commit-changes-to-git'), learn(P.git, 'update-workspace-from-git')],
        checkpoint: 'The GitHub edit appears in the workspace item after Update.',
        trapPairId: 'commit-vs-update',
        trapNote: 'Commit sends workspace changes to Git; Update brings Git changes into the workspace.',
      },
      {
        id: 's6',
        text: 'Disconnect the workspace from Git.',
        sources: [learn(P.git, 'disconnect-a-workspace-from-git')],
        checkpoint: 'The Git status column is gone.',
      },
      {
        id: 's7',
        text: 'Create a deployment pipeline. While you name it, delete the Production stage so it has only Development and Test; the number of stages can’t change after you create it.',
        sources: [learn(P.deployStart, 'step-1---create-a-deployment-pipeline'), learn(P.deployStart, 'step-2---name-the-pipeline-and-assign-stages'), ex('21b-manage-semantic-model-lifecycle', 'create-a-deployment-pipeline')],
        checkpoint: 'The pipeline shows two stages.',
        trapPairId: 'pipelines-vs-git',
        trapNote: 'Git tracks versions of one workspace; a deployment pipeline copies content between workspaces.',
      },
      {
        id: 's8',
        text: 'Assign DP600-Dev to Development and DP600-Test to Test.',
        sources: [learn(P.deployStart, 'step-3---assign-a-workspace'), ex('21-implement-cicd', 'assign-workspaces-to-stages-of-a-deployment-pipeline')],
        checkpoint: 'Each stage shows its workspace name.',
      },
      {
        id: 's9',
        text: 'Select only Mill_Lakehouse and the Copy_Sales pipeline from Lab 2, and deploy them to Test.',
        sources: [learn(P.deployStart, 'step-5---deploy-to-an-empty-stage'), ex('21-implement-cicd', 'deploy-content-between-stages')],
        checkpoint: 'The deployed items appear in DP600-Test, and the stage comparison shows them as matching.',
      },
      {
        id: 's10',
        text: 'Change the pipeline in Dev (for example, rename its Copy activity) and save it, then compare the stages before deploying again.',
        sources: [learn(P.comparePipeline, 'compare-stages'), learn(P.deployStart, 'step-6---deploy-content-from-one-stage-to-another')],
        checkpoint: 'The comparison marks the changed item as different until you deploy.',
      },
      {
        id: 's11',
        optional: true,
        text: 'Read which item types support deployment rules. A lakehouse and a pipeline aren’t among them, so there’s nothing to create here; note which items you would use rules for.',
        sources: [learn(P.deployRules, 'create-a-deployment-rule'), learn(P.deployRules, 'considerations-and-limitations')],
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete the deployment pipeline, and delete the items it deployed to DP600-Test.',
        sources: [ex('21-implement-cicd', 'clean-up')],
      },
      {
        id: 'c2',
        text: 'In GitHub, delete the token and the repository.',
        sources: [learn(P.git, 'git-prerequisites')],
      },
    ],
  },
  {
    id: 'L14',
    order: 14,
    title: 'Draft table and pattern book: .pbip, .pbit, .pbids, and shared models',
    goal: 'Save a Power BI project and look at its files, export a template, create a data source file, and build reports on a shared semantic model.',
    machineIds: ['draft-table', 'pattern-book'],
    bulletIds: ['M2.2', 'M2.6'],
    platform: 'windows',
    minutes: 75,
    prereqs: ['L04', 'L07'],
    before:
      'Needs Power BI Desktop on Windows, except step 7. The .pbids file names your warehouse’s server: keep it on your computer and never paste its contents into a problem note.',
    steps: [
      {
        id: 's1',
        windows: true,
        text: 'Open the starter file from Lab 9 (or download it from the DAX calculations exercise) and save it as a Power BI project (.pbip).',
        sources: [learn(P.pbip, 'save-as-a-project'), ex('14-create-dax-calculations', 'get-started')],
        checkpoint: 'The title bar shows you’re working in a project.',
        trapPairId: 'pbi-files',
        trapNote: '.pbix is one binary file; .pbip is a folder of text files; .pbit is a template; .pbids is a connection.',
      },
      {
        id: 's2',
        windows: true,
        text: 'Open the project folder and find the .Report and .SemanticModel folders. If the model is saved in TMDL format, its definition folder holds a tables subfolder with one .tmdl file per table.',
        sources: [learn(P.pbip, 'navigate-to-files'), learn(P.pbipModel, 'semantic-model-files')],
        checkpoint: 'You can find the model definition files (TMDL files, or a single model file in the older format).',
      },
      {
        id: 's3',
        optional: true,
        windows: true,
        text: 'Close Desktop, change a measure’s description in its .tmdl file with a text editor, and reopen the project.',
        sources: [learn(P.pbipModel, 'make-external-changes-to-tmdl-files'), learn(P.pbip, 'changes-outside-power-bi-desktop')],
        checkpoint: 'Desktop shows the new description.',
      },
      {
        id: 's4',
        windows: true,
        text: 'Export the report as a Power BI template (.pbit), then open the template.',
        sources: [learn(P.pbit, 'creating-report-templates'), learn(P.pbit, 'using-report-templates')],
        checkpoint: 'Opening the .pbit starts a new untitled report with the same pages and model.',
      },
      {
        id: 's5',
        windows: true,
        text: 'In a new Desktop file, connect to Mill_Warehouse and load one table. Then try to export a .pbids file from Data source settings. Learn shows Export PBIDS but has no Fabric warehouse example, so this is an experiment: if Export PBIDS is offered, close the file and open the .pbids; if it isn’t, record that in a problem note and go on to step 6.',
        sources: [learn(P.whConnect, 'connect-using-power-bi'), learn(P.pbids, 'how-to-create-a-pbids-connection-file')],
        checkpoint: 'You know whether Export PBIDS was offered for this source, and, if it was, what opening the .pbids did.',
      },
      {
        id: 's6',
        windows: true,
        text: 'In a new Desktop file, connect live to Sales Model in DP600-Dev and build one visual.',
        sources: [learn(P.liveConnect, 'establish-a-power-bi-service-live-connection-to-the-published-semantic-model')],
        checkpoint: 'The status bar says you’re connected live to the semantic model.',
      },
      {
        id: 's7',
        text: 'In the browser, create a report in DP600-Test that uses Sales Model from DP600-Dev, and read what Build permission allows.',
        sources: [learn(P.sharedModels, 'semantic-model-sharing-and-workspaces'), learn(P.sharedModels, 'build-permission-for-semantic-models')],
        checkpoint: 'The report in DP600-Test shows data from the model in DP600-Dev.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete the .pbids file and the template from your computer, and delete the report you made in DP600-Test.',
        sources: [learn(P.pbids, 'use-pbids-files-to-get-data')],
      },
    ],
  },
  {
    id: 'L15',
    order: 15,
    title: 'Batch winder and remote loom control: incremental refresh, large models, XMLA, OneLake integration',
    goal: 'Publish an Import model with an incremental refresh policy, use large semantic model storage format, inspect its partitions over the XMLA endpoint, and export its tables to OneLake.',
    machineIds: ['batch-winder', 'wide-beam', 'remote-loom-control', 'shared-spool'],
    bulletIds: ['S2.5', 'S1.6', 'M2.5', 'P1.5'],
    platform: 'windows',
    minutes: 105,
    prereqs: ['L02', 'L04'],
    before:
      'Needs Power BI Desktop and SQL Server Management Studio (SSMS) on Windows. The workspace connection URL is private to your tenant: never paste it into a problem note.',
    steps: [
      {
        id: 's1',
        windows: true,
        text: 'In Power BI Desktop, connect to Mill_Warehouse in Import mode and choose the staging orders table. Its sample orders are dated in the first half of 2026.',
        sources: [learn(P.whConnect, 'connect-using-power-bi')],
        checkpoint: 'Power Query Editor shows the orders table.',
      },
      {
        id: 's2',
        windows: true,
        text: 'Learn expects a Date/Time column; this table’s order date is a date, so change its type to Date/Time in Power Query first. Then create RangeStart and RangeEnd with values a few months apart inside the first half of 2026. If the incremental refresh slider later stays disabled, report it.',
        sources: [learn(P.incremental, 'filter-data'), learn(P.incremental, 'create-parameters')],
        checkpoint: 'Both parameters appear in the Queries pane with the Date/Time type.',
      },
      {
        id: 's3',
        windows: true,
        text: 'Filter the date column with RangeStart and RangeEnd, using “equal to” on only one of them, then Close & Apply.',
        sources: [learn(P.incremental, 'filter-data')],
        checkpoint: 'The table loads only rows inside your parameter range.',
      },
      {
        id: 's4',
        windows: true,
        text: 'Define an incremental refresh policy on the table: archive at least 1 year (so the 2026 orders are kept) and refresh a shorter period.',
        sources: [learn(P.incremental, 'define-policy')],
        checkpoint: 'The policy dialog’s summary describes both periods.',
        trapPairId: 'archive-vs-refresh-period',
        trapNote: 'The archive (store) period is how much history the model keeps; the refresh period is what each refresh reloads.',
      },
      {
        id: 's6',
        text: 'Before you publish, set DP600-Dev’s default storage format to large semantic model storage format, so the model gets it from its first refresh (Learn advises enabling it before the first refresh).',
        sources: [learn(P.workspaces, 'default-storage-format'), learn(P.largeModels, 'set-default-storage-format'), learn(P.incremental, 'save-and-publish-to-the-service')],
        checkpoint: 'After you publish, the model’s settings show large semantic model storage format as on.',
      },
      {
        id: 's5',
        windows: true,
        text: 'Publish to DP600-Dev, then refresh the model in the service.',
        sources: [learn(P.incremental, 'save-and-publish-to-the-service'), learn(P.incremental, 'refresh-model')],
        checkpoint: 'The refresh history shows a completed refresh.',
      },
      {
        id: 's7',
        text: 'Copy the workspace connection URL from workspace settings. Keep it private.',
        sources: [learn(P.xmla, 'to-get-the-workspace-connection-url')],
        checkpoint: 'You have a connection URL that starts with powerbi://.',
      },
      {
        id: 's8',
        windows: true,
        text: 'Connect to the workspace with SSMS and expand your model’s orders table partitions.',
        sources: [learn(P.xmla, 'connect-to-a-workspace-by-using-ssms')],
        checkpoint: 'Object Explorer lists your model, and the orders table’s Partitions dialog lists the partitions the service created.',
        trapPairId: 'xmla-read-vs-readwrite',
        trapNote: 'Browsing and querying need read; changing metadata or refreshing partitions needs read-write.',
      },
      {
        id: 's9',
        optional: true,
        windows: true,
        text: 'Script the model or one table as TMSL from SSMS and read it. Don’t run changes you don’t understand.',
        sources: [learn(P.xmla, 'connect-with-ssms'), learn(P.xmla, 'enable-xmla-read-write')],
        checkpoint: 'A query window opens with the TMSL script.',
      },
      {
        id: 's10',
        text: 'Turn on OneLake integration in the model’s settings, then refresh the model. Learn lists Premium P and Fabric F SKUs and needs the tenant setting “Semantic models can export data to OneLake”; if the option is missing or greyed out, report it.',
        sources: [learn(P.smOneLake, 'enable-onelake-integration'), learn(P.smOneLake, 'refresh-model')],
        checkpoint: 'The refresh history shows an entry on the OneLake integration tab.',
        trapPairId: 'onelake-availability-vs-integration',
        trapNote: 'This exports an Import model’s tables to OneLake; Lab 6 made eventhouse data available in OneLake.',
      },
      {
        id: 's11',
        text: 'In Mill_Lakehouse, create a shortcut to the model’s exported Delta tables.',
        sources: [learn(P.smOneLake, 'shortcuts'), learn(P.smOneLake, 'explore-export-files')],
        checkpoint: 'The shortcut shows the exported tables.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Turn OneLake integration off, delete the shortcut, and delete the Import model and its report from DP600-Dev.',
        sources: [learn(P.smOneLake, 'enable-onelake-integration')],
      },
      {
        id: 'c2',
        text: 'Course cleanup, when every lab you plan to do is finished: remove DP600-Test and DP600-Dev (Workspace settings, then remove the workspace). Items in a trial capacity become inactive when the trial ends anyway.',
        sources: [ex('21-implement-cicd', 'clean-up'), learn(P.trial, 'when-your-fabric-trial-ends')],
      },
    ],
  },
]
