import type { Lab } from './types'
import { P, ex, learn } from './sources'

const KEEP = 'Keep your DP600-Dev workspace.'

export const prepareLabs: Lab[] = [
  {
    id: 'L01',
    order: 1,
    title: 'Open the mill: start the trial and set up two workspaces',
    goal: 'Start a Fabric trial, check its size and end date, and create the two workspaces every later lab uses.',
    machineIds: ['mill-lease', 'water-wheel', 'founding-charter'],
    bulletIds: [],
    platform: 'browser',
    minutes: 30,
    prereqs: [],
    before:
      'You need a work or school account that can sign in to Fabric. Never paste your tenant name, account email, or any URL from your tenant into a problem note.',
    steps: [
      {
        id: 's1',
        text: 'Start a Fabric trial from the Account manager (Method 1 on the trial page). If your organization already has a trial you can join, Learn describes that too.',
        sources: [learn(P.trial, 'method-1-start-a-new-trial-capacity-from-the-account-manager')],
        checkpoint: 'The Account manager shows a trial status with a number of days left.',
        trapPairId: 'fabric-trial-vs-pbi-trial',
        trapNote: 'A Fabric trial gives you a trial capacity, not just a Power BI individual trial license.',
      },
      {
        id: 's2',
        text: 'Enter the trial start date on this app’s Labs page so the trial clock and schedule match your trial.',
        sources: [learn(P.trial, 'get-the-status-of-your-trial')],
        checkpoint: 'The Labs page shows days left out of 60.',
      },
      {
        id: 's3',
        text: 'Check whether your trial capacity has 4 or 64 capacity units. If it has 4 and you’re a capacity or tenant admin, you may be able to raise it to 64; this doesn’t add days.',
        sources: [learn(P.trial, 'increase-trial-capacity')],
        checkpoint: 'You know your trial capacity’s size (4 or 64 capacity units).',
      },
      {
        id: 's4',
        text: 'Read what the trial doesn’t include and what happens when it ends. No lab in this app uses an excluded feature.',
        sources: [learn(P.trial, 'whats-includedand-whats-not'), learn(P.trial, 'when-your-fabric-trial-ends')],
      },
      {
        id: 's5',
        text: 'Create a workspace named DP600-Dev and, under Advanced, choose the Trial workspace type so it runs on your trial capacity.',
        sources: [learn(P.workspaces, 'workspace-type')],
        checkpoint: 'The workspace opens empty, and its settings show it on a trial capacity.',
        trapPairId: 'capacity-vs-workspace',
        trapNote: 'The capacity supplies compute; the workspace is the container you assign to it.',
      },
      {
        id: 's6',
        text: 'Create a second workspace named DP600-Test the same way. Lab 13 deploys from Dev to Test.',
        sources: [learn(P.workspaces, 'workspace-type')],
        checkpoint: 'Both workspaces appear in your Workspaces list.',
      },
      {
        id: 's7',
        text: 'In DP600-Dev, open New item and browse the item types, grouped by workload. Don’t create anything yet.',
        sources: [learn(P.terminology)],
        checkpoint: 'You can see item types such as Lakehouse, Warehouse, and Eventhouse.',
        trapPairId: 'workload-vs-item',
        trapNote: 'A workload (for example Data Engineering) groups item types; a lakehouse is an item.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Nothing to delete yet. Keep DP600-Dev and DP600-Test for the later labs; Lab 15’s cleanup removes them.',
        sources: [ex('21-implement-cicd', 'clean-up')],
      },
    ],
  },
  {
    id: 'L02',
    order: 2,
    title: 'Thread intake: load data into a lakehouse four ways',
    goal: 'Get data into a lakehouse by upload, Dataflow Gen2, a pipeline Copy activity, and a shortcut; then find it in the OneLake catalog and compare data stores.',
    machineIds: ['thread-intake', 'bale-catalog', 'vat-selector', 'three-vats'],
    bulletIds: ['P1.1', 'P1.3', 'P1.2', 'P1.4'],
    platform: 'browser',
    minutes: 90,
    prereqs: ['L01'],
    before:
      'Work in DP600-Dev. Where an exercise says “Create a workspace”, skip that section and use DP600-Dev. Skip any optional section that needs AI features; the trial doesn’t include them.',
    steps: [
      {
        id: 's1',
        text: 'Create a lakehouse named Mill_Lakehouse.',
        sources: [ex('01-lakehouse', 'create-a-lakehouse')],
        checkpoint: 'The lakehouse explorer shows empty Tables and Files folders.',
      },
      {
        id: 's2',
        text: 'Download the exercise’s sample sales file and upload it to the Files folder.',
        sources: [ex('01-lakehouse', 'upload-a-file')],
        checkpoint: 'The file appears under Files.',
      },
      {
        id: 's3',
        text: 'Load the uploaded file into a new Delta table.',
        sources: [ex('01-lakehouse', 'load-file-data-into-a-table')],
        checkpoint: 'A new table appears under Tables, and selecting it shows rows.',
      },
      {
        id: 's4',
        text: 'Switch to the lakehouse’s SQL analytics endpoint and run a SELECT query on the new table.',
        sources: [ex('01-lakehouse', 'use-sql-to-query-tables')],
        checkpoint: 'The query returns rows in the results pane.',
        trapPairId: 'endpoint-vs-warehouse',
        trapNote: 'The SQL analytics endpoint reads the lakehouse’s Delta tables; you can’t INSERT or UPDATE through it.',
      },
      {
        id: 's5',
        text: 'Create a Dataflow Gen2 that gets the exercise’s sample data, then add the lakehouse as its data destination and publish.',
        sources: [ex('05-dataflows-gen2', 'create-a-dataflow-gen2-to-ingest-data'), ex('05-dataflows-gen2', 'add-data-destination-for-dataflow')],
        checkpoint: 'After the dataflow runs, a new table from it appears in the lakehouse.',
      },
      {
        id: 's6',
        text: 'Open Manage connections and gateways and find the connection your dataflow created. Look at its connection type and who can use it.',
        sources: [learn(P.connections, 'add-a-data-source'), learn(P.connections, 'manage-users')],
        checkpoint: 'At least one connection is listed for the source you used.',
      },
      {
        id: 's7',
        text: 'Create a pipeline with a Copy data activity that copies the exercise’s file from HTTP into the lakehouse, then run it.',
        sources: [ex('04-ingest-pipeline', 'create-a-pipeline'), ex('04-ingest-pipeline', 'configure-the-source'), ex('04-ingest-pipeline', 'configure-the-destination'), ex('04-ingest-pipeline', 'run-the-pipeline')],
        checkpoint: 'The pipeline run shows a Succeeded status.',
        trapPairId: 'dataflow-pipeline-notebook',
        trapNote: 'The dataflow transformed data with Power Query; the pipeline orchestrated a copy.',
      },
      {
        id: 's8',
        optional: true,
        text: 'Add your dataflow as an activity in a pipeline, so the pipeline runs it.',
        sources: [ex('05-dataflows-gen2', 'add-a-dataflow-to-a-pipeline')],
        checkpoint: 'The pipeline canvas shows a Dataflow activity.',
      },
      {
        id: 's9',
        text: 'Create a second lakehouse named Mill_Shortcuts and add a OneLake shortcut in its Tables folder that points to a table in Mill_Lakehouse.',
        sources: [learn(P.shortcut, 'create-a-shortcut'), ex('25-discover-onelake', 'create-a-shortcut-to-access-data-from-another-workspace')],
        checkpoint: 'The shortcut table shows a shortcut icon and returns the same rows as the original.',
        trapPairId: 'shortcut-mirror-copy',
        trapNote: 'A shortcut references the data in place; the Copy activity in step 7 made a copy.',
      },
      {
        id: 's10',
        text: 'Open the OneLake catalog’s Explore tab, filter to your workspace, and open an item’s details.',
        sources: [learn(P.catalogExplore, 'open-the-explore-tab'), learn(P.catalogExplore, 'filter-the-items-list'), learn(P.catalogExplore, 'view-item-details')],
        checkpoint: 'The details pane shows the item’s location (your workspace).',
        trapPairId: 'catalog-vs-rthub',
        trapNote: 'The OneLake catalog finds data items; the Real-Time hub (Lab 6) finds data streams.',
      },
      {
        id: 's11',
        text: 'Read the data store decision guide’s scenarios. For each, decide whether a lakehouse, warehouse, or eventhouse fits, and why. You build a warehouse in Lab 4 and an eventhouse in Lab 6.',
        sources: [learn(P.dataStoreGuide, 'scenarios')],
        trapPairId: 'stores',
        trapNote: 'Lakehouse: Spark and files. Warehouse: T-SQL writes. Eventhouse: KQL on events.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete the Mill_Shortcuts lakehouse. Deleting a shortcut doesn’t delete the target data.',
        sources: [learn(P.shortcut)],
      },
      {
        id: 'c2',
        text: 'If you scheduled the pipeline, turn the schedule off. Keep Mill_Lakehouse, the dataflow, and the pipeline for Lab 13. ' + KEEP,
        sources: [learn(P.pipeline, 'run-and-schedule-your-pipeline')],
      },
    ],
  },
  {
    id: 'L03',
    order: 3,
    title: 'Carding and twisting: clean, join, and aggregate in a Spark notebook',
    goal: 'Use a notebook to remove duplicates, fill nulls, convert types, filter, join, aggregate, add columns, and write a Delta table.',
    machineIds: ['carding-machine', 'twisting-frame', 'dye-vat'],
    bulletIds: ['P2.7', 'P2.8', 'P2.9', 'P2.5', 'P2.6', 'P2.2'],
    platform: 'browser',
    minutes: 75,
    prereqs: ['L02'],
    before:
      'Work in DP600-Dev. Skip the exercise’s “Create a workspace” part, but do create its lakehouse (name it Spin_Lakehouse). Skip every optional prompt that needs AI features; the trial doesn’t include them.',
    steps: [
      {
        id: 's1',
        text: 'Create a lakehouse named Spin_Lakehouse, import the exercise’s notebook, attach it to the lakehouse, and run the first cell to create the sample tables.',
        sources: [ex('26c-transform-data-notebooks', 'create-a-workspace'), ex('26c-transform-data-notebooks', 'generate-sample-data')],
        checkpoint: 'The Explorer pane lists the three sample tables after a refresh.',
      },
      {
        id: 's2',
        text: 'Run the shape-and-clean cells. Note how the query removes the duplicate row, replaces the null, and adds a calculated and a conditional column.',
        sources: [ex('26c-transform-data-notebooks', 'shape-and-clean-the-sales-data')],
        checkpoint: 'The result has fewer rows than the raw table, and no null remains in the cleaned column.',
        trapPairId: 'where-having-qualify',
        trapNote: 'Filtering rows before grouping (WHERE) isn’t the same as filtering groups after it (HAVING).',
      },
      {
        id: 's3',
        text: 'Run the join and aggregate cells.',
        sources: [ex('26c-transform-data-notebooks', 'join-and-aggregate-the-data')],
        checkpoint: 'The summary has one row per region.',
        trapPairId: 'merge-vs-append',
        trapNote: 'A join adds columns from another table; a union stacks rows.',
      },
      {
        id: 's4',
        text: 'Run the window-function cell and compare its row count with the aggregate.',
        sources: [ex('26c-transform-data-notebooks', 'apply-window-functions')],
        checkpoint: 'The window-function result keeps every detail row.',
      },
      {
        id: 's5',
        text: 'Write the enriched result to a Delta table and query it.',
        sources: [ex('26c-transform-data-notebooks', 'write-results-to-a-delta-table')],
        checkpoint: 'A new table appears under Tables after a refresh.',
      },
      {
        id: 's6',
        text: 'In a new cell, load the raw sales table into a pandas DataFrame and open Data Wrangler on it.',
        sources: [learn(P.dataWrangler, 'launching-data-wrangler')],
        checkpoint: 'Data Wrangler opens with a Summary panel that reports missing values.',
      },
      {
        id: 's7',
        text: 'In Data Wrangler, preview and apply the operations to drop duplicate rows, fill missing values, and change a column’s type.',
        sources: [learn(P.dataWrangler, 'browsing-data-cleaning-operations'), learn(P.dataWrangler, 'previewing-and-applying-operations')],
        checkpoint: 'Each applied operation appears as a step in the cleaning steps list.',
      },
      {
        id: 's8',
        text: 'Export the generated code back to the notebook and read it.',
        sources: [learn(P.dataWrangler, 'saving-and-exporting-code')],
        checkpoint: 'A new code cell holds the generated function.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Stop the notebook’s Spark session if it’s still running, then delete the notebook and Spin_Lakehouse. ' + KEEP,
        sources: [ex('26c-transform-data-notebooks', 'clean-up-resources')],
      },
    ],
  },
  {
    id: 'L04',
    order: 4,
    title: 'Weave planner: a star schema in a warehouse with T-SQL',
    goal: 'In a warehouse, write T-SQL that filters, joins, and aggregates; create a view and a stored procedure; then load dimension and fact tables.',
    machineIds: ['weave-planner', 'recipe-book'],
    bulletIds: ['P2.3', 'P2.4', 'P2.1'],
    platform: 'browser',
    minutes: 90,
    prereqs: ['L01'],
    before:
      'Work in DP600-Dev. Skip the exercise’s “Create a workspace” part and every optional section that needs AI features (the trial doesn’t include them). Name the warehouse Mill_Warehouse; Labs 11, 14, and 15 use it.',
    steps: [
      {
        id: 's1',
        text: 'Create a warehouse named Mill_Warehouse.',
        sources: [ex('26d-transform-data-tsql', 'create-a-warehouse')],
        checkpoint: 'The warehouse opens with an empty Explorer.',
        trapPairId: 'endpoint-vs-warehouse',
        trapNote: 'Unlike the SQL analytics endpoint in Lab 2, a warehouse accepts INSERT, UPDATE, and CTAS.',
      },
      {
        id: 's2',
        text: 'Create the staging tables and load the sample data.',
        sources: [ex('26d-transform-data-tsql', 'create-staging-tables-and-load-sample-data')],
        checkpoint: 'The staging schema lists the new tables in the Explorer.',
      },
      {
        id: 's3',
        text: 'Run the exercise’s T-SQL queries that filter, join, aggregate, and use window functions and a CTE.',
        sources: [ex('26d-transform-data-tsql', 'transform-data-with-t-sql-queries')],
        checkpoint: 'Each query returns a result grid without errors.',
      },
      {
        id: 's4',
        text: 'Create the view for reusable logic and query it.',
        sources: [ex('26d-transform-data-tsql', 'create-a-view-for-reusable-logic'), learn(P.createView)],
        checkpoint: 'The view appears under Views and returns rows.',
      },
      {
        id: 's5',
        text: 'Build the stored procedure with a parameter and run it.',
        sources: [ex('26d-transform-data-tsql', 'build-a-stored-procedure-with-parameters')],
        checkpoint: 'The procedure appears under Stored Procedures and its EXEC call completes.',
      },
      {
        id: 's6',
        text: 'Create and load the date, customer, and product dimensions and the fact table. Note how the fact load looks up surrogate keys from the dimensions.',
        sources: [ex('26d-transform-data-tsql', 'create-and-load-dimensional-tables')],
        checkpoint: 'The dim and fact schemas list the new tables, and the fact table returns rows.',
        trapPairId: 'star-vs-snowflake',
        trapNote: 'Each dimension is one flat table joined straight to the fact: a star, not a snowflake.',
      },
      {
        id: 's7',
        text: 'Run the verification queries.',
        sources: [ex('26d-transform-data-tsql', 'verify-the-final-state')],
        checkpoint: 'Every verification query returns without errors.',
      },
      {
        id: 's8',
        optional: true,
        text: 'In a separate warehouse, work through the slowly changing dimension sections of the dimensional modeling exercise.',
        sources: [ex('26-design-dimensional-models', 'simulate-an-scd-type-2-change'), ex('26-design-dimensional-models', 'simulate-an-scd-type-1-change')],
        checkpoint: 'After the type 2 change, the customer has more than one row, and only one is marked current.',
        trapPairId: 'scd1-vs-scd2',
        trapNote: 'Type 1 overwrites the old value; type 2 keeps history in a new row.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Keep Mill_Warehouse for Labs 11, 14, and 15. If you did step 8, delete that extra warehouse.',
        sources: [ex('26-design-dimensional-models', 'clean-up-resources')],
      },
    ],
  },
  {
    id: 'L05',
    order: 5,
    title: 'Inspection bench: the Visual query editor and the SQL query editor',
    goal: 'Answer the same questions with the Visual query editor and with T-SQL, look at the SQL a visual query generates, and save a result as a view.',
    machineIds: ['inspection-bench'],
    bulletIds: ['P3.1', 'P3.2'],
    platform: 'browser',
    minutes: 45,
    prereqs: ['L01'],
    before: 'Work in DP600-Dev. Skip the exercise’s “Create a workspace” part.',
    steps: [
      {
        id: 's1',
        text: 'Create the sample warehouse described in the exercise.',
        sources: [ex('06b-data-warehouse-query', 'create-a-sample-data-warehouse')],
        checkpoint: 'The Explorer lists the sample tables.',
      },
      {
        id: 's2',
        text: 'Run the exercise’s T-SQL queries that select, filter, group, and aggregate.',
        sources: [ex('06b-data-warehouse-query', 'query-the-data-warehouse'), learn(P.sqlEditor, 'sql-query-editor-in-the-fabric-portal')],
        checkpoint: 'Each query returns a result grid.',
      },
      {
        id: 's3',
        text: 'Run the data consistency checks.',
        sources: [ex('06b-data-warehouse-query', 'verify-data-consistency')],
        checkpoint: 'Each check query runs without errors.',
      },
      {
        id: 's4',
        text: 'Open a new visual query. Drag a table onto the canvas, keep a few columns, filter rows, and group by one column with an aggregation.',
        sources: [learn(P.visualQuery, 'visual-query-editor-in-the-fabric-portal')],
        checkpoint: 'The results preview shows one row per group.',
        trapPairId: 'visual-vs-sql-editor',
        trapNote: 'The Visual query editor builds the query from steps; the SQL editor runs the T-SQL you type.',
      },
      {
        id: 's5',
        text: 'Use View SQL to see the T-SQL that your visual query generates.',
        sources: [learn(P.visualQuery, 'view-sql')],
        checkpoint: 'The generated T-SQL includes a GROUP BY.',
      },
      {
        id: 's6',
        text: 'Save the visual query as a view, then save a T-SQL query as a view as the exercise shows.',
        sources: [learn(P.visualQuery, 'save-as-view'), ex('06b-data-warehouse-query', 'save-as-view')],
        checkpoint: 'Both views appear under Views.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete the sample warehouse. ' + KEEP,
        sources: [ex('06b-data-warehouse-query', 'clean-up-resources')],
      },
    ],
  },
  {
    id: 'L06',
    order: 6,
    title: 'Tension meter: an eventhouse, KQL, and OneLake availability',
    goal: 'Query an eventhouse with KQL (and its T-SQL emulation), make a KQL table available in OneLake, and browse the Real-Time hub.',
    machineIds: ['tension-meter', 'shared-spool', 'bale-catalog'],
    bulletIds: ['P3.3', 'P1.5', 'P1.2'],
    platform: 'browser',
    minutes: 60,
    prereqs: ['L01'],
    before: 'Work in DP600-Dev. Skip the exercise’s “Create a workspace” part.',
    steps: [
      {
        id: 's1',
        text: 'Create the sample eventhouse from the Real-Time Intelligence workload, as the exercise describes.',
        sources: [ex('12-query-data-in-kql-database', 'create-an-eventhouse'), learn(P.createEventhouse, 'create-an-eventhouse-1')],
        checkpoint: 'The eventhouse has a KQL database with a sample table.',
      },
      {
        id: 's2',
        text: 'Retrieve rows with take, then pick columns with project.',
        sources: [ex('12-query-data-in-kql-database', 'retrieve-data-from-a-table-with-kql')],
        checkpoint: 'The result shows only the columns you projected.',
        trapPairId: 'project-vs-extend',
        trapNote: 'project keeps only the columns you list; extend adds columns and keeps the rest.',
      },
      {
        id: 's3',
        text: 'Summarize with sum, first overall and then by a column.',
        sources: [ex('12-query-data-in-kql-database', 'summarize-data-by-using-kql')],
        checkpoint: 'The grouped query returns one row per group.',
      },
      {
        id: 's4',
        text: 'Sort with sort by and with order by, then filter with where.',
        sources: [ex('12-query-data-in-kql-database', 'sort-data-by-using-kql'), ex('12-query-data-in-kql-database', 'filter-data-by-using-kql')],
        checkpoint: 'sort by and order by return the same order.',
      },
      {
        id: 's5',
        text: 'Run the exercise’s T-SQL queries against the same KQL database.',
        sources: [ex('12-query-data-in-kql-database', 'query-data-by-using-transact-sql')],
        checkpoint: 'The T-SQL queries return results from the same table.',
        trapPairId: 'sql-vs-kql',
        trapNote: 'Same question, two languages: GROUP BY vs summarize … by, SELECT vs project.',
      },
      {
        id: 's6',
        text: 'Turn on OneLake availability for the KQL database (or one table).',
        sources: [learn(P.ehOneLake, 'turn-on-onelake-availability-for-a-kql-database-or-table')],
        checkpoint: 'The database details show OneLake availability as on.',
        trapPairId: 'onelake-availability-vs-integration',
        trapNote: 'This is Eventhouse OneLake availability; semantic model OneLake integration is in Lab 15.',
      },
      {
        id: 's7',
        text: 'Look at the table’s Delta files in OneLake. They can take a while to appear after you turn availability on.',
        sources: [learn(P.ehOneLake, 'view-delta-lake-files-in-onelake')],
        checkpoint: 'You can see a Delta folder for the table, or a note that files are still being written.',
      },
      {
        id: 's8',
        optional: true,
        text: 'Query the table’s Delta data from a notebook, as Learn describes.',
        sources: [learn(P.ehOneLake, 'query-delta-tables-from-a-fabric-notebook')],
        checkpoint: 'The notebook returns rows from the table.',
      },
      {
        id: 's9',
        text: 'Open the Real-Time hub and browse its streams and sources. Don’t connect a new source.',
        sources: [learn(P.rtHub), ex('07-real-time-Intelligence', 'create-an-eventstream')],
        checkpoint: 'The Real-Time hub page opens and lists streams or data sources.',
        trapPairId: 'catalog-vs-rthub',
        trapNote: 'Real-Time hub: streams and events. OneLake catalog: items such as lakehouses and models.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Delete the eventhouse and any eventstream the sample created, so nothing keeps ingesting into your trial capacity. ' + KEEP,
        sources: [learn(P.createEventhouse, 'delete-an-eventhouse'), ex('07-real-time-Intelligence', 'clean-up-resources')],
      },
    ],
  },
]
