import type { Lab } from './types'
import { P, ex, learn } from './sources'

const MODEL = 'Sales Model'

export const semanticLabs: Lab[] = [
  {
    id: 'L07',
    order: 7,
    title: 'Warp frame: build a Direct Lake semantic model',
    goal: 'Create a Direct Lake on OneLake semantic model from lakehouse tables, build a star schema with an inactive relationship, and write measures with variables.',
    machineIds: ['warp-frame', 'punch-card-reader', 'loom-gearbox'],
    bulletIds: ['S1.2', 'S1.3', 'S1.4', 'S1.1'],
    platform: 'browser',
    minutes: 90,
    prereqs: ['L01'],
    before: `Work in DP600-Dev. Models open in the browser in Viewing mode: switch to Editing mode before you change anything. Skip the exercise’s workspace creation and its optional section that needs AI features (the trial doesn’t include them). Name the model ${MODEL}; Labs 8 to 15 use it.`,
    steps: [
      {
        id: 's1',
        text: 'Import the exercise’s notebook, create its lakehouse from the notebook, and run all cells to create the sample star schema tables.',
        sources: [ex('15-design-semantic-model-scale', 'set-up-the-environment')],
        checkpoint: 'The lakehouse lists the dimension tables and the fact table under Tables.',
      },
      {
        id: 's2',
        text: 'Read when to choose Direct Lake on OneLake versus Direct Lake on SQL. This lab uses Direct Lake on OneLake; Lab 8 builds the other kind.',
        sources: [learn(P.dlDevelop, 'choose-the-right-storage-mode')],
        trapPairId: 'storage-modes',
        trapNote: 'Direct Lake reads Delta tables in OneLake; Import copies data into the model; DirectQuery queries the source each time.',
      },
      {
        id: 's3',
        text: `Open the lakehouse’s SQL analytics endpoint and choose New semantic model. Name it ${MODEL}, pick the exercise’s four tables, and choose Direct Lake on OneLake if the dialog asks. (The exercise starts from the lakehouse explorer instead; Learn shows both entry points.)`,
        sources: [learn(P.dlDevelop, 'create-the-model'), ex('15-design-semantic-model-scale', 'create-a-semantic-model')],
        checkpoint: 'The model opens in the browser’s model editor with the four tables. If it says tables don’t exist or can’t refresh, wait a few minutes for the tables to sync and try again.',
        trapPairId: 'dl-onelake-vs-sql',
        trapNote: 'Starting from the SQL analytics endpoint doesn’t make the model Direct Lake on SQL; the dialog choice decides.',
      },
      {
        id: 's4',
        text: 'Create the exercise’s four relationships: three active many-to-one relationships from the fact table to the dimensions, and a fourth on the ship date key to the date table with “Make this relationship active” cleared.',
        sources: [ex('15-design-semantic-model-scale', 'design-star-schema-relationships'), learn(P.editModels, 'create-a-relationship')],
        checkpoint: 'The relationships list shows four relationships, and the ship-date one is inactive.',
        trapPairId: 'regular-vs-limited',
        trapNote: 'These are regular one-to-many relationships within one source group.',
      },
      {
        id: 's5',
        text: 'Create the four measures, including the two that use variables.',
        sources: [ex('15-design-semantic-model-scale', 'create-measures')],
        checkpoint: 'The fact table shows four measures with calculator icons.',
      },
      {
        id: 's6',
        text: 'Create the ship-date measure that uses USERELATIONSHIP to activate the inactive relationship.',
        sources: [ex('15-design-semantic-model-scale', 'use-userelationship-for-the-inactive-ship-date-relationship')],
        checkpoint: 'The measure saves without an error.',
      },
      {
        id: 's7',
        text: 'Create a report from the model and build the bar chart, card, and year slicer from the exercise. Skip the calculation group step; that’s in Lab 9. Save the report as Sales Report in DP600-Dev: Labs 9 to 11 use it.',
        sources: [ex('15-design-semantic-model-scale', 'validate-the-model-with-a-report')],
        checkpoint: 'The order-date and ship-date measures show different values for at least one slicer range.',
      },
      {
        id: 's8',
        optional: true,
        text: 'Needs Lab 4 step 9. Open Mill_Warehouse, select New semantic model, name it Bridge Model, pick the customer dimension, the bridge table, the product dimension, and the sales fact table, then Confirm and switch to Editing mode. Relate customer to bridge and product to bridge as one-to-many on the key columns, and product to the fact table as one-to-many. Don’t relate the customer dimension to the fact (that would give a second, ambiguous filter path), and don’t relate the two dimensions with a many-to-many relationship. Set the product-to-bridge relationship’s cross-filter direction to Both so a customer filter reaches the fact table, then hide the bridge table and the key columns, including the fact’s customer key. Note what the result means: a customer’s value is the sales of the products that customer bought, by any customer, not the customer’s own purchases. A real bridge is needed when the fact doesn’t carry the other key, as in Learn’s accounts-and-customers example.',
        sources: [learn(P.whCreateModel, 'create-a-new-power-bi-semantic-model-in-direct-lake-mode'), learn(P.m2m, 'relate-many-to-many-dimensions-guidance'), learn(P.m2m, 'relate-many-to-many-dimensions'), learn(P.relationships, 'cross-filter-direction'), learn(P.relationships, 'resolve-relationship-path-ambiguity'), learn(P.editModels, 'create-a-relationship')],
        checkpoint: 'In a table of customer name and the sum of the sales amount, values differ per customer, and the customer rows can add up to more than the total: they’re non-additive, as Learn’s bank-account example explains.',
        trapPairId: 'regular-vs-limited',
        trapNote: 'One-to-many relationships between tables from one source stay regular relationships; Learn advises against relating the two dimensions with a many-to-many relationship.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: `Stop the notebook’s Spark session. If you did step 8, delete Bridge Model (keep the bridge table in Mill_Warehouse). Keep ${MODEL}, Sales Report, the lakehouse, and the notebook for Labs 8 to 15. Skip the exercise’s query scale-out setting.`,
        sources: [ex('02-analyze-spark', 'clean-up-resources'), ex('15-design-semantic-model-scale', 'configure-settings-for-scale')],
      },
    ],
  },
  {
    id: 'L08',
    order: 8,
    title: 'Direct Lake shuttle: two flavors, fallback, and a composite model',
    goal: 'Build a Direct Lake on SQL model next to your Direct Lake on OneLake model, see a SQL view fall back, change Direct Lake behavior, check refresh settings, and add an Import table to make a composite model.',
    machineIds: ['direct-lake-shuttle', 'double-loom', 'loom-gearbox'],
    bulletIds: ['S2.3', 'S2.4', 'S1.7', 'S1.1'],
    platform: 'browser',
    minutes: 75,
    prereqs: ['L07'],
    before: `Work in DP600-Dev with the lakehouse and ${MODEL} from Lab 7. UI labels in the browser model editor change often; if one doesn’t match, use the cited section and report it.`,
    steps: [
      {
        id: 's1',
        text: 'In the lakehouse’s SQL analytics endpoint, create a view over the fact table joined to the product dimension. Include the product key column so step 7 can relate it, plus any other columns you like.',
        sources: [learn(P.createView), learn(P.sqlEditor, 'sql-query-editor-in-the-fabric-portal')],
        checkpoint: 'The view appears under Views and returns rows.',
      },
      {
        id: 's2',
        text: 'From the SQL analytics endpoint, create a second semantic model named Sales Model SQL. This time choose Direct Lake on SQL, and include one dimension table and your view.',
        sources: [learn(P.dlDevelop, 'create-the-model'), learn(P.dlDevelop, 'model-tables')],
        checkpoint: 'The new model lists the dimension table and the view.',
        trapPairId: 'dl-onelake-vs-sql',
        trapNote: 'Only Direct Lake on SQL can use a SQL view as a Direct Lake table, and only by falling back to DirectQuery.',
      },
      {
        id: 's3',
        text: 'Writing DAX queries in the browser needs the workspace setting “User can edit data models in the Power BI service (preview)”; turn it on in DP600-Dev’s settings if it’s off. Then choose Write DAX queries from Sales Model SQL’s menu and run EVALUATE TABLETRAITS().',
        sources: [learn(P.dlHow, 'diagnose-fallback'), learn(P.daxQueryView, 'dax-query-view-in-web'), learn(P.daxQueryView, 'considerations-and-limitations')],
        checkpoint: 'The DirectLakeFallbackInfo column shows None for the dimension table and a fallback reason for the view.',
        trapPairId: 'dl-fallback',
        trapNote: 'Queries on the view table fall back to DirectQuery; the plain table stays in Direct Lake.',
      },
      {
        id: 's4',
        text: 'Open Sales Model SQL in Editing mode and, in model view, change its Direct Lake behavior from Automatic to Direct Lake only (the setting applies only to Direct Lake on SQL). Query the view table again, then change it back to Automatic.',
        sources: [learn(P.dlHow, 'control-fallback-with-directlakebehavior')],
        checkpoint: 'With Direct Lake only, a query on the view table returns an error instead of falling back.',
      },
      {
        id: 's5',
        text: `Open ${MODEL}’s settings and find “Keep your Direct Lake data up to date”. Then refresh the model manually and look at its refresh history.`,
        sources: [learn(P.dlHow, 'automatic-updates'), learn(P.dlHow, 'framing')],
        checkpoint: 'The refresh history lists your manual refresh.',
        trapPairId: 'framing-vs-import-refresh',
        trapNote: 'A Direct Lake refresh frames metadata; it doesn’t copy data like an Import refresh.',
      },
      {
        id: 's6',
        text: `Open ${MODEL} (Direct Lake on OneLake) in Editing mode, choose Get data on the ribbon, and add your SQL view from the SQL analytics endpoint as an Import table. Only the model’s owner can use Get data, and you may be asked to set credentials. The connection shows a server name from your tenant: don’t paste it into a problem note.`,
        sources: [learn(P.webModel, 'composite-semantic-models-with-direct-lake-and-import-storage-mode-tables'), learn(P.editModels, 'get-data'), learn(P.editModels, 'permissions'), learn(P.composite, 'create-composite-models-in-web-modeling')],
        checkpoint: 'The new table shows Import storage mode while the others show Direct Lake.',
        trapPairId: 'storage-modes',
        trapNote: 'Direct Lake plus Import in one model is a composite model; Direct Lake on SQL tables can’t join one.',
      },
      {
        id: 's7',
        text: 'Relate the Import table to a dimension and build a visual that uses columns from both storage modes.',
        sources: [learn(P.composite, 'source-groups'), learn(P.composite, 'use-composite-models')],
        checkpoint: 'The visual returns values from both tables.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: `Delete Sales Model SQL. Remove the Import table from ${MODEL} so Labs 9 and 10 start from Direct Lake only. Keep the view.`,
        sources: [ex('15-design-semantic-model-scale', 'configure-settings-for-scale'), learn(P.webModel, 'composite-semantic-models-with-direct-lake-and-import-storage-mode-tables')],
      },
    ],
  },
  {
    id: 'L09',
    order: 9,
    title: 'Jacquard head: calculation groups, dynamic format strings, field parameters',
    goal: 'Add a time-intelligence calculation group with a dynamic format string, give a measure a dynamic format string, and (on Windows) build DAX calculations and a field parameter in Power BI Desktop.',
    machineIds: ['jacquard-head', 'punch-card-reader'],
    bulletIds: ['S1.5', 'S1.4'],
    platform: 'mixed',
    minutes: 90,
    prereqs: ['L07'],
    before: `Steps 1 to 4 run in the browser on ${MODEL}. Steps 5 to 8 need Power BI Desktop on Windows; on a Mac, skip them and mark the lab complete without them.`,
    steps: [
      {
        id: 's1',
        text: `In ${MODEL}, create the exercise’s calculation group with its six calculation items.`,
        sources: [ex('15-design-semantic-model-scale', 'create-a-calculation-group'), learn(P.calcGroups, 'add-a-new-calculation-group-in-model-view')],
        checkpoint: 'The calculation group shows six calculation items.',
      },
      {
        id: 's2',
        text: 'Give the year-over-year item a dynamic format string, as the exercise shows.',
        sources: [ex('15-design-semantic-model-scale', 'create-a-calculation-group'), learn(P.calcGroups, 'add-a-dynamic-format-string-to-a-calculation-item')],
        checkpoint: 'The item’s properties show a dynamic format string.',
      },
      {
        id: 's3',
        text: 'In Sales Report, put the calculation group’s column in the bar chart’s legend.',
        sources: [ex('15-design-semantic-model-scale', 'validate-the-model-with-a-report'), learn(P.calcGroups, 'using-the-calculation-group-in-reports')],
        checkpoint: 'The legend lists the six calculation items.',
        trapPairId: 'calcgroup-vs-fieldparam',
        trapNote: 'A calculation group changes how measures are calculated; a field parameter (step 8) swaps which fields a visual shows.',
      },
      {
        id: 's4',
        text: 'Give the Profit Margin measure a dynamic format string: select the measure, set its format to Dynamic, and enter a DAX expression that returns a format string, for example IF([Profit Margin] < 0.1, "0.00%", "0.0%"). The browser’s labels may differ from Learn’s Desktop ribbon. With a calculation group in the model, Learn warns that measures become variant and some dynamic format strings can show errors; if that happens, report it.',
        sources: [learn(P.dfs, 'create-dynamic-format-strings'), learn(P.calcGroups, 'model-measures-change-to-variant-data-type')],
        checkpoint: 'The measure still sorts as a number in a table visual, and its display format changes.',
        trapPairId: 'dfs-vs-format',
        trapNote: 'A dynamic format string keeps the number type; FORMAT() turns the value into text.',
      },
      {
        id: 's5',
        windows: true,
        text: 'Install Power BI Desktop if you don’t have it, then download and open the DAX calculations exercise’s starter file.',
        sources: [learn(P.getDesktop, 'install-as-an-app-from-the-microsoft-store'), ex('14-create-dax-calculations', 'get-started')],
        checkpoint: 'The starter report opens in Power BI Desktop.',
      },
      {
        id: 's6',
        windows: true,
        text: 'Create the calculated table, the Date table and its calculated columns, complete the Date table (hierarchy and relationships), then mark it as a date table.',
        sources: [ex('14-create-dax-calculations', 'create-the-salesperson-calculated-table'), ex('14-create-dax-calculations', 'create-the-date-table'), ex('14-create-dax-calculations', 'create-calculated-columns'), ex('14-create-dax-calculations', 'complete-the-date-table'), ex('14-create-dax-calculations', 'mark-the-date-table')],
        checkpoint: 'The Date table appears with a calendar icon in the Data pane.',
      },
      {
        id: 's7',
        windows: true,
        text: 'Create the simple and additional measures, including the one that uses HASONEVALUE.',
        sources: [ex('14-create-dax-calculations', 'create-simple-measures'), ex('14-create-dax-calculations', 'create-additional-measures')],
        checkpoint: 'The HASONEVALUE measure is blank on the table’s total row.',
        trapPairId: 'hasonevalue-vs-isinscope',
        trapNote: 'HASONEVALUE tests the filter; ISINSCOPE tests whether a column is a grouping level.',
      },
      {
        id: 's8',
        windows: true,
        text: 'Create a field parameter with two or three measures, add it to a slicer, and use it in a visual.',
        sources: [learn(P.fieldParams, 'create-a-field-parameter'), learn(P.fieldParams, 'use-a-field-parameter-in-a-slicer')],
        checkpoint: 'Choosing a field in the slicer changes the measure the visual shows.',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: `Keep the calculation group in ${MODEL}. If you did the Windows steps, keep the starter file for Lab 14 (save it once).`,
        sources: [learn(P.calcGroups, 'considerations')],
      },
    ],
  },
  {
    id: 'L10',
    order: 10,
    title: 'Speed governor: Performance analyzer, DAX query view, and faster DAX',
    goal: 'Record visual timings, copy a visual’s query into DAX query view, write DAX queries that select, filter, and aggregate, and (on Windows) fix a slow measure.',
    machineIds: ['speed-governor', 'dax-scale'],
    bulletIds: ['S2.1', 'S2.2', 'P3.4'],
    platform: 'mixed',
    minutes: 75,
    prereqs: ['L07'],
    before: `Steps 1 to 5 run in the browser on a report over ${MODEL}. Steps 6 to 9 need Power BI Desktop on Windows; on a Mac, skip them.`,
    steps: [
      {
        id: 's1',
        text: 'Open Sales Report in edit mode, open the Performance analyzer pane, start recording, and refresh the visuals.',
        sources: [learn(P.perfAnalyzer, 'display-the-performance-analyzer-pane-in-the-web'), learn(P.perfAnalyzer, 'use-performance-analyzer')],
        checkpoint: 'Each visual shows a duration, split into categories.',
        trapPairId: 'perf-categories',
        trapNote: 'DAX query time is the engine; visual display time is rendering. Fix the bigger one.',
      },
      {
        id: 's2',
        text: 'Copy one visual’s query. Choose Write DAX queries from the model’s menu (it needs the workspace setting from Lab 8 step 3), paste the query into a new tab, and run it.',
        sources: [learn(P.perfAnalyzer, 'dax-queries-in-visuals'), learn(P.daxQueryView, 'dax-query-view-in-web')],
        checkpoint: 'The results grid returns the same numbers the visual shows.',
      },
      {
        id: 's3',
        text: 'Write your own query: EVALUATE SUMMARIZECOLUMNS with the product category column and the Total Sales measure, ordered by sales.',
        sources: [learn(P.summarizecolumns), learn(P.daxQueries)],
        checkpoint: 'The grid shows one row per category.',
      },
      {
        id: 's4',
        text: 'Add a filter to the query (for example, a single year from the date table), then add a query-scoped measure with DEFINE MEASURE and use it in the same query.',
        sources: [learn(P.defineStatement), learn(P.summarizecolumns)],
        checkpoint: 'The query runs, and the query-scoped measure doesn’t appear in the model’s Data pane.',
        trapPairId: 'query-measure-vs-model-measure',
        trapNote: 'A DEFINE MEASURE exists only for that query until you choose to add it to the model.',
      },
      {
        id: 's5',
        text: 'Back in the report, select a bar or slicer value while recording, and compare the new entries in Performance analyzer.',
        sources: [learn(P.perfAnalyzer, 'use-performance-analyzer')],
        checkpoint: 'Performance analyzer logs a new entry for the interaction.',
      },
      {
        id: 's6',
        windows: true,
        text: 'Download and open the performance exercise’s starter file in Power BI Desktop, and capture a baseline.',
        sources: [ex('16-optimize-semantic-model-performance', 'before-you-start'), ex('16-optimize-semantic-model-performance', 'capture-a-performance-baseline')],
        checkpoint: 'Performance analyzer lists the page’s visuals with durations.',
      },
      {
        id: 's7',
        windows: true,
        text: 'Send the slow visual’s query to DAX query view, find the repeated expression, and rewrite the measure with a variable.',
        sources: [ex('16-optimize-semantic-model-performance', 'analyze-the-slow-dax-query'), ex('16-optimize-semantic-model-performance', 'optimize-the-dax-measure')],
        checkpoint: 'The rewritten measure returns the same values as before.',
      },
      {
        id: 's8',
        windows: true,
        text: 'Run the COLUMNSTATISTICS query and find the highest-cardinality columns.',
        sources: [ex('16-optimize-semantic-model-performance', 'examine-column-cardinality')],
        checkpoint: 'The grid lists columns sorted by cardinality.',
      },
      {
        id: 's9',
        windows: true,
        text: 'Record again and compare with your baseline.',
        sources: [ex('16-optimize-semantic-model-performance', 'verify-the-improvements')],
        checkpoint: 'You have a second set of timings to compare (the difference may be small).',
      },
    ],
    cleanup: [
      {
        id: 'c1',
        text: 'Close the DAX query view tabs you don’t need. Close the Windows starter file without saving.',
        sources: [ex('16-optimize-semantic-model-performance', 'clean-up-resources')],
      },
    ],
  },
]
